### ISSUE TITLE
cannot publish site in ftp

### ISSUE THREAD

**Issue by aermike** [silexlabs/Silex#1001]
Try to publish site at an FTP server
Cannot read property 'size of undefined
<img width="686" alt="silex error" src="https://user-images.githubusercontent.com/4247309/74279104-f4d44400-4d22-11ea-9330-64d093c746fd.PNG">

**Comment by aermike** [comment]
The stat operation failed with error: TypeError: Cannot read property 'size' of undefined
    at toFileInfos (/opt/custom-silex/node_modules/unifile/lib/unifile-ftp.js:84:15)
    at /opt/custom-silex/node_modules/unifile/lib/unifile-ftp.js:188:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
The stat operation failed with error: TypeError: Cannot read property 'size' of undefined
    at toFileInfos (/opt/custom-silex/node_modules/unifile/lib/unifile-ftp.js:84:15)
    at /opt/custom-silex/node_modules/unifile/lib/unifile-ftp.js:188:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
job is stopped true false false
Warning: possible error in PublishJob b6131c16-34d4-4469-99c8-76a64c041ed2 (true)

**Comment by aermike** [comment]
any feedback please?

**Comment by lexoyo** [comment]
Hi @aermike 
Could you check in `node_modules/unifile/package.json` which version of the package you have? or in silex `package.json` check unifile version

**Comment by aermike** [comment]
<img width="798" alt="unifile" src="https://user-images.githubusercontent.com/4247309/74708915-81e93280-5226-11ea-89be-6e65d62c9ede.PNG">
unifile 2.0.7  with id 2.0.8

**Comment by aermike** [comment]
When try to install unifile get this message
npm install unifile --save
npm WARN notsup Unsupported engine for unifile@2.0.8: wanted: {"node":"^8.16.1","npm":"^3.9.5"} (current: {"node":"13.8.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: unifile@2.0.8

**Comment by aermike** [comment]
Try install Silex useng steps describe in 
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex
when  run npm run build 
it get an error

> silex-website-builder@2.5.60 build:client:release /opt/Silex
> webpack --config webpack.config.js

Hash: 6c58779433a9990aa1dd
Version: webpack 4.41.6
Time: 11168ms
Built at: 02/18/2020 7:09:00 AM
 1 asset
Entrypoint main = index.js
[6] (webpack)/buildin/global.js 472 bytes {0} [built]
[7] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
[8] ./src/client/App.ts + 88 modules 723 KiB {0} [built]
    | ./src/client/App.ts 14.1 KiB [built]
    | ./src/client/ClientConfig.ts 5.73 KiB [built]
    | ./src/client/view/UiElements.ts 1.16 KiB [built]
    | ./src/client/utils/Notification.ts 7.96 KiB [built]
    | ./src/client/model/Body.ts 3.64 KiB [built]
    | ./src/client/view/dialog/FileExplorer.ts 6.63 KiB [built]
    | ./src/client/controller/ContextMenuController.ts 729 bytes [built]
    | ./src/client/controller/CssEditorController.ts 629 bytes [built]
    | ./src/client/utils/Url.ts 4.28 KiB [built]
    | ./src/client/model/Element.ts 32.9 KiB [built]
    | ./src/client/controller/EditMenuController.ts 17.8 KiB [built]
    | ./src/client/model/Property.ts 24 KiB [built]
    | ./src/client/model/File.ts 9.58 KiB [built]
    | ./src/client/controller/FileMenuController.ts 12.9 KiB [built]
    | ./src/client/controller/HtmlEditorController.ts 853 bytes [built]
    |     + 74 hidden modules
    + 6 hidden modules

ERROR in /opt/Silex/src/client/view/StageWrapper.ts
[tsl] ERROR in /opt/Silex/src/client/view/StageWrapper.ts(42,30)
      TS2345: Argument of type 'HTMLElement' is not assignable to parameter of type 'string'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! silex-website-builder@2.5.60 build:client:release: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the silex-website-builder@2.5.60 build:client:release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-18T05_09_00_405Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! silex-website-builder@2.5.60 build: `npm run cleanup && npm run lint && npm run build:css:release && npm run build:html && npm run build:prodotype &nt:release && npm run build:server:release && npm run build:monaco-editor`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the silex-website-builder@2.5.60 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-18T05_09_00_424Z-debug.log

**Comment by aermike** [comment]
Any solution?
What I can do to save in ftp server?

**Comment by lexoyo** [comment]
> <img alt="unifile" width="798" src="https://user-images.githubusercontent.com/4247309/74708915-81e93280-5226-11ea-89be-6e65d62c9ede.PNG">
> unifile 2.0.7 with id 2.0.8

Can you please check which version it is? You showed package-lock.json instead of package.json

**Comment by aermike** [comment]
I don't have package-lock.json
<img width="461" alt="silex" src="https://user-images.githubusercontent.com/4247309/75091985-ec2e0a00-557b-11ea-9883-a4406fb3f672.PNG">

**Comment by lexoyo** [comment]
@JbIPS maybe?

**Comment by lexoyo** [comment]
After thinking about it, the best options if ftp does not work for you:

* Publish to Dropbox or GitHub and download the files of the published site
* Or use the desktop version of Silex to publish to a local folder (https://github.com/silexlabs/silex-desktop/releases/)

Then upload the files with an ftp client
