### ISSUE TITLE
How to pass path and service in the URL for single site mode 

### ISSUE THREAD

**Issue by parth9365** [silexlabs/Silex#1003]
Hi, 

I am trying to enable a single site mode for silex and have configured it correctly. 

But as mentioned [here](https://github.com/silexlabs/Silex/wiki/Single-site-mode), it requires "path" and "service" in the URL. 

I want to know what is the format of it? Is it a server path to the html and service? There's no example of it available.  Can you please let me know a format of it? Any example reference will be a great help, if possible. 

Thanks you and appreciate your help.

**Comment by lexoyo** [comment]
Hello
I found [here in the code](https://github.com/silexlabs/Silex/blob/d6c2be52089ad9652213cf43b438bbc96fb2b323/src/client/App.ts#L204) that silex is expecting service and path as params
It would be nice if you could add it documentation wiki

**Comment by lexoyo** [comment]
So I am guessing you need to open silex with `?service=fs&path=/my-folder/test.html` in the url

**Comment by parth9365** [comment]
Thanks a lot, @lexoyo , Let me integrate and update the documentation in detail.

**Comment by lexoyo** [comment]
hi parth, any news on your integration?

**Comment by parth9365** [comment]
I switched the editor, we were working on for now so, I haven't got a chance to integrate it. I'll try back after some time.
