### ISSUE TITLE
Bug CSS

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1004]
@lexoyo 
Salut Alex,

suite à quelques essais, j'ai remarqué ceci,

j'ai animé des éléments avec le `Hover css` tout fonctionne nickel de ce coté, mais quand je reviens par exemple sur la page "Home"  via un lien cliquable, les 2 pages se superposent.
C'est a dire que la page avec les éléments animés reste à l’écran superposé à la page home. 

Par contre si je retire la classe CSS pour l'animation, cette dernière disparait de la page home.

 PS: "testé sur preprod et editor"

**Comment by lexoyo** [comment]
Ah ok... Ok doit y avoir une collision entre les classes silex et hover css
Tu as un exemple en ligne que je puisse regarder simplement ?

**Comment by BaguetteAgile** [comment]
Je précise, en faite:

EN PREVEW: les animations ok, mais problème de superposition des pages. La page avec les animations reste toujours en superposition sur les autres pages du site
EN PUBLISH: tout fonctionne nickel...

Je te mets le liens de ma publication, mais je pense que le problème viens de SILEX en PREVIEW, car en publication c'est OK


Voici le lien de ma publication: 

 https://baguetteagile.github.io/CALICE/

La page avec animation est sur le lien: `Présentation des musiciens`

**Comment by lexoyo** [comment]
je n'arrive pas a reproduire
peux tu tout mettre sur github ou dropbox, me le partager et m'expliquer pas à pas ou clicker pour reproduire stp?

**Comment by BaguetteAgile** [comment]
Je viens de partager ma Dropbox avec toi @lexoyo 
Voici un lien Netlify du site

https://vigorous-blackwell-9cbbd9.netlify.com/

**Comment by lexoyo** [comment]
Je suis peut etre un peu confus mais ou puisje voir le site editable?
dans editable.html de https://github.com/BaguetteAgile/CALICE il n'y a qu'une seule page

**Comment by BaguetteAgile** [comment]
![Capture du 2020-03-02 11-21-53](https://user-images.githubusercontent.com/35597855/75667506-1799ae80-5c78-11ea-9d31-9d853013f2e1.png)

Tu n'as pas acces à gh-pages ??

Sinon dans ma dropbox, tu dois avoir accès.

**Comment by lexoyo** [comment]
J'ai accès à gh-pages mais le fichier que je vois n'a qu'une seule page

**Comment by BaguetteAgile** [comment]
https://github.com/BaguetteAgile/CALICE/tree/gh-pages?files=1

**Comment by BaguetteAgile** [comment]
En fait le problème venait de la conception de mon site, 
car ma page Home avait une section visible sur toutes les autres pages. 
Pour moi tu peux clôturer. 

Quoique, les animations "hover Css" ne sont pas actives sur Netlify et sur Github c'est ok,

 bizarre non ??

**Comment by lexoyo** [comment]
hmm oui c'est louche :eyes:
