### ISSUE TITLE
CSS for hold page

### ISSUE THREAD

**Issue by Rom025** [silexlabs/Silex#1005]
Hello, 
I have developped a page one year ago with silex, I would like to update this page, but the CSS seems not "conected" to the actual page.
I have this notification when I open the page on editor : "Changed the body and 1 sections with new CSS classes to the new stage component."
Is there a way for refind the CSS defined?
 
I would really appreciate if someone could help me :-)

Rom

**Comment by lexoyo** [comment]
Hi Rom
what do you mean not connected?
Can you publish your site with a bug somewhere?

**Comment by Rom025** [comment]
Hello Lexoyo, 
Thank you for your reply :-)
The CSS is not take in acount
you can find in attachlent the ziped web site and a screenshot of the previous version. 
<img width="1005" alt="Capture d’écran 2020-02-22 à 23 21 08" src="https://user-images.githubusercontent.com/61333144/75100171-b6fcd880-55ca-11ea-8bc1-528e2bfba133.png">

[Website.zip](https://github.com/silexlabs/Silex/files/4240197/Website.zip)

**Comment by lexoyo** [comment]
Hi @Rom025 
I found this in your css 
```
@font-face {
  font-family: 'earthorbiter';

  src: url(https://preprod.silex.me/ce/dropbox/get/taf-shared/Website_Rom025/BFC/Encours/police/earthorbiter/earthorbiter.eot')%20format('embedded-opentype'), %20%20url('police/earthorbiter/earthorbiter.woff')%20format('woff'), %20%20url('police/earthorbiter/earthorbiter.ttf')%20format('truetype'), %20%20url('police/earthorbiter/earthorbiter.svg);}h1 {font-family: 'earthorbiter', Arial, serif;}#menu-accordeonJ {padding: 0; margin: 0; list-style: none; text-align: left; width: 180px;}#menu-accordeonJ ul {padding: 0; margin: 0; list-style: none; text-align: center;}#menu-accordeonJ li {background-color: #444;}#menu-accordeonJ li li {max-height: 0; overflow: hidden; transition: all .5s; border-radius: 0; background: #444; box-shadow: none; border: none; margin: 0;}#menu-accordeonJ a {display: block; text-decoration: none; color: #fff; padding: 8px 0; font-family: verdana; font-size: 1.2em;}#menu-accordeonJ ul li a,
```

I believe the part you need to delete is between `@font-face {` and `%20%20url('police/earthorbiter/earthorbiter.svg);}` although I don't understand exactly what you have in the css... but it worked for me, I see your nice menu again

**Comment by Rom025** [comment]
Hello @lexoyo,

it works!
My nice menu thank you :-)

I really appreciate your help
