### ISSUE TITLE
Nothing to choose in font-family drop down

### ISSUE THREAD

**Issue by erkswede** [silexlabs/Silex#1008]
Hi
I'm trying out Silex to build a small web. On editor.silex.me I have loaded a few different templates to test with.

I'm trying to add some fonts but none of them shows up in the font-family drop down box. I managed to import fonts correctly (i think):
![image](https://user-images.githubusercontent.com/23036256/76325822-13a90480-62e8-11ea-9adc-33ad076f537a.png)

Do I need to do something else to use the fonts?
Thanks

**Comment by lexoyo** [comment]
Hello @erkswede 
It looks like the fonts are imported, so they should show up in the drop-down list 😬 
Do you have your website on GitHub? Or can you share it on Dropbox?

**Comment by erkswede** [comment]
No I don't yet, but you can easily reproduce this by going to https://editor.silex.me/, pick any theme, import a new font. No font-family is available in the drop down.
There are no fonts in the drop down even before you try to import a new one.

**Comment by lexoyo** [comment]
oh ok I see it
i did not know of this major bug in silex :(
i'll fix this as soon as i can
meanwhile you can use the old way of importing fonts:
https://github.com/silexlabs/Silex/issues/46
