### ISSUE TITLE
Save website... (editable.html)

### ISSUE THREAD

**Issue by AZWCI** [silexlabs/Silex#1010]
Don't work for me...
(under Windows10 and Google Chrome (all up to date)

Both in "Save website" or "Save website as" i have this message ;

-«Save website
Error: I did not manage to save the file.
Internal Server Error»

If i try publish (with GitHub), i havec this message ;

-«Publication
An error occured.

I did not manage to publish the website. Error from hosting provider "Github Pages": User not logged in.

Get help in Silex forums.»

........................................................................................

When i try to add image(s) with -«Drop files here! Or click here to select files»

«Click here» dont work.

And if i try to drag and drop i have this error ;

-«AN ERROR OCCURED
This operation failed with the following error message:

I did not manage to upload the files:

- SDA-aca-HD.svg
- SDA-aca-HD.svg.png
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html> ()

Ok»

**Comment by lexoyo** [comment]
Hello
That makes a lot of problems
Are you using editor.silex.me ?
Can you try to logout from cloud explorer (go up in the file explorer, to the list of services and click logout) then login (double click on github)

**Comment by lexoyo** [comment]
:eyes:
