### ISSUE TITLE
Animate Works but still  having a issue

### ISSUE THREAD

**Issue by Dhenshaw96** [silexlabs/Silex#1011]
I used a animate I found on here it works but it never leaves the screen

Here is the code I used
JS
$(function() {
    $('.hero-scroll-down').click(function() {
        $([document.documentElement, document.body]).animate({
            scrollTop: $("#after-hero").offset().top
        }, 500);
    });
})

and here is the CSS
CSS
body.silex-runtime {
  background-color: black;
  transition: background-color 0s .3s linear;
}

body.silex-runtime>* {
  opacity: .1;
  transition: opacity .3s ease-in;
}

body.silex-runtime.loaded>* {
  opacity: initial;
}

body.loaded {
  background-color: initial;
}

body.silex-runtime:before {
  content: '';
  border: 16px solid #f3f3f3;
  border-top: 16px solid #3498db;
  border-radius: 50%;
  width: 120px;
  height: 120px;
  animation: spin 2s linear infinite;
  position: absolute;
  top: 50vh;
  left: 50vw;
  z-index: 100;
}

body.silex-runtime.loaded:before {
  content: none;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}

Please help if you can Thanks

**Comment by Dhenshaw96** [comment]
![dsaiufhdusafhisadfh](https://user-images.githubusercontent.com/45112984/76689670-34ce6580-6606-11ea-93c2-7f2cdf8a2e4a.JPG)
It does this but never stops

**Comment by lexoyo** [comment]
It looks like you are missing something in the is code. There should be a `$('body').addClass('loaded')` the line after `$(function() {`

**Comment by lexoyo** [comment]
hi @Dhenshaw96 
did my answer solve the issue?
feel free to reopen the issue
