### ISSUE TITLE
Licence change

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1012]
As I am rewriting a lot of code in Silex and all of what will remain will be code I wrote, I am thinking I should change the licence

1- GPL makes it impossible to write closed source application which embeds Silex
2- GPL makes it impossible to write closed source plugins to use in Silex
3- GPL is great but I read that it does not fit the SaaS model

What do you think?
cc @JbIPS @clemos @arielsom @yanhick @silexlabs/silex-labs-contributors @tariqbenezza

**Comment by clemos** [comment]
What other licence do you consider ? MIT ?
I guess it's the good old Free vs Open Source debate :sweat_smile:

**Comment by JbIPS** [comment]
What about aGPL?
-- 
Jean-Baptiste Richardet

**Comment by lexoyo** [comment]
> What other licence do you consider ? MIT ?

why not

> I guess it's the good old Free vs Open Source debate sweat_smile

I would love silex to be foss but one should be able to create proprietary plugins

**Comment by lexoyo** [comment]
> What about aGPL?

i thought it is not ok to create proprietary plugins ?

**Comment by lexoyo** [comment]
I believe that this is what we need

https://en.wikipedia.org/wiki/Mozilla_Public_License

**Comment by JbIPS** [comment]
LGTM
