### ISSUE TITLE
pb with london cloudfare

### ISSUE THREAD

**Issue by GefeSAUVAT** [silexlabs/Silex#1013]
Hello, when I try too view my web site on ftp : ftp.cluster003.hosting.ovh.net this message appears :

What happened?

There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.
What can I do?
If you are a visitor of this website:

Please try again in a few minutes.
If you are the owner of this website:

There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page). Additional troubleshooting resources.

Cloudflare Ray ID: 5797d53fdffadbfb • Your IP: 77.205.153.25 • Performance & security by Cloudflare

Thanks for your help !

**Comment by lexoyo** [comment]
Hello
As they say you probably need to wait
Why do you use Amazon? Do you want recommendations for free very good hosting of silexiens sites?

**Comment by GefeSAUVAT** [comment]
Hello,
thank you.
I don't know why you speak about Amazon. My website is hosted by OVH.
Gilles Edmond François SAUVAT
Joyeux dévouement du coeur
<https://www.facebook.com/fondationdusourire/>


Le mer. 25 mars 2020 à 14:54, Alex Hoyau <notifications@github.com> a
écrit :

**Comment by lexoyo** [comment]
Sorry I meant OVH, I was tired
On peut aussi parler francais :)

> There is an issue between Cloudflare's cache and your origin web server

Ca veut dire que le probleme est entre cloudflare et ovh (l'origne)

Sinon tu peux publier sur github pages aussi, c'est facile depuis silex, c'est gratuit, sans pub, de bonne qualité, avec ton nom de domanaine...

**Comment by GefeSAUVAT** [comment]
Merci pour le français,
Comment puis-je transférer les données de mon site vers Github puisque je
n'y ai pas accès ?

Je suis loin d'être un pro, Github permet de stocker les données du site,
mais l'hébergement sera toujours fait par ovh ou je pourrais faire des
économies et payer seulement le nom de domaine ? Je ne comprends pas bien
les limites de la gratuité non plus, et j'aime bien savoir comment la
gratuité est "financée"
Merci de vos explications.
Fraternellement
Gefe

**Comment by lexoyo** [comment]
C'est une bonne chose de s'intéresser un comment la gratuité est financée, je suis tout à fait d'accord

Github appartient à Microsoft mais leur business model est très intéressant, ils offrent du stockage et de l'hébergement gratuitement du moment que tout est public, open source dans le cas du code. Alors service devient payant dès qu'on désire que nos données soient privées. Il n'y a pas de pub, le service est de très bonne qualité, les développeurs qui sont là cible sont peut-être un produit par contre (recrutement).

L'hébergement pour eux et assez marginal mais je pense que c'est une manière d'attirer plus de développeurs. Il n'hebergent que des fichiers statique donc pas de PHP ni de base de données. ce modèle est bien plus performant est mieux adapté à la plupart des sites, même des sites de vente en ligne. 

Tu peux utiliser github avec silex pour stocker tes fichiers et/ou pour l'hébergement, l'un ou l'autre ou les deux. Il te faut un compte par contre évidemment
