### ISSUE TITLE
[?] What Are The Programming Languages/Frameworks/Libraries/Plugins?

### ISSUE THREAD

**Issue by peterlinus** [silexlabs/Silex#1014]
I am very interested in this project but need some guidance please.
Is there any documentation on what are the programming languages, frameworks, libraries, plugins etc used in this project?
Any documentation explaining what each folder contains?
Any guidance on how to get started to further develop this project would be greatly appreciated. 
What must I learn in order to continue coding this project?
Thanks.

**Comment by lexoyo** [comment]
hi @peterlinus 
there are many ways you can help and you can learn by doing
the project uses a "js" stack: npm, command line, typescript, css, html, nodejs...
are you planning to use silex for something?

**Comment by JbIPS** [comment]
Hi @peterlinus and thank you for your involvment!
I don't think there is such documentation but I can tell you a bit about this project.

### The languages
Silex backend use Node to run but recently we switched to TypeScript which then transpiled to JavaScript.
On the front, it's only JS/HTML/CSS.
You can see the repartition by clicking on the colored bar on top of the repo.

### What goes where
All the source you'd need to edit are in the `src` folder. Inside you'll find a `client` and `server` that separate front and back respectively.

### How to start
The best way to start is by choosing an issue labeled as "Good first issue" or create one with something you want to build and we'll guide you through this first contribution.

**Comment by peterlinus** [comment]
@lexoyo Thanks for replying. 
I am looking into Embedding it into my website and also add custom components, additional functions and features to it.

@JbIPS Thank you for your pointers.
I assumed that means I have to learn TypeScript instead of Nodejs?

**Comment by peterlinus** [comment]
I see that it uses MVC. Is this using any 3rd party framework or it is a custom MVC framework?

**Comment by lexoyo** [comment]
> I am looking into Embedding it into my website and also add custom components, additional functions and features to it.

nice!

> I see that it uses MVC. Is this using any 3rd party framework or it is a custom MVC framework?

just mvc
