### ISSUE TITLE
Section in mobile view visible in all mobile pages

### ISSUE THREAD

**Issue by achuet** [silexlabs/Silex#1016]
Hi, I am getting a problem. In the mobile view, I created a section and make it visible only on a single page. But it is showing on all pages. Could you please tell me how to resolve this. Thank You

**Comment by lexoyo** [comment]
Hello 
Could you share your site please? I'll have a look

**Comment by achuet** [comment]
Hi, Thank You.
This is my website: [https://achuet.github.io/AK//index.html](https://achuet.github.io/AK//index.html)
Desktop is working great. But in mobile view only I am getting this problem

**Comment by lexoyo** [comment]
I'll have a look today

**Comment by lexoyo** [comment]
hi 
i took a look but i don't reproduce the problem, please be clear, describe and screenshots
