### ISSUE TITLE
Close Hamburger menu after click

### ISSUE THREAD

**Issue by Rom025** [silexlabs/Silex#1017]
Hello,
first thanks a lot for Silex and your help :-)
Is it possible to close automatically the hamburger menu after clik on a link?

in advance thank you for your answer.

Kind regards
Romuald

**Comment by lexoyo** [comment]
Hi Romuald, m'y pleasure !
I'm working on the next version which will have far less bugs :)

The menu will close on the publish site because you change page, is it ok with you? Or do you use the site without publishing it?

**Comment by Rom025** [comment]
Hello @lexoyo 
Before your answer I don't use publishing feature because I don't know it, but now I will use it.
It's fine for me.
Many thanks for your quick answer and your help.

Romuald
