### ISSUE TITLE
Rest Call on back API

### ISSUE THREAD

**Issue by The461** [silexlabs/Silex#1018]
Hello,
I wanted to know if it was possible to design your front end web application with Silex and call a backend API (with REST for example) ?

Thank you in advance for your answer

**Comment by lexoyo** [comment]
hello
yes it is
you probably want to use silex to create templates and then you want the content to be taken from an external data source?
can you tell me more about what you want and I will tell you how to do this

**Comment by The461** [comment]
Thank you,
that's right, I'm a front end hater 🗡️
I want to use Silex to design front end part and use REST to call my back end part.
Is there any example to do this? :)

**Comment by lexoyo** [comment]
Ok I see

I use silex with jekyll and it could be what you want to do: I add the templates in HTML Box of silex, then I publish my site in jekyll's layout folder and use the generated pages as templates
With php you could do that with twig templates. Or use jekyll or another static site generator, it's great tech. The HTML box: https://github.com/silexlabs/Silex/wiki/editor-ui#html

I also did a "hosting provider" which is a silex server side component (nodejs) which can transform the website when you publish it. The docs for that: https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure#add-a-custom-hosting-provider-to-silex

**Comment by The461** [comment]
Ok, thank you, it's usefull, I'll look at this :)
