### ISSUE TITLE
different height for section container

### ISSUE THREAD

**Issue by Rom025** [silexlabs/Silex#1024]
Hello, 

I used the blank template and I would like to know if it’s possible to have different size for the « Section Container » in the middle of the page for different pages.  

For exemple in page 1 the middle Section container have 600 px height and 1000px for Page 2 

And keep the « section container » below.

I hope my question is clear. 

In advance, thank you for your help.

Romuald

**Comment by lexoyo** [comment]
Hello
Yes sure it's a common question
You should have different sections visible only on certain pages. The pages will have different heights
You can select on which pages a section is visible in the properties panel, the visibility section
There is a documentation for silex ui, not sure it will be useful, feel free to edit it and make it better
https://github.com/silexlabs/Silex/wiki/editor-ui#properties
Feel free to ask more questions too
Bye!

**Comment by Rom025** [comment]
Many thanks @lexoyo, your answer is very helpfull. I will have a look on the documentation.

Romuald
