### ISSUE TITLE
Gallery and Slideshow widget for Silex #272

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1027]
Hello I seem to be having an issue using the gallery function. when i load up my site the gallery lists the images in full instead of confining them to the size of the html box. the images stay with in the top and side of the element but disregards the height value that was set. Thanks

@lexoyo

Salut Alex, je confirme ce petit bug, Silex charge bien toutes les photos de l'adresse Flickr, mais la galerie, ne reste pas dans la zone HTML défini lors de la conception du site, ce bug existe même en prévisualisation.

Par contre en publication du site, la page reste vierge ...

Voici un lien https://baguetteagile.github.io/essaiSilex/

**Comment by BaguetteAgile** [comment]
@lexoyo 

Salut Alex, ci-dessus le post que tu as pas eu le temps de voir.

Suite au changement du code JS, il y a du mieux ;) maintenant la galerie est visible quand le site est publié.

Cependant il reste un problème majeur, la galerie ne reste pas dans la section HTML définie ( en rose sur le lien)  lors de la conception du site.

En CSS " slideshow" les photos restent bien dans la section HTML, mais il me semble qu'il y a un problème de "zoom" les photos sont zoomer.

Voici un lien https://baguetteagile.github.io/essaiSilex/

clic sur une photo est navigue pour la suivante, il y a un effet étrange..

**Comment by lexoyo** [comment]
Ok je regarde ça bientôt, désolé pour le temps de réponse

**Comment by BaguetteAgile** [comment]
Salut @lexoyo 
si tu as le temps disponible pour jeter un coup d’œil sur cette adaptation du code ...
Merci et a bientôt.

**Comment by lexoyo** [comment]
Salut Baguette
Pour moi ca marche plutot bien, c'est normal que ca dépasse
Si tu veux que la hauteur de la galerie grandisse avec les images, utilise la nouvelle option "layout" sur preprod : mets la html box en "automatic"
Si tu veux des scroll bar et que la galerie ne dépasse pas, mets la classe css "overflow" sur le container (l'intérieur de la section qui est en rose) et ce code dans le css editor
```
.overflow {
  overflow: auto;
}
```

Et pour finir une dernière option : il y a maintenant une option "embed" dans les galeries flicker, ca te donne un html que tu peux coller dans silex
