### ISSUE TITLE
Add css and javascript

### ISSUE THREAD

**Issue by Keestroep** [silexlabs/Silex#1028]
Hello,

I am new to Silex and am still learning.
But somethind i do not understand.

How do i add stylesheets and Javascrpt AND save them thru the editor.
I know i can add a stylesheet, i know there is a css edit, but how to i connect my css code to the added stylesheet.
Same for Java script.

Please help.

Regards,

Kees

**Comment by DurtyDev** [comment]
On the left side where you see <> click on the<>

**Comment by Keestroep** [comment]
Thanks,

But still not clear to me.

On the left site i have a stylesheet editor.
But i cannot give the fie a in the editor. Can i ?

Normally i have a directory with several css files.

I can drag/drop the file into Silex, but how do i edit the one i dropped?
On the right site i see Style Name, where i can change properties of default delivered stylehseet.
But can i also edit them with the css editor?

Regards,

Kees

**Comment by lexoyo** [comment]
hi @Keestroep 

i'm not sure i understand what you mean by "i cannot give the fie a in the editor. Can i ?"

here is a doc about [Silex and CSS](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor) and here is one for [Silex and JS](https://github.com/silexlabs/Silex/wiki/Silex-and-Javascript). i believe they are up to date more or less, feel free to update the docs, it's open

also note that here is what you can do add js and css to silex

1- add code to the css or js editor from within Silex, these will be added to separate .css/.js files when you [publish the website](https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website)
2- include external css/js files by adding an HTML tag to the [HTML head editor or in an HTML Box](https://github.com/silexlabs/Silex/wiki/Silex-and-HTML) 
3- [create components](https://github.com/silexlabs/Silex/wiki/Create-Silex-components) which are html, js and css the users add to their website with the "+" menu
4- add js code to Silex itself - this is not well documented yet but will come soon, in the mean time you can read the [developer guide](https://github.com/silexlabs/Silex/wiki/Silex-Developer-Guide)

**Comment by Keestroep** [comment]
Hi,

This morning i re-read the documentation.
I think i get the point now.
I will try to execute the instructions in the documentation.

Thank you for helping.

Regards,

Harry

**Comment by Keestroep** [comment]
Hi,

Maybe i asked the wrong question.
I usually use this html statement in my idex.html file to reference my stylesheet(s)

<link rel="stylesheet" href="assets/stylesheets/mystylesheet.css" type="text/css" media="screen" />

I suppose this works different with Silex, because i do no see a possibility to add files in a directory of my website.
Am i correct ?

Regards,

Kees

**Comment by lexoyo** [comment]
It is recommended to use case only when necessary with silex, see the widgets (link in menu "?"). This is because css can mess up the editor

That said you can add your css in silex CSS editor, then it will create an external CSS file at publish time. You can add external CSS files too : use the file explorer (menu "cloud") to upload the files and import them in the HTML editor

**Comment by Keestroep** [comment]
That is the part is have trouble with.

I have a css file in Dropbox.
I use Cloud - File Explorer to select this file.

But then nothing happens.
When i click the CSS editor, i see nothing.
When i publish the website to Github, no extra files is created.

What am i doing wrong?

**Comment by lexoyo** [comment]
Oh ok
You need to copy and paste the content of the file to the CSS editor, this is the easiest way

**Comment by DurtyDev** [comment]
It also works better if you use .less css, it's Jade now known as PUG.
Silix also utilizes the Monaco Editor which you can update from the
Microsoft repository. Because of Visual Studio insisting that a step by
step build take place, I now have an appx package for UWP all I really have
to do for a fully functional is insert the silex.me server.
