### ISSUE TITLE
Deleted pages briefly visible.

### ISSUE THREAD

**Issue by barkingPete** [silexlabs/Silex#103]
Description:
I make a set of 5 web pages in Silex V2 (online) but don't link them. Just 5 pages with graphics inserted. When I use "View"- "view in new window" to preview the pages I just see the first page. And that is correct. 
I now delete the first 4 pages - leaving only the 5th/last page and save that.  When I  preview the single page I often see a quick succession of the deleted pages before the final page is displayed correctly. This is most noticeable the first time as the caching does not affect the speed of loading.
This is not a "big bad bug" but it might be worth noting that it occurs in case that influences future design decisions.

**Comment by singchan** [comment]
fixed
