### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by Keestroep** [silexlabs/Silex#1031]
Hi,
For two days i try to add an animation into my website, but i am failed to do so.
The animation does not show.
Please help.

I used #87 as instruction.

I made a very basic template with one html box and one text box

On github i have a branch "rotzooi" with a sub-dir "css" where i put the "animate.css" file

CSS Editor	
	.paged-element-hidden.animated {  animation-name: none !important;}

Java Script Editor: see attached file
![boxjs](https://user-images.githubusercontent.com/66176403/84592780-5da20900-ae48-11ea-9810-5f57e341a229.PNG)

I click on the html-box i added
I go to the right site and go below to CSS - CSS classes Help
In the box i entered 2 words:	animated fadein		
I did the same for the text box

I saved, i used Preview, and i Publised, bot none of them show an animation
I tried Chrome and Firefox.

![box](https://user-images.githubusercontent.com/66176403/84592718-0e5bd880-ae48-11ea-8fc5-c8f881113f85.PNG)

What am i doing wrong?

Regards,

Kees

**Comment by lexoyo** [comment]
Hi @Keestroep 

This post is quite old (2014) so I updated with the latest version of animate.css

Read the updated post and see that you need to do this

1. remove the "document.write" line from the JS editor, and add a line to the HTML Head editor instead
2. change the css class of the animation with one of the new names

Let me know if you need more help

**Comment by lexoyo** [comment]
Also if you make screenshots for the new version, maybe we could add them to the widget
Or a video or text corrections
That would be cool

**Comment by Keestroep** [comment]
Yes,

This worked for me.

Simple example:
- download the file animate.min.css and put it in the css directiry

- Create a hmtl box

![html_box](https://user-images.githubusercontent.com/66176403/84802712-46f2e200-b001-11ea-980f-64b7d1884613.PNG)

- open the HTML head editor (in the menu "< />") and paste this code anywhere.
<link href="./css/animate.min.css" rel="stylesheet">

![html_editor](https://user-images.githubusercontent.com/66176403/84802745-4f4b1d00-b001-11ea-97fa-411a9f2565e3.PNG)

- Then open the CSS script editor and add these lines
/* for firefox */
.paged-element-hidden.animated{
    animation-name: none !important;
}
/* */
![css_editor](https://user-images.githubusercontent.com/66176403/84803022-b072f080-b001-11ea-958e-7708b824d93b.PNG)

Select an element and look at the properties tab, in "style" section, add the CSS classes animate__animated and another one

animate__animated
animate__swing

![css_class](https://user-images.githubusercontent.com/66176403/84803065-c5e81a80-b001-11ea-97c7-3ecf4531947e.PNG)

Thanks

Regards,

Harry

**Comment by lexoyo** [comment]
Cool! thx for the screenshots :)
