### ISSUE TITLE
Sections Not Displaying on landing page

### ISSUE THREAD

**Issue by nicodt** [silexlabs/Silex#1033]
I have more than once section on my landing page but only the first one will display when opening the webpage only when I select the menu again eg. Home all the sections display. Nice tool though!!!

**Comment by lexoyo** [comment]
Hi @nicodt 

I believe I saw this in preview of a website but it will not affect the site after publication
https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website

Can you confirm?

Also this should be fixed in the next release

**Comment by nicodt** [comment]
Hi @lexoyo it in fact does influence my website after publication exactly the same as what it influenced it in the reactive viewer.

**Comment by lexoyo** [comment]
Could you show me an example please?

**Comment by nicodt** [comment]
@lexoyo Sure just remember I am an embedded Linux developer :-) hence using the tool. 
[rushiv](www.rushiv.co.za) is the hosted site and is live. Just a small caveat I have just sofar designed for mobile there is basically nothing on my desktop view as of yet hope this does not have an effect so to experience what I am experiencing take a mobile view rather you will see only the top section/div will display after that click on the hamburger menu and click home again then only all the divs or sections will display. If you need anything else please tell me and thanks for responding.

**Comment by lexoyo** [comment]
Ok I see
This is the preview version
You need to publish it with the "publish" command from the "cloud" menu

**Comment by nicodt** [comment]
@lexoyo ok when in doubt RTFM (read the fucking manual) thanks dude you are legend.
