### ISSUE TITLE
Trying to get prodotype to run as a web app

### ISSUE THREAD

**Issue by DurtyDev** [silexlabs/Silex#1034]
attempting to create a web app from prodotype , and silex templates. 
get everything together in a node.js
npm install electron
npm install silex
npm install silex templates
npm build doesn't work, however i can choose build from options. 
the server says type= text
any sugesstions? using windows visual studio 2019

**Comment by lexoyo** [comment]
Hi
You should look at how [the app hosted on editor.silex.me](https://github.com/silexlabs/editor.silex.me) is done
Is it what you are trying to do? Let me know if you have questions

**Comment by DurtyDev** [comment]
Yes sir.
