### ISSUE TITLE
Cannot publish site to FTP server- using online version of Silex

### ISSUE THREAD

**Issue by arkagi** [silexlabs/Silex#1040]
Hello I'm using the online version of Silex, and trying to publish to my own FTP server.
I get the error:
"I did not manage to publish the website. Cannot read property of 'size' undefined."

I know that Silex can properly connect to the server because under the publish settings, it has logged into 
the FTP server and I can select the folder of where to publish the site.

Any suggestions to fix this?

Thanks.

**Comment by lexoyo** [comment]
Hello
Could you try on https://preprod.silex.me please and see if it is fixed?
Backup your site before you save, because a site saved on preprod can not be opened on editor anymore
Thx

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
Sorry I get the same error using the pre-production version.
Saving the editable.html works, but for some reason it doesn't save to the specified folder.  For example, if I specify the publish settings as   mysite.com/htdocs/abc  it saves editable.html to mysite.com/htdocs/
This happens in the current online version too.

**Comment by arkagi** [comment]
sorry closed by mistake

**Comment by lexoyo** [comment]
After thinking about it, the best options if ftp does not work for you:

* Publish to Dropbox or GitHub and download the files of the published site
* Or use the desktop version of Silex to publish to a local folder (https://github.com/silexlabs/silex-desktop/releases/)

Then upload the files with an ftp client

**Comment by gitonim** [comment]
> Hello I'm using the online version of Silex, and trying to publish to my own FTP server. I get the error: "I did not manage to publish the [website](https://ductscleaning.com.au/). Cannot read property of 'size' undefined."
> 
> I know that Silex can properly connect to the server because under the publish settings, it has logged into the FTP server and I can select the folder of where to publish the site.
> 
> Any suggestions to fix this?
> 
> Thanks.

I am also facing the same problem if you have found the solution then do tell me as well

**Comment by lexoyo** [comment]
Hello
This issue is supposed to be fixed
A quick workaround would be to publish to Dropbox or GitHub then download as zip and upload it to your server
But you could also run silex locally (see install silex with npm in the docs), it will probably show more detailed errors in the command line
Or try silex desktop maybe?

**Comment by gitogithub** [comment]
> > Hello I'm using the online version of Silex, and trying to publish to my own FTP server. I get the error: "I did not manage to publish the [website](https://ductscleaning.com.au/). Cannot read property of 'size' undefined."
> > I know that Silex can properly connect to the server because under the publish settings, it has logged into the FTP server and I can select the folder of where to publish the site.
> > Any suggestions to fix this?
> > Thanks.
> 
> I am also facing the same problem if you have found the solution then do tell me as well

Today same issue here

**Comment by lexoyo** [comment]
Oh old issue
Ça you give me details pls?

* you use v3.silex.me?
* what browser
* what hosting company ?

**Comment by gitogithub** [comment]
you use v3.silex.me? Not yet
what browser? Chrome
what hosting company ? Tophost

However, I used dropbox as workaround. Thanks!

**Comment by lexoyo** [comment]
Ah ok
I'm glad you found a workaround
how is your experience with Silex ? What is your project ?
