### ISSUE TITLE
beta download problem

### ISSUE THREAD

**Issue by diogov0299** [silexlabs/Silex#1041]
Hey, when i download the offline beta, i can't find an executable in the downloaded zip.. I don't know if i am missing something!

Thank you :)
**_UPDATE: I managed to find help online, but now i am stuck on the install dependencies part_**

**Comment by lexoyo** [comment]
Hello
Could you explain what you did please? What did you download etc
Also what is your OS ?

**Comment by lexoyo** [comment]
Also here are the latest downloads
https://github.com/silexlabs/silex-desktop/releases/

**Comment by lexoyo** [comment]
Feel free to reopen the issue when you are back :)
