### ISSUE TITLE
Bug: Impossible d'importer un site existant !

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1046]
@lexoyo 
Bonjour Alex,

depuis quelques jours, il est impossible d'importer ou d'ouvrir un site web aussi bien sur Dropbox que Github.
J'ai le message aussi bien sur Editor.silex et Preprod.

Voici le message d'erreur.

![Capture du 2020-09-14 15-56-54](https://user-images.githubusercontent.com/35597855/93095625-a1084f80-f6a3-11ea-82ad-3964e9120105.png)

Par contre les templates s'ouvre parfaitement.

**Comment by lexoyo** [comment]
hello
ouah j'ai fait une grosse boulette la
je fix ca ce soir
merci @BaguetteAgile !!

**Comment by lexoyo** [comment]
voila c'est fix @BaguetteAgile 
tu peux me confirmer ?

**Comment by BaguetteAgile** [comment]
Mauvaise nouvelle @lexoyo 

Silex cherche indéfiniment...

voici les captures d’écran:

![Capture du 2020-09-14 19-43-52](https://user-images.githubusercontent.com/35597855/93120000-fe5fc900-f6c2-11ea-88ae-c5486bed0a29.png)


![Capture du 2020-09-14 19-44-11](https://user-images.githubusercontent.com/35597855/93120027-07509a80-f6c3-11ea-8121-384f957b8762.png)


![Capture du 2020-09-14 19-44-52](https://user-images.githubusercontent.com/35597855/93120036-0ae42180-f6c3-11ea-8f35-794e1177d65f.png)

**Comment by lexoyo** [comment]
Ah oui ça c'est normal, ouvre le déjà une fois en cliquant sur import stp
