### ISSUE TITLE
silex desktop for Windows

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1048]
Windows build is failing

* First failing build: https://github.com/silexlabs/silex-desktop/runs/743414113?check_suite_focus=true
* So I removed windows https://github.com/silexlabs/silex-desktop/commit/6c32713147d7f1917154b6a3b2bcce8f33025b0f

Try with "windows-2016" as suggested here

https://gist.github.com/azu/673426500458f63f019c8f5e013f282a

**Comment by DurtyDev** [comment]
I'm still using 5.06

**Comment by lexoyo** [comment]
this issue is finally fixed :pray: by this commit
https://github.com/silexlabs/silex-desktop/commit/6b24db262812b926bd7cf34380209f6fa3a2cc26

the release with windows app is available here
https://github.com/silexlabs/silex-desktop/releases

please help me test :fire: !

cc @ceubri

**Comment by DurtyDev** [comment]
Downloading it now

**Comment by lexoyo** [comment]
Ok thx @DurtyDev 
Fingers crossed (I don't have windows)

**Comment by DurtyDev** [comment]
Java error on install. Missing the npm package

**Comment by lexoyo** [comment]
ok thx @DurtyDev , I'll fix this new issue

**Comment by DurtyDev** [comment]
Won't let me post a screenshot cause  it's too big.

**Comment by lexoyo** [comment]
hello @DurtyDev @ceubri
it is now working on windows ! (i believe, could you test?)
https://github.com/silexlabs/silex-desktop/releases/tag/v2.7.9

**Comment by DurtyDev** [comment]
Okay. Will download and let you know. Thanks for the hard work

**Comment by ceubri** [comment]
yes it's alive !!! 
There is just a warning, but after it's installing normally.
GREAT
![image](https://user-images.githubusercontent.com/7302680/98515533-7a156680-226b-11eb-9501-036fa95dc544.png)

**Comment by DurtyDev** [comment]
New version installed without a hitch this time. Like the new options (
div, nav, etc)

**Comment by lexoyo** [comment]
Excelent! Thank you for the update :)

**Comment by DurtyDev** [comment]
This version is spectacular. Good work

**Comment by ceubri** [comment]
However I couldn't quit the program... 
I had to "force to quit" (ctrl+Alt+Supp)...

**Comment by lexoyo** [comment]
Thank you @DurtyDev :smile: 
Ok @ceubri I'll create a new issue thx
