### ISSUE TITLE
Balise <body>

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1053]
Salut @lexoyo 
J'ai un bout de code que je dois intégrer a chaque page de mon site juste après la balise <body>

Comment faire directement dans Silex ?
Ou
Comment faire directement dans chaque page .html

C'est un code de Google Tag Manager.

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=***********"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

Merci.

**Comment by lexoyo** [comment]
Salut baguette !
Moi je la mets dans un HTML box que je mets sans couleur donc qui est invisible

**Comment by BaguetteAgile** [comment]
Oh..... aussi simple que ça ... ;) ;) ;)

Je test et j'espère réussir a faire fonctionner ma balise.

C'est pour réussir a prendre la main sur "Google Analytics" pour empêcher qu'il se charge a l'ouverture du site, pour le RGPD

**Comment by lexoyo** [comment]
Intéressant !
Tu sais comment respecter RGPD avec GTM?

**Comment by BaguetteAgile** [comment]
`Intéressant !
Tu sais comment respecter RGPD avec GTM?`

En faite j'ai besoin de GTM pour que `Axeptio` prenne la main sur les cookies du site

https://www.axeptio.eu/

Si tu as le temps, peux tu me dire si les cookies de mon site sont bien bloquer avant l'acceptation de l'utilisateur, parce que là je nage un peu...

C'est `Axeptio` qui gère les cookies via GTM

https://rvmproduction.netlify.app/

**Comment by lexoyo** [comment]
Ah c'est super intéressant ce acceptio

Dans ton site, meme sans avoir accepté les cookies, tu as ces services qui posent deja des cookies

* facebook
* google translate
* un truc de font

![Screenshot from 2020-11-02 17-07-48](https://user-images.githubusercontent.com/715377/97890666-18ff0780-1d2e-11eb-88a7-f5b34aaba2a2.png)
![Screenshot from 2020-11-02 17-05-23](https://user-images.githubusercontent.com/715377/97890676-1b616180-1d2e-11eb-8e62-ff2c6c7160f1.png)

**Comment by BaguetteAgile** [comment]
Pour le moment avec `Axeptio` je bloque les cookies de `Google Analytics et le pixel de Facebook.`
avec la version gratuite, ns avons que cette possibilité. 
En prenant une version payante le nombre de cookies est illimité, mais il faut compter 150€ pour une année rien que pour la gestions des cookies.

Ce système est vraiment pas mal du tout, en plus c'est Français !!

J'essai de le faire fonctionner correctement avec la version gratuite déjà. 
c'est vraiment pas évident de trouver un outil performant gratuit. 

J'avais trouver ceci
https://www.cookiebot.com/fr/

mais cette solution casse le code de Silex, et le site ne ressemble plus a rien, une fois en ligne ( Le Preview et OK mais en ligne c'est la cata ... )

Il faudrait, si tu as le temps que je mette une version en ligne afin que tu jette un œil au problème.

**Comment by lexoyo** [comment]
> J'avais trouver ceci
> https://www.cookiebot.com/fr/
> mais cette solution casse le code de Silex, et le site ne ressemble plus a rien, une fois en ligne ( Le Preview et OK mais en ligne c'est la cata ... )
> Il faudrait, si tu as le temps que je mette une version en ligne afin que tu jette un œil au problème.

oui ca serait un super travail d'equipe :)
n'hésite pas

**Comment by BaguetteAgile** [comment]
@lexoyo 

Salut Alex, je viens de mettre en ligne la version avec le consentement cookies, qui je pense ne fonctionne pas ! 

Donc pour mettre en place cette solution il faut coller un script dans le Head et insérer un autre script dans le code HTML de la page spécifique et à l'emplacement exact où vous souhaitez que la déclaration relative aux cookies apparaisse.

script du head

`<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="54761351-d90c-441c-a933-914d94a4aefe" data-blockingmode="auto" type="text/javascript"></script>`

script a placer dans la page html ( que j'ai placer dans une box html en transparent et sur toute les pages )

`<script id="CookieDeclaration" src="https://consent.cookiebot.com/54761351-d90c-441c-a933-914d94a4aefe/cd.js" type="text/javascript" async></script>`

http://www.calicebluesrock.be/index.html

**Comment by lexoyo** [comment]
Yes c'est super !
Ca marche tres bien je viens de tester
