### ISSUE TITLE
Running Silex Web locally with hot reload 

### ISSUE THREAD

**Issue by Chetan11-dev** [silexlabs/Silex#1070]
Steps performed 
 npm run start:debug 
 npm run watch
I am attempting to run Silex with hot reload to inspect the state of some component I tried to do a console.log in src/ts/client/App.ts  
Now Both commands have recognized the update and rebuilt project in dist folder but in the browser the  console.log statement do not appear. 
I believe it is my lack of knowledge about editor. Please guide me.

**Comment by Chetan11-dev** [comment]
Output of npm run start:debug and npm run watch respectively on update
![Screenshot from 2020-11-24 20-40-52](https://user-images.githubusercontent.com/53407137/100112679-8584a680-2e95-11eb-9803-9aed8fca27d9.png)

Silex Editor console panel in browser 
![Screenshot from 2020-11-24 20-40-38](https://user-images.githubusercontent.com/53407137/100112741-96cdb300-2e95-11eb-8c2f-3e27b3b06ab6.png)

**Comment by Chetan11-dev** [comment]
I expect this statement to log '   Silex   ' in console panel but it does not 
![Screenshot from 2020-11-24 20-43-31](https://user-images.githubusercontent.com/53407137/100113042-e9a76a80-2e95-11eb-8ca6-d2c013e194ae.png)

**Comment by lexoyo** [comment]
hello
so this is what i understood:

* you did both npm run start:debug and npm run watch
* the watch rebuilds the site
* when you reload the page you don't see the console log

is this correct?

it is surprising because you are clearly supposed to see the console log
did you try to run `npm run build` and then `npm start` ?

**Comment by Chetan11-dev** [comment]
Thank you lexoyo for prompt reply.
Here is what i did 
Frest clone of repo 
made changes to app.ts added  console.log statements 
ran npm run build, npm run start 
Result: Not able to see console.log. 
Suprisingly when I searched for keyword I wrote in console.log I see code has actually been immited in dist/main.js
![Screenshot from 2020-11-25 19-54-46](https://user-images.githubusercontent.com/53407137/100240074-289df480-2f58-11eb-980b-5a990466794b.png)

**Comment by Chetan11-dev** [comment]
Could we do a Google Meet Meeting to screenshare on a window between 10:00 am to 4:00 pm in CET timezone (You may give me time window which is comfortable to you and we would joint the meeting) and resolve issue quickly. Once again Alex Thanks for your help.

**Comment by lexoyo** [comment]
> Suprisingly when I searched for keyword I wrote in console.log I see code has actually been immited in dist/main.js

this is really strange
maybe try to put it higher in the file?

> Could we do a Google Meet Meeting to screenshare on a window between 10:00 am to 4:00 pm in CET timezone (You may give me time window which is comfortable to you and we would joint the meeting) and resolve issue quickly. Once again Alex Thanks for your help.

In open source we don't usually do that my friend :)
Let's try a little bit more here and we will do that in cas it is really needed

In any case, could you let me know what you are trying to achieve?
Also you can commit your test somewhere and I'll look into it

**Comment by Chetan11-dev** [comment]
I maybe due to caching. I disabled cache Thanks to https://stackoverflow.com/questions/5690269/disabling-chrome-cache-for-website-development 
Thank You Alex for your time

**Comment by Chetan11-dev** [comment]
One more question could you tell me the code location of 
where bottom component is located?
![Screenshot from 2020-11-27 05-49-31](https://user-images.githubusercontent.com/53407137/100398403-70b23980-3074-11eb-96e5-dc408817cd45.png)
where onChange handler of component fires say change in color of component?

**Comment by lexoyo** [comment]
Sure
This component is called breadcrumbs, it is in src/ts/client/components
If you are planning to contribute, it is best to discuss the what and how beforehand :)

**Comment by Chetan11-dev** [comment]
I am Author of Dart Code Generation Tool (https://marketplace.visualstudio.com/publishers/ChetanJain). I am working on learning dnd web builder architecture similar to your open source project which will be done in reactjs.

**Comment by Chetan11-dev** [comment]
I believe I have expierience of doing file handling. So this feautre could be developed by me
https://github.com/silexlabs/Silex/issues/625
Questions: 
Where is Code located performing this operation(creates .html file, assets )? 
What call tiggers this operation (I mean where is onClick of this
![Screenshot from 2020-11-27 14-20-16](https://user-images.githubusercontent.com/53407137/100429740-c2ca7d80-30bb-11eb-86b5-2370bc25edac.png)
)?

**Comment by Chetan11-dev** [comment]
Sorry Alex I do not mean to offend you but I am currently not ready for open source contribution.

**Comment by lexoyo** [comment]
Hey @Chetan11-dev you did not offend me 
I was just worried that you would work on something and then discover that it already exists in silex or something like that :)
How is your learning?
