### ISSUE TITLE
renaming a style isn't applied to all instances

### ISSUE THREAD

**Issue by sidmint** [silexlabs/Silex#1075]
Two things:

1. When I rename a style at one place/instance, and if the style is present at multiple instances, then the renamed styled won't get applied automatically at other instances and other instances switch to 'All style' instead requiring to be applied the renamed style manually.
2. If I rename a style without selecting any element and go forward ignoring the warning 'you need to select at least one element....', then all the instances of that style switch to 'All style' instead of getting renamed, which i expected.

**Comment by lexoyo** [comment]
Thank you @sidmint for the bug report, I will look into it

**Comment by lexoyo** [comment]
@sidmint is this still relevant?

**Comment by lexoyo** [comment]
@sidmint I just published a bug fix for the style editor, please test again and let me know if your 2 bugs are still there?

**Comment by sidmint** [comment]
> let me know if your 2 bugs are still there?

both bugs not fixed yet.

**Comment by lexoyo** [comment]
ok I'll look into it soon
thx

**Comment by lexoyo** [comment]
> When I rename a style at one place/instance, and if the style is present at multiple instances, then the renamed styled won't get applied automatically at other instances and other instances switch to 'All style' instead requiring to be applied the renamed style manually.

thank you @sidmint this was a tricky bug to report
[here is the fix I did](https://github.com/silexlabs/Silex/pull/1102/commits/8c8b9bef9c5458729c56197f8ecea2d153e4c8c9), it will be live in the next release

you can test it [here on staging](https://preprod.silex.me/)

> If I rename a style without selecting any element and go forward ignoring the warning 'you need to select at least one element....', then all the instances of that style switch to 'All style' instead of getting renamed, which i expected.

I could not reproduce this, could you check if it is fixed by the fix of the first issue please?

**Comment by sidmint** [comment]
> could you check if it is fixed by the fix of the first issue

Thanks, it got fixed too.
