### ISSUE TITLE
Crash on Add Element>Image> 3216 x 2936 (96dpi)

### ISSUE THREAD

**Issue by form-and-void** [silexlabs/Silex#1076]
I am new here so I am not sure if this is the right place, but wanted to report that multiple attempts of adding an image element to the startup template (with the sailboat) caused the program to freeze, then crash entirely without saving work. I am not sure if I can help solve this problem, but hope this report is helpful. Great product by the way!

**Comment by lexoyo** [comment]
Hello @form-and-void and welcome
What is the browser you are using please?

**Comment by lexoyo** [comment]
@form-and-void is this still relevant?
