### ISSUE TITLE
Blocages & cadenas

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#108]
-- @ceubri : <i>ce serait pratique de pouvoir bloquer la position des éléments.</i>

Se serai bon ,aussi, de bloquer se que l'on souhaite : position, dimension et autres; ce qui permettrai de pouvoir modifier seulement le contenu ou certaines valeurs ? (case à cocher près des valeurs X,Y,W,H ?).

**Comment by lexoyo** [comment]
Votez pour moi, mettez des :+1:
