### ISSUE TITLE
Application error when I publish website

### ISSUE THREAD

**Issue by fernandammoutinhobarros** [silexlabs/Silex#1083]
Hi @lexoyo 

I've tried to publish on silex and on prepod.silex, but I get this error.
It was working fine, as you can see here
http://www.consulpav.com/rar2021/test/
I'm using one of your templates

But now is crashing when I publish. How can I solve this?

![image](https://user-images.githubusercontent.com/25388113/105041024-6a2fb500-5a5a-11eb-8060-385564f3961d.png)
"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail"

**Comment by lexoyo** [comment]
hello
i will look into that
maybe you can try with silex desktop app?
https://github.com/silexlabs/silex-desktop/releases/tag/v2.7.14

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo  

Thanks.
What's the wright file, for windows 10?

**Comment by lexoyo** [comment]
The .exe

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo 
when try I Install I get this error. 
I  tried with admin priveliges.

Translated: "Windows cannot access the specified device, path or file. The user may not have the appropriate permissions to access the item."

![image](https://user-images.githubusercontent.com/25388113/105058562-424a4c80-5a6e-11eb-9809-7af3b89eeb1d.png)

**Comment by lexoyo** [comment]
Oh ok :-/
Windows did not ask for permission?

**Comment by fernandammoutinhobarros** [comment]
nop, i runned the file as admin

**Comment by fernandammoutinhobarros** [comment]
Silex editor is down


![image](https://user-images.githubusercontent.com/25388113/105061976-031dfa80-5a72-11eb-9a5e-8e3adccb085b.png)

**Comment by fernandammoutinhobarros** [comment]
Ok.
I was able to install desktop version on admin account.
Tried to publish but this happens
![image](https://user-images.githubusercontent.com/25388113/105103454-88bc9d00-5aa8-11eb-88f9-249308498b62.png)

**Comment by lexoyo** [comment]
hi @fernandammoutinhobarros 
could you try with preprod.silex.me please?

**Comment by lexoyo** [comment]
i just tried to fix the problem but i have too little info
still i updated editor.silex.me and preprod.silex.me so you can try again
we have had problems with the server so maybe you just tried while it was down

**Comment by fernandammoutinhobarros** [comment]
Tried with prepod and this happens


![image](https://user-images.githubusercontent.com/25388113/105156527-e0d4bd00-5b03-11eb-9150-cf967bf3da9d.png)

**Comment by lexoyo** [comment]
wow
can you try again please? 
https://preprod.silex.me/
these are temporary errors

**Comment by fernandammoutinhobarros** [comment]
with prepod

![image](https://user-images.githubusercontent.com/25388113/105162740-eaadee80-5b0a-11eb-87c3-4f038f735c94.png)

**Comment by fernandammoutinhobarros** [comment]
https://editor.silex.me/
not working
stops here
![image](https://user-images.githubusercontent.com/25388113/105163154-73c52580-5b0b-11eb-8cbe-f5ee5c0b0e2d.png)

**Comment by lexoyo** [comment]
https://editor.silex.me/ is definitely up, what is your browser?

for the publication error, could you share your site with me plz?

**Comment by fernandammoutinhobarros** [comment]
The editable file?

**Comment by lexoyo** [comment]
Yes
The HTML and the json files

**Comment by fernandammoutinhobarros** [comment]
I'm using chrome.
Which one works best?

**Comment by fernandammoutinhobarros** [comment]
Tried silex editor on mozzila and it's working, but it still doesn't publish the webpage.

![image](https://user-images.githubusercontent.com/25388113/105171688-737e5780-5b16-11eb-933d-3da18ab39131.png)

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo 

Rebuild the page, using the prepod on mozzila, but the same happens when i publish

Tried again with editor on mozzila and same happens.

![image](https://user-images.githubusercontent.com/25388113/105353062-ab54d000-5be6-11eb-86f8-88a44f636382.png)

**Comment by lexoyo** [comment]
I tried and it works well for me
Could you try to publish to a new folder in your dropbox or a new repo in github?

**Comment by fernandammoutinhobarros** [comment]
Ok.
I opened on the desktop version, and for now it's working.
I will try later on the browser

**Comment by lexoyo** [comment]
Ok great!
I think it was a temporary server problem
Let me know if you have this issue again
Obrigado ;)

**Comment by fernandammoutinhobarros** [comment]
ok

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo 

Just to give you an update, although this subject is closed.  😎

I used it again in the online editor, to test it and this time it published without errors, even the version that gave errors.
It must have been a big bug.

I think it has something to do with copy&paste of the page elements, when I copy an element that I want to repeat, after that when I publish, it gives errors. If I do every element from scratch, nothing happens... Or not... 🙄😶

The final version of the page is [here](http://www.consulpav.com/rar2022/)

thanks for the help  👍 😊

**Comment by lexoyo** [comment]
Great !

I appreciate the feedback, thx Fernanda

Your website looks good! You should add this css code in order to get 
ridd of the horizontal scroll

```

body, html { overflow-x: hidden; }

```

**Comment by fernandammoutinhobarros** [comment]
Great,

thanks for the css tip!😀
