### ISSUE TITLE
help me upload Siliex builder to my hosting account

### ISSUE THREAD

**Issue by ilham45** [silexlabs/Silex#1084]
Hi there. 
Any chance to help me to upload Siliex builder to my hosting account , Include admin area 
Thank you 
ilham

**Comment by lexoyo** [comment]
hello @ilham45 
here are the docs you need
https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure

**Comment by lexoyo** [comment]
Or maybe this one to start
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex
