### ISSUE TITLE
slideshow does not work in small cellphone screen

### ISSUE THREAD

**Issue by gtiani** [silexlabs/Silex#1092]
I'm trying to use the slideshow feature. For the large computer screen it works fine. When I switch to the small cellphone screen, the images are huge and extend beyond the slideshow box size. The arrows are shifted way outside the slideshow box and I have no control over the size. I'm in absolute mode. But, changing the values in the height and width do not change the window size. The image remains huge and uncontrollable.
Is the slideshow feature supposed to work in the small screen mode? 
I have a crude website to test some of the features at mistibooks.com
On a computer it looks alright.
On a cellphone, it looks terrible with the arrows way outside of the box and the slideshow image huge. Scrolling to the top of the site and pressing the arrow buttons actually does change the image lower down. But, everything is a real mess and I don't have any control over size or position in the cellphone mode.
Any help or suggestions would be greatly appreciated.
Sincerely,
Gary

**Comment by lexoyo** [comment]
hello @gtiani 

> Is the slideshow feature supposed to work in the small screen mode?

yes it should be mobile friendly

On mistibooks.com I see a problem with the slideshow UI, I will look into this soon

In the mean time here is a fix you can paste in the CSS editor:

```
.unslider {
    position: absolute;
    margin-left: -20px;
}
```

**Comment by gtiani** [comment]
Hello Alex,
Do I paste that in after the other CSS text like this: (the first 2 lines were already there)

silex-component-slideshow
silex-use-height-not-minheight
.unslider { 
position: absolute;
margin-left: -20px; 
}

I don't see any difference in the behavior. The image in mobile is still huge.
I selected the slideshow then added the text to CSS. 
Did I miss something?

**Comment by gtiani** [comment]
If it means anything, while in the Silex editor in mobile mode, if I move the mouse over the slideshow and hold the left mouse button down, the image immediately changes to fit inside of the slide show. As soon as the left mouse button is released, the image immediately changes to huge.

**Comment by lexoyo** [comment]
Could you paste the whole content of the CSS editor please?

I don't see a huge image on a mobile phone on mistibooks.com, is it only in the editor?

**Comment by gtiani** [comment]
You're right. The huge image is on the Silex editor. On the actual mobile website, the image is ok. However the control arrows are way outside of the slideshow window.
Here's the CSS:
.unslider {
    position: absolute;
    margin-left: -20px;
}

**Comment by lexoyo** [comment]
My bad, please replace you CSS with this:

```
@media (max-width:480px) {
    .unslider {
        position: absolute !important;
        margin-left: -20px !important;
    }
}
```

**Comment by gtiani** [comment]
That last change did not seem to do anything.
This CSS did something. I added the border just to see if it worked. The image for mobile is now contained. However, I can no longer move the slide show. The mouse will move it. But, then the slideshow jumps back to where it was. I'm new to CSS. Any suggestions would be appreciated. So far, I seem the slideshow window seems to be locked to a location that I can't change.

.silex-component-slideshow {          (***needed this to get anything to happen***)
    .unslider {
        position: absolute !important;  (***the "relative" did not work***)
        border: 9px solid black;  (***added this just to see something happen***)
    }
}

**Comment by gtiani** [comment]
Has anyone actually seen the slideshow work in both the large screen and mobile mode? 
If it is possible, I will keep trying. It looks like a great function if I works. It's very frustrating not to be able to move the slideshow window. It seems to like one location and refuses to move.

**Comment by lexoyo** [comment]
@gtiani I did the test, just a simple slideshow in an empty page

[Here is the result](https://lexoyo.me/silex-tests/slideshow/)

Thanks to the code I pasted the slideshow works fine on mobile

**Comment by gtiani** [comment]
Thank you, Alex.
I have enough workarounds now. I can get both large screen and mobile working. I just have to get used to using Silex. 
Thank you for all your help and thanks for making Silex available in the public domain.
Sincerely,
Gary

**Comment by lexoyo** [comment]
Your very welcome!
Also I just fixed the bug, so next time you add a slideshow you will not need the workaround
Have fun!

**Comment by gtiani** [comment]
I still have to add this to the CSS editor so the image stays inside of the slideshow window for mobile mode (while in the Silex editor) when I add a new Slideshow.
.silex-component-slideshow{ 
position: absolute !important;
margin-left: -20px; 
}
