### ISSUE TITLE
host URL rather than custom domain shows on website and email forms

### ISSUE THREAD

**Issue by gtiani** [silexlabs/Silex#1093]
I'm not sure if this is a Silex issue or not. When I type in "mistibooks.com" into the browser URL, the site opens but then displays "https://jolly-joliot-2c1793.netlify.app/" in the URL (the hosting URL). Also, when an email is sent from the website to Formspree, the forwarded email shows the message "https://jolly-joliot-2c1793.netlify.app/".
Is there a way to only show "mistibooks.com" and never see the netlify message?
I tried the Stealth URL feature from the DNS account. But, it fails and says the host website does not support Stealth URL.
Sincerely,
Gary

**Comment by lexoyo** [comment]
hello
yes there is a way to do that in netlify
did you look into the "dns" settings?

**Comment by lexoyo** [comment]
hi @gtiani is this still relevant?
