### ISSUE TITLE
Setting the reply_to field in the contact form

### ISSUE THREAD

**Issue by gtiani** [silexlabs/Silex#1094]
From Silex, I add a contact form and set all the fields. The form gets sent to formspree and then gets forwarded to the recipient fine. But when the recipient replies, the reply field is set to "Formspree <noreply@formspree.io" rather than the recipient. Formspree says there is a field "reply_to" that should be set. Is there a way to set the "reply_to" field from Silex?
The email show these fields:
field1: Gary (I also tried putting the email address here but that didn't help)
field2: gtiani@rcn.com
field3: "test message text entered here"
I don't see any other fields to set. Is there a way to a "reply_to" field?
Sincerely,
Gary

**Comment by lexoyo** [comment]
Hello
There is no way to do that with the form component, you would need to use the HTML form (and then you can use netlify forms) and create a form in HTML. Or you could use mailchimp to create a subscription form. 
Why would you need that? You receive the email anyway right?

**Comment by gtiani** [comment]
Yes, the email comes through fine. But, normally, clicking on reply is all that's necessary. Now, I have copy the email address from field2 and paste it into the "to" field. If I forget to do that, I end up replying to nobody.
I'll try the HTML approach. I don't know HTML. So, another opportunity to learn, I guess.
Thanks,
Gary

**Comment by lexoyo** [comment]
Gary, thos is currently not possible with the form component

you cab create HTML forms with an HTML box or use MailChimp for example
