### ISSUE TITLE
Browser Not Showing Well

### ISSUE THREAD

**Issue by DemonRem** [silexlabs/Silex#1095]
i create my website portal but seems its look ugly and i cant find the reason of it
well this zip is the website index and rest files except my content data and i prefer not upload it

[web.zip](https://github.com/silexlabs/Silex/files/6291324/web.zip)

and as real website its show like that 

photo 1 the editor

![1](https://user-images.githubusercontent.com/29927382/114295620-0d6af600-9aaf-11eb-91a4-b60b532bcf13.png)

photo 2 in non editor

![2](https://user-images.githubusercontent.com/29927382/114295634-1fe52f80-9aaf-11eb-824c-3acb53b4c697.png)

**Comment by lexoyo** [comment]
hello @DemonRem 
can you please give me a link to the online version? i will probably see the problem right away

**Comment by lexoyo** [comment]
in the picture and the ziped files, I see that you do not use "sections". they are useful to have things centered in the website and always visible whaterver size your window
you should put the image in the container of a section

**Comment by DemonRem** [comment]
well online version i belive you mean to the link of the website : http://www.redstormstudio.com

**Comment by lexoyo** [comment]
I see that you do not use "sections". they are useful to have things centered in the website and always visible whaterver size your window
you should put the image in the container of a section

**Comment by lexoyo** [comment]
@DemonRem here is a link explaining sections
https://github.com/silexlabs/Silex/wiki/FAQ#why-should-i-use-sections

**Comment by lexoyo** [comment]
let me know @DemonRem if you have any more questions
