### ISSUE TITLE
Bug when I change the tag name of the body

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#1097]
When I select the body and change the tag name using this UI:
![Screenshot from 2021-04-20 15-07-06](https://user-images.githubusercontent.com/6483546/115400963-24fe5900-a1ea-11eb-82af-9fd1c7e2ae4e.png)

Silex lets me change the tag name of the body but then the HTML head editor does not work anymore :face_with_head_bandage:

**Comment by lexoyo** [comment]
fixed
