### ISSUE TITLE
icône pour un site

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#110]
Je cherche à mettre une icône pour mon site web (un .ico par défaut du site, situé sur l'onglet). C'est possible?

comme ceci : 
![capture decran 2014-04-23 a 14 36 26](https://cloud.githubusercontent.com/assets/6841971/2777351/eab2a092-cae3-11e3-831d-eadc9dfbff3f.png)

**Comment by lexoyo** [comment]
Done and on preprod

**Comment by lexoyo** [comment]
![screen shot 2015-05-19 at 00 47 50](https://cloud.githubusercontent.com/assets/715377/7692092/ba7b9d46-fdc0-11e4-9d90-dac8ec5d1cda.png)
