### ISSUE TITLE
Suppression des identifiants automatique

### ISSUE THREAD

**Issue by Maxime0043** [silexlabs/Silex#1100]
Bonjour,
J'aurais besoin d'aide concernant les identifiants sur Silex qui se supprime tout le temps.
Lorsque j'ajoute manuellement des identifiants dans le code généré par Silex, et que je modifie les éléments en question sur l'outil Silex, les identifiants se retrouvent complètement supprimés. Par ailleurs, les identifiants me servent à interagir avec les éléments en JavaScript.

Merci.

**Comment by lexoyo** [comment]
Dans les fichiers editables de Silex (avant publication) tu peux ajouter ce que tu veux comme classes CSS, markup HTML et IDs
Il faut juste réouvrir le fichier dans Silex et ca ne devrait rien changer

Par contre la bonne pratique est d'utiliser les classes CSS pas les ID. Tu peux [ajouter des classes CSS à un élément depuis l'interface Silex](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#custom-css-classes), cf [ce guide pour utiliser JS dans Silex](https://github.com/silexlabs/Silex/wiki/Silex-and-Javascript)

N'hésite pas à en dire plus sur ton cas d'usage et on pourra parler de bonnes pratiques avec Silex

**Comment by Maxime0043** [comment]
Très bien, merci.

J’utilise principalement les IDs pour récupérer les données entrées dans les champs des formulaires en JavaScript.

**Comment by lexoyo** [comment]
Pour des formulaires je te recommande du pur HTML, en utilisant les HTML Box
Je n'ai pas de contexte mais ca peut t'etre utile (ou pas :)
