### ISSUE TITLE
New version of Silex available for tests

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1103]
Hello fellow makers

[Here is a new version of Silex available for tests](https://preprod.silex.me/). Please ask questions here or post the result of your tests :fire: 

It represents 4 months of my volunteer time :eyes: 

New features

* [a new "elements tree" panel, see the screenshot and details here](https://github.com/silexlabs/Silex/pull/1102)
* publication of zip files (needs docs, please ask if you can take time to test and write a little documentation)
* CI/CD improvements

Bug fixes

* fix Bug when I change the tag name of the body
* fix styles duplication
* fix slideshow on mobile
* fix copy/paste when more than 2 levels of containers
* remove margin-top -1 on sections
* fix visibility for section containers
* fix font manager
* fix help link

cc @ceubri @baguetteagile @molyrichez @fernandammoutinhobarros @gravinyl @DemonRem @gtiani @form-and-void

**Comment by ceubri** [comment]
The new "elements tree" is great, very helpful !
Nice job :)

**Comment by lexoyo** [comment]
It is now live on editor.silex.me
