### ISSUE TITLE
Problème sur la taille des sections

### ISSUE THREAD

**Issue by Maxime0043** [silexlabs/Silex#1104]
Bonjour,
J'ai un petit problème concernant la taille des sections qui sont fixes. Je n'arrive pas à trouver le moyen de rendre la taille des sections ou des conteneurs adapté à son contenu.
Notamment, j'utilise des radio buttons pour afficher ou cacher certains conteneurs. Mais, lorsqu'un conteneur est plus grand qu'un autre, il va empiéter sur la section en-dessous.

Auriez-vous des solutions à m'apporter concernant ce problème ?
Merci.

**Comment by lexoyo** [comment]
Oui c'est une utilisation avancée de Silex:

* mets tous tes éléments en position `auto` (tous les éléments de la section, y compris les éléments à l'intérieur de containers)
* positionne les éléments en utilisant les option du paneau "layout" (margin, flex...)
* dans la hauteur de la section, supprime la valeur ou mets `0`

![layout panel](https://user-images.githubusercontent.com/715377/116402246-759a3580-a82c-11eb-9eff-4221ccf95a3d.png)

**Comment by Maxime0043** [comment]
Je peux le faire pour les conteneurs, cependant je ne peux pas interagir avec les sections.

![image](https://user-images.githubusercontent.com/57800452/116403105-767f9700-a82d-11eb-96ad-f4e4f0ab37f4.png)

**Comment by lexoyo** [comment]
Oui les sections sont toujours en `auto`, c'est tout ce qui est dedans que tu dois changer

**Comment by Maxime0043** [comment]
Effectivement les sections sont en `auto`. 
De ce que j'ai pu voir dans Silex, c'est que lorsqu'on crée une section, il y a un conteneur qui est automatiquement ajouté à l'intérieur. 
Et ce conteneur comporte la propriété `min-height`, qui prend la valeur du `height` que l'on a définit dans Silex.
Donc, quand je lui mets une hauteur de 0, le contenu de la section se retrouve sur celle du dessous

**Comment by lexoyo** [comment]
Pas si son contenu est en `auto`

Tu peux mettre en ligne un exemple qui ne fonctionne pas et je te dirai quoi faire

**Comment by lexoyo** [comment]
Ici un exemple qui fonctionne:
* section avec hauteur `0`
* contenu en auto

![Screenshot from 2021-04-28 15-36-32](https://user-images.githubusercontent.com/715377/116413088-961bbd00-a837-11eb-812b-cbcdd6e4a8dd.png)

**Comment by Maxime0043** [comment]
Voici le lien vers une page exemple : [site](http://maxime-pinna.alwaysdata.net/sadaqa/don.html)

La section au-dessus du footer n'a pas une taille adaptée

**Comment by lexoyo** [comment]
je ne comprends pas de quelle section tu parles

**Comment by Maxime0043** [comment]
J'ai trouvé mon erreur, j'avais oublié de mettre un conteneur en position automatique, ce qui fait que le footer remontait sur la section concernée.

Je vous remercie de m'avoir aidé !

**Comment by lexoyo** [comment]
Avec plaisir pas de problème
