### ISSUE TITLE
Possiblitité d'avoir un header / footer commun pour différents projets silex ?

### ISSUE THREAD

**Issue by MrCookie78** [silexlabs/Silex#1106]
Bonjour,
Travaillant à deux sur le même projet, nous sommes obligés, pour chaque page de notre site, de créer un nouveau projet silex afin d'éviter des conflits lors de commit. Ce qui entraîne le fait que nous devons ajouter à la main, pour chaque nouvelle page, le header et le footer accompagnés de leur css et js respectif.
Et si nous faisons une modification du header ou footer, nous devons par la suite effectuer cette modification sur toutes les autres pages, ce qui est très peu pratique.
Avez-vous une solution plus efficace ?

**Comment by lexoyo** [comment]
Bonjour @MrCookie78 
C'est une très bonne question, je suis souvent dans ce cas aussi et je n'ai pas de bonne solution pour le moment malheureusement

Peut etre qu'en utilisant le copié collé tu peux t'en sortir : 

* 1 site par personne
* 1 site commun
* de temps en temps tu copies de ton site et tu colles dans le site commun

Ca ne sera pas si simple pour les CSS/JS ou les settings des sites... 

Si tu as des compétences en dev et du temps il y a des trucs possibles aussi

**Comment by lexoyo** [comment]
cc @molyrichez

**Comment by molyrichez** [comment]
Je sais pas... enfin, ce serait TOP de pouvoir copier des sections d'un doc
à l'autre ça c'est sûr. Maintenant, que ce soit le même, je vois pas
l'intérêt là tout de suite. Dans le cas où on fait une série de 200 LP et
que le client demande des changements sur les header et footers... là oui

Le jeu. 29 avr. 2021 à 09:47, Alex Hoyau ***@***.***> a
écrit :

**Comment by MrCookie78** [comment]
Merci de vos réponses, je vais partir sur du copié collé je pense..
