### ISSUE TITLE
Une image dans une text-box ?

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#111]
Je crois savoir la réponse, mais est-ce possible d'intégrer une image dans une text-box ?

**Comment by lexoyo** [comment]
Tu peux aussi le faire maintenant avec le [Markdown widget](https://github.com/silexlabs/Silex/issues/125)

**Comment by lexoyo** [comment]
this is solved by today's release
see the new inline text editor, the style editor, the font manager
and the [related docs](https://github.com/silexlabs/Silex/wiki/editor-ui#text-editor)
