### ISSUE TITLE
Help create the new official website for Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1110]
<a href="https://github.com/silexlabs/Silex/issues/1110"></a>
Hello

It has been more than a year that @ceubri and I started to create a new website for Silex

We need you all to help review the website, identify missing content or mistakes

Please look at the <a href="https://silex2020.netlify.app/">work in progress</a> here and comment bellow

<a href="https://silex2020.netlify.app/">
<img alt="Silex website builder" src="https://user-images.githubusercontent.com/715377/116722785-21838280-a9df-11eb-95e6-284a7099dd8e.png">
</a>

cc @tariqbenezza @molyrichez @baguetteagile @gravinyl @sidmint @godzone @singchan  @FranGamer189  @DurtyDev @nadinedorsaint

**Comment by sidmint** [comment]
I like the website design.
Issues:
1. There's a very little horizontal scroll present which is not required.
2. The top panel is not smooth when scrolling vertically, specially noticeable when scrolling with speed. It jerks itself to maintain its position.

Chromium 90, Linuxmint.

**Comment by lexoyo** [comment]
Thank you @sidmint 
This is very valuable points
I'll fix both

**Comment by lexoyo** [comment]
@sidmint could you try again and let me know if the scroll is still there? I don't have it on my chromium/linux

**Comment by lexoyo** [comment]
any feedback before i release the site @tariqbenezza @molyrichez @BaguetteAgile @gravinyl @sidmint @godzone @singchan @FranGamer189 @DurtyDev ?

**Comment by sidmint** [comment]
> @sidmint could you try again and let me know if the scroll is still there? I don't have it on my chromium/linux

1. horizontal scroll still present
2. top panel issue still prersent, though it might be little lesser, I'm not sure.

**Comment by lexoyo** [comment]
anyone else has the scroll issue? thx

**Comment by ceubri** [comment]
Yes the top menu is not fixed when scrolling, it jerks.
Chrome  on Android

**Comment by lexoyo** [comment]
Ok thank you @ceubri 

I just fixed it for desktop
