### ISSUE TITLE
Preview mode: newly created page is not blank

### ISSUE THREAD

**Issue by mmaatthhiieu** [silexlabs/Silex#1116]
Hello,

I created a first web page with various elements. So far, so good. I create another one that I leave completely blank. Then, I switch to preview mode. I'm on my second page, but instead of being blank, it contains all the elements of my first page. I have checked that the box corresponding to my first page is checked for each element of this same page when I go to the Visible on section. So I don't understand how this is possible. Thanks in advance for your help.

**Comment by lexoyo** [comment]
hello
I don't see how it is possible
would you share the site?

**Comment by lexoyo** [comment]
these links are not public, i can't access it

the link to your github repo would be enough

i think I can find it by myself, I'll let you know

**Comment by mmaatthhiieu** [comment]
ok great !!

**Comment by mmaatthhiieu** [comment]
Thanks to take the time to look. So, I put the following part in the Javascript editor : 

$(document).on('ready', function() {
      
      $(".center").slick({
        dots: true,
        infinite: true,
        centerMode: true,
		slidesToShow: 1,
		slidesToScroll: 1,
		autoplay: true,
		autoplaySpeed: 2000
      });
      
    });

I put that one in the CSS editor : 

html, body {
      margin: 0;
      padding: 0;
    }

    * {
      box-sizing: border-box;
    }

    .slider {
        width: 100%;
        margin: 100px auto;
    }

    .slick-slide {
      margin: 0px 20px;
    }

    .slick-slide img {
      width: 100%;
    }

    .slick-prev:before,
    .slick-next:before {
      color: black;
    }


    .slick-slide {
      transition: all ease-in-out .3s;
      opacity: .2;
    }
    
    .slick-active {
      opacity: .5;
    }

    .slick-current {
      opacity: 1;
    }

And I kept that one in my HTML element : 

<section class="center slider">
    <div>
      <img src="carousel1.PNG">
    </div>
    <div>
      <img src="carousel2.PNG">
    </div>
    <div>
      <img src="carousel3.PNG">
    </div>
    <div>
      <img src="carousel4.PNG">
    </div>
    <div>
      <img src="carousel5.PNG">
    </div>
    <div>
      <img src="carousel6.PNG">
    </div>
    <div>
      <img src="carousel7.PNG">
    </div>
    <div>
      <img src="carousel8.PNG">
    </div>
    <div>
      <img src="carousel9.PNG">
    </div>
  </section>

However, my carousel doesn't work properly. When I'm in preview mode, all the images appeared one after the other... I tried few things but nothing worked. Any ideas ?

**Comment by mmaatthhiieu** [comment]
Thanks a lot for your time ! I made changes taking your comments into account and it's working.
