### ISSUE TITLE
Problems with position a Html Container

### ISSUE THREAD

**Issue by aallnneess** [silexlabs/Silex#1117]
Hello @all :-)

im new to Silex, and thanks for the great Work. 

Unfortunately, I still have a few problems. For example with the positioning of HTML containers on desktop & mobile:

![NewName](https://user-images.githubusercontent.com/73443724/119132977-a93b3a80-ba3b-11eb-9ba7-100f5c50741a.gif)

Inside Html Container:

```
<form>
  <div class="form-group">
    <label>Name:</label> <input type="text" class="form-control" name="text_name" placeholder="Placeholder Textfeld">
  </div>

  <div class="form-group">
    <label>Anschrift:</label> <input type="text" class="form-control" name="text_name" placeholder="Placeholder Textfeld">
  </div>

  <div class="form-group">
    <input type="submit" class="btn btn-primary" name="submit" value="Senden">
  </div>
</form>
```

I use the Desktop version.

And here:
 - Sction Container is not normal or flex
 - Html Container is absolute position....

But i cant position it "absolute".....

![NewName2](https://user-images.githubusercontent.com/73443724/119134059-f5d34580-ba3c-11eb-923e-aa60edb16781.gif)

Thanks in advance

**### EDIT:** Becouse it is the second page ?! ......

**Comment by lexoyo** [comment]
Hello
The "absolute" in mobile does not work right now, it is legacy
I will fix this (hopefully soon)
for now in mobile, everything is "auto"

**Comment by aallnneess** [comment]
Hello,

okay, but why are there so much empty space in page 2 ?

I just can't push the object up. With the example projects that worked somehow ...

![NewName3](https://user-images.githubusercontent.com/73443724/119138292-04702b80-ba42-11eb-90d2-2fda6cb5888d.gif)

Or am I doing something wrong here?

thanks

**Comment by aallnneess** [comment]
And i cant use the Layout options in mobile editor....no effect.....

![image](https://user-images.githubusercontent.com/73443724/119161915-165dc880-ba5a-11eb-91e1-73f356dbef50.png)

**Comment by aallnneess** [comment]
Hey,

I just wanted to report back: I have been working with Silex in the last few days. 
And slowly I understand how it works. Now it's getting really fun! 

Thanks for your work :-)

**Comment by lexoyo** [comment]
> And i cant use the Layout options in mobile editor....no effect.....
> 
> ![image](https://user-images.githubusercontent.com/73443724/119161915-165dc880-ba5a-11eb-91e1-73f356dbef50.png)

Yes this is a known issue
In fact it is more of an unfinished feature

**Comment by lexoyo** [comment]
You should probably close this issue?
