### ISSUE TITLE
Image jumping when changing pages

### ISSUE THREAD

**Issue by aallnneess** [silexlabs/Silex#1118]
Hello,

I have had this problem several times now. 
Unfortunately I don't know why. 
Im using the desktop version.

I position a logo image in the header, which is available on all pages (mobile & desktop). 
(automatic position)
When I switch sides the logo moves. 
Although both sides have exactly the same height / width etc.

![springing](https://user-images.githubusercontent.com/73443724/119695460-7b486280-be4e-11eb-90c8-c184c6a9baa9.gif)

Not within Silex:

![NewName3](https://user-images.githubusercontent.com/73443724/119695745-c82c3900-be4e-11eb-8d53-65df6b546891.gif)

Not in Preview:

![NewName55556](https://user-images.githubusercontent.com/73443724/119695912-f3af2380-be4e-11eb-905e-3475c6ee4089.gif)

Any idea ?

thanks
Matthias

**Edit:**

I've changed it too absolutely, but something is moving here too.

**Comment by lexoyo** [comment]
hi
please give me a link to an online version so that i can inspect elements

**Comment by aallnneess** [comment]
Hey,

thanks for your answer.

Ive recreate it in the online version of Silex....It works as it should.

So, then I'll just work online now. Is not a problem.

thanks

**Comment by aallnneess** [comment]
Hey :-)

I have the same problem again:

In Silex preview all things works best:

![silexview](https://user-images.githubusercontent.com/73443724/120894182-70908900-c617-11eb-8f7d-ed7369a08d62.gif)

but published there are moving:

![published](https://user-images.githubusercontent.com/73443724/120894197-89993a00-c617-11eb-8ab0-a24664910f8d.gif)

https://github.com/aallnneess/testTheSilex

**Comment by lexoyo** [comment]
i believe what you mean is rhe same as here?
https://github.com/silexlabs/Silex/issues/1123

**Comment by aallnneess** [comment]
No, the nav bar or header items move when I click on another pagelink from the main page....very ugly ?!

![hgfcdxyf](https://user-images.githubusercontent.com/73443724/120901491-916ad580-c63b-11eb-8fee-d7302be6317b.gif)

ive checked all the height/width in main/contact page..i cant find an error.....

**Comment by lexoyo** [comment]
oh 
very strange indeed
let me check soon and I'll get back to you
probably on Monday

**Comment by lexoyo** [comment]
you can continue working, I'll find out what the pronlem is

**Comment by aallnneess** [comment]
so, should i upload the project files to fix this ? or is it not to fix ?

**Comment by lexoyo** [comment]
i need to see the website in order to tell you what's wrong

**Comment by aallnneess** [comment]
here is the website:

http://152.89.239.184:8080/Error/index.html

thanks

**Comment by aallnneess** [comment]
If the problem cannot be solved, please give me a short feedback, then I would have to look for something else.
(although Silex is the best I have found in open source)

thanks

**Comment by lexoyo** [comment]
@aallnneess it looks like you have added bootstrap with the form (in the HTML box)

and apparently bootstrap changes the links

you can add this CSS to the page with the form (not sure if it works perfectly):

```css
p {
    margin-top: 20px;
    margin-bottom: 20px;
}
```

if this does not work you can try this

```css
p {
    margin-top: 20px !important;
    margin-bottom: 20px !important;
}
```

finally if it does not work, an easy fix would be to add bootstrap on every page (in the head editor)

it is not optimal though

**Comment by aallnneess** [comment]
Okay, thanks!!

Thats nearly the only thing i dont check, but its so easy to understand.

My fault, sry!

**Comment by lexoyo** [comment]
no problem :)

**Comment by aallnneess** [comment]
Btw: if you put in the "Main" Html Header the bootstrap...it works fine if you preview or publish - but not in the editor !
