### ISSUE TITLE
Comportement étrange suite a publication

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1130]
Salut @lexoyo 

suite a la mise en oeuvre de la solution Axeptio pour le RGPD ( Oui je lâche pas l'affaire, je test toujours ;) ;) ) en passant par GTM pour la gestion des cookies il faut mettre en place GTM sur le site internet et ensuite envoyer les Tags sur le site.

Comme stipulé par Google, il faut coller un script dans le Head et coller un autre script  dans la **section Body** de toute les pages, c'est ici que ça bloque:

`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MLXMLSX"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

je m'explique:
en prévisualisation, Aucun souci le site reste conforme visuellement
en mise en ligne sur Netlify, Aucun soucis également;

lorsque je met en ligne via **mon hébergeur de site Gandi** avec le nom de domaine valable, le site ne ressemble plus a rien visuellement.

J'ai tout essayer ( code coller dans une HTML box )
code **dans le body**
code **dans une section**
code **dans une section container** 

Capture d'écran via Netlify
![Capture d’écran du 2021-06-23 18-24-11](https://user-images.githubusercontent.com/35597855/123135520-2e0ddf80-d452-11eb-8569-4146cffb3b44.png)

Capture d'écran via le serveur Gandi

![Capture d’écran du 2021-06-23 18-22-48](https://user-images.githubusercontent.com/35597855/123135630-50076200-d452-11eb-8819-28534f37f1be.png)

Merci de regarder !

PS: Le nouveau site de Silex est très beau, j'ai pas encore eu le temps de regarder en profondeur, mais le suit les nouveautés...

**Comment by lexoyo** [comment]
Hello

Cool que tu ne lâches pas
Pour mettre dans le body, ce que je fais en général c'est que je le mets dans une HTML box

Tu as recadré dans la console de debug pour voir c'est tout est chargé normalement ?

**Comment by BaguetteAgile** [comment]
Salut,

je viens de laisser le site en live,
apparemment se serait une erreur d'interprétation du navigateur Chrome car sur Firefox pas de soucis.

Peux-tu prendre le temps de visiter le lien ?

http://www.calicebluesrock.be/

PS: autre chose d'étrange:
j'avais installer le script "Reflection" pour les photos dans une ancienne version, je l'ai supprimé par la suite et dans la console je trouve toujours le script, pourtant je supprime bien le répertoire complet avant de publier ...

**Comment by BaguetteAgile** [comment]
Autant pour moi @lexoyo 
je viens de vider le cache du navigateur et c'est OK ;)

a mon avis sa fonctionne bien, je continue mes essais et te tiens au courant.

**Comment by lexoyo** [comment]
hello
si ca marche bien n'hésite pas a fermer l'issue :)
