### ISSUE TITLE
Solution Axeptio pour le RGPD

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1132]
Salut @lexoyo 

Voilà je me suis pencher sur le problème du RGPD ( encore ;) ) avec la solution Axeptio et GTM qui fonctionne a merveille ;) ;)

Veux-tu que je fasse un tuto explicatif pour l’installation sur Silex ?
Peut-être faire un Wiki ?
En tout cas prévenir les utilisateurs de Silex que cette solution existe pour leur site.
En version gratuite gestion de 2 cookies aux choix, pour plus il faut passer a la version payante.

Ben maintenant, je vais continuer avec Orejime qui est libre est gratuit ;)

**Comment by lexoyo** [comment]
Salut baguette !!
Bravo c'est super

> Veux-tu que je fasse un tuto explicatif pour l’installation sur Silex ?
> Peut-être faire un Wiki ?

Ca serait super, tu peux faire un widget ? Une issue dans l'esprit des [autres widgets](https://github.com/silexlabs/Silex/issues?q=is%3Aopen+is%3Aissue+label%3Awidget) 

En fait une sorte de tuto quoi :)

**Comment by BaguetteAgile** [comment]
Salut @lexoyo,

je reviens vers toi pour cette solution RGPD.

Je m'aperçois qu'il y a un problème avec ce widget, j'ai contacter le support de Axeptio et voici leur réponse:

Ma question:

**Bonjour,

je rencontre un soucis d'affichage avec le widget.

Sur PC ou en mode paysage sur smartphone tout fonctionne a merveille, par contre en mode portrait sur un GSM le widget s'affiche puis disparaît de l'écran, il faut tourner le smartphone en mode paysage pour de nouveau apercevoir le widget et ainsi saisir ses choix.

Je précise que le site est hébergé chez Gandi.

PS: Mon site a 2 affichages différent, c'est a dire que le menu principal sur PC n'est plus visible sur smartphone, le menu est donc remplacer par un menu Hamburger**


`Bonjour,
 
Il doit y avoir un conflit avec votre css. Le bug décrit n'apparait que sur un certain break point. 
Je vous invite donc à regarder dans ce sens-là.
 
Je vous souhaite une bonne journée.
Bien à vous,
Manon`

Donc si je comprend bien il y a un code css a rajouter afin de résoudre ce problème de Break point.

Un rapport avec ceci dans la page styles.css ??

`@media (min-width: 481px) {
    .silex-editor {
        min-width: 1400px;
    }`

Je précise ceci, nous avons la possibilité de régler la hauteur de défilement ( par défaut 800 px ) directement chez Axeptio

HAUTEUR DE DÉFILEMENT À PARTIR DE LAQUELLE LES COOKIES SONT PRÉSENTÉS À L'UTILISATEUR

Merci de prendre le temps de regarder.

**Comment by BaguetteAgile** [comment]
Salut @lexoyo,

peux-tu s'il te plait regarder à ce problème quand tu as le temps, car en faite sa bloque complètement le site internet, et les internautes ne savent pas qu'il faut passer en mode paysage pour régler ce soucis ...

Merci d'avance ;)
