### ISSUE TITLE
Issue with slideshow not showing chosen images

### ISSUE THREAD

**Issue by slip13420** [silexlabs/Silex#1137]
Hey all, new issue.  When using the slideshow addon, everything works correctly however the sidebar still shows "no file chosen".
Any help appreciated!

![image](https://user-images.githubusercontent.com/52355525/125856902-934aae40-16a2-47bb-87ba-cb69005313a9.png)

**Comment by slip13420** [comment]
Ok So I have played around with this a little more.  One thing I noticed is the preview of the image is loading correctly, the issue is the DIV has a height of 0.
![image](https://user-images.githubusercontent.com/52355525/127222314-9ae420a0-b60c-4a07-b020-8a7fd3b2ae9e.png)
If I manually add a height like this...
![image](https://user-images.githubusercontent.com/52355525/127222487-1ba80ec3-6ba7-4242-bf03-c3611a776dc6.png)
It will show the preview.
![image](https://user-images.githubusercontent.com/52355525/127222532-ff38590b-029f-496d-88ad-433b97ac43d2.png)
However, I still get the no file chosen text.  So couple of questions, A) where does the height for the preview div come from, and B) where does the "no file chosen" come from?  Thanks in advance.

**Comment by lexoyo** [comment]
This is a known bug
It is annoying but non blocking so it will not be fixed soon as I am the only dev here (sadly)

**Comment by lexoyo** [comment]
> One thing I noticed is the preview of the image is loading correctly, the issue is the DIV has a height of 0.

Oh this is interesting thx
Would you be able to fix it ?

You would need to run silex locally and use (instructions for [linux and macos](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-linux-or-macos-or-cloud9), [for windows](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-windows))

Then there will be a css file to edit

**Comment by lexoyo** [comment]
> B) where does the "no file chosen" come from? Thanks in advance.

This is not really a bug, the 'choose file' input should be 'upload' and it should not show the file name field. This is because it is a native input, it can not remember the name as it holds the name of a local file

**Comment by slip13420** [comment]
> > One thing I noticed is the preview of the image is loading correctly, the issue is the DIV has a height of 0.
> 
> Oh this is interesting thx
> Would you be able to fix it ?
> 
> You would need to run silex locally and use (instructions for [linux and macos](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-linux-or-macos-or-cloud9), [for windows](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#local-installation-on-windows))
> 
> Then there will be a css file to edit

So for this one, I've found on line 58 in the prodotype source file FileEditor.js is where it's defined...
![image](https://user-images.githubusercontent.com/52355525/127359484-c861b230-f22f-493f-9638-f3f6b2462fbb.png)
Forgive my ignorance as I'm still very new to node.js but how do I go about recompiling that when it is a dependency in the node project I built?  What I mean is it currently lives in /node_modules/prodotype/src but of course if I change that file nothing happens.  If I can do that somehow, I will test a fix and do a pull request.  Thanks in advance!

**Comment by slip13420** [comment]
Ok so I was able to fix this issue.  I forked prodotype and fixed it in there.  Git repo is https://github.com/slip13420/Prodotype if you want to check it out.  Only change made was in FileEditor.js.

**Comment by lexoyo** [comment]
Great :)
Would you create a pull request?

**Comment by slip13420** [comment]
Done, pull request is https://github.com/silexlabs/Prodotype/pull/29
