### ISSUE TITLE
Login Form No Longer Popping Up

### ISSUE THREAD

**Issue by slip13420** [silexlabs/Silex#1143]
So this is a weird one.  Using the example of setting the page to [Single Site Mode](https://github.com/silexlabs/Silex/wiki/Single-site-mode), and [Integrate Silex with your infrastructure](https://github.com/silexlabs/Silex/wiki/Integrate-Silex-with-your-infrastructure), I was able to have login-form.html pop-up sometimes.  However it now never pops up.  Not sure what I'm doing wrong.  If I however manually browse to lgin-form.html, it redirects to /ce/custom-service/login_callback fine and then I'm able to login to the app.  Index.js looks like this...

```
'use strict';

var serveStatic = require('serve-static')
const path = require('path');
const { SilexServer, Config } = require('silex-website-builder');
const CustomProvider = require('./custom-hosting-provider');


const config = new Config();

// provide only our custom hosting to user when they want to publish
config.publisherOptions.skipHostingSelection = true;
config.publisherOptions.enableHostingUnifile = false;

// disable other services
config.ceOptions.enableSftp = false;

const silex = new SilexServer(config);

// add our custom service
const CustomService = require('./custom-service');
silex.unifile.use(new CustomService());

// add our custom hosting provider
silex.publishRouter.addHostingProvider(new CustomProvider(silex.unifile))

// serve modified html
silex.app.use('/', serveStatic(path.resolve('./dist/')));

// define a form to get the user login and password
silex.app.use('/login-form.html', (req, res) => res.sendFile(__dirname + '/login-form.html'));

silex.start(function() {
  console.log('server started');
});
```

Any help appreciated!

**Comment by lexoyo** [comment]
Hello
The code looks good to me
I believe the popup is opened only if the user is not logged in already
Check the network calls and see what the /services path returned. If your service says isLoggedIn is true then it is normal

**Comment by slip13420** [comment]
Ok, thanks I'll have a look.  The issue I don't understand though is if I load up in Incognito mode, I still get no login form.  Being incognito would mean I'm for sure not logged in.  I'll check the network calls.

**Comment by slip13420** [comment]
Digging through this a little more I see the session is not logged in and I never see the login page.

![Screenshot_20210909_140808](https://user-images.githubusercontent.com/52355525/132762893-641a5a6b-e546-4d6d-9efe-ce1bcf911a70.png)

**Comment by slip13420** [comment]
I'll add the custom service code as well to see if that helps.

```
const { FsConnector } = require('unifile');
const save_dir = "/opt/website/";

/**
 * Service connector extends the local filesystem connector (unifile-fs)
 * The root URL will depend on the user name, i.e. in ${ rootUrl }/${ session.user }/
 */
class CustomService extends FsConnector {
  // **
  // extend Fs service
  constructor(config) {
    super(config);
    // change fs infos
    this.name = 'custom-service';
    this.infos.name = 'custom-service';
    this.infos.displayName = 'File System';
    this.infos.description = 'File System Connector';
  }

  // **
  //Auth commands
  getInfos(session) {
    return Object.assign({
      isLoggedIn: !!session.user,
      isOAuth: false,
      username: session.user
    }, this.infos);
  }
  // In this example the form will set a user in the session
  // The form is one specific form for this example
  getAuthorizeURL(session) { return Promise.resolve('/login-form.html') }

  // check authentication
  // and create a root folder for the user
  login(session, loginInfos) {
    if(loginInfos.password === 'password') {
      // store the user
      session.user = loginInfos.user;
      // create the user's directory if it does not exist already
      return this.mkdir(session, '')
      .then(() => this.mkdir(session, 'Website'))
      .catch((e) => session);
    }
    // logout if pass is not correct
    session.user = null;
    return Promise.resolve(session);
  }
  // **
  //Filesystem commands: prepend the user to all paths
  readdir(session, path) { return super.readdir(session, `${ save_dir }${ session.user }/${ path }`) }
  stat(session, path) { return super.stat(session, `${ save_dir }${ session.user }/${ path }`) }
  mkdir(session, path) { return super.mkdir(session, `${ save_dir }${ session.user }/${ path }`) }
  writeFile(session, path, data) { return super.writeFile(session, `${ save_dir }${ session.user }/${ path }`, data) }
  createWriteStream(session, path) { return super.createWriteStream(session, `${ save_dir }${ session.user }/${ path }`) }
  readFile(session, path) { return super.readFile(session, `${ save_dir }${ session.user }/${ path }`) }
  createReadStream(session, path) { return super.createReadStream(session, `${ save_dir }${ session.user }/${ path }`) }
  rename(session, src, dest) { return super.rename(session, src, dest) }
  unlink(session, path) { return super.unlink(session, `${ save_dir }${ session.user }/${ path }`) }
  rmdir(session, path) { return super.rmdir(session, `${ save_dir }${ session.user }/${ path }`) }
  batch(session, actions, message) { return super.batch(session, actions, message) }
}
// export for use in index.js
module.exports = CustomService;

```

**Comment by slip13420** [comment]
Ok, after more testing the issue is it only pops up after you have logged in once.  What I mean is if you go incognito or use a browser you haven't used before, you have to manually got to /login-form.html and login first.  Then each subsequent load of the page brings up the login form popup correctly.  Any ideas?

**Comment by lexoyo** [comment]
Hi @slip13420 
sorry for the delay, are you still working on it?

> Ok, after more testing the issue is it only pops up after you have logged in once. What I mean is if you go incognito or use a browser you haven't used before, you have to manually got to /login-form.html and login first. Then each subsequent load of the page brings up the login form popup correctly. Any ideas?

ok i think i understand

the login popin is opened when the user click on your service in the file explorer (https://cloud-explorer.org/)

and then when the file explorer opens up, it tries to reconnect to the last visited service and may open the popup again

maybe what you need is to make sure the user is logged in before opening silex (maybe open another login page which redirects to silex?) or after silex has loaded (add a script to silex html page?)

let me know if i can help

**Comment by lexoyo** [comment]
also feel free to join the chat if it is easier (not sure)
https://gitter.im/silex-website-builder/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by lexoyo** [comment]
no prob @slip13420 :)
have a nice weekend !
