### ISSUE TITLE
Can't use drives other than the root home folder (C:\...\My Documents) on Windows

### ISSUE THREAD

**Issue by Kaoras** [silexlabs/Silex#1148]
Hey, so I'm interested in using Silex as an editor, but I have a setup where my System is primarily used for root (C:, because Windows 10 x64) and all my other assets will be stored on other drives because they have more space.

But it seems like Silex will only import and save to My Documents on C:.  Even when I use the "Click to select files!" prompt to open the native file manager, I can't import or save to, say, the D: drive.  Or any other drive, outside of root.

**Comment by lexoyo** [comment]
Hello @Kaoras 

> it seems like Silex will only import and save to My Documents on C:.

Yes this is what it does

This behavior could be changed [in the code here](https://github.com/silexlabs/silex-desktop/blob/master/index.js#L16), would you like me to tell you more about this?

>  Even when I use the "Click to select files!" prompt to open the native file manager, I can't import or save to, say, the D: drive. Or any other drive, outside of root.

You mean event to upload an image for example? this would be strange
