### ISSUE TITLE
Basic user guide ?

### ISSUE THREAD

**Issue by saliez** [silexlabs/Silex#1151]
As a first time beginner, where to find the most basic elements of an user guide:
Meaning and options of the "+" ?
Uses and options of a container ?
What if the screen of the reader has a different dimension ?
Edit options ?
What is allowed using "</>" ?
How to show lists of lists ? i.e, an <li>AAA<ul><li>aaa</li></ul></li>
......
Discovering by trials and errors take much time !

**Comment by lexoyo** [comment]
Hello @saliez 
Did you check the wiki?
https://github.com/silexlabs/Silex/wiki
