### ISSUE TITLE
Links with #  disapear when thers more than one page

### ISSUE THREAD

**Issue by fernandammoutinhobarros** [silexlabs/Silex#1152]
I have the following problem (I'm using the desktop version):
I have a menu in a text box, where each word is a link that jumps to a section of the page.
Now I've added a new page, which uses the same menu, but the links disappear every time I edit the text box.

When it was just one page it worked perfectly, I added the link with #section-name, now I use the filename.html#section-name, but the links disappear every time I enter the text box.
If I edit without leaving the text box it works, but if I change window I have to redo it all over again.

What am I doing wrong?

Thanks for the help.

**Comment by fernandammoutinhobarros** [comment]
My page www.rar2022.net

**Comment by lexoyo** [comment]
Oh interesting

I think you don't need "filename.html" even with multiple pages, could you try that?

**Comment by fernandammoutinhobarros** [comment]
Tested it:
What happens is that it get's all messed up:
Some links of some sections that appear on that page work fine, others don´t work at all.
The ones that don't appear on that page try to jump to a section that doesn't exist on that page.

If the links refers to a sectionY only on pageA, and if i'm on pageB , it creates the link  "pageB#sectionY"

**Comment by lexoyo** [comment]
@fernandammoutinhobarros i see on your site that all the links work now?

i tried to reproduce but did not succeed, can you help me reproduce?
maybe due to the new version i released yesterday

**Comment by fernandammoutinhobarros** [comment]
I didn't put online the version with the problem, but I can share with you

**Comment by fernandammoutinhobarros** [comment]
If I edit the text box where the links are,  without leaving it works, but if I re-edit the text box, some links disappear, manly the ones that go to sections of the page, and then I have to insert them all again, without leaving the text box.

**Comment by lexoyo** [comment]
Ok 
Please share with me the buggy version
