### ISSUE TITLE
Blank screen on launch using appimage on Fedora 35

### ISSUE THREAD

**Issue by primal-buddhist** [silexlabs/Silex#1154]
Hi

1. Downloaded the appimage
2. Set to executable
3. Launch
4. An application screen launches eventually but is just whitespace in an application window.
5. Logs show a coredump (Process 240165 (silex-desktop) of user 1000 dumped core.
6. I can close the window

Using Fedora 35.

**Comment by lexoyo** [comment]
Thank you @primal-buddhist for the report

I am installing fedora 35 now in order to investigate this issue

**Comment by lexoyo** [comment]
@primal-buddhist I finally found out that this is not a silex problem but all electon apps in fedora 35, as [you can read here](https://www.reddit.com/r/Fedora/comments/qm3qm1/fedora_35_most_electron_apps_are_not_starting/)

They say a solution is to add `--disable-seccomp-filter-sandbox` to the command starting the app, so for example with Silex you can do `$ ./silex-desktop-2.7.24.AppImage --disable-seccomp-filter-sandbox`

I just tested and it works

**Comment by lexoyo** [comment]
And I found out that by upgrading electron version, this issue is fixed

Please just download the latest version of Silex desktop, it will work then

Thank you for the bug report, good catch !

**Comment by primal-buddhist** [comment]
Fantastic

**Comment by lexoyo** [comment]
> @primal-buddhist I finally found out that this is not a silex problem but all electon apps in fedora 35, as [you can read here](https://www.reddit.com/r/Fedora/comments/qm3qm1/fedora_35_most_electron_apps_are_not_starting/)
> 
> They say a solution is to add `--disable-seccomp-filter-sandbox` to the command starting the app, so for example with Silex you can do `$ ./silex-desktop-2.7.24.AppImage --disable-seccomp-filter-sandbox`
> 
> I just tested and it works

Use this workaround then ?
