### ISSUE TITLE
How to save in asp MVC core 6

### ISSUE THREAD

**Issue by fasteddys** [silexlabs/Silex#1158]
how do I get the composed page and save in asp mvc

**Comment by lexoyo** [comment]
Hello
You probably simply need to publish in the right folder?
I don't know asp mvc so ..

**Comment by lexoyo** [comment]
Please ask a more specific question, I am sure we can workout something

**Comment by fasteddys** [comment]
Is there a way to send the designed HTML back to server such that it can be decomposed its the files and fodler structures.

Maybe as a zip file, server  or Ajax call. I can integrate it into ASP myself is thats possible

**Comment by lexoyo** [comment]
Sure, you can do that

When you publish your site you can choose a folder on GitHub or FTP or your local computer (silex desktop only)

Does it answer your question?

**Comment by lexoyo** [comment]
Here are some Q&A related to that

* [About Silex HTML files](https://github.com/silexlabs/Silex/wiki/FAQ#about-silex-html-files)
* [Integration of Silex with php project](https://github.com/silexlabs/Silex/wiki/FAQ#integration-of-silex-with-php-project)

**Comment by fasteddys** [comment]
Thanks, Let me try that
