### ISSUE TITLE
Self hosting silex: Internal error when selecting a template (Heroku)

### ISSUE THREAD

**Issue by ClemCa** [silexlabs/Silex#1159]
As can be seen below, Silex does not seem to work on Heroku.
I used the one-click install button on the official website and didn't change anything after the build was done.

![image](https://user-images.githubusercontent.com/26848693/147803124-50b995ea-9060-4587-b7a1-2b7e1d955f02.png)

**Comment by lexoyo** [comment]
Hello @ClemCa 
Can you give here the env vars you set in heroku install form?
Also what steps did you do to open the file exactly?
And did you try the same file on https://editor.silex.me ?

**Comment by ClemCa** [comment]
Hi, sorry for the delay. I left all the options empty, as they are marked optional

**Comment by lexoyo** [comment]
The SERVER_URL is required, that is probably what went wrong

**Comment by ClemCa** [comment]
I did fill it though, heroku wouldn't let one continue without filling it, after all.

**Comment by ClemCa** [comment]
I put clemca.herokuapp.com, and you can find it there.

**Comment by lexoyo** [comment]
Hi I tested again and it works form me on heroku

I believe you need to put a full URL, with the protocol for example (`http://`)

Also try with / without a slash at the end maybe?

**Comment by ClemCa** [comment]
Hi, I gave up on it in the end, found something else. You can close it. Was
weird though. Maybe something was wrong with my chrome installation.
