### ISSUE TITLE
Text all scrambled in textbox   Noob in need of help

### ISSUE THREAD

**Issue by konsumopfer77** [silexlabs/Silex#1160]
Hello, im a noob to skilex so maybe its not a bug but just my limited understanding of how the software works but i got the following problem, when i try to put text in a Textbox its all scrambled, its only using one column and overlapping horribly.  I Tried to work arround this Problem with  the use of ENTER but its really getting messy once i try to make it work for both phone and desktop user.
 Also i would be super happy if someone could recomend a good soruce for tutorials, i could only find so much so far and am a little overwhelmed by the structure of this forum to be honest.
![zzzzzzz111111111](https://user-images.githubusercontent.com/44984803/147825066-86b7ef7e-9756-4320-bc25-ba33e1581946.png)

**Comment by lexoyo** [comment]
Hi @konsumopfer77 

Good to have you here!

I am not sure why it does that, could you please let me know what browser you use and what exact steps you do?

This forum has no structure I guess ;)
Did you see the online documentation here on GitHub, the "Wiki" tab ? There is a tutorial and pages about the software. Also there is a page with links to video tutorials

**Comment by konsumopfer77** [comment]
@lexoyo Hi, thanks : )

I work via chromium  but i tested it on chromium and firefox.  The weird thing is, when i checked from a friends pc and had the same bug, it "solved" itself after i changed the window size (it was full screen at first but it still worked when i changed back to full screen)   Im defnitly going to check out the wiki tab, thank you (i didnt notice it before) This will come in handy for sure

**Comment by lexoyo** [comment]
Hi @konsumopfer77 
Did you solve your issue?

**Comment by konsumopfer77** [comment]
Hey, thanks for aksing.
I kind of worked arround it.  Its still like that every time i copy a new block of text in a text-box in silex. It has something to do with how silex apparently cant aproperly  seperate the text in diffrent passages depending on how big the text box is. Instead it stacks all passages in the same place and it looks all scrambled. Its a little annoying to do changes in the text this way but one can work arround it by clicking on the beginning and press enter manually for every paragprah.  I'm still not sure if thats by design or a bug or just me misshandeling the tool somehow 
: )

**Comment by lexoyo** [comment]
So it only occurs with text boxes with text pasted from word or something ?
