### ISSUE TITLE
Comparison to Now Defunct Serif WebPlus X8

### ISSUE THREAD

**Issue by steveveach** [silexlabs/Silex#1161]
Hello everyone,

I'm considering switching to this application after years of using an amazing WYSIWYG program from a small UK company called Serif. The software WebPlus X8 has been defunct for a few years. Is anyone here that is using Silex a former WebPlus user?

Thanks!

**Comment by lexoyo** [comment]
Hello
I didn't know this software
Can you tell us more about it so that we can compare?
