### ISSUE TITLE
Question to BurgerMenu

### ISSUE THREAD

**Issue by konsumopfer77** [silexlabs/Silex#1162]
Hi there folks,
Is there a way to make the background of the burger menu transparent or disable it somehow? 
Or if not, can i add an background image instead of a monochrome box?
I probably overlooked it but i have been on it for hours and couldnt find options for that (couldnt even manage to change the font color in the Menu from that ugly purple to something else)

![burgermenu](https://user-images.githubusercontent.com/44984803/155632252-3eebe03a-d2e2-4134-87f1-e0e4855ec1c8.png)

**Comment by lexoyo** [comment]
Hello @konsumopfer77 

To answer your question I created [a new section about the hamburger menu in the docs here](https://github.com/silexlabs/Silex/wiki/editor-ui#hamburger-menu). There is a "Hamburger menu design" part.

Do you find the answers to your questions there? Feel free to ask for clarifications, it will help others :)

**Comment by konsumopfer77** [comment]
@lexoyo  Oh yes indeed, thank you!
I read this before but i guess i confused the color options for the icon with the background and figured it doesnt work.
Thats awesome
