### ISSUE TITLE
Silex next version

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1165]
This is the upcoming Silex version, please test on https://preprod.silex.me

Details of all changes and bug report here

**Comment by lexoyo** [comment]
cc @ceubri @konsumopfer77 @bhandarys @molyrichez @meipey @fernandammoutinhobarros @BaguetteAgile

when you have a moment, I'd appreciate your tests and feedbacks one more time (in english or french or spanish)

thank you for your help over the years <3

nice features comming soon !! :fireworks:

**Comment by BaguetteAgile** [comment]
Salut @lexoyo 

dans cette nouvelle version, je ne trouve pas l'onglet " Test new element here "

https://staging.silex.me/

c'est l'ancienne version en ligne ?

**Comment by lexoyo** [comment]
Ah désolé c'est pas clair
En fait il faut créer un plugin pour ajouter des onglets
C'est pas la peine de tester ca, juste les fonctionnalités normales et la publication etc. J'ai peur des régression à cause des trucs que j'ai fait pour passer la validation w3c
Merci pour les tests @BaguetteAgile

**Comment by BaguetteAgile** [comment]
Impossible d'ouvrir un projet sur Dropbox !
Github c'est OK

![Capture d’écran du 2022-03-29 23-05-52](https://user-images.githubusercontent.com/35597855/160707679-0f6a1c1a-6dcb-4484-9378-a5042f1b9b1d.png)

**Comment by lexoyo** [comment]
Ah ok super merci pour le bug report @BaguetteAgile 
Dropbox devrait etre fix maintenant, j'ai changé l'url de la preprod c'est pour ca

**Comment by BaguetteAgile** [comment]
`Dropbox devrait etre fix maintenant, j'ai changé l'url de la preprod c'est pour ca`

C'est opérationnel pour Dropbox ;)
Je vais pouvoir commencer les tests.

**Comment by lexoyo** [comment]
hello, ca y est je release cette version (silex desktop et editor.silex.me) 
cc @BaguetteAgile @ceubri @molyrichez
