### ISSUE TITLE
Single Site Mode - HTTP 405 error

### ISSUE THREAD

**Issue by bhandarys** [silexlabs/Silex#1167]
I have set up Silex with node JS based on the following link.

https://github.com/silexlabs/Silex/wiki/How-To-Add-Silex-To-Your-Node.js-Project

I then followed the guidelines given in the below URL to create a Single Site Mode

https://github.com/silexlabs/Silex/wiki/Single-site-mode

However when I try to open Silex with the following URL

http://localhost:6805/?path=/websites/user1&service=custom-service

, I get a HTTP 405 error. The folder websites is in my root folder (Should this not be a relative path based on where the server is running?)

Error is - Could not open recent file Event EISDIR: illegal operation on a directory, read 405

My versions are:
Node: 14.16.1
"silex-website-builder": "^2.7.29",
"unifile": "^2.0.19"
OS: Windows 10
Browser: Chrome (version 98.0.4758.102) - On Firefox, I am getting an "Uncaught Error: Should not already be working." at react-dom.development.js:22265)

Please guide on how to proceed

**Comment by lexoyo** [comment]
Hello
In single site mode, the path is supposed to be a path to a file not a directory
I think, not 100% sure... Could you try?

**Comment by bhandarys** [comment]
Hi Alex, You are right. Thank you.

I modified the path to 

http://localhost:6805/?path=/websites/user1/editable.html&service=custom-service

and it is working. I am sorry, I should I tried it first. I got this path from network section of the browser when working in normal mode.

**Comment by lexoyo** [comment]
>  I got the path from network section of the browser when working in normal mode.

that's smart, good tip :+1: 

> Hi Alex, You are right. Thank you.

cool! de nada
