### ISSUE TITLE
play button doesn't appear

### ISSUE THREAD

**Issue by jeremoury** [silexlabs/Silex#1172]
using this Js, css and html code https://www.labnol.org/internet/light-youtube-embeds/27941/
I can't see the play button on my iframe using Silex (it's working using Codepen.io).. don't know why ?

**Comment by lexoyo** [comment]
hi @jeremoury 
would you show me what you did?
is there a silex website online somewhere?

**Comment by jeremoury** [comment]
I would like to replace a YouTube embedded player by an iframe. And only when the user click on the play button, the video is launched. (I have a lot of Vimeo and YouTube embedded players on my website : www.jeremyoury.fr)

like this : https://codepen.io/labnol/pen/vYXYrOW
or like this : https://paulirish.github.io/lite-youtube-embed/variants/custom-poster-image.html

**Comment by jeremoury** [comment]
with Silex, I have the iframe, and if I click on it the YouTube player is launching.
But unfortunately, I can't see the "fake" play button over the iframe.

**Comment by lexoyo** [comment]
If you don't show me I can't say...

**Comment by jeremoury** [comment]
like this : https://jeremoury.github.io/test/

using this code : https://paulirish.github.io/lite-youtube-embed/variants/custom-poster-image.html
