### ISSUE TITLE
onswipe.js  not downloading

### ISSUE THREAD

**Issue by gtiani** [silexlabs/Silex#1173]
I installed the desktop version of Silex and tried re-building my website. I get the following error message:

Warning: these files could not be downloaded:
  onswipe.js

In the js folder, I see 4 files: "front-end.js", "jquery.js", "script.js", "unslider-min.js"
When I last used the online version of Silex, I saw a "onswipe.js" file in the js folder. With the desktop version I don't see the "onswipe.js" file. 
Could you let me know where the "onswipe.js" file comes from?
Thanks,
Gary

**Comment by gtiani** [comment]
Sorry, my fault. There must be a compatibility issues. After I deleted the old slideshow and started a new one, the onswipe.js file downloaded fine using the desktop version.
Sincerely,
Gary

**Comment by lexoyo** [comment]
Hello
No prob
This is probably because i fixed the slideshow recently (#1165)
