### ISSUE TITLE
What IP does editor.silex.me use while connecting to a FTP server

### ISSUE THREAD

**Issue by santomet** [silexlabs/Silex#1176]
Hello, My web hosting provider blocks FTP access from any IP other than specified. What IP is being used by the included FTP client?

Sorry for writing here, but apparently this acts as a forum :)

**Comment by lexoyo** [comment]
Hello
Yes indeed it's like a forum :)
The IP is the one of editor.silex.me, you can use ping to know the IP or any other method
Also you can use silex desktop and it will be your IP then
