### ISSUE TITLE
new user trying to publish

### ISSUE THREAD

**Issue by tiellas-xoxo** [silexlabs/Silex#1177]
Hey im new to all of this e.i silex, web design, github. Im looking for some help because i feel like the issue is something simple im overlooking.

I made a simple website in silex but now that its finished im running into an issue where it wont publish. This didnt occur in any of my tests, i was even able to publish a beta version of the site with only certain pages, but i cant figure out the issue with the full site. All of the pages are simply text and images, theres very little coding involved. Any help appreciated!

**Comment by lexoyo** [comment]
Hello
I will try to help you, can you share your files?
There are freelancers here, they can be faster probably cc @ceubri @bagetteagile

**Comment by tiellas-xoxo** [comment]
Hey! Thank you

Attaching them here, and ill reach out to the others you tagged if i dont hear back by the end of the day!

https://github.com/tiellas-xoxo/test-site.git

**Comment by BaguetteAgile** [comment]
Hi, this is what I get.

https://chic-trifle-fe8c2f.netlify.app/

**Comment by tiellas-xoxo** [comment]
I am importing all images for the site through dropbox, and then sent the site file here using git. So do i need to import all the images to the repository too? Or how can i share the dropbox files for the site?

For reference, here is the beta version i released that uploaded fine using dropbox 

https://github.com/tiellas-xoxo/tiellas.git

im sorry for being so mixed up, if theres a way i can compensate you for your help today let me know

**Comment by tiellas-xoxo** [comment]
![Untitled-1](https://user-images.githubusercontent.com/100728646/163591378-cc9ab9bd-bc06-4e9a-ba59-b969793f5bf4.png)

this is the message i get everytime i try to publish. It gets through uploading all images, tries to run some more and then fails

**Comment by BaguetteAgile** [comment]
For me, it is necessary to put all the images in the directory "Master" of Github (attention to the weight of this one)

Then in Silex you will have to reselect each image...

When this is done, you can publish the site.

**Comment by tiellas-xoxo** [comment]
Ok I'm going to try that now and update!

Is there a reason this site is giving me issues but the first one didnt? The first one used all images from dropbox and published to gitpages perfectly on tiellas.com

**Comment by tiellas-xoxo** [comment]
![image](https://user-images.githubusercontent.com/100728646/163601804-64eeb642-72cf-460f-8db4-c4db80e0caf3.png)
![image](https://user-images.githubusercontent.com/100728646/163601904-6438c68b-f8fc-4bf8-8251-94b7fdc2518b.png)
![image](https://user-images.githubusercontent.com/100728646/163601923-97dfaad4-5704-41e6-ae56-41b3efdc503c.png)

**Comment by BaguetteAgile** [comment]
I've had this error message many times before, I think it's related to the server.
I advise you to start again the manipulation, publish.

**Comment by tiellas-xoxo** [comment]
Keeps popping up every time, but i'll keep trying and update.

**Comment by lexoyo** [comment]
Yes baguette is right about the heroku error, it happens sometimes, maybe too many people
Let me know if it is still the case I'll reboot the server
Also you can use the desktop version, this will work always

**Comment by tiellas-xoxo** [comment]
if i use the desktop version can i still import the site from dropbox or will i have to rebuild it

**Comment by tiellas-xoxo** [comment]
> ![Untitled-1](https://user-images.githubusercontent.com/100728646/163591378-cc9ab9bd-bc06-4e9a-ba59-b969793f5bf4.png)
> 
> this is the message i get everytime i try to publish. It gets through uploading all images, tries to run some more and then fails

still just getting this everytime i deploy from silex site. going to rebuild using github to store pic instead of dropbox and see if that makes a difference.

**Comment by tiellas-xoxo** [comment]
i got it to work now! Thanks for the tip, desktop version is the way to go
