### ISSUE TITLE
Settings page error

### ISSUE THREAD

**Issue by arthuragone** [silexlabs/Silex#1180]
When on the website settings page of Silex I don't see any "save" button. 
And I can't click on the left bar menu to go to "fonts" settings or any other settings. 

Firefox on windows

**Comment by lexoyo** [comment]
Hello
This is strange as a lot of people use silex on Firefox windows and I didn't get reports about that... 
Could you take a screenshot maybe for pe to be sure we are talking about the same thing?
Also there is no save button, just save the website after closing the settings dialog

**Comment by lexoyo** [comment]
Coyld you try with the previous version of silex? Using the desktop version maybe

**Comment by lexoyo** [comment]
I managed to reproduce this bug, it will be fixed in the next release

**Comment by lexoyo** [comment]
It is live now on editor.silex.me please let me know if it fixed the bug @arthuragone
