### ISSUE TITLE
The Link of my Website is not shareable

### ISSUE THREAD

**Issue by trevorwining** [silexlabs/Silex#1185]
i have been working on my website from a long time and i have done so much work on it to make it a helpful and interesting website for the community. i was not pretty sure that my efforts will be lost as i can not share the link of it.

i am looking for its solution!!!!

if there is any developer over here who can help me out??

i was asked to share my problems on silex labs as there are a lot of people who can help me over here!!!!! 

here is the link of my site https://www.ahijoy.com/

**Comment by lexoyo** [comment]
Hi
This is spam right?

**Comment by lexoyo** [comment]
This website is not made with silex
i don't understand, please explain better
