### ISSUE TITLE
Modification de code

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1186]
Bonjour @lexoyo 

j'ai créer un nouveau site pour un client avec ce bout de code pour appeler directement le client.
Cependant ceci fonctionne très bien sur Chrome bureau et mobile et rien sur Firefox !

Que faut-il changer ou ajouter au code pour palier au problème ?

      <a href="tel:+32123456789">Cliquer ici pour appeler Le client +32123456789 </a>

      <img src="./Téléphone.png">

</a> 

Merci

**Comment by BaguetteAgile** [comment]
OK je test ...

**Comment by lexoyo** [comment]
ca a marché @BaguetteAgile ?

**Comment by BaguetteAgile** [comment]
Toujours la même chose, sur Chrome, smartphone, PC ok.
sur Firefox ne fonctionne pas, il y a une erreur dans la console.

![Capture d’écran du 2022-06-14 13-44-42](https://user-images.githubusercontent.com/35597855/173569654-55b5d6d4-7bd2-44ef-af56-3026e88925ee.png)


Voici le lien du site:

https://www.toituredebruyne.be/

**Comment by lexoyo** [comment]
Je viens de tester sur mon tel android avec firefox et ca fonctionne

Tu tests sur desktop?
