### ISSUE TITLE
Formspree

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1189]
Salut @lexoyo,

j'ai créer un formulaire de contact via " Contact Form " sur Silex, mais sur le site final, le formulaire change d'aspect !

Pourquoi le formulaire change d’aspect ?
Bug de Silex ?
J'ai d'autre site ou le formulaire ne change pas d'aspect.

Formulaire d'origine:

![Capture d’écran du 2022-06-14 14-33-27](https://user-images.githubusercontent.com/35597855/173578152-dcdb37c9-d5b5-4280-b481-40173402ce09.png)

Formulaire en ligne:

![Capture d’écran du 2022-06-14 14-33-45](https://user-images.githubusercontent.com/35597855/173578209-3b91a45a-b0e0-443c-aab1-67aba5575383.png)

https://www.toituredebruyne.be/contact.html

**Comment by lexoyo** [comment]
hello @BaguetteAgile 
je vois que tu as mis une html box
je viens d'essayer sur editor.silex.me et le contact form a gardé son style... etrange
si tu veux tu peux remettre une componsant form qq part et je regarderai
