### ISSUE TITLE
Is it possible

### ISSUE THREAD

**Issue by Hellscap3d** [silexlabs/Silex#1195]
First provide some context

**If you use Silex online, please complete the following information**
 - URL: [e.g. editor.silex.me]  None
 -  - Browser        Chrome

**The context**
What are you working on?

I'm working on a website to host user made portfolios, on replit. is it possible to get an instance running on there?

**Your question**
Let us know what you want to know here.

**Comment by lexoyo** [comment]
Hello

Please read the [FAQ "integrate silex with my product"](https://github.com/silexlabs/Silex/wiki/FAQ#integration-in-my-product) and let me know what you think here

**Comment by Hellscap3d** [comment]
> Hello
> 
> Please read the [FAQ "integrate silex with my product"](https://github.com/silexlabs/Silex/wiki/FAQ#integration-in-my-product) and let me know what you think here

I read that, but I get an error while trying to install it as a node dependency.

**Comment by lexoyo** [comment]
Tell me more
