### ISSUE TITLE
I found a bug: This app sucks

### ISSUE THREAD

**Issue by GOUST3D** [silexlabs/Silex#1196]
**Describe the bug**
Garbage

**To Reproduce**
Can't select items correctly, the layer system sucks
There is no automatic snapping
the app takes 50 clicks or task manager to close, gg

**Expected behavior**
Not broken

**If you use Silex online, please complete the following information**
Garbage

**If you use Silex desktop app, please complete the following information**
Garbage fix it

**Additional context**
garbage

**Comment by lexoyo** [comment]
Ok I'm on it @GOUST3D !
Thanks for the bug report, that helps a lot

**Comment by GOUST3D** [comment]
> 

I apologize I am being very rude writing this the way I am, I am aware. It is unnecessary.

It just feels very annoying to use and the ability to not just directly click on an element and have it select something above in a layer stack is frustrating.

The fact automatic snapping isn't enabled by default as well.

And for whatever reason on win10 taking 50+ clicks to close the program, just made me pissed. Sorry.

**Comment by lexoyo** [comment]
No problem @GOUST3D I understand how hard it is sometimes to work with Silex :)

I'm working on Silex more and more, you will certainly appreciate the improvements

If you want you can start 1 issue with just 1 problem you have. I'm sure there are workarounds

Bye!
