### ISSUE TITLE
I found a bug: ...ERROR downloading

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [silexlabs/Silex#1197]
ERROR downloading:
Page Not Found
https://www.electronjs.org/apps/silex
from here:
https://www.silex.me/

**Comment by lexoyo** [comment]
Hello @Clemens-Ratte-Polle 
Thanks for the bug report
Indeed electron changed their website
I have fixed the link on silex website, [here is the new link](https://github.com/silexlabs/silex-desktop/releases/latest)
I also added badges to warn the user that the desktop apps are in beta (windows, macos, linux)
