### ISSUE TITLE
Format image dans Silex (webp)

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1198]
Bonjour @lexoyo ,

A propos de l'optimisation des sites Silex, je viens de m’apercevoir que le format .webp pour les photos n'est pas pris en charge par Silex.

Est-ce vraiment intéressant de convertir nos photos dans ce format ?
Google Page Speed Insight préconise ce format afin de gagner en rapidité et chargement de données.

J'ai lu sur le net que Safari ne prend pas en charge ce format ?

**Comment by lexoyo** [comment]
Hello
webp fait gagner 20% sur le poids des images je crois, donc c'est pas mal oui
Je l'ajoute en "feature request"

**Comment by lexoyo** [comment]
c'est assez simple a faire, il faut ajouter "webp" à ces 2 endroits et bien tout tester pour voir si ca marche:

* https://github.com/silexlabs/Silex/blob/349e996b80513f86204356fd7a62d3902198ae12/src/ts/server/ServerConfig.ts#L110
* https://github.com/silexlabs/Silex/blob/99cb95e45656dc91b0953c0773e00fadf1815ecb/src/ts/client/components/dialog/FileExplorer.ts#L22
