### ISSUE TITLE
Adding images and videos from local gallery

### ISSUE THREAD

**Issue by KodaliDhiya** [silexlabs/Silex#1202]
1, Is there any way to select images from local gallery,
2, how to add videos to silex other than html editor

**Comment by lexoyo** [comment]
1. What do you mean exactly?
2. No, just html editor, with an embed code from youtube or peertube, or with a video html tag

**Comment by KodaliDhiya** [comment]
I want to add images from my local gallery to silex

**Comment by lexoyo** [comment]
Did you try the slideshow component?
