### ISSUE TITLE
Publication Error

### ISSUE THREAD

**Issue by NSX2022** [silexlabs/Silex#1203]
I'm working on a concept website for a friend that is extremely basic (I haven't added Flask/API integration or multiple pages) and would just like a live concept page

**If you use Silex online, please complete the following information**
 - URL: https://editor.silex.me
 - Browser Opera GX

**The context**
I'm working on a simple concept website for a friend, and got this error when I tried to publish the skeleton via GitHub page hosting
![image](https://user-images.githubusercontent.com/111909768/201972138-4a9e093d-109a-4742-96dd-ebc73b166a78.png)

**Your question**
What can I do to fix this? Is it a problem with the repository not being empty?

**Comment by lexoyo** [comment]
Hello
I can look at your repository, can you give me the url?

**Comment by NSX2022** [comment]
> Hello I can look at your repository, can you give me the url?
> […](#)
> On Nov 15, 2022, 17:27, at 17:27, NSX2022 ***@***.***> wrote: I'm working on a concept website for a friend that is extremely basic (I haven't added Flask/API integration or multiple pages) and would just like a live concept page **If you use Silex online, please complete the following information** - URL: https://editor.silex.me - Browser Opera GX **The context** I'm working on a simple concept website for a friend, and got this error when I tried to publish the skeleton via GitHub page hosting ![image](https://user-images.githubusercontent.com/111909768/201972138-4a9e093d-109a-4742-96dd-ebc73b166a78.png) **Your question** What can I do to fix this? Is it a problem with the repository not being empty? -- Reply to this email directly or view it on GitHub: #1203 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

https://github.com/NSX2022/endgame_emporium_xeon

I don't think that Silex created the files there however, so I do not know how useful this will be

I can try to send the website files if you need them

**Comment by Falco312** [comment]
Hi, I have the same issue, I try to publish to Dropbox.

**Comment by lexoyo** [comment]
Hello
I recently moved editor.silex.me from heroku to our own green server, maybe that is the problem
Would you try on the old server here and tell me if it works?
https://heroku.silex.me/

**Comment by Falco312** [comment]
To me it works perfekly this time, tested on Opera browser

www.woodyko.cz

**Comment by lexoyo** [comment]
So it works on heroku.silex.me but not editor.silex.me?

**Comment by lexoyo** [comment]
Ok thx
I'll fix that soon

**Comment by lexoyo** [comment]
Ok, indeed it was our new server
I had setup 2 instances of silex, and publication was asking status on 1 or the other instance, which did not know about the publication status on the other one
Now fixed

Thank you @NSX2022  @Falco312

**Comment by Falco312** [comment]
Thank you, I am really satisfied with tool and support.

**Comment by lexoyo** [comment]
Great ! :))

Don't forget to subscribe to the newsletter
https://mail-list.silexlabs.org/subscription/cemnfkaVrK?locale=en-US

And to give 5 min to silex as described in the section "Show Silex Some ❤" here
https://www.silex.me/community/

Have fun
