### ISSUE TITLE
Full-Width 100% (french)

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#121]
Je constate qu'il est difficile de faire un site en Full-Width-100% et d'avoir le contenu centrer. J'ai essayé plusieurs chose notamment pour avoir un BG (background) à la façon Parrallaxe sans charger le fichier (ce qui est plus rapide je pense?). 

J'ai trouvé une solution met qui demande quelques manipulations relativement simple. 

Le résultat : http://leofrancia.fr/websites/full-width/

<b>1- sur le composant-bg mettre <code>width:100%</code> (en mode Apollo)</b>

<b>2- Pour un site de 800px de largeur (important). Dans l'éditeur CSS ajouter </b>

<code>.center-content{
    margin-left:-400px !important;
    left:50% !important;
}</code>

<i> Ca permettra de centrer le contenu sur le bg.</i> Pour le moment tout est bon, voila un site près pour le 100%. Tout ce qui sera dans le container sera centré. Tout ce qui sera hors du container peut être en 100% en lui mettant 100% directement dans la box Apollo ou avec une class-CSS :

<code>full-width {
    left: 0% !important;
    width:100% !important;
} </code>

et écrire 'full-width' sur la class-CSS.

<b>3- Pour avoir plusieurs bg fixe il faut ajouter dans l'éditeur CSS :</b>

<code>.full-bg{
  width:100% !important;
  margin:0;
  padding:0;
  background: no-repeat center fixed; 
}</code>

<i>En gros les images de fonds sont sur le background, et les contenus sont centrè sur les images de fonds. Je trouve que c'est plus maniable.</i>

<b>Pour un site de 1280px de large il faudra modifier le 'center-content' en divisant par 2 = 640 donc :</b>

<code>.center-content{
    margin-left:-640px  !important;
    left:50%  !important;
}</code>

Quand pensez-vous ? C'est plus maniable ? peu être intéressant aussi d'automatisé la manipulation ?

**Comment by lexoyo** [comment]
This is no longer needed
Please use sections now
