### ISSUE TITLE
XYZ widget for Silex

### ISSUE THREAD

**Issue by Refina123** [silexlabs/Silex#1421]
## About this widget

Adding the feature xyz to your site

## Set up the widget

Add this **in the HTML head editor**:

```html
...
```

Add this **in the JS editor**:

```js
...
```
Add this **in the CSS editor**:

```css
...
```

## How to use

Add the **CSS class `xyz` to...

## Conclusion

Please comment if you like this widget

**Comment by BaguetteAgile** [comment]
Hello @Refina123 

It seems to me that the codes are missing in your post ?

**Comment by lexoyo** [comment]
Strange...
