### ISSUE TITLE
NGINX 502 Error - Troubleshooting

### ISSUE THREAD

**Issue by DirrigM** [silexlabs/Silex#1423]
Hi Silex Team !

I work on [editor.silex.me](https://editor.silex.me/) since few months. Sometimes I make a pull on my laptop, work on my pictures, push after on my github and work again on [editor.silex.me](https://editor.silex.me/), and everything is fine. Until I did a "git revert" on my repository today, and since I have this message on [editor.silex.me](https://editor.silex.me/):

```
Open file
Error: I did not manage to open this file.
NGINX 502 Error :/
If you are the developer, check your application's logs. See the link below for details
[Docs - 502 Troubleshooting](https://caprover.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error)

```
There is a link between my revert and this error message ? Or there is something to do for silex after a revert ?

**Comment by lexoyo** [comment]
Would you try with silex desktop?
Or even better if you are familiar with command line try with silex-website-builder from npm please

**Comment by DirrigM** [comment]
Silex Desktop starts fine, I choose my filesytem and this is rolling a long time and after that I have this message :
```
Open file
Error: I did not manage to open this file. Network error, please check your internet connection or try again later.
```
Check my network and it is fine, try with another PC and it's also the same result as above.

I have  npm v9.2.0 and node v18.12.1. Silex (localhost by npm) starts fine with the environment variables : 
ENABLE_FS=true
ENABLE_HOSTING_GH_PAGES=true
GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET configured

I can explore my FileSystem, I click on my index.html but doesn't do anything. Also I can't use Github (maybe I missconfigured...)

I'm gonna try with another network just in case...

**Comment by DirrigM** [comment]
I don't have the answer but I fix the problem with a backup of the last week that I saved in an another PC. I pull up, I replace the index.html and the index.json with my backup and I push on github and since I can use editor.silex.me... Maybe my .json file was corrupted by the revert...
Anyhow thank you anyway for your quiet answer :-)
