### ISSUE TITLE
adding css code to editor not lasting after publishing

### ISSUE THREAD

**Issue by NullPounce** [silexlabs/Silex#1436]
silex desktop in windows 11
 CSS is not my best but when I add this code in the "code" button, the CSS editor it works even in the browser with index.html but not after I publish.

///////////////////////////
//////////////////////////

a.editable-style.image-element[data-silex-type="image-element"] {
  text-decoration: none;
}

a.editable-style.image-element[data-silex-type="image-element"] img {
  margin-top: 10px;
  transition: transform .1s ease;
  width: 100%;
}

a.editable-style.image-element[data-silex-type="image-element"]:hover img {
  transform: scale(1.03);
}

a.editable-style.image-element[data-silex-type="image-element"] {
  text-decoration: none;
}

a.editable-style.image-element[data-silex-type="image-element"] img {
  margin-top: 10px;
  transition: transform .1s ease;
  width: 100%;
}

a.editable-style.image-element[data-silex-type="image-element"]:hover img {
  transform: scale(1.03);

/////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////

live at nullpounce.com and this code does a image hover over effect on only href images
but not when I publish it.

here is an example html snippet of an image that needs the CSS effect

//////////////

<a class="editable-style image-element silex-id-1677492664195-4" href="https://github.com/NullPounce/VirtuTerm"><img src="assets/term.gif"></a>

////////////

**Comment by lexoyo** [comment]
Hi
Please check in the published html if the class .editable-style is removed?

**Comment by NullPounce** [comment]
found a string of said css code inside css\styles.css in the published folder but no reference in index.html

think this is the one liner inside styles.css ?

.nav-mark a {transition: background-color .5s ease;}.sub-nav.sub-nav-active {width: 250px; box-shadow: 0 1px 10px black;}.sub-nav {transition: all .15s ease-out; z-index: 100; cursor: pointer;}.image-element img {opacity: 1; transition: opacity 0.5s ease-in-out;}a.editable-style.image-element[data-silex-type="image-element"] {text-decoration: none;}a.editable-style.image-element[data-silex-type="image-element"] img {margin-top: 10px; transition: transform .1s ease; width: 100%;}a.editable-style.image-element[data-silex-type="image-element"]:hover img {transform: scale(1.03);}a.editable-style.image-element[data-silex-type="image-element"] {text-decoration: none;}a.editable-style.image-element[data-silex-type="image-element"] img {margin-top: 10px; transition: transform .1s ease; width: 100%;}a.editable-style.image-element[data-silex-type="image-element"]:hover img {transform: scale(1.03);}


in the gui, at the very bottom after clicking on a image with a href i have added ".editable-style" as a css class an that also does not work

**Comment by NullPounce** [comment]
site still works before publish when I upload the files to static hosting so I'm going to close this.

**Comment by lexoyo** [comment]
It's important to publish, the site is heavy otherwise

**Comment by lexoyo** [comment]
I think you should remove all .editable-style from your css
