### ISSUE TITLE
Is there any way to specify the home/start page?

### ISSUE THREAD

**Issue by barkingPete** [silexlabs/Silex#147]
Normally the first page is the home page - and that is understandable. But what does one do if one has built a large web site and wants to "insert" a new Page 1/Home page. At the moment it seems that the only way is to start again building the new page as the first page.

Is there a way of specifying "I want this page to be the home page". If not - it might be a useful feature for those at the end of a long edit! :0)

**Comment by lexoyo** [comment]
It should be fixed by now, can you confirm? thx
