### ISSUE TITLE
Add missing CSS properties to the editor

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1500]
* [x] z-index

**Comment by lexoyo** [comment]
@ceubri @MoreauJonas
Please add the styles you need here
When you have to use custom css

**Comment by lexoyo** [comment]
Here is a list by chatgpt

Vérifiez si c'est dans la liste avant de suggérer une propriété svp

#### Layout
- [ ]  [`position`](https://developer.mozilla.org/en-US/docs/Web/CSS/position)
- [ ] [`top / right / bottom / left`](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties)
- [ ] [`display`](https://developer.mozilla.org/en-US/docs/Web/CSS/display)
- [ ] [`float`](https://developer.mozilla.org/en-US/docs/Web/CSS/float)
- [ ] [`clear`](https://developer.mozilla.org/en-US/docs/Web/CSS/clear)
- [ ] [`box-model (margin / border / padding / width / height)`](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties)
- [ ] [`flex`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex)
- [ ] [`grid`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid)

#### Colors and Backgrounds
- [ ] [`color`](https://developer.mozilla.org/en-US/docs/Web/CSS/color)
- [ ] [`background`](https://developer.mozilla.org/en-US/docs/Web/CSS/background)

#### Fonts
- [ ] [`font`](https://developer.mozilla.org/en-US/docs/Web/CSS/font)
- [ ] [`text-transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform)
- [ ] [`text-decoration`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)

#### Text Effects
- [ ] [`text-shadow`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow)
- [ ] [`text-overflow`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)
- [ ] [`white-space`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space)
- [ ] [`text-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align)

#### Borders
- [ ] [`border`](https://developer.mozilla.org/en-US/docs/Web/CSS/border)
- [ ] [`border-radius`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius)

#### Lists
- [ ] [`list-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style)

#### Effects
- [ ] [`transition`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition)
- [ ] [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)
- [ ] [`box-shadow`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow)
- [ ] [`opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity)

#### Tables
- [ ] [`border-collapse`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse)
- [ ] [`border-spacing`](https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing)
- [ ] [`vertical-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align)

#### Animations
- [ ] [`animation`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)

#### Generated Content
- [ ] [`content`](https://developer.mozilla.org/en-US/docs/Web/CSS/content)
- [ ] [`quotes`](https://developer.mozilla.org/en-US/docs/Web/CSS/quotes)
- [ ] [`counter-reset / counter-increment`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters)

#### Images and Gradients
- [ ] [`object-fit / object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Scaling_of_svg_backgrounds)
- [ ] [`mask`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask)

#### Other
- [ ] [`z-index`](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index)
- [ ] [`cursor`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)
- [ ] [`visibility`](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility)
- [ ] [`overflow`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow)
- [ ] [`clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip)
- [ ] [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)
- [ ] [`resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)
- [ ] [`scroll-behavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior)
- [ ] [`will-change`](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)

**Comment by MoreauJonas** [comment]
Container:

- création simple de ul/ol > li et donc tous le CSS qui en découle (list-style-position / list-style etc…)


CSS:

- text-decoration
- text-transform
- overflow
-  z-index
- pointer-events
- cursor
-  columns
- column-gap
- Border → sur un seul coté : 0px 0px 0px 1px
- outline
- word-break
-  white-space
- content


TARGET:

- :not(:first-child)
- :first-child
- :nth-child(even)
- :nth-child(odd)

**Comment by ceubri** [comment]
- max-height
- min-width
- background: linear-gradient(-45deg, #FFF6FA, #ffffff);
- object-fit: cover;
- object-position: center;
- ::placeholder {color: #8873FE;}
- input:focus {border: 2px solid ##9977FE; background-color:#ffffff;}
- :focus { outline: none;}

**Comment by lexoyo** [comment]
Thx guyz!
