### ISSUE TITLE
Left panel and mobile editor bug

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#1504]
Reproduce:

* open silex v3
* switch to mobile portrait view
* open the page panel

What I expect

* the view slides on the right
* the width of the mobile editor stays the same

What I see

* the view slides on the right
* the width of the mobile editor shrinks

**Comment by GetLikha** [comment]
On V2, if I select an element in mobile view and switch to desktop, the element selected doesn't deselect, and the hover outlines glitch and show the mobile view hover outlines.

I can record a screen capture as an example

**Comment by lexoyo** [comment]
Hello
It is normal that the object do not deselect, but the glitch is probably a bug
I tried but I don't reproduce. And honestly I will not have the time to look into this
I hope you can still do your work?

**Comment by GetLikha** [comment]
> Hello It is normal that the object do not deselect, but the glitch is probably a bug I tried but I don't reproduce. And honestly I will not have the time to look into this I hope you can still do your work?

Yes all we do is select an empty space, and we switch back without any problems😊
