### ISSUE TITLE
Mobile Version Keeps Breaking

### ISSUE THREAD

**Issue by NullPounce** [silexlabs/Silex#1506]
one small edit my phone loads the mobile version and the next it does not, I have started with and without a template, I would like to know what exactly is breaking it, position of something i think. desktop version.

**Comment by lexoyo** [comment]
Hello
Would you share the website after publication and in a broken state pls?

**Comment by NullPounce** [comment]
it's nullpounce.com

i'll have to try and make those versions, i'll open a template and start adding my stuff in and the mobile version loads fine then one tiny edit and it only loads desktop, when I have time i will look into it more. So far I've noticed i can make a template and start copying over my things and that does not break it, I believe it has something to do with the position and size and area of some items.

I also don't think Silex looks for mobile identifiers and only the screen size, not sure what I need to change to make it load mobile.
I see 2 options, 1 edit at a time until making the site is done, being careful of sizing and not breaking mobile, then the other which is possibly a code snippet to add some where.

**Comment by lexoyo** [comment]
Hello
Sorry for the delay, I'm working hard on the next version of silex, it's hard to switch  back and forth
Your site seem to work on mobile

**Comment by lexoyo** [comment]
I'm closing this as I can not reproduce
Let me know if you still need help
Also I can give you access to Silex v3 soon if you want to try and see if it works better for you
