### ISSUE TITLE
I found a bug: ...The appimage no work in Linux (Garuda Linux). I open the program is ok but I can't see the interface only I see a white color.

### ISSUE THREAD

**Issue by carlosgraphic** [silexlabs/Silex#1508]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**If you use Silex online, please complete the following information**
 - URL: [e.g. editor.silex.me]
 - The website you are working on [e.g. https://yourwevsite.com]

**If you use Silex desktop app, please complete the following information**
 - Silex desktop version: [e.g. v2.7.23]
 - OS: [e.g. Windows 10]
  - The website you are working on [e.g. https://yourwevsite.com]

**Additional context**

**Comment by jrreally** [comment]
Hi Carlosgraphic,

I am running Debian 12 and see the same thing - if you start the program in the CL you will see a message "Sarting app on http://localhost:6805/custom.html" To use Silex copy and paste to a browser.

**Comment by lexoyo** [comment]
That's a good workaround thank you @jrreally 

I'm currently not maintaining the desktop app
