### ISSUE TITLE
Mobile site not loaading correctly

### ISSUE THREAD

**Issue by SPACESODA** [silexlabs/Silex#1509]
** the bug**
The mobile version of my silex site is not working. I published my website on gitpages and it works fine on the web but on mobile the layout seems to get jumbled, any fixes for this?

**Expected behavior**
The mobile site shuld look like the mobile version that was created in silex desktop.

 - Silex desktop version: [ v2.7.30]
 - OS: [Windows 10]
 - Browsers [Brave and Chromei]
  - The website i'm working on [spacesoda.github.io]

**Comment by lexoyo** [comment]
Hello
Could you try to publish from https://editor.silex.me ?

**Comment by SPACESODA** [comment]
> Hello Could you try to publish from https://editor.silex.me ?
> […](#)
> On May 16, 2023, 16:32, at 16:32, SPACESODA ***@***.***> wrote: ** the bug** The mobile version of my silex site is not working. I published my website on gitpages and it works fine on the web but on mobile the layout seems to get jumbled, any fixes for this? **Expected behavior** The mobile site shuld look like the mobile version that was created in silex desktop. - Silex desktop version: [ v2.7.23] - OS: [Windows 10] - Browsers [Brave and Chromei] - The website i'm working on [spacesoda.github.io] **Additional context** Add any other context about the problem here. -- Reply to this email directly or view it on GitHub: #1509 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

**update**
I was able to get  the silex template "start up" published and working on both mobile and desktop using https://editor.silex.me/.

**New Issue**
The silex website is not updating the changes made to the website after the first publish, I have changed several elements on  in the editor which are not being shown on the live site after publishing, instead only the default content from the template called "start up" is being shown.

**Comment by lexoyo** [comment]
Ok great
Please open a new issue for the new problem and don't forget to give me details (e.g. links) so that I can reproduce
