### ISSUE TITLE
Beta / Bug testing

### ISSUE THREAD

**Issue by Daydreamofpeach** [silexlabs/Silex#1518]
Hi there, 
I am such a fan of your aims and goals with v3 and would love to be a part of testing and bug reporting / troubleshooting, I am also interested in developing some plugins

**Comment by lexoyo** [comment]
Hello !
That's awesome, thx ! :D 
We have setup  https://community.silex.me/  with @BaguetteAgile 
Let's use it and bring everyone there ?
