### ISSUE TITLE
I found a bug: Silex v3  "Gitlab API error"

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#1526]
@lexoyo 

**Describe the bug**

l'erreur apparaît qd je change une valeur avec les flèches du clavier.

![Capture d’écran du 2023-08-01 11-54-56](https://github.com/silexlabs/Silex/assets/35597855/af8e9153-e8fb-4080-895f-c4b48077d93b)

**Comment by lexoyo** [comment]
Merci pour le rapport de bug

**Comment by lexoyo** [comment]
pour info j'ai regardé, et le probleme est qu'on fait plein de "save" dans ce cas, je vais devoir implémenter un mécanisme de sauvegarde plus intelligent

**Comment by BaguetteAgile** [comment]
Je viens de tester @lexoyo, le message est toujours là lors des changements via clavier.

**Comment by lexoyo** [comment]
Ah merde
Tu as bien rafraîchi la fenêtre en vidant le cache?

**Comment by lexoyo** [comment]
Ok la j'ai compris, c'etait dans le cas d'un save qui prend du temps (comme avec l'api gitlab qui est lente)

Pour info voici le fix: https://github.com/silexlabs/grapesjs-storage-rate-limit/commit/e2906e074f0e9755ca520b961c26b4ee88ae2810

Tu peux me confirmer que ca marche @BaguetteAgile ?

**Comment by BaguetteAgile** [comment]
OK @lexoyo , je confirme. Je ferme l'issue.
