### ISSUE TITLE
I found a bug: Incorrect File Linking

### ISSUE THREAD

**Issue by GetLikha** [silexlabs/Silex#1529]
Salut, @lexoyo!

I successfully exported my file using ZIP, but then I encountered some errors when I opened the file.
![image](https://github.com/silexlabs/Silex/assets/132113888/d7368400-70dd-4b6b-af2c-6beba17ee557)
This is how the page looked like, it's not styled. I looked further into it and I noticed something.
![image](https://github.com/silexlabs/Silex/assets/132113888/7edaf5d3-5522-46dd-8b64-0e7315306ce5)
It isn't linked properly. Using `/css/index.css` links it to a folder called css in the root of the drive. Using `css/index.css` works just fine.
![image](https://github.com/silexlabs/Silex/assets/132113888/b2daf3af-8639-4a61-aab2-c9f169369235)
Then now I'm encountering a new problem, it isn't styled correctly.
![image](https://github.com/silexlabs/Silex/assets/132113888/29cca10d-a852-4bfd-877f-9e30d281cb48)
That is how it's supposed to be styled.

**Comment by lexoyo** [comment]
Ok
Did you try to put it online somewhere ?
I am not sure it can be seen judt by clicking on it
What files are missing in the browser network console?

**Comment by GetLikha** [comment]
> 

I haven't put it online yet, but it still shouldn't be that way shouldn't it? 
And pardon me but, what do you mean by the browser network console? What info do I provide from there?

**Comment by lexoyo** [comment]
What was the url of your page when you opened it?

It should be something with localhost

**Comment by lexoyo** [comment]
Or maybe I should write relative paths in the html (./css/style.css)

**Comment by GetLikha** [comment]
> Or maybe I should write relative paths in the html (./css/style.css)

Yeah just using relative paths is the recommended path, especially when there's different folders.

So relative path should work

**Comment by lexoyo** [comment]
Hello @GetLikha 
This bug is fixed with this commit: https://github.com/silexlabs/editor.silex.me/commit/b7af66b5d392b83ba7d48b64b9c297afe363e3e0
Can you confirm it is fixed when you have a moment please?

**Comment by GetLikha** [comment]
Yep it works in v117!

**Comment by lexoyo** [comment]
Cool !
