### ISSUE TITLE
Tags for Image (V3)

### ISSUE THREAD

**Issue by GetLikha** [silexlabs/Silex#1531]
Still working my way around alpha 93 of V3, and if you set a tag name for an image to something else, the option to set it back to IMG disappears. 
![image](https://github.com/silexlabs/Silex/assets/132113888/9726149a-9918-4245-a0bc-34fa7cb61a9d)
![image](https://github.com/silexlabs/Silex/assets/132113888/c4078277-59a3-4870-8ac9-1a066c3c4751)

Maybe it should be removed for certain elements? Only makes sense. Because on export, the IMG becomes the tag name you set.
![image](https://github.com/silexlabs/Silex/assets/132113888/67b2b6f0-c1f6-4020-8beb-a048416b5670)

Also yeah the dropdown text is hard to see, maybe because I'm using dark mode?

**Comment by GetLikha** [comment]
So I digged a bit further, if you set a link, the IMG tag becomes an <a> tag, instead of <img> being wrapped around with an <a> tag.
![image](https://github.com/silexlabs/Silex/assets/132113888/d2ea964d-9623-498c-91ea-f1373d6bf85c)
![image](https://github.com/silexlabs/Silex/assets/132113888/c60bed4c-1f4e-42e6-84d7-49ed155acb99)

**Comment by lexoyo** [comment]
Oh that's a good one, thank you @GetLikha 

When you set a link on an element, it does not wrap it into a link, instead it makes it an A tag. It is because from v3 silex philosophy is to be as close to html/css as possible

When the element is an image element, this breaks the image. Probably other elements too. Please note that when you remove the link it goes back to IMG (right?)

What we should probably do it to warn the user in the link editor and the tag selector?

For the color of the dropdown, could you check if it is your browser? Silex is supposed to be in dark mode already (no light mode yet)

**Comment by GetLikha** [comment]
> 

Ah I see, so I should wrap the <img> with a container that'll become a <a> tag, that's actually a pretty neat way to teach people how html/css works.

I think just a pop up that warns the user like `Warning: Changing this setting may cause the element to work incorrectly.` then maybe a link to a docs about it.

As for the dropdown, well I'm not 100% sure, but the dropdown should still be styled correctly across all browsers right? I'm using Opera One.

**Comment by lexoyo** [comment]
Very true, I will have to do something about this in any case

> As for the dropdown, well I'm not 100% sure, but the dropdown should still be styled correctly across all browsers right? I'm using Opera One.

Oh i'm not sure about opera... Hmm someone should investigate that as opera is an important actor of the free/libre open source world

Would you open an issue with the opera-related problems?

**Comment by GetLikha** [comment]
I'd love to do that, I'll use both Chrome and Opera and see if there's any bugs.

Also I'd love to contribute to docs, do you mind if I can create pages on how to use Silex?

**Comment by lexoyo** [comment]
I would love a collaborative effort on the docs

Let's discuss it in the forums? You probably already have access to create pages otherwise ask JP on the forums. Also in this issues there are useful information about how links work that we should use in the docs :)

**Comment by lexoyo** [comment]
Or just go for it if you feel like it! :)

**Comment by lexoyo** [comment]
I ended up removing the link option for images, that was the simplest to do
Can you confirm it solves this issue please @GetLikha ?

**Comment by lexoyo** [comment]
It looks like this
![Screenshot from 2023-08-28 09-39-19](https://github.com/silexlabs/Silex/assets/715377/c8b539f7-c7a9-47cb-9e2f-1c8b695527f9)

**Comment by GetLikha** [comment]
It works!
I also wrapped it around a container and added a link, it works well

**Comment by lexoyo** [comment]
Great thx!
