### ISSUE TITLE
Page Settings won't close on open (V3)

### ISSUE THREAD

**Issue by GetLikha** [silexlabs/Silex#1533]
![2023-08-14-13-59-30](https://github.com/silexlabs/Silex/assets/132113888/5d126639-5a1c-4bdb-aa79-31afac53aef0)
Whenever I open page settings, I can't close it, either using the X, Cancel or Ok button
I can't recall if I already opened this because I swear I did

**Comment by GetLikha** [comment]
I also have some suggestions for Site Settings and Page Settings
It's confusing because site settings and page settings has similar settings like language, favicon, social media sharing and HTML head

Maybe instead site settings can contain just the Website Name, Website Language, favicon and head
And for page settings it's title, description, and social network sharing?

Because if I put code in the <head> of site settings, I'm not sure if it'll also apply for page settings, because it doesn't show there. So maybe either change the customization for page and site settings or make site settings work like symbols? Just a thought \:)

**Comment by lexoyo** [comment]
Hello @GetLikha 
Thank you for this bug report, I found and fix this bug: https://github.com/silexlabs/Silex/commit/1bb94a5304e38699ead0fe1405bad1a5b71aeec0#diff-829a43fd501ecd4effd94d573e70de7881aa94b1fac66f50f177102b32177ccbL49
Also made the head code editor way better 
Would you please confirm the fix works for you?

**Comment by GetLikha** [comment]
Hey there!
I just checked on version 106, it still doesn't work.
I'll try on different devices, but yeah






---- On Tue, 22 Aug 2023 14:14:36 -0300 Alex Hoyau ***@***.***> wrote ---





Hello https://github.com/GetLikha
 Thank you for this bug report, I found and fix this bug: https://github.com/silexlabs/Silex/commit/1bb94a5304e38699ead0fe1405bad1a5b71aeec0#diff-829a43fd501ecd4effd94d573e70de7881aa94b1fac66f50f177102b32177ccbL49
 Also made the head code editor way better
 Would you please confirm the fix works for you?

**Comment by lexoyo** [comment]
Oh that's surprising
I'll re-check tomorrow
Did you make sure to empty the browser cache?

**Comment by GetLikha** [comment]
I cleared my cache, that was the problem 
Page settings works now!


I also love what you did with the head code. Just to confirm, if I add something in the head code for site settings, it'll be applied to all pages? Or?
Just want to confirm for docs and other stuff, while learning how to use v3 myself :D.






---- On Tue, 22 Aug 2023 17:43:25 -0300 Alex Hoyau ***@***.***> wrote ---





Oh that's surprising
 I'll re-check tomorrow 
 Did you make sure to empty the browser cache?

**Comment by lexoyo** [comment]
Great !.
The head code in the settings is applied on all pages yes :)
Feel free to ask
Have a nice day
