### ISSUE TITLE
Silex opens to a blank no gui

### ISSUE THREAD

**Issue by waelkasim** [silexlabs/Silex#1537]
Hi, installed the Appimage on my Debian 12/Gnome AMD64 desktop with Gear Lever, when launched I get a blank white nothing .. no gui .. nothing at all. I downloaded older releases all to the same result. Please help. Thanks.

**Comment by lexoyo** [comment]
Hello
Thank you for the feedback
Unfortunately the desktop version of Silex is not up to date with the latest devs (v3), so I can not take too much time debuging it
Would you please use either [editor.silex.me (v2, will soon be deprecated)](https://editor.silex.me/) or [v3.silex.me (v3, recommended)](https://v3.silex.me/)
