### ISSUE TITLE
l'outils d'intégraton des listes <ul>,<ol> et <li> ont disparu

### ISSUE THREAD

**Issue by MoreauJonas** [silexlabs/Silex#1538]
**Describe the bug**
Il n'est plus possible d'intégrer des listes (ordonnées ou non), comme sur les versions précédentes de silex

Avant:
![image](https://github.com/silexlabs/Silex/assets/102809203/1d913113-3e24-4f7c-8f20-783ce8d28738)

Après:
![image](https://github.com/silexlabs/Silex/assets/102809203/2dd1fcf6-9529-4c0d-9132-f02c8be39864)

**If you use Silex online, please complete the following information**
 - URL: [[e.g. editor.silex.me]](https://v3.silex.me/)
 - Browser [e.g. chrome]

 - Silex desktop version: 3.0.0-alpha.117
 - OS: [e.g. Windows 11]
 - Browser Chrome

**Comment by lexoyo** [comment]
Juste une question @MoreauJonas 
Est-ce qu'on a ul et li dans la liste des tag names? Est-ce que ca serait pas mieux que dans l'éditeur de texte ? Je réfléchis tout haut la
