### ISSUE TITLE
fonts in Silex

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#154]
The goal is to add fonts from Open Font Library, Google web fonts, etc 

In the settings dialog, there should be a “fonts manager” tab. With a link to it in the text style manager would.

When a font is added to a website it would be available in the text style manager.

So the font

### Solution 1

The font manager would be a list of fonts included in the site. One would be able to add fonts from Open Font Library, Google web fonts, etc by providing the URL of the font page.

### Solution 2

Use APIs to list and preview the fonts and install them

**Comment by lexoyo** [comment]
this is solved by today's release
see the new inline text editor, the style editor, the font manager
and the [related docs](https://github.com/silexlabs/Silex/wiki/editor-ui#text-editor)
