### ISSUE TITLE
Cannot save website thru GitHub

### ISSUE THREAD

**Issue by olriskinkutz** [silexlabs/Silex#1542]
I logged into my github account, choose save as, and then hit "OK" top right. A few moments later, the following error appears: "Save website Error: I did not manage to save the file. Could not complete action writefile: Cannot create file here." What's going wrong here? I've tried logging out of Github and back in again through Silex.

**Comment by lexoyo** [comment]
Hello
This is because github is special: the first level of folders are called repositories so you can not add a file at the first level
The second level is a branch so same
Create a folder then another folder into it (or use the default which is called main) then save your website inside it
