### ISSUE TITLE
Angular 14 , Integration Silex in vuexy Theme ,

### ISSUE THREAD

**Issue by FaziHamza** [silexlabs/Silex#1550]
How i integrate Silex in vuexy Theme , or any Angualr 14 Project ? how it possible ?

**Comment by lexoyo** [comment]
You should use GrapesJS directly
https://grapesjs.com/

**Comment by FaziHamza** [comment]
Thanks for inform me but if i need to use Silex directly what i need to do ?

**Comment by lexoyo** [comment]
I have no idea sorry

**Comment by FaziHamza** [comment]
> You should use GrapesJS directly https://grapesjs.com/

once i import its give me JSON like silex ? or only html ?

**Comment by lexoyo** [comment]
Both
