### ISSUE TITLE
Custom <head> code must be reapplied

### ISSUE THREAD

**Issue by jcamille2023** [silexlabs/Silex#1559]
Hello,
When using v3, I often find myself having to reapply the custom code I insert into the head, usually an outside stylesheet. Usually I have to reapply it when I switch pages; and it happens to both the site-wide custom head tags and the ones for the page. The code is saved, it is just not automatically applied. It presented an issue when I published my site and nothing was applied, but after I reapplied the <head> tag, it worked fine.

In case it helps, I'm on Chrome v120.0.6099.201 on Windows 11.

**Comment by lexoyo** [comment]
Nice catch @jcamille2023 thank you for the bug report
 I'll let you know when it is fixed

**Comment by lexoyo** [comment]
Apparently it works fine with Firefox, strange

**Comment by lexoyo** [comment]
hey @jcamille2023 
I managed to fix that, it will be live in a week or so, next release :birthday:

**Comment by lexoyo** [comment]
It works but not when I switch to a different page
