### ISSUE TITLE
Insert Video (and audio) in Silex

### ISSUE THREAD

**Issue by barkingPete** [silexlabs/Silex#156]
I like SIlex. But I would like it more if I could easily add a video box or play audio on a page.

I thought I would have a look at the obvious method - open a HTML box on a page and add a HTML5 video tag. The result seems work - see test site at : http://81.187.107.36  There seem to be problems between browser functionality but chrome works OK.

However images on the page are sometimes not displayed or other graphic features are "wrong". I am still trying to characterise these features and situations. 

It would be really nice feature if we had an "Insert Video" choice under the "Insert" menu option. Not sure how one who insert an "invisible" Audio player but that would obviously be useful too. One thing that would need to be considered would be to turn the video/audio player off when changing the page.

**Comment by barkingPete** [comment]
I have noticed one problem with this method and the current silex versions. The video is started on opening the site and not on opening the page. So it would be difficult to include more than one video and only then on the first/home page.

The page object show and unshow methods (or whatever they are called) might need modification to cope with any embedded HTML scripts/functions

**Comment by singchan** [comment]
+1

**Comment by barkingPete** [comment]
I suppose I should add some detail to the comment I made above. I suppose that if the video did not "auto-start" and was instead started using on-screen controls the it may be possible to use a number of video instances on several pages. But the video player would still need to be stopped when a page was changed. This would need some sort of message passing/event system that could be used. Not sure if that is possible in this version of the silex architecture?

**Comment by lexoyo** [comment]
Hmm... Not sure if it is possible with all the video players... Youtube, Dailymotion and more importantly video.js (because it is open source ;)

**Comment by lexoyo** [comment]
Hello 

I have found a way to fix this. The videos will stop when not on the current page. For this I remove all iframes content while not on the current page.. This should do the trick in most cases.
https://github.com/lexoyo/Silex/commit/82190b00c5207bff8c46e81ae2b287cd7ee31baa

It will be soon online

cc @Stuff31

**Comment by barkingPete** [comment]
Ha - a neat idea. I look forward to seeing if this works. It was easy in previous versions to demonstrate video on the home/first page but impossible to use successfully with more than one page..Keep up the good work lexoyo!

**Comment by lexoyo** [comment]
Done, it is online 
Thx for your support @barkingPete :santa: 
What are you up to now?

**Comment by barkingPete** [comment]
Hello Alex

 Thanks for your message and sorry I did not reply sooner. Problems in
Greece and Ukraine have distracted me a bit!
I am "up to my ears" in non computer related work. I have to maintain the
house here in Brighton and I have to complete the building of  my shack in
Greece. As for my flat in Ukraine - I hope neither side needs to shoot at
it! What a bad situation...

So I have been too much to concentrate on the Silex system. I note you have
improved the video playing on other pages and I will try to test it when
the building work is complete for this year. Here in UK it has been raining
for so long everything has turned to mud! Which makes any building work
very difficult.

But just because I don't visit Silex  too often - I think it is an
excellent idea! keep up the good work comrade. :0)

Onward

**Comment by lexoyo** [comment]
:+1:
thx for the support and good luck with your many activites!
