### ISSUE TITLE
How to enable Dashboard, Templates and SFTP on Docker

### ISSUE THREAD

**Issue by AndresJ551** [silexlabs/Silex#1598]
Hello! Nice work with Silex, it looks great and the provided image is easy to install.

I'm following the instructions from https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex
It's working but seems like it's only for one project, I can't select any template or go back to the dashboard to select SFTP as an option to publish.

All I get is the editor page:
![image](https://github.com/silexlabs/Silex/assets/2750488/95055e37-d6b0-4a60-ad10-d29eb7ba09f6)
Selecting "Sign off" only refresh the page and the colourful square on the top right does nothing.

"Publish" shows the dialog:
![image](https://github.com/silexlabs/Silex/assets/2750488/e5134c10-8bab-4eae-adb3-235a07d117b7)
But I have FS disabled on my environment:
```
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=18.20.2
      - YARN_VERSION=1.22.19
      - SILEX_EXPRESS_JSON_LIMIT=1mb
      - SILEX_EXPRESS_TEXT_LIMIT=10mb
      - SILEX_EXPRESS_URLENCODED_LIMIT=1mb
      - SILEX_SESSION_NAME=silex-session
      - SILEX_SESSION_SECRET=
      - SILEX_PORT=6805
      - SILEX_HOST=*my_domain*
      - SILEX_PROTOCOL=http
      - SILEX_DEBUG=FALSE
      - SILEX_SERVER_CONFIG=
      - SILEX_SSL_PORT=
      - SILEX_SSL_PRIVATE_KEY=
      - SILEX_SSL_CERTIFICATE=
      - SILEX_FORCE_HTTPS_TRUST_XFP_HEADER=
      - SILEX_CORS_URL=*my_domain*
      - SILEX_FS_ROOT=
      - SILEX_FS_HOSTING_ROOT=/silex_data/hosting
      - SILEX_URL=*my_domain*
      - SILEX_FORCE_HTTPS=false
      - UNSPLASH_ACCESS_KEY=
      - ENABLE_SFTP=true
      - UNSPLASH_APP_NAME=
      - ENABLE_FS=false
      - SKIP_HOSTING_SELECTION=false
```
I did both the docker pull from https://hub.docker.com/r/silexlabs/silex and the Docker image build with the exact same results.
I can provide access to the front-end for the installation if needed.

While searching I found the https://github.com/silexlabs/silex-dashboard as a "plugin" but have no documentation about how to install it.

Thanks!

**Comment by lexoyo** [comment]
Hello
Thank you for the positive feedback
What you are looking for is this repo
https://github.com/silexlabs/editor.silex.me
That is the code behind v3.silex.me
It has a Dockerfile too and adds a few en vars / options
Are you deploying on a server? What's your project?
Have a nice day

**Comment by lexoyo** [comment]
Another question is: where do you think I should put the link to this repo?

**Comment by AndresJ551** [comment]
Thanks for the fast reply!
Yes, I'm deploying on a VPS. I'm happy to share the link with you privately.
I think you should add a comment right here https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#as-a-web-app-silex-web-version I know it's  different repo, but I found this one first while searching (and popped up as an alternative to webflow on https://alternativeto.net/software/webflow/about/)
I will try installing the editor version and let you know!

**Comment by lexoyo** [comment]
Great!
Feel free to contact me on Silex community chat
https://short.silex.me/chat
Or here :)
I'm always curious about people projects and use cases
Bye!
