### ISSUE TITLE
Webp images are useable, but not properly supported

### ISSUE THREAD

**Issue by JPAKx4** [silexlabs/Silex#1607]
When selecting an image I can upload a .webp and it will show as an option for a few seconds, and then disappear. If I select it before it updates, then it works completely fine.

To reproduce: new project, add an image, and set the source. I'm using GitHub, but the other options probably work for reproducing this bug. Upload the .webp, then select it quickly. You can only try this once, if you miss the window you have to refresh the editor for it to appear again.

Images show up completely fine. projectgetmoving.org is my Silex site, every image is a .webp

**Comment by lexoyo** [comment]
Hello @JPAKx4
thank you for the bug report
Please note that I work on Silex v3 now, I don't maintain Silex v2 which is the one you are using
Silex v3 is not officially released yet but you can use it already on v3.silex.me
Your project looks great! Come talk on community.silex.me
have a nice day
