### ISSUE TITLE
v3 site navigation page menu

### ISSUE THREAD

**Issue by JonnyTech** [silexlabs/Silex#1611]
Just discovered Silex and jumped straight in to version 3.

I am trying to create a multi-page site with a menu to navigate to them.

Does this exist in v3 or can you provide any code to create a basic menu?

**Comment by lexoyo** [comment]
Hello
There is no menu block, instead you need to create your menu from scratch (in the future there will be a way to share "libraries" of blocks with others)
A menu is often a container with links to pages inside.
Let me know if you need a more complex menu and I will guide you
