### ISSUE TITLE
network error when opening localhost

### ISSUE THREAD

**Issue by betternightlifeproject** [silexlabs/Silex#1617]
installed and was working with silex last night. i deployed it using vercel and then after a bit i went back to continue working. now when I open localhost it gives me a notification that says "An error occured. NetworkError when attempting to fetch resource." going through any action results in the same error. here's the issues that show up when i load the page. i'm using firefox.
![image](https://github.com/user-attachments/assets/fdce67b9-8c73-42c8-ab2f-06f9c8832a35)
![image](https://github.com/user-attachments/assets/36e111d7-8450-47c7-a3cc-cc0d5397449a)
![image](https://github.com/user-attachments/assets/334e7087-e78d-4dd8-81c1-259b2af07a7a)

**Comment by lexoyo** [comment]
Could you tell me what code you use exactly to run Silex?
Is it live somewhere, can I try it? Instead of the Web colsole can you screenshot the network tab?

**Comment by betternightlifeproject** [comment]
i was using the npm/npx install, i switched to the desktop client and it still wasn't working so i poked around a bit more. idk why i didn't think about firewall, but checking silex-desktop as allowed to bypass on private as well as public networks did the trick.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by lexoyo** [comment]
Oh yes OK, good to know
If you want I give you the editor rights and you add it to the docs somewhere?

Beware that the desktop app is Silex v2 and is obsolete
