### ISSUE TITLE
download zip / ftp export : css link bug

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#1618]
I just try to export 2 websites with :
- the download zip
- the ftp export options

There is a bug (same on the 2 websites) : the css link is rewriten, it should be :
- link rel="stylesheet" href="./css/index.css"
but it's :
- link rel="stylesheet" href="/css/index-356358c66ed9696aa6ec81629a874bb10f0f1b53ddde45ed60bb1fd45baa1fba.css"

It's very strange @oliviermgx @lexoyo ?

**Comment by lexoyo** [comment]
> There is a bug (same on the 2 websites) : the css link is rewriten, it should be
>    link rel="stylesheet" href="./css/index.css"

Tu écris ça parce que tu as vu dans les fichiers générés que c'est le nom du fichier ?

En attendant, en mode à l'arrache tu peux ajouter ce que tu veux dans le head

**Comment by oliviermgx** [comment]
@ceubri je ne comprends pas bien. A quel moment tu as décidé que ton css s'appellerait "index.css" ? 
Parce que le nom complexe index-356358c66ed9696aa6ec81629a874bb10f0f1b53ddde45ed60bb1fd45baa1fba.css est celui que génère justement l'export (en tout cas pour la publi ftp que je connais et que j'ai eu à modifier, sachant que le zip n'a pas été modifié lui depuis longtemps).

**Comment by ceubri** [comment]
En fait je n'ai pas de CSS : c'est le CSS de silex.
À l'export, le CSS généré est "mal attaché" : du coup l'html s'affiche sans CSS...

**Comment by lexoyo** [comment]
Comme dit @oliviermgx on va avoir besoin d'être sur que ce css n'a pas le bon nom
On comprend pas ce que tu veux dire quoi
Tu peux nous donner accès au repo à tous les deux ? (@oliviermgx c'est quoi ton id gitlab ?)

**Comment by oliviermgx** [comment]
"@oliviermgx"

**Comment by ceubri** [comment]
C'est fait vous devez avoir accès à silex_adeline-vous-coiffe

**Comment by ceubri** [comment]
https://gitlab.com/ceubri/silex_Adeline-vous-coiffe-manual

**Comment by oliviermgx** [comment]
Mince, je ne reproduis pas l'erreur, j'ai pu exporter et publier sans erreur
Suis dispo demain (element ? visio ?)

**Comment by ceubri** [comment]
C'est étrange....De mon côté j'obtiens ce zip...

    Le lundi 4 novembre 2024 à 09:19:10 UTC+1, oliviermgx ***@***.***> a écrit :  
 
 


Mince, je ne reproduis pas l'erreur, j'ai pu exporter et publier sans erreur
Suis dispo demain (element ? visio ?)

**Comment by ceubri** [comment]
[53188580-1730733999492-esn7j.zip](https://github.com/user-attachments/files/17620460/53188580-1730733999492-esn7j.zip)

**Comment by ceubri** [comment]
Si tu testes le zip, tu verras que ça marche pas du tout :)

**Comment by oliviermgx** [comment]
Il faut vraiment qu'on le fasse ensemble car j'ai testé le ZIP et le FTP et ça marche chez moi. On va trouver !

**Comment by oliviermgx** [comment]
j'ai trouvé quelque chose.
@lexoyo le lien construit est en absolu <link rel="stylesheet" href="/css/index-356358c...
ne devrait il pas être en relatif ?
Je ne voyais pas de mon côté car j'ai testé à la racine à chaque fois...

**Comment by lexoyo** [comment]
ah ok
ca me paraissait mieux en absolu mais pas sur
@ceubri tu l'héberge pas a la racine?

**Comment by oliviermgx** [comment]
@lexoyo en fait, pour ce qui est du ftp en tout cas, peut être il faudrait même mettre le path que l'utilisateur défini dans son panel de connexion : "Path where to publish" ou bien mettre en relatif.
et pour ce qui est de la publi zip, il faudrait être en relatif de manière à pouvoir tester son zip (index.html) depuis n'importe quel dossier de l'ordi sur lequel le zip a été téléchargé ?

**Comment by ceubri** [comment]
> en attendant @ceubri tu peux ajouter un "." devant /css (donc href="./css/index-356...) dans ton index.html sur la ligne link ça devrait le faire ? dis moi si ça marche ainsi, si tu veux bien pour confirmer mon hypothèse ? merci

yes cela fonctionne pourle css
mais il a fallut également que je renomme **/assets** en **./assets**

**Comment by ceubri** [comment]
> ah ok ca me paraissait mieux en absolu mais pas sur @ceubri tu l'héberge pas a la racine?

- quand on dezippe et ouvre l'index : les liens sont brisés
- même quand on est à la racine de public-html : les liens sont brisés

Du coup c'est pas top

**Comment by lexoyo** [comment]
> @lexoyo en fait, pour ce qui est du ftp en tout cas, peut être il faudrait même mettre le path que l'utilisateur défini dans son panel de connexion : "Path where to publish" ou bien mettre en relatif. et pour ce qui est de la publi zip, il faudrait être en relatif de manière à pouvoir tester son zip (index.html) depuis n'importe quel dossier de l'ordi sur lequel le zip a été téléchargé ?

Alors en fait ce chemin c'est celui sur le FTP non ?
Mais on pourrait ajouter un "base url"

> > ah ok ca me paraissait mieux en absolu mais pas sur @ceubri tu l'héberge pas a la racine?
> 
>     * quand on dezippe et ouvre l'index : les liens sont brisés
> 
>     * même quand on est à la racine de public-html : les liens sont brisés
> 
> 
> Du coup c'est pas top

Mais les liens sont bien en `/assets/.. ` et `/css/... ` ?

C'est fait pour être utilisé avec un serveur web, pas direct de l'ouvrir comme un fichier

Passer de chemins absoluts à relatifs c'est faisable

Le truc c'est qu'on a besoin de chemins absoluts pour les sites basés sur du contenu dynamique car la page html peut avoir un permalink qui sera dans des dossiers et sous dossiers

Si vous voulez faire ça, voici quelques pistes @oliviermgx

* soit tu fais comme pour les fonts, tu ajoutes un publication transformer, tu ajoutes un fichier qui utilises un publication transformer (méthode transformPermalink, cf assetUrl.ts) 
   https://github.com/silexlabs/Silex/blob/b4a900158e3467aa8fb5a967f63a4b3bf9ab00be/src/ts/client/publish-fonts.ts#L26
   https://github.com/silexlabs/Silex/blob/b4a900158e3467aa8fb5a967f63a4b3bf9ab00be/src/ts/client/assetUrl.ts
   https://github.com/silexlabs/Silex/blob/b4a900158e3467aa8fb5a967f63a4b3bf9ab00be/examples/client-config-transformers.js#L38
* ou alors direct tu changes le chemin par défaut ici pour les CSS et la pour les assets
   https://github.com/silexlabs/Silex/blob/b4a900158e3467aa8fb5a967f63a4b3bf9ab00be/src/ts/client/grapesjs/PublicationManager.ts#L369
   https://github.com/silexlabs/Silex/blob/b4a900158e3467aa8fb5a967f63a4b3bf9ab00be/src/ts/client/assetUrl.ts#L67

J'ai une préférence pour la 2e solution comme ça on laisse les plugins modifier si besoin. Mais il faudra bien tester sur tous les projets, j'ai peur des side effects

Il faudra donc appliquer des chemins relatifs seulement si c'est un site sans permalink mais peut être que ça marche sans rien modifier, il y a ici une gestion du relatif pour les CSS mais pas pour les assets (je crois comprendre en lisant ce code)
https://github.com/silexlabs/silex-cms/blob/main/src/client/publication.ts#L695

**Comment by lexoyo** [comment]
> même quand on est à la racine de public-html : les liens sont brisés

@ceubri j'ai regardé aussi et je pense que ca doit marher quand tu dépose dans public-html

tu as le site en ligne qui a ce bug?

**Comment by ceubri** [comment]
exact ça fontionne !! autant pour moi déso j'ai mal tester :
- https://adelinevouscoiffe.fr/00.html
en fait je testais sans ajouter le "index-356358c66ed9696aa6ec81629a874bb10f0f1b53ddde45ed60bb1fd45baa1fba.css"
- car avant l'export ftp ne renommait pas les .css (c'était index.css)

--> Bref : cela fonctionne online (c'est juste les zip qui ne s'y retrouvent pas)
