### ISSUE TITLE
Escape key doesn't work

### ISSUE THREAD

**Issue by sreeveena** [silexlabs/Silex#163]
Operating system: Mac os 10
Operations:  open, close button, escape key:

 Browser: Safari
Text Editor:
1. Esc key does not work without modification in text editor as well as after entering data in the text editor.

 Browser: Chrome
 Text Editor:
1. Esc key does not work in text editor. 

Browser: firefox
Text Editor:
1. Esc key does not work after entering data in the text editor.

**Comment by singchan** [comment]
fixed
