### ISSUE TITLE
Beautiful about me page template

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#167]
- [download](https://github.com/lexoyo/lexoyo.github.io)
- [preview](http://lexoyo.me/)

The free [About me page template](https://github.com/lexoyo/lexoyo.github.io) is an easy to customize page, regrouping all your links in one place. As [this article about "about me pages"](http://hellboundbloggers.com/2011/01/about-me-personal-profile-16926/) says:

>  a personal profile page points to all your content around the web. It’s about more than just your Facebook or Twitter profiles, it’s about your entire online identity. At present your online identity was fragmented across all of the sites you use every day, for example your relationship status, education, location on Facebook, your personal information described at  Twitter, your resume is outlined on Linkedin, and your technical stuff or your passions are presented in your blog.  An about me page gives you a single webpage profile to bring your entire identity to one place in a simple and easy way.

Use [Silex.me](http://www.silex.me) to edit this template and make it your own.

[![screen shot 2014-08-02 at 2 34 21 pm](https://cloud.githubusercontent.com/assets/715377/3787930/4d58378a-1a43-11e4-80bc-5bff8d84b139.png)](http://lexoyo.me/)

[download the archive here](https://github.com/lexoyo/lexoyo.github.io), unzip and open the file editable.html with [Silex editor](http://www.silex.me/silex/) (online).

Then edit the texts, change the links and publish your site (file menu, then "publish")

Related templates
- [Tech tools template](https://github.com/silexlabs/Silex/issues/175)
- [Perso1, Richard favorite free template](https://github.com/silexlabs/Silex/issues/224)

**Comment by Philip2uk** [comment]
What a beautiful piece of work.  Thanks for sharing!
Unfortunately, it does not work on my Android mobile device - I tried it in a number of different Browsers!

**Comment by lexoyo** [comment]
Hi @Philip2uk !
Thank you for the bug report - it is also my about me page, so it'd better work fine ;)

I have tested in an emulator and it looks like this:
![screen shot 2015-01-26 at 1 07 29 am](https://cloud.githubusercontent.com/assets/715377/5893966/e60968fc-a4f7-11e4-9ad9-51808b5dd8d0.png)

Is it different on your device? What is it for a device and what version of android do you have? 
Thank you again!

**Comment by Philip2uk** [comment]
Thanks for looking so quickly!  'Fraid the transparency doesn't work on my Android device (on various Browsers) - still looks good, but the beautiful interaction is not there!

**Comment by lexoyo** [comment]
Oh ok, I think I see

I have disabled the opacity effect on touch enabled devices - you can see this is in the CSS (view > open CSS editor in Silex)

This is because I set the opacity at 100% on roll over, and there is no roll over on touch enabled devices

**Comment by Philip2uk** [comment]
Ah, right - thanks so much!

**Comment by lexoyo** [comment]
:cool: 
keep in touch!

**Comment by lexoyo** [comment]
I'm opening a "showcase" section on [Silex official website](http://www.silex.me/), feel free to submit an issue like this one for one of your creations
