### ISSUE TITLE
Silex and RTL text (Right-To-Left)

### ISSUE THREAD

**Issue by saggers** [silexlabs/Silex#177]
Do Silex is RTL-supported? for using rtl-lang. like hebrew and arabic?

**Comment by lexoyo** [comment]
Hi 
I just found out that you can do this with CSS

For an element to be right to left:
* select the element
* in the css class property ([right column](https://github.com/silexlabs/Silex/wiki/Editor-UI#properties), last property), add a css class name like `rtl` - [see "custom css classes" for help](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#custom-css-classes)
* open the [css editor](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor), and add this rule: `.rtl { direction: rtl }` to apply a right to left direction to the elements with the css class `rtl`

To do this to all the text elements at once, open the [css editor](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor), and add this rule: `.text-element { direction: rtl }`

**Comment by lexoyo** [comment]
This is live now on editor.silex.me
So I'll close this now

Any comment about this new release is welcome here #690

**Comment by lexoyo** [comment]
(there is a RTL / LTR option in the style editor)
