### ISSUE TITLE
dropbox issue "Can not loggin, user not connected yet. You need to call the 'connect' service first"

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#180]
When I try to connect to drop box I log in and authorize then it gives me the error "Can not loggin, user not connected yet. You need to call the 'connect' service first"

**Comment by hilteci** [comment]
Has this issue been updated?  I'm new to Silex and just installed on my Debian server today but seeing the same problem reported here.

Also, I cannot get the local storage option working when running in debug mode either.  This would actually be my preference over dropbox.  When I try to authenticate locally (using a valid username and password set up on my server), I get a message about 'express deprecated req.param(name)' and the 'Wrong login or password' message.  I have gone into www.js and changed this to req.params, but this also causes an error.

Is there a solution for this for those of us who have installed the source code?

**Comment by singchan** [comment]
Hello @hilteci  
This problem is solved, be it will again happen if you delete the folder into which Silex stores the session files (by default dist/sessions but you can change it with an environment variable, see [this section of the readme about env vars](https://github.com/silexlabs/Silex/blob/master/readme.md#environment-variables))

> Also, I cannot get the local storage option working when running in debug mode either. This would actually be my preference over dropbox. When I try to authenticate locally (using a valid username and password set up on my server), I get a message about 'express deprecated req.param(name)' and the 'Wrong login or password' message. I have gone into www.js and changed this to req.params, but this also causes an error.

You are supposed to set your users logins and passwords in a config file called `config.js` in the folder `/dist/server/`, which contains something like this:

```
// here you can override unifile default config
// simply rename this file to config.js
exports.sessionSecret = 'silex not so secret';
exports.cookieName = 'silexcookie';

// activate service www and set your users admin/pass
exports.www.USERS = {
    'marcel': 'abcdefgh',
    'hilteci': 'ijklmno'
};
```

No need to run in debug mode (this would cause admin/admin to work, which is bad luck ;)

**Comment by singchan** [comment]
If you feel like this can be useful, please add all this in [Silex wiki](https://github.com/silexlabs/Silex/wiki)

**Comment by hilteci** [comment]
Hi @singchan,

Thanks for the message.  I will be happy to document this and put it on 
the wiki once I get it working.  I really like Silex so far, but I just 
need to be able to export my files somehow (preferably to local storage).

I am using the default sessions folder, and my environment variable is 
set correctly to use this folder.

After setting up the config.js file with my user info, the node server 
won't start at all.  I get the following output in the node console 
(same error whether I start in debug mode or as root or any other 
combination):

$ npm start> Silex@0.8.0 start /silex/Silex> node 
dist/server/server.js/silex/Silex/dist/server/config.js:7exports.www.USERS 
= {^TypeError: Cannot set property 'USERS' of undefinedat 
Object.<anonymous> (/silex/Silex/dist/server/config.js:7:19)at 
Module._compile (module.js:425:26)at Object.Module._extensions..js 
(module.js:432:10)at Module.load (module.js:356:32)at 
Function.Module._load (module.js:313:12)at Module.require 
(module.js:366:17)at require (module.js:385:17)at Object.<anonymous> 
(/silex/Silex/dist/server/server.js:51:13)at Module._compile 
(module.js:425:26)at Object.Module._extensions..js (module.js:432:10)npm 
ERR! Linux 3.16.0-0.bpo.4-amd64npm ERR! argv "/usr/bin/nodejs" 
"/usr/bin/npm" "start"npm ERR! node v5.1.0npm ERR! npm v3.5.1npm ERR! 
code ELIFECYCLEnpm ERR! Silex@0.8.0 start: `node 
dist/server/server.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at 
the Silex@0.8.0 start script 'node dist/server/server.js'.npm ERR! Make 
sure you have the latest version of node.js and npm installed.npm ERR! 
If you do, this is most likely a problem with the Silex package,npm ERR! 
not with npm itself.npm ERR! Tell the author that this fails on your 
system:npm ERR! node dist/server/server.jsnpm ERR! You can get 
information on how to open an issue for this project with:npm ERR! npm 
bugs Silexnpm ERR! Or if that isn't available, you can get their info 
via:npm ERR! npm owner ls Silexnpm ERR! There is likely additional 
logging output above.npm ERR! Linux 3.16.0-0.bpo.4-amd64npm ERR! argv 
"/usr/bin/nodejs" "/usr/bin/npm" "start"npm ERR! node v5.1.0npm ERR! npm 
v3.5.1npm ERR! path npm-debug.log.6299c1c177b4cea5ba2bee18a2f8a35enpm 
ERR! code EACCESnpm ERR! errno -13npm ERR! syscall opennpm ERR! Error: 
EACCES: permission denied, open 
'npm-debug.log.6299c1c177b4cea5ba2bee18a2f8a35e'npm ERR! at Error 
(native)npm ERR! { [Error: EACCES: permission denied, open 
'npm-debug.log.6299c1c177b4cea5ba2bee18a2f8a35e']npm ERR! errno: -13,npm 
ERR! code: 'EACCES',npm ERR! syscall: 'open',npm ERR! path: 
'npm-debug.log.6299c1c177b4cea5ba2bee18a2f8a35e' }npm ERR! npm ERR! 
Please try running this command again as root/Administrator.npm ERR! 
Please include the following file with any support request:npm ERR! 
/silex/Silex/npm-debug.log

The npm-debug.log file has the following contents:

0 info it worked if it ends with ok1 verbose cli [ '/usr/bin/nodejs', 
'/usr/bin/npm', 'run', 'start:debug' ]2 info using npm@3.5.13 info using 
node@v5.1.04 verbose run-script [ 'prestart:debug', 'start:debug', 
'poststart:debug' ]5 info lifecycle Silex@0.8.0~prestart:debug: 
Silex@0.8.06 silly lifecycle Silex@0.8.0~prestart:debug: no script for 
prestart:debug, continuing7 info lifecycle Silex@0.8.0~start:debug: 
Silex@0.8.08 verbose lifecycle Silex@0.8.0~start:debug: unsafe-perm in 
lifecycle true9 verbose lifecycle Silex@0.8.0~start:debug: PATH: 
/usr/lib/node_modules/npm/bin/node-gyp-bin:/silex/Silex/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin10 
verbose lifecycle Silex@0.8.0~start:debug: CWD: /silex/Silex11 silly 
lifecycle Silex@0.8.0~start:debug: Args: [ '-c', 'SILEX_DEBUG=true node 
dist/server/server.js' ]12 silly lifecycle Silex@0.8.0~start:debug: 
Returned: code: 1 signal: null13 info lifecycle Silex@0.8.0~start:debug: 
Failed to exec start:debug script14 verbose stack Error: Silex@0.8.0 
start:debug: `SILEX_DEBUG=true node dist/server/server.js`14 verbose 
stack Exit status 114 verbose stack at EventEmitter.<anonymous> 
(/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)14 verbose 
stack at emitTwo (events.js:87:13)14 verbose stack at EventEmitter.emit 
(events.js:172:7)14 verbose stack at ChildProcess.<anonymous> 
(/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)14 verbose stack at 
emitTwo (events.js:87:13)14 verbose stack at ChildProcess.emit 
(events.js:172:7)14 verbose stack at maybeClose 
(internal/child_process.js:818:16)14 verbose stack at 
Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)15 
verbose pkgid Silex@0.8.016 verbose cwd /silex/Silex17 error Linux 
3.16.0-0.bpo.4-amd6418 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" 
"start:debug"19 error node v5.1.020 error npm v3.5.121 error code 
ELIFECYCLE22 error Silex@0.8.0 start:debug: `SILEX_DEBUG=true node 
dist/server/server.js`22 error Exit status 123 error Failed at the 
Silex@0.8.0 start:debug script 'SILEX_DEBUG=true node 
dist/server/server.js'.23 error Make sure you have the latest version of 
node.js and npm installed.23 error If you do, this is most likely a 
problem with the Silex package,23 error not with npm itself.23 error 
Tell the author that this fails on your system:23 error SILEX_DEBUG=true 
node dist/server/server.js23 error You can get information on how to 
open an issue for this project with:23 error npm bugs Silex23 error Or 
if that isn't available, you can get their info via:23 error npm owner 
ls Silex23 error There is likely additional logging output above.24 
verbose exit [ 1, true ]~

If I remove the dist/server/config.js file and run in debug mode again, 
when trying to login with admin/admin I get the following output to the 
node console (very similar to what I saw previously except this time the 
auth page submition was OK which I didn't see before):

express deprecated req.param(name): Use req.params, req.body, or 
req.query instead node_modules/unifile/lib/services/www.js:52:15express 
deprecated req.param(name): Use req.params, req.body, or req.query 
instead node_modules/unifile/lib/services/www.js:52:44express deprecated 
req.param(name): Use req.params, req.body, or req.query instead 
node_modules/unifile/lib/services/www.js:53:33express deprecated 
req.param(name): Use req.params, req.body, or req.query instead 
node_modules/unifile/lib/services/www.js:53:60express deprecated 
req.param(name): Use req.params, req.body, or req.query instead 
node_modules/unifile/lib/services/www.js:57:53auth page submition OK 
adminexpress deprecated req.param(name): Use req.params, req.body, or 
req.query instead node_modules/unifile/lib/services/www.js:60:19Error: 
EACCES: permission denied, open 
'/silex/Silex/dist/sessions/I5tbvfekoCxv7VGkIZAcQuIIOQG2MZch.json'at 
Error (native)

I have tried different variants of req.param(name) like req.params(name) 
or req.params.name, and I don't get the deprecated message, but when I 
do that the login still fails with a TypeError. It doesn't look to me 
like the deprecation is the problem - the login info is still 
submitting, it's not able to start a session (also no session file 
remains after this, which is probably a good thing, right?).

I appreciate all your help.

Thanks, Joe

**Comment by lexoyo** [comment]
Ok, I see 2 problems: @singchan instructions have a bug since www is not initialized yet in the config file, I'll think about a fix

The second problem: `EACCES: permission denied, open '/silex/Silex/dist/sessions/I5tbvfekoCxv7VGkIZAcQuIIOQG2MZch.json'` means that you have not given the write access rights to nodejs on the folder '/silex/Silex/dist/sessions/' so it canot save the sessions

**Comment by hilteci** [comment]
Thanks, Alex.

I'm really loving Silex.

**Comment by hilteci** [comment]
For problem number two:  EACCES: permission denied, open '/silex/Silex/dist/sessions/I5tbvfekoCxv7VGkIZAcQuIIOQG2MZch.json'

I was running with -s or and/or sudo, but I suppose this did not extend to folder write permissions within nodejs.  I chmod'ed 777 the sessions folder, then started a session in debug mode with admin/admin, and then locked the folder back down.  It seems to work ok once the session is there even when the folder is at its original permissions, so I think this will work for now.

However, if I'm not running in debug mode so admin/admin isn't available (therefore requiring the server/config.js file defining usernames and passwords), then yes I'm still seeing problem number one with www not initialized.  I'm still very new to Silex and getting to know the code, - can you give me some starting places to start looking at where/how www can be initialized so I can try to poke around for a fix here as well?

**Comment by lexoyo** [comment]
The [debug mode adds admin/admin here](https://github.com/silexlabs/Silex/blob/master/dist/server/server.js#L82) which also activate it.

A quick workaround would be to add the same kind of init but with real login/pass pairs in [the "else" block here](https://github.com/silexlabs/Silex/blob/master/dist/server/server.js#L87)

But a real fix would be to replace the current config mechanism - the [merge of the objects exported by config.js](https://github.com/silexlabs/Silex/blob/master/dist/server/server.js#L47), by a call of an "init" function for example. This would mean exporting a function in config.js instead of objects, and Silex would call it with the object `silexConfig` as a parameter. You would need to change [server.js here](https://github.com/silexlabs/Silex/blob/master/dist/server/server.js#L47) and also [config-sample.js](https://github.com/silexlabs/Silex/blob/master/dist/server/config-sample.js) and maybe the readme and/or the new documentation effort in [Silex wiki](https://github.com/silexlabs/Silex/wiki)

For either solution, please do not hesitate to ask for pointers :)
