### ISSUE TITLE
Better publication #1

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#187]
the following feature will result in a published website with 
* 1 html page per Silex page after publication
* no more deep linking in preview
* good UX on any display (size, pixel perfect, load time, transitions)

tasks 

* [x] 1 HTML file per page so each click => page reload => no deeplinking
* [x] no deeplinks even in preview => much simpler, support anchors
* [x] progress indication, display warnings and errors
* [x] optimize speed of the publication
* [x] resize the website with CSS, according to `website width` setting, in desktop and mobile modes and in the editor

**Comment by lexoyo** [comment]
This is now live on preprod.silex.me please test!!!

**Comment by lexoyo** [comment]
Ok I'm on it

**Comment by lexoyo** [comment]
Ok, so here is my conclusion

There are old components in your template, like this container in blue:
![screenshot from 2019-01-31 16-10-23](https://user-images.githubusercontent.com/715377/52089939-84beaa00-2575-11e9-9e87-af9bd62d3225.png)

To see that it is a component, double click on it and check that there are params in the right panel

So you have 2 workarounds, the good and the quick one, which I hope work because I could not really test (I have tested but not on your website):

1- the quick fix: add this code to the "head editor"
```
$(function() {
  console.log('xxxx')
  var bodyEl = $('body');
  $.prototype.pageable = function(options) {
    console.log('yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy')
    return {
      currentPage: ''
    }
  };
  console.log('xxxx')
});
```

2- the good way to go: select all containers which are components and remove them (move their contents out of the containers beforehand)

Can you try both and let me know how it goes?

**Comment by lexoyo** [comment]
Hi did you succeed?

**Comment by Rizota** [comment]
Hi, unfortunately it didnt work. First i have tried the  option and site doesnt even load - only the menu bar.

and I have also tried the second option, deleted all of the "animation" containers and it didnt help (the menu doesnt work/scroll....)

So I have finished this site "manually" in html...
