### ISSUE TITLE
How to link text in text box to another page on same site if site is unpublished?

### ISSUE THREAD

**Issue by Jxcxb91** [silexlabs/Silex#194]
When using the text box in the silex editor I notice the link function at the top, but it only seems to have options to link external links with a web address to text in the text box, and I am still in the process of developing my site more fully so it isn't published yet. Is there any way to link text to another page on the same site if it isn't published using the Silex editor?

**Comment by lexoyo** [comment]
this is now simple with the new text editor comes a link editor
[see this doc](https://github.com/silexlabs/Silex/wiki/editor-ui#63-link-editor-1)
