### ISSUE TITLE
Creating a link fixed at the bottom of a page with a variable height?

### ISSUE THREAD

**Issue by Jxcxb91** [silexlabs/Silex#201]
Hi, I was wondering if I could get advice towards an issue that I'm having.

A certain page on my site is planned to contain a collapsible table, which compresses from 6-7 rows when fully collapsed to well over 100 when expanded fully. This carries some logistic issues that I'm not sure how to approach solving.

First, I typically use containers to extend pages past their default height if they require. However, because this page will have a variable height depending on the state of the table, I was curious as how I might be able to make the bottom of the page adjust according to the state of the table.

Important to mention is that for the site I'm creating, a link to the home page is fixed on the bottom left corner of every page. If I am to set this link in any fixed position, it will only function if the table remains fixed as well. I'm still learning CSS and HTML, and have yet to begin learning javascript (though I plan to begin very soon) so I don't know how to approach this issue. Anyone who can give me some advice will be greatly appreciated. Is this definitely possible or should I think about redesigning my concept for the page in mind?

**Comment by lexoyo** [comment]
This is now done easily with sections (the last section will always be at the bottom
