### ISSUE TITLE
How can I use animations?

### ISSUE THREAD

**Issue by dutchpigeon** [silexlabs/Silex#212]
Who can tell me step by step how I can animate elements?
I followed the instructions in this article on an existing template page I am trying out on but it does not work:
https://github.com/silexlabs/Silex/issues/87

May I ask how and where you add the CSS class in the CSS box (apollo mode)?
I tried to paste it as is, perhaps this is what I am doing wrong?

.element{
height: 360px;
width: 900px;
top: 260px;
left: 53px;
position: absolute;
"animated fadeIn"
}

Note that I am new on trying html5 out and am not that good with programming/codes ;)

Thanks

**Comment by singchan** [comment]
duplicate of 
* https://github.com/silexlabs/Silex/issues/445 
* https://github.com/silexlabs/Silex/issues/84
* https://github.com/silexlabs/Silex/issues/87
