### ISSUE TITLE
Créer un footer avec Silex ?

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#214]
Bonjour !

L'idée est de faire un footer sur une <b>nouvelle publication</b> et le mettre sur un site sans avoir à modifier le contenue de chaque pages. 

J'ai essayé de mettre ce footer sur une HTML-BOX avec une "iframe" qui va chercher l'url du footer.html : 

voici le site test : http://leofrancia.fr/websites/footer
</br>
</br>
En local, le footer ressemble à ça : 
![capture d ecran 2014-10-16 a 18 12 53](https://cloud.githubusercontent.com/assets/6841971/4665982/647239e2-554f-11e4-9b6d-38bdaa123996.png)
</br>
</br>
<b>Problèmes en local :</b> 
- il y a toujours la scroll verticale sur le footer
- il faut mettre une HTML-BOX sur chaque pages (les hauteurs varies en fonction du contenu). Ca implique que le site "s'alourdit".
- Le plus souvent le footer est en w=100% sur les sites. Comme le background est en w=100% je rajoute un container qui centre le contenu. Donc lorsque la fenêtre windows est très petite le contenu ce cache.

<b>Problèmes en ligne :</b> 
- le contenu du footer ne s'affiche pas. Le code sur HTML-BOX est celui ci : 
![capture d ecran 2014-10-16 a 18 06 15](https://cloud.githubusercontent.com/assets/6841971/4665914/b65f04ca-554e-11e4-9483-942f28488a5b.png)
on devrait voir ceci à la place du bloc blanc "Page 1" : http://leofrancia.fr/websites/footer/edit.footer/

</br>
</br>
</br>
<b>question : </b>
- peut-etre qu'il y aurai moyen de concevoir, comme ici, un footer en silex en récupérant la publication nommé " footer.html " et qu'il se mette <b>automatiquement</b> en bas de page ? 
- De choisir un emplacement spécifique de ce style : 
![capture d ecran 2014-10-16 a 17 47 48](https://cloud.githubusercontent.com/assets/6841971/4665527/d5d7c47a-554b-11e4-8bee-3c5b3fa06c59.png)

Je ne suis pas expert sur la conception de footer .. mais je cherche des solutions pour en faire un de ce style en silex :)

**Comment by lexoyo** [comment]
Est-ce que finalement il ne faudrait pas juste un nouveau type de container, les  "background containers" qui ne serait pas drag/dropable mais positionné relativement comme le container principal... 

Exemple : 

* j'insère un bg container, il se met sous le container principal
* je marque le container principal comme étant sur la page1 et le nouveau bg container sur la page 2
* j'insère encore un bg container, que je met tout en bas, et qui est sur toutes les pages, un footer quoi

Le résultat c'est que sur la page 1 et 2, le bg container qui est au dessus varie de hauteur, mais le footer est toujours la, et le site change de hauteur

**Comment by Stuff31** [comment]
Je pense que se sera bon, pourra t-on le sizé a 100%? :)
Ca peut être bien qu'il y soit de base?

**Comment by Stuff31** [comment]
<i>C'est pas mal de mettre un bg pour chaque nouvelle page</i>

**Comment by lexoyo** [comment]
> Je pense que se sera bon, pourra t-on le sizé a 100%? :)
> Ca peut être bien qu'il y soit de base?

Pour qu'on puisse avoir du contenu centré il faudrait peut être que chaque bg container ait un mode centré ou 100%
Ou bien qu'un bg container soit à 100% et contienne un autre container centré?

> C'est pas mal de mettre un bg pour chaque nouvelle page

Hmm yes pourquoi pas :)
Donc création de site => un header et un footer?

**Comment by Stuff31** [comment]
<blockquote>Ou bien qu'un bg container soit à 100% et contienne un autre container centré?</blockquote>
C'est la bonne solution mais peut être confuse pour certain (les deux containers)? 
Une case à cocher 100% sur les propriétés sans se soucier qu'il y ait deux containers pourrai contrer ça. 

En gros des propriétés spécifique footer/header (Ce sont normalement les mêmes propriétés sauf qu'il y en a un au top et l'autre au bottom)

<blockquote>Donc création de site => un header et un footer</blockquote>
Oui :)
