### ISSUE TITLE
Links with target=_blank

### ISSUE THREAD

**Issue by digitaleffects** [silexlabs/Silex#221]
how can I create a hyperlink to open in a new window?  I cannot enter target=_blank anywhere...

**Comment by fedegod** [comment]
Oh please, someone add this function to the silex, i don't know how to code anything, i need that link on a .jpg file opens a page in the same window (_self). THankS, congratulations for this great web-design software.

**Comment by lexoyo** [comment]
Thank you @fedegod for your feedback
I will add it to the roadmap since it is important to you
For now you can [test the next version of Silex](https://github.com/silexlabs/Silex/issues/264), it already has improvements such as a favicon, search engine params etc for non programmers

**Comment by lexoyo** [comment]
this is done for text, but still needs to be the same for links on elements
[see this doc](https://github.com/silexlabs/Silex/wiki/editor-ui#63-link-editor-1)
