### ISSUE TITLE
better UX

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#227]
In order to ameliorate the ergonomy:
- move elements with the arrows of the keyboard
- create guidelines
- possibility to align elements together
- "open recent files" option in file menu
- use "shift" key button while moving an object to maintain "x" or "y" value (like in photoshop)
- possibility to "paste in place" an object

**Comment by lexoyo** [comment]
> move elements with the arrows of the keyboard
> use "shift" key button while moving an object to maintain "x" or "y" value (like in photoshop)

These ones are implemented and you can [test it here](http://preprod.silex.me)

**Comment by ceubri** [comment]
cool ;)
