### ISSUE TITLE
Silex publication process

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#238]
[This document is now in the wiki here](https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website)

**Comment by sharmivssharmi** [comment]
how do I publish to github pages?

**Comment by JbIPS** [comment]
Same as the other. But you need to specify your path as username.github.io/master/root_of_site. 
You can find more information on [GitHub Pages](https://pages.github.com/)

**Comment by sharmivssharmi** [comment]
Hi,
I am new to github too, what do you mean by same as the other. In silex editor, I have two publish settings, one with dropbox, and then ftp. Please elaborate what should i give to publish or open a file from github?

**Comment by JbIPS** [comment]
First thing first, which version of Silex are you using? silex.me or preprod.silex.me?
GitHub publication is only available on preprod

**Comment by ieabbas** [comment]
What is indicated by an "Unknown Service Undefined" error?

**Comment by lexoyo** [comment]
Hello
Did you choose a folder in the settings > publication settings?

**Comment by ieabbas** [comment]
Absolutely. I have designated a directory for the website to be published, and followed every step of the help process for publishing. I think it has something to do with the images I'm using, but I'm not sure really.

**Comment by lexoyo** [comment]
what is the publication path?

**Comment by ieabbas** [comment]
The path was directly in my installed Dropbox. Basically
"D:\Dropbox\WebsiteRootDirectory

**Comment by singchan** [comment]
ok this is why
you typed the path in the text field right?
you are supposed to click on the "browse" button to the right of the text
field, and then choose a folder by clicking on the white arrow to the right
of the folder name

**Comment by dingenskirchen** [comment]
So if I want to save or publish anything I have to enter my Dropbox/WebDAV/FTP/GitHub username and password? It's not possible to save/publish to a local drive?
Seems more like a new and somewhat creative way of phishing than a website editor/designer.

**Comment by lexoyo** [comment]
Hi 

This is OAuth in most cases, the host do not even have your password. And when you authorize Silex to access your data, it opens a popup and not an iframe so that you can check that the URL is the one of the service, not the host of Silex instance

The reason why we do not save to local drive is that it would force you to install a software on your computer (which is even more risky if someone put a key logger in the project's executables (just joking))

You concerns are legitimate, so you are encouraged to look at the source code, and host your own instance of Silex. This is the only true way to trust only yourself (which is a good thing)

**Comment by JbIPS** [comment]
I'd like to add the project managing the remote storages is [unifile](https://github.com/silexlabs/unifile) if you want to look at it :smile: You'll see the data aren't stored anywhere! Have fun using Silex

**Comment by jennparker** [comment]
Documentation is complete on wiki:
https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website

**Comment by lexoyo** [comment]
Nice!

[I changed this
](https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website/_compare/71c1ba74765652c4e8315c9d929930a34e62356f...35e08806730bede6b0225076c88e7537c0e09221)

My remarks
* is this page linked to somewhere?
* for the publication, there are these docs available: [a video in english](https://youtu.be/LZl_owOFQLQ?t=20m19s), [a video in french](https://www.youtube.com/watch?v=eg_4QnQR4kw), [another video in french](https://www.youtube.com/watch?v=j500skZbcDU), [one more video in french](https://www.youtube.com/watch?v=tJVIfFhZN4g)
* the screenshots are obsolete we need to change it
* the publication is also related to this page: [Contributing-changes-to-Silex-website](https://github.com/silexlabs/Silex/wiki/Contributing-changes-to-Silex-website)

**Comment by jennparker** [comment]
Awesome - thanks for catching that and making those changes! 

- I  just linked it in the FAQ, but ultimately, I think we definitely should make the main page more of an index where we can group and order all of these pages. TODO

- Those videos will be awesome additions TODO

- Update the screenshots TODO

- Ahh, sorry, that is my misunderstanding. I thought that [Contributing-changes-to-Silex-website](https://github.com/silexlabs/Silex/wiki/Contributing-changes-to-Silex-website) was for individuals wishing to contribute changes to the main Silex website or editor, but it sounds like this article is actually designed for for someone wishing to edit their own website that they created using Silex. Is this correct?

**Comment by jennparker** [comment]
These TODO updates are now being tracked [here](https://github.com/silexlabs/Silex/issues/608)

**Comment by blueskythinker** [comment]
Is it possible to build a site externally in html, then bring it in and publish through you?

**Comment by lexoyo** [comment]
Not for the moment no

**Comment by lexoyo** [comment]
[This document is now in the wiki here](https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website)

**Comment by dvoraksensei** [comment]
Greetings, I am trying to save my silex site to ftp. I can get logged into my ftp folder and see sub folders, but when I try to save into a sub folder I get a 500 error "access denied". I know I have access because it works in filezilla. Any ideas?
