### ISSUE TITLE
menu properties

### ISSUE THREAD

**Issue by Hans3901** [silexlabs/Silex#246]
Hello, 
the menu properties: position and size arrows don't work. :-(
Question how to make a dropdown menu? 
Please reply

**Comment by lexoyo** [comment]
Hi Hans

> the menu properties: position and size arrows don't work. :-(

I am not sure what you mean by "position and size arrows"

> Question how to make a dropdown menu? 

For this you will need CSS, but it is quite easy. I'll make a widget for you ok?

**Comment by Hans3901** [comment]
Hi Alex,

Maybe you did not recieve my reply on Github and thanks in advance if you can make a widget :-) 

Kind regards
Hans Visser  

----- Oorspronkelijk bericht -----
Van: "Alex Hoyau" <notifications@github.com>
Aan: "silexlabs/Silex" <Silex@noreply.github.com>
Cc: "Hans3901" <hem.visser@online.nl>
Verzonden: Dinsdag 10 februari 2015 16:26:01
Onderwerp: Re: [Silex] menu properties (#246)



Hi Hans 



the menu properties: position and size arrows don't work. :-( 

I am not sure what you mean by "position and size arrows" 



Question how to make a dropdown menu? 

For this you will need CSS, but it is quite easy. I'll make a widget for you ok?

**Comment by lexoyo** [comment]
Here you are:
https://github.com/silexlabs/Silex/issues/247

Test it and tell me what you think?

**Comment by Hans3901** [comment]
Hi Alex,
Superrr, great tutorial!  i'm looking now to get the text 'home' and 'contact' in the same line as in the dropdown menu and to hoover the button color :-)
Thanks
