### ISSUE TITLE
One page arranges stuff different than all others

### ISSUE THREAD

**Issue by blauer** [silexlabs/Silex#252]
Hi!
I made a site based on one of the templates. Everything worked fine, but as i was adding stuff to it, one page suddenly behaved strangely. It's longer than the others, menu links do not work, some stuff shows up twice.. 
Maybe one can have a look on it, i don't know what to do.

**Comment by singchan** [comment]
Please share it to me in dropbox
a.hoyau [at] im-paris [dot] fr

**Comment by blauer** [comment]
Hi,
thanks for the quick response. 
I shared the folder. Its about the "Fraesen" page. When you view the page, the Menu-Links in the top do not work, once you switched to this page.

I deleted the stuff it doubled, but before, the whole menu bar was there a second time in the very bottom of the page. When you viewed the page you just saw the top one - with no working links. 

I hope you can figure out whats happening. 
A general question - where do I set the page size in Silex?
Greetings

**Comment by lexoyo** [comment]
> the Menu-Links in the top do not work

I do not see what you mean
I go to the page (in silex editor) and everything looks good :-/

> A general question - where do I set the page size in Silex?

the size of the website is the size of the "main container" (the one which
was there from the beginning)
if you need a variable height depending on the page there are several
tricks you can do, is this what you need?


On Mon, Mar 9, 2015 at 7:37 PM, blauer <notifications@github.com> wrote:

> Hi,
> thanks for the quick response.
> I shared the folder. Its about the "Fraesen" page. When you view the page,
> the Menu-Links in the top do not work, once you switched to this page.
>
> I deleted the stuff it doubled, but before, the whole menu bar was there a
> second time in the very bottom of the page. When you viewed the page you
> just saw the top one - with no working links.
>
> I hope you can figure out whats happening.
> A general question - where do I set the page size in Silex?
> Greetings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silexlabs/Silex/issues/252#issuecomment-77915204>.
>



-- 
If you want to keep in touch with Silex Labs subscribe here
<http://eepurl.com/MCCDP>

**Comment by blauer** [comment]
I meant, when you view the page via "Preview", then the links do not work. But i already found a container that wasn't supposed to be there, I deleted it now everythings super-fine again. 
I find it sometimes hard to see where different Containers are, when they are the same color.
Especially when you insert a new one or copy/paste something. But thats my personal problem i guess :smile: 

Yes thats what I am talking about. Whats the easiest way to achieve different heights on different pages?

Thats a great support you guys have here, :+1: :+1:

Greetings, 
David

**Comment by lexoyo** [comment]
To set a different background size, there is this trick. It is temporary because it will be made easier in the next version of Silex

Put this in the script editor
```javascript
$(window).load(function() {
    // list all pages from the head section and open the 1st one by default
    var firstPageName = null;
    var currentPageName = null;
    var pages = $('a[data-silex-type="page"]');
    if (pages && pages.length>0){
        var firstPage = pages[0];
        firstPageName = firstPage.getAttribute('id');
    }
    // the current page name as css class on the body
    function applyCssPageName() {
        if(currentPageName) {
            // remove previous page
            $('body').removeClass(currentPageName);
        }
        var newPageName = location.hash.substr(location.hash.indexOf('#!') + 2);
        if (!newPageName) newPageName = firstPageName;
        console.log(newPageName);
        $('body').addClass(newPageName);
        currentPageName = newPageName;
    }
    $( window ).bind( 'hashchange', function() {
        applyCssPageName();
    });
    applyCssPageName();
});
```

And this in the CSS editor - replace `page-X` and `page-Y` by page names (this is what appears in the URL when you click on the links, do not forget the `.` before the page names), and `50px` by the size you want.
```css
.page-X .background {
    height: 50px !important;
}
.page-Y .background {
    height: 50px !important;
}
```

It will work only outside of the editor (preview)

**Comment by lexoyo** [comment]
did it work?

**Comment by blauer** [comment]
Sorry, yes works well, thanks a lot!
When will the new silex come out?

**Comment by lexoyo** [comment]
> When will the new silex come out?

My life as a freelancer will tell ;)

**Comment by blauer** [comment]
Haha :D Good answer.
