### ISSUE TITLE
Border Colour, no picker

### ISSUE THREAD

**Issue by internetimagery** [silexlabs/Silex#254]
Something that is really minor, but would add to the polish of this amazing work. 
Clicking the colour picker box on the "border" section doesn't pop up with a picker (yet?). Instead just asking for the hash value of the colour. Would be nice to have a standard colour picker that can pop up on all colour fields (and also in the css editor, because why not?)

**Comment by lexoyo** [comment]
Sure it would be nice too
But my priority is to finish the "mobile version" mode in Silex editor

**Comment by internetimagery** [comment]
Of course. :)
