### ISSUE TITLE
3 pages CV template (free)

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#258]
• [Download](http://www.templamatic.com/templates/3490)
• [Preview](http://www.templamatic.com/templates/3490/preview)

Here is a [3 pages CV template to advertise your skills](http://www.templamatic.com/templates/3490/preview). It is made with [Silex](http://www.silex.me) and it can be hosted anywhere.

[![cv](https://cloud.githubusercontent.com/assets/715377/6884206/506db8e2-d5e5-11e4-8d67-360016253854.jpg)](http://www.templamatic.com/templates/3490/preview)

To make your own website based on this template, [download the archive here](http://www.templamatic.com/templates/3490), unzip and open the file editable.html with [Silex editor](http://editor.silex.me/) (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by RowRowBoatBoat** [comment]
template non-existant.

**Comment by lexoyo** [comment]
ok, this is a good way to do it :)
I think templamatic.com is now down permanently?

**Comment by RowRowBoatBoat** [comment]
I think so, would like to see this theme get updated; it's broken when used with the editor.

**Comment by RowRowBoatBoat** [comment]
[template_3490.zip](https://github.com/silexlabs/Silex/files/1161878/template_3490.zip)

Here's the files if you want them. Would like to use it honestly.

**Comment by lexoyo** [comment]
I believe it was removed from the official templates because it was a bit complex... The 1st silex site of @ceubri if I remember correctly

**Comment by RowRowBoatBoat** [comment]
Ahhh, I can see that. Just been looking for something along the same lines.

**Comment by lexoyo** [comment]
@antosilex had a bunch of CV too

**Comment by RowRowBoatBoat** [comment]
I'll just edit the source to make it work, still would be cool to see more templates like this.
