### ISSUE TITLE
Awesome "Hep Café!" Template

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#260]
• [Download](http://www.templamatic.com/templates/3326)
• [Preview](http://www.templamatic.com/templates/3326/preview)

Here is a [single page "long scrolling" template, for a restaurant or a food related businesses](http://www.templamatic.com/templates/3326/preview). It is made with [Silex](http://www.silex.me), and can be hosted anywhere.

[![cafe](https://cloud.githubusercontent.com/assets/715377/6884230/4ffd9f7a-d5e6-11e4-9183-8d6c5b7a96b7.jpg)](http://www.templamatic.com/templates/3326/preview)

To make your own website based on this template, [download the archive here](http://www.templamatic.com/templates/3326), unzip and open the file editable.html with [Silex editor](http://editor.silex.me/) (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by jaylamhill** [comment]
It's great.

**Comment by slydog75** [comment]
Just downloaded.. Editable.html does not exist.  SHould I use the HEP.html in the TEMPLATE-HEP file or the index.html file in the www directory (which doesn't want to open in Silex)?

**Comment by Stuff31** [comment]
Hello slydog75 ,
An error on my part in the Read Me is HEP.html need open in Silex to change the template .

**Comment by slydog75** [comment]
Thanks Stuff

**Comment by slydog75** [comment]
Ok, another issue.  When I open HEP.html in Silex, it says it that had to upgrade it to the new Silex version. Once it does that, the menus don't work anymore.  How can I fix this?

**Comment by Stuff31** [comment]
Strange ... I is not no problem from my side .
Give me more details about this problem.

**Comment by slydog75** [comment]
Ok, I uploaded the modified HEP.HTML file.
https://drive.google.com/file/d/0B4_-i-LppzHnTVNOT1ZrTUd2WDQ/view?usp=sharing
All I've done to this file is open it in Silex 'upgraded' it then i saved it.  I'm using Google chrome to test.    Let me know if you need anything else.

Thanks for the help.

**Comment by Stuff31** [comment]
Mmm, okay, the menu works. I think you do not happen to change the menu. To do two things:

1- To change the menu text: Double click on the text button
2- To change that will position the scroll page 2: Silex> View> Scripts JS editor. Then change the value of btn_02

<i>For information "btn_02" is the button labeled "Page 2" on the template. To change the name "btn_02" we must set this mode to Apollo Silex.</i>

**Comment by slydog75** [comment]
So I purposely  uploaded a file that I hadn't changed anything  on yet.  All I did was allow silex to modify the file.  Are you saying the file I linked above actually works correctly for you?

**Comment by slydog75** [comment]
I did a side by side comparison of the Silex 2.0 file (original) vs the Silex 2.2.4 file and it adds a bunch of Silex ID codes and stuff.  Not sure if that's what's causnig the issue yet or not.

**Comment by lexoyo** [comment]
Hi may this is a backward compatibility issue, I will check this out today

**Comment by slydog75** [comment]
Thanks Lexoyo.  It's a great layout!

**Comment by lexoyo** [comment]
hello
could one of you share the template with me on dropbox (a.hoyau at im-paris dot fr)
so that I can fix it?

**Comment by lexoyo** [comment]
Also @slydog75 can you try with this version of Silex, I did many bug fixes on it
http://preprod.silex.me/

**Comment by Stuff31** [comment]
Nice, thank's @lexoyo

**Comment by Stuff31** [comment]
@lexoyo to solve the problem , I updated the sources templatmatic .
@slydog75, tell me if this works.

**Comment by slydog75** [comment]
So far so good guys, thanks.  I'll let you know if I run into any other issues.

**Comment by slydog75** [comment]
OK, more problems guys.  When I use the "publish" function in Silex it completely messes up the website.  Take a look:  http://100.34.88.42/

**Comment by lexoyo** [comment]
I can not see the website, it says "forbidden"

**Comment by lexoyo** [comment]
@slydog75 all your scripts contain corrupted data... 
Also I tried to publish and it worked as expected
Can you try again with editor.silex.me (not preprod) as I made a new release yesterday (see [this tweet](https://twitter.com/lexoyo/status/634140385741250560))

**Comment by lexoyo** [comment]
Templamatic is definitely down, do you still have this website somewhere @Stuff31 ?

**Comment by lexoyo** [comment]
@Stuff31 since templamatic is down, I'll have to close this issue
Do you have this site somewhere?
