### ISSUE TITLE
Can't open files from subfolder

### ISSUE THREAD

**Issue by mrqproductions** [silexlabs/Silex#263]
Hi. 
I am trying to open files from a subfolder on either my dropbox or ftp site.  The files were published to this path but won't open from them.  

When I choose to open a file I can browse to the subfolder and select the file.  However the file doesn't open.  The only thing that happens is the spinning timer symbol that just keeps turning.  

Files will open when they are at the root of the dropbox or ftp but not from a subfolder, which is what I prefer. 

Thank you in advance for any assistance with this. 

Cheers,
Q

**Comment by lexoyo** [comment]
Hi Q!

When you say "The files were published to this path but won't open from them." you mean that you used the "file menu > publish"? Or just saved them there?

Once a website is published it generates an index.html file, regroup the assets in `assets` and separates the javascript and CSS from the main html page. This is good to put your website online, but the generated `index.html` cannot be opened in Silex.

**Comment by mrqproductions** [comment]
Hi Lexoyo
Thank you for responding so quickly.   Now I think I understand what's happening.  It would appear that I thought the publish location was also where I can retrieve the files to be edited.  

Am I correct, that one would work with files and assets in a sort of "working" folder and then the publish process organizes everything into their respective folders (eg assests, css, javascript) at the publish location?

Thank you for clarifying this for me. 

Is there any documentation that explains best or common practices when working with Silex? 

Cheers,
Q

**Comment by lexoyo** [comment]
Ah ok
You understand well

> Am I correct, that one would work with files and assets in a sort of "working" folder and then the publish process organizes everything into their respective folders (eg assests, css, javascript) at the publish location?

exactly

> Is there any documentation that explains best or common practices when working with Silex?

These are some "pages" which are [issues here with label "doc"](https://github.com/silexlabs/Silex/labels/doc) and [other people questions here](https://github.com/silexlabs/Silex/labels/question)

And there are videos about Silex in french on youtube

**Comment by mrqproductions** [comment]
I found the videos.  Between my limited french and the fact that the interface is in english I was able to garner a lot of information from them.  

The "doc" items look to be a great help as well.  

Thank you again for your help.   I really appreciate it. 

Cheers,
Q

**Comment by lexoyo** [comment]
:pray:
