### ISSUE TITLE
A new Silex website about horses

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#268]
[This beautiful website is about a riding stable near Paris, France](http://clairiere-epona.com/). It was designed and crafted by @antosilex who is not a web developer but he learned how to use Silex during [Silex Labs](http://www.silexlabs.org) workshops.

[![Clairiaire Epona](https://cloud.githubusercontent.com/assets/715377/10267646/28c1e33a-6a9c-11e5-8c14-863897e9e04d.png)](http://clairiere-epona.com/)

**Comment by antosilex** [comment]
And who is not a désigner either!!

Thanks even so ;)

**Comment by singchan** [comment]
Le site du petit poney poilu commence à ressembler à quelque chose je te
l'accorde
Ca se voit que tu y as mis de l'amour et ca m'inquiète un peu quant à tes
tendances
