### ISSUE TITLE
Leo Francia, french talented web designer, showcase website

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#269]
[This website advertises the services proposed by Leo](http://www.leofrancia.fr/) (@Stuff31), a veteran of Silex community.

Feel free to let him know you need some help with Silex on a commercial project, he will be there as a back you up.

[![screen shot 2015-04-27 at 12 19 39 am](https://cloud.githubusercontent.com/assets/715377/7339560/2ed2d3bc-ec73-11e4-9a0c-307dc507c3d9.png)](http://www.leofrancia.fr/)

**Comment by singchan** [comment]
@Stuff31 is the site down?

**Comment by lexoyo** [comment]
The website seems down? Feel free to reopen the issue if it comes back up
