### ISSUE TITLE
Films en Form, french film producers with a great website

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#270]
[This website is one more website by Leo](http://www.filmenforme.com/) (@Stuff31), for a company which make really beautiful movies, short films and documentaries.

It makes use of the [video background widget](https://github.com/silexlabs/Silex/issues/204), and several other [Silex widgets](https://github.com/silexlabs/Silex/labels/widget). Ask Leo here for advice, take advantage of the community. And once your done, you can [give back 5 minutes of your time](https://github.com/silexlabs/Silex/blob/master/docs/contribute.md).

[![screen shot 2015-04-27 at 12 25 36 am](https://cloud.githubusercontent.com/assets/715377/7339580/5b5b25d2-ec74-11e4-9595-0961e1f8ee46.png)](http://www.filmenforme.com/)

**Comment by leathers93** [comment]
Good morning! I love the design and set up of your website. I was wondering how you were able to get the Film en forme logo to show at the top. I try to add a text box with my logo, send to front, and preview but does not work. I was able to get the youtube video to run once in preview though, just nothing else shows

**Comment by Stuff31** [comment]
Hello, thank you!
Strange because I did not do anything special ... The logo + text are the background , and the video is behind the background . To put behind the background , drag the video out of the background .
Otherwise can be added to the CSS "z -index: 10; " or more to see ?

**Comment by lexoyo** [comment]
Unfortunately this beautiful website seems down now
