### ISSUE TITLE
code/website gets confused

### ISSUE THREAD

**Issue by Photocreator** [silexlabs/Silex#273]
Hallo, I encounter the following problem while using Silex html5 editor: It often happens that things/the layout I created earlier, disappears or changes due to changes something in my website design. Without any reason I can think of! For example, I try to create a slide show in my website. To do this, I follow the procedure: I create a folder "js" (I do not need to create a folder "css" since I created this earlier on in order to make some pictures I use in my layout animate) Already the creation of this folder, makes all my animations disappear! No animation happening anymore! All at once! So I have stopped trying to ceate a slideshow for the moment; I just leave it for now 'cause it makes things go wrong!

**Comment by lexoyo** [comment]
Hi @Photocreator 
Thank you for your feedback it is good to know how hard it is for users
Can you share your website folder in dropbox with me? My email on dropbox is `a.hoyau [at] im-paris [dot] fr`
I will look at what is wrong with the slideshow

**Comment by singchan** [comment]
Is this problem solved? Should I close the issue?

**Comment by Photocreator** [comment]
hallo, no, the problem is not solved. But this is getting to difficult for me right now. I am not a programmer or something like that; just an ordinary user, knowing a bit more than the average user, or so I thought at least... I have to wait for a while, just hoping things will get better in the future if everything will work more stable. Meanwhile, I just cannot get it (the website that is) to work and everything is getting confused all the time, leaving me frustrated and not knowing anymore what to do or where to begin. I would still like to design a website for this friend of mine,  but this is getting way over my head! So, no, the problem is not solved, but I cannot help in the matter. Other, more knowledgeable people, have to look into this matter I am afraid; I am just an ordinary guy, wanting to create a website; that's all!

**Comment by lexoyo** [comment]
Hi @Photocreator 
I can help you if you share your website with me on dropbox (`a.hoyau [at] im-paris [dot] fr`)
Also there has been a major release a few days ago, with bugfixes, so maybe you can try again...

**Comment by Photocreator** [comment]
I will try again probably; it's been a while since I last worked on the project, so I will have to "get into the stuff" again anyway.To me it was getting to confusing at the time; maybe things will go more smoothly now.
Regards, Arnoud                                                                                        
 


     On Monday, July 13, 2015 5:24 PM, Alex Hoyau <notifications@github.com> wrote:
   

 Hi @Photocreator 
I can help you if you share your website with me on dropbox (a.hoyau [at] im-paris [dot] fr)
Also there has been a major release a few days ago, with bugfixes, so maybe you can try again...—
