### ISSUE TITLE
Pop-up silex

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#275]
Bonjour,

Je cherche créer une pop-up lorsqu'on clique sur un lien youtube, dans le genre du Widget Flickr.
Est-ce possible?

Pour le moment le lien du site est celui-ci (en construction) : 
http://leofrancia.fr/websites/tristanfrancia/#!page-fiction

Ensuite ce sera celui-là : 
http://tristanfrancia.com/

**Comment by lexoyo** [comment]
Alors moi ce que je ferais c'est une page avec dedans une HTML box et le code embed youtube dedans... Ca répondrait à ton besoin? Tu voudrais un truc automatique avec des fleches c'est pluttot ca?

**Comment by lexoyo** [comment]
Ou alors tu fais comme dans le widget flickr, tu utilises fancy box :+1: 
Tu poses plusieurs images avec des liens vers tes vidéos youtube genre `http://www.youtube.com/embed/L9szn1QQfas?autoplay=1`
Tu inclues le plugin lightbox
```
// lightbox
document.write('<script type="text/javascript" src="js/jquery.fancybox.pack.js"></scr'+'ipt>');
document.write('<link rel="stylesheet" href="css/jquery.fancybox.css"></link>');
```
Sur les images tu mets la classe css `macssclass` (ou un autre nom) et tu ajoutes le code js
```
$(document).ready(function() {
	$(".macssclass").fancybox({
		maxWidth	: 800,
		maxHeight	: 600,
		fitToView	: false,
		width		: '70%',
		height		: '70%',
		autoSize	: false,
		closeClick	: false,
		openEffect	: 'none',
		closeEffect	: 'none'
	});
});
``` 
J'ai pas testé, juste repris un exemple de leur site, dis moi si ca fonctionne. Et n'hsites pas à jouer avec les options

**Comment by Stuff31** [comment]
Oui c'est ce que je recherche ;)
J'ai fait tout ça et la pop-up fonction mais ça ne m'affiche pas le lien, ça affiche la meme chose que ce que je clique... je ne comprend pas car ça devrai marcher..
resultat : http://leofrancia.fr/websites/tristanfrancia/#!page-fiction

Les liens des tuiles est une html-box qui ce présente comme ça (ici deux tuiles): 
```html
<li>
<a class="tile" href="https://www.youtube.com/watch?v=FcuvEVSocrg&amp;index=1&amp;list=PLD2glZsWRs1jghlCe2oThZulleEPlno3b" target="_blank">
<img src="assets/Recto_verso.jpg" alt="">
<h1>recto verso</h1>
<h2>2014 | 7'32 - Drame</h2>
<p>Production: Le Gros Indien Production, Film en Forme<br><br></p>
<h3><br>✓ 1 Selection officielle</h3>
</a>
</li>

<li>
<a class="tile" href="https://www.youtube.com/watch?v=NuedLUfyYoA&amp;list=PLD2glZsWRs1jghlCe2oThZulleEPlno3b&amp;index=2" target="_blank">
<img src="assets/Menthe_a_leau.jpg" alt="">
<h1>Menthe à l'eau, film en 3D sans lunettes</h1>
<h2>2012 | 2'14 - Comédie</h2>
<p>Production : Film en Forme<br><br></p>
<h3><br>✓ 1 Selection officielle &nbsp;&nbsp;&nbsp; ☀ Diffusion TV</h3>
</a>
</li>
```

Je met la class <code>macssclass</code> sur cette html-box

**Comment by singchan** [comment]
C'est parce que tu as mis un lien vers la page YouTube, alors qu'il faut le
lien vers la vidéo (code embed dans partager)

**Comment by lexoyo** [comment]
C'est parce que tu as mis un lien vers la page YouTube, alors qu'il faut le
lien vers la vidéo (code embed dans partager)

**Comment by Stuff31** [comment]
Ok merci Alex, j'ai testé plusieurs truc mais rien ne change. Si je comprend bien c'est comme ça que tu me dis de faire : 
```<a class="tile" href="https://www.youtube.com/embed/L9szn1QQfas?autoplay=1>```

Je suis sur le bon chemin ou c'est une autre methode qu'il faut utiliser?

**Comment by lexoyo** [comment]
Oui normalement c'est bien ça...
Est-ce qu'avec ce lien ça marche ?
http://www.youtube.com/embed/L9szn1QQfas?autoplay=1

**Comment by Stuff31** [comment]
Malheureusement ça ne marche pas...

**Comment by lexoyo** [comment]
Peux tu me partager le site stp ? a.hoyau at im-paris dot fr

**Comment by lexoyo** [comment]
Ok I got it working, I have added `various fancybox.iframe` to the class of the link (beside `title`)
(merde j'ai écris en anglais désolé j'ai bugué)
Et enlève `various` des autres éléments (ou remplace par un autre nom de classe)

**Comment by Stuff31** [comment]
Waou merci! Je suis surpris car les embeds se charge que lorsqu'on clique et pas au chargement du site :) l'ensemble du site se navigue rapidement.
:+1:

**Comment by Stuff31** [comment]
Je suis entrain de faire un petit template (free) pour mettre en place son 'iframe vidéo liste'.
C'est intéressant je trouve, non? :)

**Comment by lexoyo** [comment]
Carrément :+1: 
J'ai vu que ta liste est faite en HTML dans une html-box.. Pour les débutants ca serait peut etre mieux avec un container et des éléments positionnés à la main non? Il y a une raison pour laquelle tu as préféré la html-box?

**Comment by Stuff31** [comment]
Oui en effet il y a plusieurs raison : 
• Avoir un 'design' déjà conçu et modifiable dans l'ensemble
• Pouvoir ajouter des 'tuiles' sans avoir a modifier la hauteur du container pour quelles soit visible (heigth:auto)
• Pouvoir ajouter une tuile au dessus des autres sans avoir a changer la position des autres
• Pouvoir (si on le souhaite) avoir un largeur auto si on est sur un site en 100% de largeur (tuiles dynamique). Il peux y avoir 2 tuiles comme 5 selon la largeur de l'écran.

Le design n'est pas fou mais je pense que c'est pas mal comme ça (width 100% et centré + liste width&height:auto) : 
http://leofrancia.fr/websites/movie-ad/#!page-a-propos


Mais pour un débutant c'est vrai que ce n'est pas facile, j'ai essayé avec une image et un lien mais je n'y arrive pas ...

**Comment by singchan** [comment]
OK je comprends..  Je pense que je peux t'aider à faire fonctionner le truc
avec image et lien si tu veux ?

Et avec quelques classes CSS on pourrait même faire des containers
positionnés les uns derrière les autres et que tu déplaces avec le up/down
(en preprod pour l'instant). A voir si c'est mieux pour un template, je ne
sais pas mais c'est assez simple à faire

**Comment by Stuff31** [comment]
Oui :) si c'est faisable en Silex c'est le top et du coups plus accessible pour les débutants.

Je suis partant !

**Comment by lexoyo** [comment]
I will close this issue, feel free to re-open it if you are still around
