### ISSUE TITLE
problems creating second page in website

### ISSUE THREAD

**Issue by Photocreator** [silexlabs/Silex#276]
Hallo, I encounter the following problem while using Silex html5 online editor: I cannot go on with my website project, since on the second page (I am using the Light-grey template) items from the first/index/home page also appear. These items cannot be removed, since removing also affects the layout of the first page directly. The pages seem to be linked somehow in a wrong manner. I do not know how to solve this or how to move forward from here; I don't think I am doing anything completely wrong. As soon as I go to the next/second page to work further on my project, items from the first page already, partly, exist and cannot be removed without directly influencing the layout of the first page. (not all items are also on the second page, but some are and these are very persistent)

**Comment by lexoyo** [comment]
Welcome back @Photocreator :)
What you need is to change the visibility of the elements
Look at the property `visible on`. Note that if nothing is checked, the element is visible on every pages

![screen shot 2015-05-21 at 14 48 42](https://cloud.githubusercontent.com/assets/715377/7748823/85113e7c-ffc8-11e4-9b3e-3bc5ba0f5762.png)
