### ISSUE TITLE
Improve the way templates ca be imported in Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#283]
Here is an idea to ease the use of [these Silex templates](http://templates.silex.me): when you click on file > new, silex should display the list of templates, then you can start from a template instead of a blank page

What do you think? 

cc @singchan @samashley @AndreaMonzini @Hans3901 @theedoms @Stuff31

**Comment by lexoyo** [comment]
Interesting comment from @remirivas
https://twitter.com/remirivas/status/649147837398257664

**Comment by samashley** [comment]
Seems like a good idea :-)

**Comment by lexoyo** [comment]
example of how wix does it
https://www.wix.com/support/html5/getting-started/templates/kb/selecting-a-template-searching-for-a-template

**Comment by lexoyo** [comment]
Hello

I have started to work on this issue

The 1st step was to re-organize the "silex-templates" repo which was mixed with the website templates.silex.me

Please note that from now on, when you download silex templates from templates.silex.me you have only the templates and they are at the repository root

**Comment by lexoyo** [comment]
I continue to work on this, and I think that the idea is to display a dialog when silex starts, and with several lists of templates:

* blank layouts (blank page, header/footer/body, ...)
* community templates (the ones from http://templates.silex.me/)
* designers templates (the ones from [@Stuff31](http://www.templamatic.com/stuff), [ceubri](http://www.templamatic.com/ceubri)...)

These lists should have preview images and buttons (info, select this one and preview the template)

And the user should also be able to open a website he/she has started previously

I'm also thinking of a list of "recent websites" (this would be text only, no image)

Inputs welcome before I start coding!

**Comment by lexoyo** [comment]
I have been working hard on this matter, and @budislav helped me with the design:
http://preprod.silex.me/

What remains
* improve the templates (maybe remove some of them)
* add a template section for resumes by @antosilex 
* add a section for @ceubri and @Stuff31 

Any comment @remirivas  @samashley @AndreaMonzini @Hans3901 @theedoms ?

**Comment by lexoyo** [comment]
![screenshot from 2016-11-14 23-43-41](https://cloud.githubusercontent.com/assets/715377/20285826/3986dd92-aac4-11e6-97ff-f3fca21bbe22.png)

**Comment by AndreaMonzini** [comment]
Responsive Blank layout seems to be a great idea.

**Comment by singchan** [comment]
Please vote for the template we should keep or remove
https://github.com/silexlabs/silex-templates/issues/26

**Comment by lexoyo** [comment]
Done, it is online now
https://editor.silex.me/

All the tests you can do are welcome! 
Thank you for your contributions, it was very helpful!
