### ISSUE TITLE
Basic first steps?

### ISSUE THREAD

**Issue by dotcalm** [silexlabs/Silex#284]
Where do I find the basics on this program/ I have put html5/css template in silex (used one of your templates) from dropbox and opened index page and I see no way to edit it? There is no editing area on chrome or firefox - I'm stuck.

**Comment by singchan** [comment]
You should open editable.html, since index.html is the published /
optimized version for the web

**Comment by lexoyo** [comment]
@dotcalm did you manage to edit the template?

**Comment by dotcalm** [comment]
I thought I had a silex template for html5/css – but I had downloaded another html5 one and got confused as to how to (or if it was possible) make it work in the editor.
