### ISSUE TITLE
make production

### ISSUE THREAD

**Issue by pierreozoux** [silexlabs/Silex#287]
I tried to add the following config to the Makefile:

```
production:
	npm install --production
	node_modules/grunt-cli/bin/grunt install
```

But the grunt install fails as it needs some dependencies from dev.
It would be great to have an effective separation of production and dev in `package.json`.

I wanted to do it, but I think you have more experience than me on what is necessary for dev and what is necessary for production.

Thanks!

**Comment by lexoyo** [comment]
Oh I just aw this issue
I am working on it on a branch here
https://github.com/lexoyo/Silex/tree/build
