### ISSUE TITLE
Choix de la page qui s'affiche à la connexion sur le site

### ISSUE THREAD

**Issue by ameliepic** [silexlabs/Silex#292]
Bonjour,
J'ai un site de plusieurs pages. Après publication, lorsque l'on se connecte à mon site, le navigateur s'ouvre sur ma page "contact", sûrement parce que c'est celle que j'ai créée en premier. Or, je ne veux pas que mon site s'ouvre sur cette page mais sur une autre page nommée "présentation". Quelqu'un peut-il me dire comment procéder? 
Merci.
Amélie

**Comment by lexoyo** [comment]
Salut @ameliepic 
Le site s'ouvre bien sur la 1ere page (en haut de la liste des pages). Et je n'ai j'amais fait la fonction pour réordonner les pages :-/
Donc tu as 2 solutions :
* intervertir 2 pages en renommant et en utilisant le copié collé
* éditer le html dans un éditeur de texte et intervertir les 2 balises "page", qui sont de la forme `<a id="page-1" data-silex-type="page" class="page-element">Page 1</a>` (silex les liste dans leur ordre d'apparition, elles peuvent être n'importe ou)

**Comment by ameliepic** [comment]
Très bien. Merci!

**Comment by lexoyo** [comment]
It should be fixed by now, can you confirm? thx
