### ISSUE TITLE
There are many nice templates to help you get started

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#301]
Here is a <a href="https://github.com/silexlabs/Silex/labels/template">list of Silex templates</a>. Download one and unzip it to your Dropbox or FTP, then open it in Silex.

<a href="https://github.com/silexlabs/Silex/labels/template"><img width="453" alt="screen shot 2015-07-30 at 15 35 11" src="https://cloud.githubusercontent.com/assets/6483546/8984240/a19a231c-36d0-11e5-99c5-8b3242debe65.png"></a>

**Comment by singchan** [comment]
this is not important anymore since the templates are displayed on the dashboard
