### ISSUE TITLE
Background not sizing properly on mobile phones

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#311]
I didnt build a mobile site because i dont know how.  But my regular site loads fine on any smart phone with the exception that the background dowsnt size properly as it does on a pc.  Ideas? www.fulldrawnaddiction.com

**Comment by lexoyo** [comment]
Hi @promoviper ! Nice website :)
What's wrong with the background ? 

When I scroll down here is what I see. Isn't it what you expect?
<img width="313" alt="screen shot 2015-08-20 at 15 35 55" src="https://cloud.githubusercontent.com/assets/715377/9384518/48ddd854-4751-11e5-90e9-72fee44a0690.png">

**Comment by promoviper** [comment]
Thank you. :) 
It ads the products again at the bottom almost like a double of the site. This is on mobile phone only it puts the extra at the bottom. Won't load correctly 

Sent from Yahoo Mail on Android

**Comment by lexoyo** [comment]
I do not see that can you send me a screenshot (here or at a.hoyau at silexlabs dot org)
What mobile phone do you use?
If i can reproduce it I will fix it :8ball:

**Comment by promoviper** [comment]
Droid note 

Sent from Yahoo Mail on Android

**Comment by singchan** [comment]
fixed
