### ISSUE TITLE
Web editor page switching not working

### ISSUE THREAD

**Issue by mattrunyon** [silexlabs/Silex#317]
Since the latest update, the web editor is not switching pages for me. I have tried in Chromium, Firefox, Opera (all on Linux), and Chrome on Mac. When I click the page thumbnail of any not active page, the active page is not switched.

I have figured out it has something to do with saving and loading a project on v2.2.5. I opened a v2.2.4 project into the editor and it gave me the notification that it upgraded to the latest version of Silex. I could still switch at this point. Then I saved and reopened. Navigation not working.

I reverted some lines in the head to the 2.2.4 version and it made my 2.2.5 version able to navigate again (although when it saves it will become unable to navigate pages). To do this I changed the following code in the html file that was generated when I saved.

    <meta name="generator" content="Silex v2.2.5">
    
    <script type="text/javascript" src="//editor.silex.me/static/2.5/jquery.js" data-silex-static=""></script>
    <script type="text/javascript" src="//editor.silex.me/static/2.5/jquery-ui.js" data-silex-static=""></script>

    <script type="text/javascript" src="//editor.silex.me/static/2.5/pageable.js" data-silex-static=""></script>
    <script type="text/javascript" src="//editor.silex.me/static/2.5/front-end.js" data-silex-static=""></script>
    
    <link href="//editor.silex.me/static/2.5/normalize.css" rel="stylesheet" data-silex-static="">
    
    <link href="//editor.silex.me/static/2.5/front-end.css" rel="stylesheet" data-silex-static="">

to

    <meta name="generator" content="Silex v2.2.4">
    
    <script type="text/javascript" src="http://static.silex.me/2.4/jquery.js"></script>
    <script type="text/javascript" src="http://static.silex.me/2.4/jquery-ui.js"></script>
    <script type="text/javascript" src="http://static.silex.me/2.3/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="http://static.silex.me/2.4/pageable.js"></script>
    <script type="text/javascript" src="http://static.silex.me/2.4/front-end.js"></script>
    
    <link href="http://static.silex.me/2.4/normalize.css" rel="stylesheet">
    
    <link href="http://static.silex.me/2.4/front-end.css" rel="stylesheet">

Hope this helps

**Comment by lexoyo** [comment]
Thank you for the detailed bug report, it saves me time :+1: 

I fixed it here
https://github.com/silexlabs/Silex/commit/2e34831aa633278ced81e07be0d2e272b06597f7

The problem was a side effect from this fix
 https://github.com/silexlabs/Silex/commit/5c23806528a6ae4ceeea2b1f9b79f3a5a13ed3a8

**Comment by lexoyo** [comment]
@mattrunyon you should probably put back the tags from v2.2.5 now
