### ISSUE TITLE
Ouverture de l'editable impossible

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#318]
Bonsoir, je voulais mettre à jour mon site, mais je n'arrive pas à ouvrir l'editable sur silex?

je m'explique:

J'ai fait mon site avec la 1er version de silex V2, je l'ouvre très bien aujourd'hui mais lorsque j'enregistre et que je quitte silex, impossible de l'ouvrir à nouveau?

Que peut-on faire à ce sujet?

**Comment by lexoyo** [comment]
Salut 
Ca doit être un bug de la classe "Backward Compatibility"
Peux tu me partager le site sur dropbox ? (a.hoyau à im-paris.fr)

**Comment by lexoyo** [comment]
J'ai corrigé ca ce midi vite fait, tu peux essayer sur 
http://preprod.silex.me/

**Comment by Stuff31** [comment]
Ok merci, j'ai essayé sans succès avec tous les editables sauf le ''LEO2.html'' et le ''LEO2(copy).html'' qui fonctionnent avec un rendu ci-joint : 

![capture d ecran 2015-09-02 a 18 51 59](https://cloud.githubusercontent.com/assets/6841971/9655552/2f6bf22a-5232-11e5-9375-d39b153daaf5.png)

Ce n'est pas urgent, j'attendrai que tu fixe ca.

**Comment by lexoyo** [comment]
Ah pardon, c'est sur preprod.silex.me qu'il faut que tu essayes

**Comment by lexoyo** [comment]
Salut Léo, je peux fermer cette issue?

**Comment by Stuff31** [comment]
Salut ! Oui ça fonctionne parfaitement bien et c'est très rapide!

Merci ;)
