### ISSUE TITLE
Awesome "RESTO" Template

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#320]
• <a href="http://www.templamatic.com/templates/3905">Download</a>
• <a href="http://www.templamatic.com/templates/3905/preview">Preview</a>

Here is a single page "long scrolling" template, for a restaurant or a food related businesses. It is made with <a href="http://www.silex.me">Silex</a>, and can be hosted anywhere

<a href="http://www.templamatic.com/templates/3905">
![resto-big](https://cloud.githubusercontent.com/assets/6841971/9669348/b721aad0-5286-11e5-99a5-0d7e5e1eee74.jpg)
</a>

To make your own website based on this template, <a href="http://www.templamatic.com/templates/3905">download the archive here</a>, unzip and open the file editable.html with <a href="http://editor.silex.me">Silex editor</a> (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by lexoyo** [comment]
This template was hosted on templamatic
Does someone have the files?
