### ISSUE TITLE
Awesome "WUSTH" Template

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#321]
• <a href="http://www.templamatic.com/templates/3906">Download</a>
• <a href="http://www.templamatic.com/templates/3906/preview">Preview</a>

Here is a single page "long scrolling" template, for a entertaiment or communication related businesses. It is made with <a href="http://www.silex.me">Silex</a>, and can be hosted anywhere

<a href="http://www.templamatic.com/templates/3906">
![wusth-big](https://cloud.githubusercontent.com/assets/6841971/9669456/87e9b02c-5287-11e5-80d2-a92f6b2aa090.jpg)
</a>

To make your own website based on this template, <a href="http://www.templamatic.com/templates/3906">download the archive here</a>, unzip and open the file editable.html with <a href="http://editor.silex.me">Silex editor</a> (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by AndreaMonzini** [comment]
Hello,
i tried the live preview and after i click on "what we do" the top menu disappear.
Is that a feature or a bug?
thank you.

**Comment by lexoyo** [comment]
I believe it is normal, it comes back when you scroll down

**Comment by Stuff31** [comment]
Yes indeed it is a function , its menu has a certain scroll . It is obviously easy to change.

**Comment by lexoyo** [comment]
This template was hosted on templamatic
Does someone have the files?
