### ISSUE TITLE
Idée ou suggestion width:100%(full)?

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#322]
Bonjour!
Alors, j'utilise tout le temps des containers, à chaque fois qu'il y a une image avec du texte il y a un container, dès que je met une image c'est avec un container (pour avoir l'option cover/auto). 

Je me retrouve souvent à mettre un container en width:100%(full: qui prend tout l'écran), pour cela je le glisse sur l'arrière plan. Il me semble intéressant de mettre une option dans les propriétés de façon a choisir arrière-plan ou non (100% ou normal). J'en met beaucoup dans les templates mais lorsque qu'on le déplace avec la souris ça ce remet sur le 1er plan (BG).
Voila, à voir..?

**Comment by lexoyo** [comment]
Pour etre sur que je comprenne bien, il y a 2 points : 
- le fait de garder un container au fond du site (background)
- le fait d'avoir un élément à 100% de la largeur?

**Comment by Stuff31** [comment]
Oui je crois que c'est ça.

Je vais le dire d'une façon différente: quand mon site fait 900px de large je met souvent des container a 100% sur absolument toute la largeur pas que sur les 900px. Donc un élément à 100% de la largeur.

**Comment by lexoyo** [comment]
Je pourrais ajouter à coté de width / height, des boutons pour px ou %
Ca résoudrait le problème ?
Il resterait le problème du fait de garder un container au fond du site non?

**Comment by Stuff31** [comment]
oui tout a fait, il resterait le problème du fait de garder un container au fond du site.

**Comment by lexoyo** [comment]
pour les %, je viens de faire un premier pas : afficher "px" à droite de width/height/top/left
https://github.com/silexlabs/Silex/pull/371

testable sur preprod

**Comment by lexoyo** [comment]
@Stuff31 que penses tu du nouveau systeme de "section", ca réponond à ton besoin?

**Comment by lexoyo** [comment]
@Stuff31 que penses tu du nouveau systeme de "section", ca réponond à ton besoin?
