### ISSUE TITLE
Testers needed

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#326]
I am about to released a new version, with bug fixes and better performance.

Please test on [preprod](http://preprod.silex.me) so that I can release it publicly. Feel free to comment / report bugs here.

**Comment by AndreaMonzini** [comment]
Hello,
do you have more info about the difference of the "preprod"?
i will try to test it.

**Comment by lexoyo** [comment]
Thank you @AndreaMonzini but I just published and it is now live on editor.silex.me
I have made opitmisations in the "stage" (drag drop etc.), and also the html is cleaner etc
