### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by donixa-com** [silexlabs/Silex#328]
My site done but most of the links don't work. The links on 2 containers I added on page 2 seem to invisibly cover up and disable the links on all other pages. I have been through this code over and over and cant figure it out.

**Comment by donixa-com** [comment]
My site is iamthedonald.com

**Comment by lexoyo** [comment]
Hi @donixa-com 

This issue has been reported already by @mattrunyon, here are 2 solutions. 
Note that for people downloading the template as of now, I have fixed this issue.


# Solution 1

Open the css editor (View menu then CSS style editor). Remove the styles between `/* transition */` and `/* header */`. 

This will remove the transitions between pages and fix the issue

# Solution 2

Open the css editor (View menu then CSS style editor). Replace the styles between `/* transition */` and `/* header */` with this code

```
/* transition */
.silex-runtime .paged-element {
    transition: opacity .5s ease-out;
    opacity: 0;
    display: block;
}
.silex-runtime .paged-element.paged-element-visible {
    opacity: 1;
}
.silex-runtime .paged-element.html-element,
.silex-runtime .paged-element .html-element{
    display: none;
}
.silex-runtime .paged-element.paged-element-visible.html-element,
.silex-runtime .paged-element.paged-element-visible .html-element{
    display: block;
}
```

This will fix the problem and keep transitions for everything but the iframes

**Comment by donixa-com** [comment]
Solution 2 did not work. Removing the transition style codes worked like a charm! Site is perfect now I spent days trying to fix it on my own. Many thanks or shall I say mille fois merci :)
