### ISSUE TITLE
[feature request] responsive / mobile editor

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#33]
offer a simple solution to create responsive websites

**Comment by AndreaMonzini** [comment]
is it in the roadmap?
I'm interested in responsive features.
thank you

**Comment by lexoyo** [comment]
Absolutely! :)

I will release a new version soon, which is a first step in this direction (the one you tried on preprod), and then I will release the first version with a "mobile version editor", which generates media queries and a "hamburger" menu

**Comment by lexoyo** [comment]
I started the work on this branch but you can not try it online yet
https://github.com/lexoyo/Silex/tree/mobile

**Comment by AndreaMonzini** [comment]
Great news !

**Comment by AndreaMonzini** [comment]
Hello, any news about responsive/mobile solutions with Silex?
Thank you.

**Comment by lexoyo** [comment]
The first step was this release https://github.com/silexlabs/Silex/pull/302
The styles are not inline anymore. 

Since then I have optimized ([here](https://github.com/silexlabs/Silex/commit/7d68ee166dae9e6d9dfb864fb45aad1460671c62) and [here](https://github.com/silexlabs/Silex/commit/1229b22835e7f272418207a90e61ddfe08645066)) and debugged a lot, I have set up a better build (no more grunt / npm alone, [better config of the google closure compiler](https://github.com/silexlabs/Silex/commit/2005429a85ab26b391baae555f0a03f74a0cf873) and [fixed all resulting warnings](https://github.com/silexlabs/Silex/commit/4bff2c21afe7b46ea23de7364d42d4f12339dbba)) and an automatic deployment / CI (see [this blog post about deployment on Gandi, our sponsor for hosting](http://the.webapp.cat/2015/07/Deploy-to-Gandi-Simple-Hosting.html)). 

All this was necessary before I can start to merge my work on mobile, because the fact that styles are not inline was mandatory and it has a lot of side effects. Feel free to ask any questions about this.

Also I have added a few little things which are not mobile related, like the [tip of the day](https://github.com/silexlabs/Silex/commit/6cbe0bfa57a37c55b33a70ceb33cdc59afc12310), [https support](https://github.com/silexlabs/Silex/commit/a313aff54e1d4272f4bb23877afde7c460fe1441) (editor.silex.me should soon be https)...

**Comment by lexoyo** [comment]
Hello, here is a work in progress
https://silex-editor.herokuapp.com/

This includes

* switch to mobile editor mode: view > mobile editor
* enable/disable mobile version for the current website: file > settings > publish settings > enable mobile verstion
* automatic mobile menu generation
* when you change styles in the mobile editor, it does not change it in the normal editor (this is a feature not a bug), but a change in the normal editor will be available in mobile editor

There are still bugs and these limitations

* drag/drop do not work properly yet

And here is my to do list

* keyboard up/down/left/right => move in the DOM
* warn when display in mobile and not mobile-enable
* properties to add: show/hide, absolute, page display in menu
* disable insertion of new elements

**Comment by lexoyo** [comment]
Hello, here is a work in progress
https://silex-editor.herokuapp.com/

This includes

* switch to mobile editor mode: view > mobile editor
* enable/disable mobile version for the current website: file > settings > publish settings > enable mobile verstion
* automatic mobile menu generation
* when you change styles in the mobile editor, it does not change it in the normal editor (this is a feature not a bug), but a change in the normal editor will be available in mobile editor

There are still bugs and these limitations

* drag/drop do not work properly yet

And here is my to do list

* keyboard up/down/left/right => move in the DOM
* warn when display in mobile and not mobile-enable
* properties to add: show/hide, absolute, page display in menu
* disable insertion of new elements

cc @singchan @silexlabs/silex-labs-contributors @silexlabs/silex @antosilex

**Comment by lexoyo** [comment]
@AndreaMonzini the mobile editor / responsive mode is live on editor.silex.me
