### ISSUE TITLE
Comment mettre plusieurs pages actives?

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#331]
Bonsoir, je suis entrain de refaire le menu de mon site avec ce code CSS:       
 <code>.menu .page-link-active {}</code>

J'ai mis cette classe sur tous les boutons du menu et tout fonctionne :)
Cependant sur le bouton "COMMANDES" il y a plusieurs pages où j'aimerai laisser activé ce code.. 
Y a t-il un moyen de faire ça?

**Comment by lexoyo** [comment]
Hmm tu peux faire
.menu .page-link-active,
.menu .page-page1,
.menu .page-page2 { ... }

**Comment by Stuff31** [comment]
Je viens d'essayer mais ça ne marche pas..?

<i>ps: je me suis trompé, il ne faut pas d'espace entre 'menu' et 'page' sinon ça ne marche pas : </i>
<code>.menu.page-link-active { ... }</code>

**Comment by lexoyo** [comment]
ah oui en effet, je viens de comprendre
Essaie de faire ce qui est décrit ici dans la section 'Page events' à la fin (je l'ai rajouter pour cette occasion)
https://github.com/silexlabs/Silex/issues/200

Et après tu mets 
```
.menu.page-link-active,
.page-page1-opened .menu,
.page-page2-opened .menu 
{ ... }
```

**Comment by Stuff31** [comment]
Haaa c'est parfait :)

Merci Alex!
