### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Yuzmeister** [silexlabs/Silex#332]
Hi. Sorry for the trouble. but to make it quick, lets just pressume that i have checked all requirements and details and yet, I fail to set up a web based instance on my site.Well I did go through installation, that's done and I am on the part of the Business card. That s where i'm stuck, Of course, again, username and everything (that I know of, as far as the groundwork goes) has been verified. Is there any possible cause, solution or any detail that I should review? 

Apologies and Thank you in advance!

**Comment by singchan** [comment]
Hello
Where did you get Silex from?
Silex latest version is v2 and it looks like you are talking about the v1
V2 is available hosted here
http://www.silex.me
And you will be able to store your data (assets and html website) on your
Dropbox or FTP
