### ISSUE TITLE
Text Box size

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#335]
Would it be possible that the text box editor shows the real size of the text box
to avoid that the text doesn't fit in the text box after closing the text box editor

**Comment by lexoyo** [comment]
I do not see how to do this...
I would rather adapt the text box to the content?
Or edit the text in place in the text box...

**Comment by antosilex** [comment]
Could you put the text box in the text editor ?
To allow visualizing the borders : the size of the box
