### ISSUE TITLE
Can the web based Silex web editor include php scripts?

### ISSUE THREAD

**Issue by cfcbee** [silexlabs/Silex#336]
Hi, new to Silex and trying to build a new website with it. Could not find any information about using php. 

Need a contact Email form and could not find anyway to include the php processing script into the editor. There does not seem to be any information about php in the help blog either. I am starting to assume php is not supported by the Silex editor is this true?

In which case I assume the php pages will need to be uploaded to the web server separately after publishing the web site from Silex, is this how it should work?

many thanks for the info.

**Comment by lexoyo** [comment]
Hi @cfcbee and welcome to you !!

Indeed you are right, Silex produces static HTML/CSS/JS files, so you will want to add your php scripts somewhere and add an HTML form in Silex with an HTML box

Let us know how it goes and do not hesitate to post your php script + html/css code as a widget, which is an issue in github like these ones https://github.com/silexlabs/Silex/labels/widget

**Comment by cfcbee** [comment]
Thanks for the info.
