### ISSUE TITLE
error unkown api

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#340]
i get that when i try to publish

**Comment by lexoyo** [comment]
You get what? There is no screenshot nor text

**Comment by promoviper** [comment]
I get it in the middle of publishing my site.  Also the get started button on your home page just keeps reloading the silex home page instead of launching the editor.

**Comment by lexoyo** [comment]
> I get it in the middle of publishing my site.  

Sorry I do not understand what happens when you publish your website?
In any case, please try to select the publish folder *again* in `File / Settings / Publish settings`

> Also the get started button on your home page just keeps reloading the silex home page instead of launching the editor.

Oh thank you so much, I fixed it

**Comment by lexoyo** [comment]
Oh I just got it, you have the error "error unkown api", of course
Select the publish folder *again* in `File / Settings / Publish settings`

**Comment by promoviper** [comment]
That fixes it but what is causing my background to not load correctly on mobile devices... see pic


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by lexoyo** [comment]
> That fixes it but what is causing my background to not load correctly on mobile devices... see pic 

I do not see any pic, and it loads fine on my device

**Comment by promoviper** [comment]
I attached a pic to this email look at the bottom


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by lexoyo** [comment]
Github does not forward attachments, please add it in github
