### ISSUE TITLE
New website made with Silex: Stylcuisines, a luxury kitchen design firm

### ISSUE THREAD

**Issue by promoviper** [silexlabs/Silex#341]
[Here is a website made with Silex:](http://www.stylcuisines.fr/), which has a video background and an elegant simple style

<a href="http://www.stylcuisines.fr/"><img src="https://cloud.githubusercontent.com/assets/715377/24374096/e3109c4a-1333-11e7-82bf-acfc4fe6eacf.png"/></a>

It is made with [Silex website builder](http://www.silex.me) and uses [the video background widget](https://github.com/silexlabs/Silex/issues/204).

**Comment by singchan** [comment]
very nice! i add it to the "showcase" section of www.silex.me

note: you should make it responsive now with the new mobile editor in silex, let me know if you need help

**Comment by lexoyo** [comment]
The website seems down? Feel free to reopen the issue if it comes back up
