### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by jpmathieu** [silexlabs/Silex#342]
Bonjour,
je commence avec silex, et après avoir vu les vidéos je bloque sur l'insertion d'une image,elle se charge dans ma drop box mais je ne peux paas cliquer dessus (sens interdit au survol) et donc je n'ai pas la main pour l'inserer dans silex, meme chose avec le fonction  image de fond! les photos sont en jpg et la taaille entre 400 ko et 1 mo
Pouvez-vous m'aider?
merci

**Comment by lexoyo** [comment]
bonjour @jpmathieu 
peux tu me donner le nom de l'un des images tel qu'il s'affiche dans silex ?

**Comment by jpmathieu** [comment]
03 Piscine.jpg  (216ko)
DSC_0748.jpg ( 980 )

**Comment by jpmathieu** [comment]
03 Piscine.jpg (216ko)
DSC_0748.jpg ( 980 )
dans drop box

**Comment by lexoyo** [comment]
ah c'est étrabge 
tu peux me faire une capture écran?

**Comment by jpmathieu** [comment]
![capture](https://cloud.githubusercontent.com/assets/15053342/10411909/3b390024-6f75-11e5-8110-56240b2bc961.JPG)
et quand je passe la souris  sur l'image elle devient un rond rouge barré en travers, donc impossible de la selectionner

**Comment by lexoyo** [comment]
Oh ok je vois : le "JPG" est en majuscule et ça me rappelle que j'ai vu passer un bug report qui dis que ça doit être en minuscule

**Comment by lexoyo** [comment]
@jpmathieu tu as pu ajouter les images?
tu peux les renommer depuis silex, en changeant JPG par jpg

**Comment by jpmathieu** [comment]
Le 14/10/2015 00:45, Alex Hoyau a écrit :
>
> @jpmathieu <https://github.com/jpmathieu> tu as pu ajouter les images?
> tu peux les renommer depuis silex, en changeant JPG par jpg
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/silexlabs/Silex/issues/342#issuecomment-147875031>.
>
Bonjour,
pardon de répondre aussi tard!
Je pense que le bug vient pas seulement des maj, je peux importer des 
gif en minuscule des jpg renomées en jpg.JPG mais l'ouverture est 
aléatoire( 1 /2ou3).Même  des jpg inclus dans votre dossier ipsoom 
peuvent ne pas s'ouvrir. Peut être est - ce mon système qui bug (firefox?).
Je ne vois pas comment renommer dans silex les photos? Je suis pas 
encore habitué mais je pense qu'il faut être connecté sur DB en même 
temps que sur silex?
Je ne suis pas un geek.J'essaie silex car j'ai travaillé avec des geek 
(http://www.marsnet.org/spip.php?article408 
<cid:part1.07090207.09080900@gmail.com> ) pour mon site internet 
(http://www.gitesousleschenes.com/ 
<cid:part2.03090402.03050302@gmail.com>)  sur Marseillequ'ils hébergent 
avec leurs serveurs,mais Spip est trop complexe a gérer!
Bref pour mon gite je voudrais développer ce site et silex pourrais me 
permettre une certaine autonomie.
Une question, pour transférer le travail de drop box sur mon compte de 
serveur marsnet, je suppose que je devrais passer par un ftp genre file 
zilla?
Merci pour votre réactivité,
amitiés
--

**Comment by jpmathieu** [comment]
Bonjour,
j'ai un souci de galerie, j'ai pris juxebox builder lite (suivant vos liens simple wiewer).
La galerie a fonctionné une fois.
Depuis j'ai des problèmes :1 d'affichage  je colle l'embed code dans la html box de ma page mais celle ci ne se prévisualise pas (le dossier contenant la galerie est dans drop box.)
Je ne peux pas reouvrir la galerie faite avec jbl car si le dossier ouvert est bon il ne me propose pas le fichier de config alors qu'il est présent dedans (config xml).
Je ne sais pas si vous pouvez regarder du coté de l'aide jbl [https://juicebox.net/forum/viewtopic.php?pid=9274#p9274](url) ou si c'est avec silex!!
J'avoue que je m'y perds un peu dans les differentes configuration embeded de jbl , et la réponse de jbl ne fonctionne pas!!
merci d'avance

**Comment by lexoyo** [comment]
bonjour @jpmathieu 
je ne connais pas jbl, mais ca ne doit pas etre sorcier!
je ne comprends pas cette phrase, peux tu préciser?

> Je ne peux pas reouvrir la galerie faite avec jbl car si le dossier ouvert est bon il ne me propose pas le fichier de config alors qu'il est présent dedans (config xml).

**Comment by jpmathieu** [comment]
Bonsoir,
en fait quand je crée  une gallerie  jbl demande d'enregistré à l'étape avant de publier. .quand j'enregistre dans le dossier choisi pour la galerie jbl me demande si je veux overwrite les fichiers contenus ds le dossier,si  je fais oui la gallerie s'enregistre ds le dossier mais après pour réouvrir cette galerie  le bon dossier s'ouvre  mais la fenêtre ne montre pas les fichiers index html  et piscine html (nom de la gallerie) ni config xml alors qu'ils sont présents dedans! donc pas possible de l'ouvrir! Par contre index et piscine html s'ouvre avec frf et config avec dropbox!!!
J'ai telecharger et reinstallé xx fois je place  à l'installation le dossier jbl ds C/program files x86 et enregistre le dossier gallerie ds drobox au niveau des fichiers silex.
on peux pas enregistrer deux galeries ds le même dossier sinon voir l'aide [](url) jbl et je fais comme indiqué sur vos post git hub , une html box inserée ds la page de la galerie et je copie l'embed code de la gallerie  mais rien !
J'ai posté sur l'aide jbl mais la réponse  ne marche pas et ne réponds pas à l'impossibilité d'ouvrir la gallerie enregistrée.
merci

**Comment by jpmathieu** [comment]
oups 
voici le lien de l'aide jbl:
[https://www.juicebox.net/support/embedding/](url)

**Comment by lexoyo** [comment]
Est-ce que tu peux publier ton site qq part?
Par exemple avec https://www.netlify.com/

**Comment by lexoyo** [comment]
Et je viens de voir ta question :

> Une question, pour transférer le travail de drop box sur mon compte de serveur marsnet, je suppose que je devrais passer par un ftp genre file zilla?

Tu peux utiliser la fonction "publication" et utiliser publication par FTP
[La doc sur la publication](https://github.com/silexlabs/Silex/issues/238)
[Une video de demo](https://www.youtube.com/watch?v=13MPr7fPr_M) (avec dropbox mais c'est le meme principe pour le ftp)

**Comment by jpmathieu** [comment]
Bonjour,
en fait j'attends de finir le site avec silex pour le publier sur mon 
hebergeur et remplacer l'ancien.
Je t'ai mis comme collaborateur sur mon dossier dropbox j'espère que tu 
pourras voir.
Ceci dit j'abuse un peu car c'est surtout un problème jbl  et non de silex
amitiés
JP Mathieu

Le 06/02/2016 11:12, Alex Hoyau a écrit :
>
> Et je viens de voir ta question :
>
>     Une question, pour transférer le travail de drop box sur mon
>     compte de serveur marsnet, je suppose que je devrais passer par un
>     ftp genre file zilla?
>
> Tu peux utiliser la fonction "publication" et utiliser publication par FTP
> La doc sur la publication <https://github.com/silexlabs/Silex/issues/238>
> Une video de demo <https://www.youtube.com/watch?v=13MPr7fPr_M> (avec 
> dropbox mais c'est le meme principe pour le ftp)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/silexlabs/Silex/issues/342#issuecomment-180729772>.
>

-- 


---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by lexoyo** [comment]
> Je t'ai mis comme collaborateur sur mon dossier dropbox j'espère que tu pourras voir. 

Je n'ai rien reçu :-/

Et autre truc : ce w-e j'ai créé un outil pour faire des "slide show" avec github
https://github.com/lexoyo/jekyll-slideshow/#jekyll-slideshow

C'est un peu technique mais si tu veux prendre le temps de l'utiliser je peux t'aider... [Pose des questions ici](https://github.com/lexoyo/jekyll-slideshow/issues).
