### ISSUE TITLE
problème de vidéo sur Chrome

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#345]
Je remarque une extreme lenteur sur une vidéo que j'ai embedé (youtube). J'ai testé aussi avec le widget "video player widget" mais je constate le même problème. <b>C'est que sur Chrome</b>

OSX 10.6.8
Chrome Version 46.0.2490.71 (64-bit)
Silex Preprod

Le lien du site ou la vidéo ce charge lentement. Mais peut être que ça viens d'autre chose?..
http://tristanfrancia.com/

**Comment by lexoyo** [comment]
Je n'ai pas de ralentissement chez moi..

**Comment by Stuff31** [comment]
Ah c'est que chez moi alors, je regarderai et si je trouve le problème je le posterai.
