### ISSUE TITLE
problème sur les containers

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#346]
Sur les propriétés "background image" , lorsque je change "top", "left" et "repeat" sur Chrome  et que j'ouvre à nouveau silex mais sur Firefox ça remet à zéro. 

Et quand je publie à partir de Chrome et que j'ouvre le .html, ça me fait la même chose.

**Comment by lexoyo** [comment]
En effet, je le note et je te préviens quand c'est corrigé
Si tu maquettes avec firefox tu n'auras pas ca problème (ca marchera sous ff et chrome)

**Comment by Stuff31** [comment]
Ok ça marche
merci

**Comment by lexoyo** [comment]
Should be fixed thanks to this commit
https://github.com/lexoyo/Silex/commit/f65ffd0351beeb93d08539ecf2bbca8c48168ead

You can test it here or wait for it to be live :)
http://silex-editor.herokuapp.com/
