### ISSUE TITLE
font problem

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#347]
in the text box editor all the fonts are the same from "roboto condensed" until the end of the list

it would be nice to have a tutorial to add new fonts too

**Comment by lexoyo** [comment]
Thank you, I'll have a look soon
I will probably remove these fonts

**Comment by antosilex** [comment]
That is not what i ´ve asked ;)

**Comment by antosilex** [comment]
is there a tutorial to add new fonts ?

**Comment by lexoyo** [comment]
You can use this tutorial to learn how to get a font
http://knowledge.hubspot.com/articles/kcs_article/cos-general/how-do-i-add-google-fonts-to-my-new-landing-pages

Use the CSS editor to insert the code

And do not hesitate to make a tutorial here once you have understood how it works
https://github.com/silexlabs/Silex/wiki

**Comment by antosilex** [comment]
ok to get it but i don't succeed to use it with silex

**Comment by lexoyo** [comment]
you get the line with `@import`? you paste it in css editor
and then you use the font wit the other lines also in the css editor, e.g.
```
h1 {
   font-familly: ...
}
```

**Comment by lexoyo** [comment]
I have found this 
https://github.com/silexlabs/Silex/issues/46

**Comment by singchan** [comment]
duplicate of https://github.com/silexlabs/Silex/issues/347
