### ISSUE TITLE
open pages

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#349]
Hello

I have added a service which I called "open pages". When you save your website you can use this service and it will be available online automatically,

This is a prototype for now, disabled by default in Silex. You can test it here
http://silex-editor.herokuapp.com/

And when you login, it will let you choose a name for your "open pages" account. This means that your site will be available on
http://silex-editor.herokuapp.com/og/yourname/

For example i did this site to test
http://silex-editor.herokuapp.com/og/lexoyo/index.html

Please test and let me know
Note that your website on open pages will be erased after some time
cc @pierreozoux @silexlabs/silex

**Comment by pierreozoux** [comment]
Ouahou! Amazing!

I have some comments:
 - is it possible that the first page has the default name `index.html`, (then people don't have to bother for their first page)
 - is it possible when you hit `http://silex-editor.herokuapp.com/og/yourname/` it looks for `index.html`
 - for the url, I'd prefer something like:
  - shared version:
   - http://example.org/yourname/ (to see your page)
   - http://example.org/yourname/editor/ (to edit your page)
  - personal version:
   - http://example.org/
   - http://example.org/editor

I know I am demanding :) With these features, I think it would be perfect :) But it is impressive! I love it :)

**Comment by lexoyo** [comment]
good ideas!
sure this is possible (all 3)

**Comment by pierreozoux** [comment]
Could you explain me how to activate open pages on my instance please? Thanks!

**Comment by lexoyo** [comment]
It is experimental for now, just set the env var `SILEX_DEBUG` to  `true`, e.g.
```
$ SILEX_DEBUG=true npm start
```
