### ISSUE TITLE
Silex is stuck in ftp access

### ISSUE THREAD

**Issue by Ector3** [silexlabs/Silex#354]
I have been using dropbox just fine, but I decided to try the ftp for my website to see if it worked
and silex online is just frozen when trying to add a picture or open a file. Of course I tried  restarting the browser eeven restart the computer and nothing... Please help

**Comment by lexoyo** [comment]
So you can login to your ftp, you see the files there?
Did you try to simply save your website (html)?

**Comment by Ector3** [comment]
I deleted the cookies and everything works fine now in dropbox, but the ftp denies access even after 
copy and paste the credentials from filezilla. I logged out of filezilla and typed in the credentials to make sure credentials are correct.

**Comment by lexoyo** [comment]
Ok :8ball: 
Which hosting company is it?

The only way for me to debug this may be that you send me the credentials by email (a.hoyau [at] silexlabs dot org)

**Comment by Ector3** [comment]
Thank you. I just got this website host thing a couple of days ago. As it turns out I had not even pointed my dns
to the host and just now also finding out about placing things in the correct folder.
I have not dealt with websites in a few years. So, let me make sure that all the info is in the correct folder in the 
host. And if still not working I will get back to you. 

Thank you,
 


Ector Gutierrez 
Cell: (504) 301-7246 




Date: Tue, 10 Nov 2015 16:21:11 -0800

**Comment by lexoyo** [comment]
So @Ector3 could you manage working with FTP ? 
I am running a bug fix campaign right now :)
