### ISSUE TITLE
New feature: poll while you wait for publish 

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#358]
Hello

Thx to @ondrejec I have added this panel while you wait for your site to be published.

![screenshot from 2015-11-23 23 22 50](https://cloud.githubusercontent.com/assets/715377/11351955/df41c566-9239-11e5-9f81-4bfed661bc3d.png)

It is made with http://surveymonkey.com and the info about the publication process is still available at the top of the dialog. 

The goal is to determine what is important to our users and crowd fund the top 3 requests.

What do you think?
cc @silexlabs/silex @silexlabs/silex-labs-contributors @singchan @pierreozoux

**Comment by JbIPS** [comment]
Great idea! Hope we'll get result soon

**Comment by pierreozoux** [comment]
Yes! Perfect! Bravo :)

**Comment by lexoyo** [comment]
Hello

It's been a few days since this is in production, and we have an average of 60 people who publish a site every day, and 1 form submission / answer to the poll

* [silex stats](https://lexoyo.piwik.pro/), and specifically [the publication "goal"](https://lexoyo.piwik.pro/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#/module=Goals&action=goalReport&idSite=3&period=day&date=yesterday&idGoal=5)
* The [poll answers](https://fr.surveymonkey.com/results/SM-LX6GGR8J/)
