### ISSUE TITLE
BLUEY-creation, Interior decorative objects creations

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#359]
<a href="http://www.bluey-creation.fr">A showcase site</a> that I made with SILEX on original handmade creations ( I myself realized these objects interior design concrete and steel; my girlfriend is pretty frames with geometric shapes of leather) .
<b>
www.bluey-creation.fr
</b>

[![bluey](https://cloud.githubusercontent.com/assets/6841971/11363212/b1269a44-9298-11e5-99fd-f5ca9d49a713.jpg)](http://www.bluey-creation.fr/)

**Comment by lexoyo** [comment]
Very beautiful !!

**Comment by lexoyo** [comment]
Comment as tu fais le diaporama sur la home?

**Comment by Stuff31** [comment]
(je n'arrive pas a mettre le contenu des codes sur Github...)

Je l'ai fait avec une HTML-BOX et ce code:

<pre>
<div class="pic-wrapper">
  <figure class="pic-1"></figure>
  <figure class="pic-2"></figure>
  <figure class="pic-3"></figure>
  <figure class="pic-4"></figure>
</div>
</pre>

et en mettant ce code dans l'editeur CSS:
<span>
* {
  margin: 0;
  padding: 0;
}

.pic-wrapper {
  position: absolute;
  width: 100%;
  height: 100%;
  overflow:hidden;
}

figure {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity:0;
  /*animation*/
  
  animation: slideShow 24s linear infinite 0s;
  -o-animation: slideShow 24s linear infinite 0s;
  -moz-animation: slideShow 24s linear infinite 0s;
  -webkit-animation: slideShow 24s linear infinite 0s;
}

.pic-1 {
  opacity: 1;
  background: url(http://docode.com.ua/wp-content/uploads/pictures/pic-1.jpg) no-repeat center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.pic-2 {
  animation-delay: 6s;
  -o-animation-delay: 6s;
  -moz--animation-delay: 6s;
  -webkit-animation-delay: 6s;
  background: url(http://docode.com.ua/wp-content/uploads/pictures/pic-2.jpg) no-repeat center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.pic-3 {
  animation-delay: 12s;
  -o-animation-delay: 12s;
  -moz--animation-delay: 12s;
  -webkit-animation-delay: 12s;
  background: url(http://docode.com.ua/wp-content/uploads/pictures/pic-3.jpg) no-repeat center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.pic-4 {
  animation-delay: 18s;
  -o-animation-delay: 18s;
  -moz--animation-delay: 18s;
  -webkit-animation-delay: 18s;
  background: url(http://docode.com.ua/wp-content/uploads/pictures/pic-4.jpg) no-repeat center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
/* keyframes*/

@keyframes slideShow {
  0% {
    opacity: 0;
    transform:scale(1);
    -ms-transform:scale(1);
  }
  4% {
    opacity: 1
  }
  24% {
    opacity: 1;    
  }
  28% {
    opacity: 0;
    transform:scale(1.1);
    -ms-transform:scale(1.1);
  }
  100% {
    opacity: 0;
    transform:scale(1);
    -ms-transformm:scale(1);
  }    
 }

@-o-keyframes slideShow {
   0% {
    opacity: 0;
    -o-transform:scale(1);
  }
  4% {
    opacity: 1
  }
  24% {
    opacity: 1;    
  }
  28% {
    opacity: 0;
    -o-transform:scale(1.1);
  }
  100% {
    opacity: 0;
    -o-transformm:scale(1);    
  }
}

@-moz-keyframes slideShow {
   0% {
    opacity: 0;
    -moz-transform:scale(1);
  }
  4% {
    opacity: 1
  }
  24% {
    opacity: 1;    
  }
  28% {
    opacity: 0;
    -moz-transform:scale(1.1);
  }
  100% {
    opacity: 0;
    -moz-transformm:scale(1);    
  }
}

@-webkit-keyframes slideShow {
  0% {
    opacity: 0;
    -webkit-transform:scale(1);
  }
  4% {
    opacity: 1
  }
  24% {
    opacity: 1;    
  }
  28% {
    opacity: 0;
    -webkit-transform:scale(1.1);
  }
  100% {
    opacity: 0;
    -webkit-transformm:scale(1);    
  }
}
</span>

et en le remaniant un peut.

**Comment by lexoyo** [comment]
OK, ça vient de ce slide show je pense
http://codepen.io/docode/pen/EjyVQY

**Comment by Stuff31** [comment]
Ah je ne le trouvais plus, oui c'est exactement celui là!
;)
