### ISSUE TITLE
Create anchor for links

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#363]
I'm trying to add some links on my website so I'm currently using text boxes with the 'link' property. But the generated HTML is just a div with some data to react on click. 
The problem is I can't use my middle-click or decide of the target. Moreover, it's not very good for accessibility.
Could we insert anchor the same way we do for text box? Or couldn't an element be converted to an anchor when the link property is not null?

**Comment by lexoyo** [comment]
When you publish it replaces it with real clicks
