### ISSUE TITLE
The future of web intra-development ?

### ISSUE THREAD

**Issue by ATIXIUM** [silexlabs/Silex#365]
Greetings, I've been following SiLex since the good 'old flash days, however Now Silex has evolved into a Much more improved interface for building impressive HTML5 pages! 

Anyhow I would love to suggest the future of Silex to get many Many people onboard by the use of animation through GreenSock ? Is that even possible? to incorporate easy animations for HTML5 websites? It's rare to see any CMS out there that can actually do that.
-Just imagine the outcomes from being able to animate any pages in layers and output it for HTML5 from the use of your CMS through an easy interface. Just a suggestion, thanks for your time.

**Comment by lexoyo** [comment]
Hey @ATIXIUM !

I believe it is possible! It should be simple to make a widget (which is basically a tutorial for now in Silex v2). The user can "attach" a css class to an element and js script can be added and use css classes to select element and add animations to it...

If you need this I can try to guide you to use greensock in silex?

**Comment by lexoyo** [comment]
I will close this issue, feel free to re-open it if you are still around
