### ISSUE TITLE
Background picture on all pages

### ISSUE THREAD

**Issue by Hambone0304** [silexlabs/Silex#378]
I put a background picture on the first page and when i made a new page it was there to but i dont want it on the second page because i would like to use a different background image.

**Comment by lexoyo** [comment]
The simplest thing is to put it as an image and select it's visibility in the properties. Or as a background image of a text field for example...

A more complex method is to use css to change the background image of an element (or the body or the main container) depending on the page, for example

```
BODY.page-[your page name] {
    background-image: url('[your image name]') 
} 
```

More about [css in Silex here](https://github.com/silexlabs/Silex/issues/184)
