### ISSUE TITLE
add a flash game to my website

### ISSUE THREAD

**Issue by theycallmebacon1** [silexlabs/Silex#384]
How would I go about to add a flash game to my website?

**Comment by lexoyo** [comment]
1. Create an `assets/` folder in the same folder as your site's HTML page
2. Upload your flash file in this folder
3. Add this code to an "HTML box", but replace `game.swf` by the name of your flash file (be careful there are **2 occurrences of the flash file name**
```
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%">
<param name="movie" value="assets/game.swf">
<param name="quality" value="high">
<embed src="assets/game.swf" quality="high" 
	pluginspage="http://www.macromedia.com/go/getflashplayer" 
	type="application/x-shockwave-flash" width="100%" height="100%">
</embed>
</object>
```

Is this clear enough for you? Do not hesitate to ask for more details

**Comment by theycallmebacon1** [comment]
Thanks, it worked. Clear and consise

**Comment by theycallmebacon1** [comment]
Actually, after the game is on, i am unable to move it into a position i want. I also cant modify the HTML box's code. Is there a way I can turn the game off so I can rearrange its location and size

**Comment by lexoyo** [comment]
@theycallmebacon1 I changed my previous answer to make the flash anim draggable on the stage. Otherwise it was put over Silex's UI elements.

Fot that I have added the param `wmode` with value `transparent`.

**Comment by lexoyo** [comment]
And here is an example which works by me, with a sample swf of adobe (just copy/paste this to test)
```
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" height="100%" width="100%">
    <param name="movie" value="http://www.adobe.com/content/dotcom/en/devnet/actionscript/samples/drawing_5/_jcr_content/articlecontentAdobe/generic/file.res/5_3Drotation%5B1%5D.swf">
    <param name="quality" value="high">
    <embed wmode="transparent" src="http://www.adobe.com/content/dotcom/en/devnet/actionscript/samples/drawing_5/_jcr_content/articlecontentAdobe/generic/file.res/5_3Drotation%5B1%5D.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" height="100%" width="100%">
</object>
```
