### ISSUE TITLE
Bug External link

### ISSUE THREAD

**Issue by genma** [silexlabs/Silex#385]
In Silex interface, when you add an external link to a box via the "Properties" part.
When you type a link, link text is in white, on a white field, so it is not possible to read it. It is necessary to highlight it to check that the link has not been mistyped.

**Comment by lexoyo** [comment]
Thx for the bug report @genma !!
Fixed and should be in production in a few minutes
[The fix](https://github.com/silexlabs/Silex/commit/426e8c28f6c24e8e05075026206be8d3ab41789f) was simple
