### ISSUE TITLE
Silex with real time collaboration

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#389]
> this is a note about a test I just did

I made a test integrating [Mozilla TogetherJS](https://togetherjs.com/docs/) with Silex. This make it possible to invite other people and see their mouse over Silex UI to design together. You can [play with it here](http://silex-editor.herokuapp.com) (menu view > collaborate). And [see the code here](https://github.com/silexlabs/Silex/commit/8c710cbe21e35b146bb050d12e8b8867566e132f).

![screenshot from 2016-02-23 01-17-06](https://cloud.githubusercontent.com/assets/715377/13237285/35b1a8b6-d9cb-11e5-8f31-4b194785ae56.png)

It works well, and if I continue I would add this missing part: when a user changes something in the website or opens or undo/redo, the others should see it.

It is not a lot of work to finish this, but the problem is that the website needs to be shared among all the participating users. And also undo/redoo and changing page could be a big mess while editing a website collaboratively.

The challenge is about UX/user experience more than technical

**Comment by budislav** [comment]
This is awesome feature!
This mean all of participating users need to have access to dropbox files?

I think silex users should have some kind of profile. I imagine this like home page so we can see all project from that page, create new project, see a list of our friends (colleagues - they can edit) and users who just can see live project editing for many purpose (tutorials or presentation of work). 

If this Mozilla TogetherJS is open we can make this thing.
If profiles can be hosted on silex server that would be awesome.

So one person should create one project and others can just contribute and only owner have permissions to delete the project. Also if we want to see who made some changes we will need history side panel. 

I don't think that two person should work on same project in same moment. That would not be impossible and there is no need for that. I think there should be some order. For example if one person is working other person can just watch. Also if one person (owner of project) is offline others can work on project in that time.

Also this blue Mozilla TogetherJS side menu should be implemented into silex UI on other way definitely. If this is open we can make this on our way right?

I can make some UI proposals.

**Comment by lexoyo** [comment]
> This is awesome feature!
> This mean all of participating users need to have access to dropbox files?

If we want several people editing the site, yes they should all have access to the files, through Dropbox or FTP or the great services coming soon: github and owncloud and webdav 

> I think Silex users should have some kind of profile. I imagine this like home page so we can see all project from that page, create new project, see a list of our participating users and they are connected with project through mozilla togetherjs somehow. This "home page" don't need to be a page it can be side panel but I think new page will give us more space.

I thought about this, having a "silex" account/profile, but we could make it optional maybe? Silex is also about privacy...

To do that we should use mozilla persona, like the "open pages" service test I did, please [check the user experience here](http://silex-editor.herokuapp.com/), click on open and choose "open pages"

> One person should create one project and others can just contribute and only owner have permissions to delete the project. Also if we want to see who made some changes we will need history side panel.
> I don't think that two person should work on same project in same moment. That would not be impossible and there is no need for that. I think there should be some order. For example if one person is working other person can just watch, when that person is finished he or she need to press one button so other one can contribute (like toki woki). Also if one person (owner of project) is offline others from the list can work on project in that time.
> I would like to make some UI proposals.

Sounds good, but then it is a lot of work... how about we find a way to have contributors

> Also this blue Mozilla TogetherJS side menu should be implemented into silex UI on other way definitely. If this is open we can make this on our way right?

It is probably possible using TogetherJS API

**Comment by budislav** [comment]
> To do that we should use mozilla persona, like the "open pages" service test I did, please check the user experience here, click on open and choose "open pages"

Tried now and I like this mozilla persona but I think we really need to simplify the process from UX perspective. Can we rename this mozilla persona into silex account? We can write somewhere it is based on mozilla persona. I think it's little confusing and too much popups. I will make UI mockups.

>  how about we find a way to have contributors

I have nothing against but I can't imagine two person (or more) edits same text or page (anything) in exact same moment.

**Comment by budislav** [comment]
I don't see collaborate option from menu view. Is this option disabled?

**Comment by budislav** [comment]
> I thought about this, having a "silex" account/profile, but we could make it optional maybe?
I think it shouldn't be optional if they want to save the project and collaborate with others. If they just want to try it they don't need account.
It is not hard to make one account for this awesome tool and they would likely make one for Silex because they would probably come back again. Also we would know how many users use Silex and with this account they can send feedback and others things in future can be connected with account. Account is necessary I think.

**Comment by singchan** [comment]
togetherjs is dead now :(
