### ISSUE TITLE
Unable to build and run the project

### ISSUE THREAD

**Issue by webaddiction** [silexlabs/Silex#393]
> npm run build
> npm run build:css && npm run build:html && npm run build:js:release

> Silex@0.8.0 build:css C:\Users\User\Desktop\builder\Silex-master
> lessc src/css/_styles.less dist/client/css/admin.css --clean-css="--advanced"
--source-map

> Silex@0.8.0 build:html C:\Users\User\Desktop\builder\Silex-master
> jade src/html/index.jade --out dist/client/ --no-debug

  rendered dist\client\index.html

> Silex@0.8.0 build:js:release C:\Users\User\Desktop\builder\Silex-master
> java -jar node_modules/superstartup-closure-compiler/build/es6compiler.jar --j
s submodules/closure-library/closure/goog/ --js src/js/ --externs src/externs.js
 --js_output_file dist/client/js/admin.js --compilation_level ADVANCED_OPTIMIZAT
IONS --warning_level=VERBOSE --language_in ECMASCRIPT6_STRICT --language_out ECM
ASCRIPT3 --create_source_map dist/client/js/admin.js.map --closure_entry_point s
ilex.App --only_closure_dependencies --manage_closure_dependencies --define="goo
g.DEBUG=false"

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build:js:release"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build:js:release: `java -jar node_modules/superstartup-clos
ure-compiler/build/es6compiler.jar --js submodules/closure-library/closure/goog/
 --js src/js/ --externs src/externs.js --js_output_file dist/client/js/admin.js
--compilation_level ADVANCED_OPTIMIZATIONS --warning_level=VERBOSE --language_in
 ECMASCRIPT6_STRICT --language_out ECMASCRIPT3 --create_source_map dist/client/j
s/admin.js.map --closure_entry_point silex.App --only_closure_dependencies --man
age_closure_dependencies --define="goog.DEBUG=false"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Silex@0.8.0 build:js:release script 'java -jar node_modul
es/superstartup-closure-compiler/build/es6compiler.jar --js submodules/closure-l
ibrary/closure/goog/ --js src/js/ --externs src/externs.js --js_output_file dist
/client/js/admin.js --compilation_level ADVANCED_OPTIMIZATIONS --warning_level=V
ERBOSE --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT3 --create_sour
ce_map dist/client/js/admin.js.map --closure_entry_point silex.App --only_closur
e_dependencies --manage_closure_dependencies --define="goog.DEBUG=false"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     java -jar node_modules/superstartup-closure-compiler/build/es6compi
ler.jar --js submodules/closure-library/closure/goog/ --js src/js/ --externs src
/externs.js --js_output_file dist/client/js/admin.js --compilation_level ADVANCE
D_OPTIMIZATIONS --warning_level=VERBOSE --language_in ECMASCRIPT6_STRICT --langu
age_out ECMASCRIPT3 --create_source_map dist/client/js/admin.js.map --closure_en
try_point silex.App --only_closure_dependencies --manage_closure_dependencies --
define="goog.DEBUG=false"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\Desktop\builder\Silex-master\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build: `npm run build:css && npm run build:html && npm run
build:js:release `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Silex@0.8.0 build script 'npm run build:css && npm run bu
ild:html && npm run build:js:release '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:css && npm run build:html && npm run build:js:release

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\Desktop\builder\Silex-master\npm-debug.log

**Comment by lexoyo** [comment]
The error is 
`Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object`

Are you sure that java is correctly installed? What version of Java do you have?

**Comment by webaddiction** [comment]
yes , you point out correctly thanks ... i have solved the problem.
