### ISSUE TITLE
lost site after publishing. no backup option

### ISSUE THREAD

**Issue by jo549k** [silexlabs/Silex#395]
file>publish> select dropbox folder> publish again. 

after publishing facebook like button and facebook comments show a white space.

when i went back to silex and opened my site it only opens a black background with just the names of the tabs on the left panel but the area where the content is, there is nothing displayed.

**Comment by singchan** [comment]
Hello
Can you share your Dropbox folder with a.hoyau at im-paris.fr please?

**Comment by lexoyo** [comment]
Hello
Can you share your Dropbox folder with a.hoyau at im-paris.fr please?

**Comment by jo549k** [comment]
Ill share it in a bit.

**Comment by jo549k** [comment]
sorry in the share i mentioned that the file was the .html but it is not.
the correct file is index.html

**Comment by lexoyo** [comment]
Ok I see that Facebook has messed up the HTML page :(

I have cleaned up but then I see nothing in the pages... Did you have something else than Facebook on the pages?

**Comment by jo549k** [comment]
No I did not. That's the messed up part. Everything was fine including
Facebook. But after I published it it all happened. Would like the
published version? It's actually in the Dropbox under the the folder name
"new site"

**Comment by jo549k** [comment]
I also had a contact form from 123contactform.com

**Comment by lexoyo** [comment]
> No I did not. That's the messed up part. Everything was fine including Facebook. But after I published it it all happened. 
> Would like the published version? 
> It's actually in the Dropbox under the the folder name "new site"

ok i'll check that to see if I can revert the publish action

**Comment by jo549k** [comment]
Thank you very much. Do you work at Silex?

**Comment by lexoyo** [comment]
> Thank you very much. Do you work at Silex?

I'm a volunteer, I'm lead dev of Silex
So if you loose your site it is on me :(

**Comment by lexoyo** [comment]
Ok, I could get it back, see the `test-alex.html` in your dropbox folder
Please backup this site, double click on each image to put it back
Then backup again and try publish
Facebook is really messing up with the HTML, but it should work
I'll think of a way to embed it better

**Comment by jo549k** [comment]
Lol...... sorry bro. That won't happen. I'm positive.

**Comment by jo549k** [comment]
Hello. Where you able to fix it

**Comment by lexoyo** [comment]
Yes it is in your dropbox folder, the file named test-alex.html
Double click on each image to put it back

**Comment by jo549k** [comment]
Ok. Thanks. Do i owe you anything?

**Comment by lexoyo** [comment]
Hey thank you for asking!
You could share this with your friends if you want :)
https://www.linkedin.com/hp/update/6122824471804989443

**Comment by lexoyo** [comment]
And if you want to help the non profit organization develop free templates and documentation and mobile editor you can participate to the crowd funding campaign :)
http://crowdfunding.silex.me/
