### ISSUE TITLE
cant get image onto page from cloud explorer

### ISSUE THREAD

**Issue by accesbois** [silexlabs/Silex#397]
Bonjour, I cant get image onto page from cloud explorer,for both dropbox and ftp server (fastmail).

files are shown,but cant be dragged.

Thanks for any help.

**Comment by singchan** [comment]
Hello
There is a known bug in Cloud Explorer, it can't open files with extension
in uppercase, e.g. *.JPG instead of *.jpg

**Comment by accesbois** [comment]
thank you for the reply,I'm only just getting into all this.

**Comment by lexoyo** [comment]
Should I close this issue?

**Comment by accesbois** [comment]
Yes, issue resolu,merci bien,
 
--
simon low
simonlow@fastmail.fm
 
 
 
On Fri, 22 Apr 2016, at 12:11 AM, Alex Hoyau wrote:
> Should I close this issue?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/silexlabs/Silex/issues/397#issuecomment-213133980

**Comment by lexoyo** [comment]
Super, à bientôt ;)
