### ISSUE TITLE
create tables in Silex editor

### ISSUE THREAD

**Issue by sujitpatil123** [silexlabs/Silex#399]
Hello sir,
I want to add or create table row column structure like we create in word documents; but i did not find any option to create table in Silex editor. You given nice options like to add text,images but one step further I want to add Table(not html table) in my website.
Please give me any solution.
Thanks in advance...

**Comment by lexoyo** [comment]
Hi @sujitpatil123 

Very interesting question!

What I did last time I needed this was use an image, this was [here on silex website](http://www.silex.me/#silex). And also before this I had copy pasted [the table from wikipedia](https://en.wikipedia.org/wiki/Silex_website_builder#Features) and it worked but not great...

Otherwise there are tools like these maybe? 

Table generators
* http://www.tablesgenerator.com/html_tables
* http://www.rapidtables.com/web/tools/html-table-generator.htm
* http://html-tables.com/

Pricing table generators
* http://www.pricefish.com/

Let me know how it goes since this question will probably be useful to others

**Comment by sujitpatil123** [comment]
Hi,
Thanks for your prompt response and suggestions; but these Table 
generators tools making procedure lengthier to create website and also 
not providing table properties as I want.
I already tried,  creating table in word doc then copy and paste in 
Silex editor but this won't give exact table structure which i copied.
I thought there will be any feature in Silex editor for table.
Please provide a Table feature in Silex Editor; it will be more helpful 
to users like me.

Thanks & Regards,
Sujit Patil

**Comment by lexoyo** [comment]
I agree we should make a new type of element for tables
This is quite easy to do, so if someone know a little bit of javascript and want to contribute it I can help you

**Comment by lexoyo** [comment]
you can use [the new multicolumn section widget for this](https://github.com/silexlabs/Silex/issues/603)

**Comment by sidmint** [comment]
@lexoyo:
> What I did last time I needed this was use an image, this was [here on silex website](http://www.silex.me/#silex).

i may want to use this method for table but I've this concern of image display for different screen resolutions out there. How much is this a concern practically?

**Comment by sidmint** [comment]
As of now, I've made a table by joining multiple individual text elements. It works good this way with following limits:

- empty space at top and bottom of elements can't be reduced to make the table look slim across the rows.

- when the borders of two elements combine, it may give double lines or disturb the border decoration at times depending upon the difference in properties of the combining elements such as background colour. I dealt with this by removing the border of one the elements [removing bottom and right ones helped better].

**Comment by lexoyo** [comment]
Interesting thx @sidmint 
I believe tables are always complicated when it come to responsive
When you use text boxes it is probably easier to make them position automatic?
Another solution may be copy paste the table from a word document

**Comment by sidmint** [comment]
> When you use text boxes it is probably easier to make them position automatic?

I had arranged through 'absolute', tried automatic but it was alligning boxes in a single column and was not respecting my two/more column layout. That may still be doable via another container for each column, but I didn't try that.

**Comment by sidmint** [comment]
> Another solution may be copy paste the table from a word document

I wasn't able to do that, help requested. I'm selecting a table from odt/docx file and pasting it directly in Silex or in text box/container/html box but nothing is happening. I'm using LibreOffice and not MS Word.
