### ISSUE TITLE
Problem in adding a source code/ java code in siles

### ISSUE THREAD

**Issue by promarketer** [silexlabs/Silex#400]
Hi I am trying to add following code in the silex website i am creating

```
<div id="_TC_DOTD_BANNER"></div>
<script type="text/javascript">
 _TRIPLECLICKS_DOTD_BANNER_URL="http://www.tripleclicks.com/13591009/dotdBanner.php?curr=USD&view=S";
</script>
 <script type="text/javascript" src="http://www.tripleclicks.com/common/dotdBanner.js"></script>
```

when i enter this code in HTML box the image of the banner is not shown and the html box is empty.

but when i enter normal html banner code it shows the banner image

 i understand the first code contains java and sliex is compatible with java

 will you please help me in adding this code? I am not having basic knowledge of html/ java``

**Comment by promarketer** [comment]
"``<div id="_TC_DOTD_BANNER"></div>
> <script type="text/javascript">
> _TRIPLECLICKS_DOTD_BANNER_URL="http://www.tripleclicks.com/13591009/dotdBanner.php?curr=USD&view=S";
> </script>
> <script type="text/javascript" src="http://www.tripleclicks.com/common/dotdBanner.js"></script>"

**Comment by singchan** [comment]
Hi @promarketer 
Sorry for the delay :(
I tried and saw the ad only the first time I previewed the site
So I tried this code and it seems to work... Put this in your html box:
```html
<iframe frameborder="none" width="100%" height="100%" src="http://www.tripleclicks.com/13591009/dotdBanner.php?curr=USD&amp;view=S"></iframe>
```
See how I took the value of `_TRIPLECLICKS_DOTD_BANNER_URL` and put it in an iframe?

If you have questions, please ask :)
