### ISSUE TITLE
Error: I did not manage to save the file

### ISSUE THREAD

**Issue by virtualsamurai** [silexlabs/Silex#401]
I tried to save my project to dropbox but received the following error:

Error: I did not manage to save the file

**Comment by lexoyo** [comment]
Hello 
This is odd... Can you create folders or upload files?

**Comment by virtualsamurai** [comment]
I was able to create a dropbox folder, but not save my project to it

**Comment by virtualsamurai** [comment]
my bad. my drop box was at maximum storage quota.

**Comment by lexoyo** [comment]
oh ok 
it happened to me too recently :8ball:
