### ISSUE TITLE
Améliorations sidebar de droite PROPERTIES

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#410]
Je trouve qu'il y a trop d’espaces verticaux dans la sidebar de droite : obligé de scroller, il faudrait :
> avoir des onglets par exemple (je viens de voir cette discussion et le visuel est tip top https://github.com/silexlabs/Silex/issues/387). 
> mettre SEO à la fin
> regouper BG color + image
> avoir la fenêtre style CSS classes tout en haut (utilisée le plus souvent)

**Comment by lexoyo** [comment]
It should be fixed by now, can you confirm? thx
