### ISSUE TITLE
Améliorations fenêtre CSS editor 

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#411]
- avoir une fenêtre pour éditer CSS en grand / détacher la fenêtre (les lignes de codes sont longues et on ne voit pas grand-chose)
- gérer les styles : h1, h2… par exemple créer un h2 (taille, couleur, famille) et pouvoir attribuer ce même h2 à d’autres textes

**Comment by lexoyo** [comment]
this is solved by today's release
see the new inline text editor, the style editor, the font manager
and the [related docs](https://github.com/silexlabs/Silex/wiki/editor-ui#text-editor)
