### ISSUE TITLE
created webpage not opening

### ISSUE THREAD

**Issue by abhishek082007** [silexlabs/Silex#414]
I created a webpage using your framework and saved in dropbox, now I want to edit it its not opening again..

**Comment by lexoyo** [comment]
Hi
Is there an error message? 
You can share the folder with me on Dropbox (a.hoyau@
 At im-paris.fr)

**Comment by singchan** [comment]
any news?

**Comment by abhishek082007** [comment]
no error message, it just keeps loading

**Comment by lexoyo** [comment]
Hi,

I have received @abhishek082007 website by Dropbox. I do not have the assets, only the HTML page, but can open it in Firefox and Chrome:
![screenshot from 2016-05-13 10-43-35](https://cloud.githubusercontent.com/assets/715377/15242640/9bd49caa-18f7-11e6-85d8-387e9f2b9a22.png)

@abhishek082007 could you open the web developer console (https://developer.mozilla.org/en-US/docs/Tools/Web_Console) in Firefox or Chrome and see if there is something wrong when you open your site?

Also please note that your script lacks a `}` at the end:

![screenshot from 2016-05-13 10-49-12](https://cloud.githubusercontent.com/assets/715377/15242801/5cc40874-18f8-11e6-9f18-427d91c41e75.png)

Feel free to talk to me on the chat room we have just opened:
https://framateam.org/signup_user_complete/?id=x1ay4zdjdffh5j67xzkfsofpyw

**Comment by abhishek082007** [comment]
thanks for telling me, lemme try your sollution
