### ISSUE TITLE
website link incorrect

### ISSUE THREAD

**Issue by bodyguerdson** [silexlabs/Silex#418]
On the right hand side of the screen you can link what you have selected to either an external address or another page inside silex. If i select external link then i can type in an address like in my example: www.bodyguerdson.com yet if i click on said link after i put my website online and then click the link it tries to go to http://bodyguerdson.com/ptc/www.bodyguerdson.com (the site i have the link on is: www.bodyguerdson.com/ptc/) but if i type in www.bodyguerdson.com in my address i go to my website like normally since i have it up and running. What can I do?

Edit: I also made triple sure i have it spelled correctly in silex

**Comment by lexoyo** [comment]
hi
did you try with "http://" before "www.bodyguerdson.com"?

**Comment by bodyguerdson** [comment]
i don't think i have, i'll probably try tomorrow as i don't have time today and then i'll update this post
