### ISSUE TITLE
padding + resize = glups

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#420]
If i have padding on an element for example on a button:
`.button{ padding: 5px 15px;}`

 if i want to resize it with the mouse >> it scales ... glups

**Comment by lexoyo** [comment]
I am working on a brand new "Stage" component so I prefere not to spend time on this bug for now, and we will see if the new component is better at this
https://github.com/lexoyo/stage

**Comment by ceubri** [comment]
ok great

**Comment by lexoyo** [comment]
ca c'est fix depuis longtemps
