### ISSUE TITLE
erreur d'encodage de caractères lors de la publication

### ISSUE THREAD

**Issue by fecou** [silexlabs/Silex#421]
Lorsque je fais une publication, quel que soit le fichier de base, les fichiers css et js ne sont pas encodé en UTF-8. Du coup ils sont illisibles. Je n'arrive pas à trouver à quoi cela peut-être dû. J'ai essayé aussi sur editor.silex.me mais le résultat est le même...

**Comment by lexoyo** [comment]
salut 
on m'a justement rapporté ce bug ce matin, je vais m'y pencher. c'est étrange car je ne vois pas pourquoi ca a changé d'un coup... 

quand tu dis que tu as testé aussi sur editor.silex.me, tu as essayé ailleurs aussi ?

**Comment by lexoyo** [comment]
et tu es sur le http ou https de editor.silex.me ?

**Comment by fecou** [comment]
Salut,
J'ai testé à la fois en installant un éditeur en local et sur http://editor.silex.me/.
Merci de ton intérêt pour ma question.

**Comment by lexoyo** [comment]
J'a justei reporté un fix que j'avais fait sur la préprod (preprod.silex.me / branche develop) et là ca fonctionne, tu peux réessayer stp?
https://github.com/silexlabs/Silex/commit/3ab576b876dc498d0172e2d0bc23ad501524d01b

**Comment by fecou** [comment]
J'ai essayé depuis http://preprod.silex.me/, http://editor.silex.me/, et http://localhost:6805/ en effaçant les fichiers produits à chaque fois mais rien y fait. Toujours la même erreur d'encodage sur les js et les css.

**Comment by lexoyo** [comment]
ah... tu as vidé le cache du navigateur?

**Comment by fecou** [comment]
Merci! j'ai essayé en vidant le cache et en passant sur chrome (avant firefox). Sur http://editor.silex.me/, l'erreur persiste. Sur  http://preprod.silex.me/, le jquery est bon mais le script.js et hamburger.png sont manquants. Pour info dans mes publish settings, j'ai /api/1.0/ftp/exec/put//home/felixftp/public_html/silextest/test.

**Comment by lexoyo** [comment]
tu peux mettre le jquery généré sur http://gist.github.com/ stp?

**Comment by fecou** [comment]
Je t'ai envoyé un mail avec l'adresse du résultat...

**Comment by fecou** [comment]
Il semblerait qu'il y ait un bug avec la publication en ftp qui sera corrigé dans la prochaine version. En attendant la prochaine version, il est donc préférable d'utiliser dropbox.
Grand merci à Lexoyo.

**Comment by lexoyo** [comment]
Je viens de trouver un autre moyen de palier à ce bug en attendant correction:

> après publication, télécharger ces fichiers et les mettre dans le répertoire `js` du site publié, avec le meme nom: [jquery.js](http://www.silex.me/js/jquery.js), [jquery-ui.js](http://www.silex.me/js/jquery-ui.js), [pageable.js](http://www.silex.me/js/pageable.js), [front-end.js](http://www.silex.me/js/front-end.js), et pareil pour ces fichiers à mettre dans le répertoire `css`: [front-end.css](http://www.silex.me/css/front-end.css), [normalize.css](http://www.silex.me/css/normalize.css)

**Comment by fecou** [comment]
Bonjour,

En effet, ça marche comme ça. Le soucis c'est qu'à chaque publication,
il faut remettre les fichiers en place...
En attendant, je proposerai de participer modestement à votre crowfunding.
Merci.

Félix.

**Comment by lexoyo** [comment]
:+1: :crown:
