### ISSUE TITLE
a "crowdfund me!" button

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#429]
As suggested by @pierreozoux I have added a "crowdfund me!" button on editor.silex.me
https://github.com/silexlabs/Silex/pull/428

What do you think?
![screenshot from 2016-06-03 15-28-28](https://cloud.githubusercontent.com/assets/715377/15780015/dfdc7914-299f-11e6-9f19-9d29ecc1bd14.png)

**Comment by pierreozoux** [comment]
I was more seeing a ribbon like this: ![ribbon](https://camo.githubusercontent.com/52760788cde945287fbb584134c4cbc2bc36f904/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f77686974655f6666666666662e706e67)
But it is nice already :)

**Comment by lexoyo** [comment]
I have added a "contribute" button a while ago :)
