### ISSUE TITLE
Slideshow stops working after publishing

### ISSUE THREAD

**Issue by thomasak22** [silexlabs/Silex#435]
Hi, I used the Gallery and Slideshow widget (https://github.com/silexlabs/Silex/issues/272) to add a slideshow to my website.  This widget works fine when I'm previewing from the silex interface (View > Preview) but after publishing my site and opening the html file or loading onto the web, the slideshow doesn't go further than displaying the 'loading...' text.  Any help would be appreciated.

**Comment by lexoyo** [comment]
Hello 
Have you published it online si that I can see what happens?

**Comment by thomasak22** [comment]
Yes, www.monograph.co.za

Thanks!

**Comment by lexoyo** [comment]
@thomasak22 the following scripts and styles are missing
![screenshot from 2016-06-27 10-13-47](https://cloud.githubusercontent.com/assets/715377/16372977/f34bce06-3c4f-11e6-8a5b-5fac471709b7.png)

You should add them to `/js/` and `/css/` folders

I will change the widget's code so that it can be done automatically

**Comment by thomasak22** [comment]
Thanks, it worked! 

Do you perhaps know if there's a way to change the interval between images? 

And is it perhaps possible to click on the slideshow to manually go forward or backward?

One other issue I noticed was the flickr ID is displayed at the top left of the page when viewing on an iOS device. Is there a way to remove this?

Thanks again for the help!

![img_7596](https://cloud.githubusercontent.com/assets/16944764/16375871/e0c5b892-3c5d-11e6-8d1e-a437c545abf4.PNG)

**Comment by lexoyo** [comment]
> Thanks, it worked!

Great! I have changed the widget so that it works directly after publish: in #272 there is this code in head section:
```html
<script type="text/javascript" src="js/silex.jquery.flickr.js"></script>
<script type="text/javascript" src="js/jquery.fancybox.pack.js"></script>
<link rel="stylesheet" href="css/jquery.fancybox.css">
```

... instead of the `document.write` instructions

> Do you perhaps know if there's a way to change the interval between images?

Sure, you can change it in the code you have pasted in the JS editor
```
        function slideIt(jQuerySelector){
            $(jQuerySelector).find('ul > li:gt(0)').css('opacity', '0');
            setInterval(function() {
              $(jQuerySelector).find('ul > li:first')
                .fadeOut(1000) //  <=================== HERE IS THE DURATION OF THE TRANSITION IN MS
                .next()
                .css('opacity', '1')
                .fadeIn(1000) //  <=================== HERE IS THE DURATION OF THE TRANSITION IN MS
                .end()
                .appendTo($(jQuerySelector).find('ul'));
            },  10000); // <=================== HERE IS THE TIME BETWEEN SLIDES IN MS
        }
```

> And is it perhaps possible to click on the slideshow to manually go forward or backward?

Should be easy to do but I can't figure out how right now

> One other issue I noticed was the flickr ID is displayed at the top left of the page when viewing on an iOS device. Is there a way to remove this?

oups right... you can play with the code, change the `getPhotosetId` function. for example it could look into an array and return the pĥotoset ID corresponding to a page name, instead of assuming the page name is the ID... Tell me if you can not figure out how to do that and I will help

**Comment by thomasak22** [comment]
Hi, thanks so much for the help!

I changed the interval between images, thanks.

I unfortunately don't know how to change the getPhotosetID. Would you mind explaining how I go about changing this?

Also, when you get some free time, would you mind looking into adding a way to manually go forwards or backwards in the slideshow?

Thanks again for the help!

**Comment by lexoyo** [comment]
Hi

> I unfortunately don't know how to change the getPhotosetID. Would you mind explaining how I go about changing this?

if you have only one slide show, then replace this portion of code

```
function getPhotosetId(pageName){
    return pageName;
    //return albums[pageName] || albums['default'];
}
```

with this (`YOUR PHOTOSET ID` should be what your page name was)
```
function getPhotosetId(pageName){
    return "YOUR PHOTOSET ID";
    //return albums[pageName] || albums['default'];
}
```
Then you can name your page as you wish

> Also, when you get some free time, would you mind looking into adding a way to manually go forwards or backwards in the slideshow?

I will try to do that in the near future

You can use any other slide show by copy/pasting the slide show embed code into an html box

**Comment by lexoyo** [comment]
Ok I found a way
You can add this to your scripts (at the end or whereever
```
var jQuerySelector = $('.slideshow');
function nextImage() {
    $(jQuerySelector).find('ul > li:first')
        .fadeOut(1000)
        .next()
        .css('opacity', '1')
        .fadeIn(1000)
        .end()
        .appendTo($(jQuerySelector).find('ul'));
}
function prevImage() {
    $(jQuerySelector).find('ul > li:last')
        .prependTo($(jQuerySelector).find('ul'))
        .fadeIn(1000)
        .next()
        .css('opacity', '1')
        .fadeOut(1000)
        .end()

}
$('.next-button').click(nextImage);
$('.prev-button').click(prevImage());

```

then add the css class `next-button` to an element in Silex and  `prev-button` to another one. a click on these elements will switch to the next or previous images.
