### ISSUE TITLE
multilingual Silex websites

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#44]
I am considering different solutions for Internationalization of a Silex website, which should be investigated
- see this question http://stackoverflow.com/questions/21212321/best-communities-and-tools-for-internationalization-of-free-software
- http://en.wikipedia.org/wiki/XLIFF
- select "gettext" .po files from Dropbox
- mark text fields as translatable (will translate each p element of the text field)
- a widget to display the languages and load the needed files, and translate dynamically the website (jquery plugin)
- links
  - http://i18next.com/
  - http://www.poedit.net/screenshots.php
  - http://zanata.org/
  - http://stackoverflow.com/questions/7175597/internationalizaton-of-html-files
  - http://www.grails.org/plugin/i18n-gettext
  - http://slexaxton.github.io/Jed/
  - http://code.google.com/p/jquery-i18n-properties/
  - http://stackoverflow.com/questions/13895012/what-plugin-to-use-for-internationalization-with-jquery-mobile-and-requirejs
  - http://blogs.technet.com/b/port25/archive/2010/06/15/new-open-source-jquery-globalization-plugin-released.aspx

**Comment by singchan** [comment]
here is how other website builders do
http://www.websitebuilderexpert.com/how-to-build-a-multi-language-website/

**Comment by singchan** [comment]
I stumbled upon i18next lib again and saw this example of use with jquery
https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

We definitely could add a "language" panel in silex for text boxes:

* give a name to a text element, like "nav.home" in i18next example
* selection of a language => take the text from i18n resource object
* change the text of the text box => change the translation in the i18n resource object for the current language 
* save the website would save the i18n resource object in the page
* and maybe: publish the website => put it in a lang.json file

**Comment by lexoyo** [comment]
This might be better done by a website generator like jekyll
So I am not planning to do that soon
