### ISSUE TITLE
Start-up template ($18)

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#444]
• <a href="http://www.templamatic.com/templates/4411">Download</a>
• <a href="http://www.templamatic.com/templates/4411/preview">Preview</a>

Here is a single page "long scrolling" template, for a start-up or a new product launch or a landing page for your marketting campaigns. It is made with <a href="http://www.silex.me">Silex</a>, and can be hosted anywhere.

[![screenshot](https://cloud.githubusercontent.com/assets/6483546/17017250/e21a5706-4f32-11e6-8bec-e69497609082.jpg)](http://www.templamatic.com/templates/4411)

To make your own website based on this template, <a href="http://www.templamatic.com/templates/4411">download the archive here</a>, unzip and open the file editable.html with <a href="http://editor.silex.me">Silex editor</a> (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by lexoyo** [comment]
This template was hosted on templamatic
Does someone have the files?
