### ISSUE TITLE
unknown service home?

### ISSUE THREAD

**Issue by peaksurfer** [silexlabs/Silex#447]
I am trying to publish my site and getting 20 or 28 asset files to load but on the 21st it says "unknown service home" and quits the upload. How do I resolve this?

**Comment by lexoyo** [comment]
What is the service you use, Dropbox or FTP?

**Comment by peaksurfer** [comment]
FTP

**Comment by peaksurfer** [comment]
When I directed the path of publication to my dropbox I had no problems, 
but the files were just in my dropbox, not published. So I redirected 
the publication path to my site -- 
ftp://albertbates.cool/home/abcool/domains/albertbates.cool/public_html 
and it expected it mighty queue me for a password, but it started 
downloading, got 17 or so files in, and then came back with the "unknown 
service home." message.

**Comment by lexoyo** [comment]
oh ok
use the browse button on the right of the text field, do not enter the path by hand. when you click on ftp in the file browser you will be asked for the ftp password

**Comment by lexoyo** [comment]
is your problem solved?
