### ISSUE TITLE
Scroll to the top of the page when the user changes page

### ISSUE THREAD

**Issue by Tyrael84** [silexlabs/Silex#452]
How do I set it so every time a link is clicked it goes to the top of the new page? I have no anchors and don't care for them right now. I simply want every link to load at the top of the page. I don't need users to go back exactly to where they were when the click 'back' it's not important. 

Thanks.

**Comment by lexoyo** [comment]
Hi
As explained [here in the Silex+JS issue](https://github.com/silexlabs/Silex/issues/200) and with [help from this post](http://stackoverflow.com/questions/16475198/jquery-scrolltop-animation), I found that you can use the pageChanged event on the body and jquery animation to do that: add this code in the "script editor" (view menu)
```
$(function() {
  $('body').on('pageChanged', function (event, pageName) {
    var body = $("html, body");
    body.stop().animate({scrollTop:0}, '500', 'swing');
  });
});
```

**Comment by Tyrael84** [comment]
I tried searching but all the discussions made it hard to find a clear cut way to do it. Thank you very much! :)

**Comment by lexoyo** [comment]
:+1:
