### ISSUE TITLE
Change the font size for the Mobile edition 

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#454]
How can i have different font size in my desktop version and mobile version ?
I'd like to have a smaller font size for the mobile version and keep a bigger one for the desktop version

**Comment by lexoyo** [comment]
Hi @antosilex 
I will write a guide to add CSS rules on the mobile version only

**Comment by antosilex** [comment]
Could you give me some tips to try to write my own CSS which would work for the mobile version only ?

**Comment by lexoyo** [comment]
here is a rule to change texts in mobile version only
```
 @media (max-width: 480px) {
        p, h2 {
            text-align: justify;
            padding: 0 30px;
        }
    }
```

**Comment by antosilex** [comment]
Thanks 👍 
I used it for changing the font size and it works !! 😄 
     
@media (max-width: 480px) {
       h2 {
            font-size: 10px;
        }
    }

**Comment by lexoyo** [comment]
This is addressed by the style editor, which is live now on editor.silex.me
So I'll close this now

Any comment about this new release is welcome here #690
