### ISSUE TITLE
Silex hangs when configured file destination is unavailable

### ISSUE THREAD

**Issue by rpmzandwijk** [silexlabs/Silex#457]
I configured a WebDAV destination to save the site files to. However, this particular WebDAV destination is an OwnCloud WebDAV and somehow Silex can't cope with that.

Since Silex can't cope with it, every file action (open file, save file, file browser) hangs while the message 'Loading...' is showed. It is also impossible the reconfigure file destinations, due to the hang.

This is on OS X 10.11.6 with Safari 9.1.2.
![screen shot 2016-08-08 at 11 04 54](https://cloud.githubusercontent.com/assets/19532850/17474780/144dd77e-5d58-11e6-8339-93c265f25e00.png)

**Comment by lexoyo** [comment]
hi @rpmzandwijk 

this looks very much like a bug :(

1- to make silex stop trying to connect, simply open this URL: http://editor.silex.me/api/1.0/webdav/logout
2- to connect to owncloud, I put this url as the "host": `https://framadrive.org/remote.php/webdav/`, how does yours look like?

**Comment by rpmzandwijk** [comment]
@lexoyo, logging out with the URL you provided works. Thanks.

My host URL is looking the very same. It appears that it doesn't matter if the credentials are good or wrong. It just hangs.

I also ran a test with another OwnCloud provider. That connection just works. The provider which has the issue runs a slightly adopted version of OwnCloud. However, mounting it with WebDAV from within OS X also just works.

**Comment by lexoyo** [comment]
can you provide a link to the owncloud provider plz?

**Comment by rpmzandwijk** [comment]
Sure I can. I've sent you an email, with URL and credentials for an OwnCloud instance, so you can run tests by yourself.

**Comment by rpmzandwijk** [comment]
@lexoyo, WebDAV connections to OwnCloud seem to work right now. Did you guys fixed something? And do you still need the OwnCloud account I send you?

**Comment by lexoyo** [comment]
Hi @rpmzandwijk 
I did make a new release but I did not touch anything on the server side :-/
I did not try the account you made me yet, so I guess we should wait and see?
You did not change your browser or something?

**Comment by rpmzandwijk** [comment]
OS and browser versions are still the same. Also, TransIP (the OwnCloud provider) didn't change anything. I use the ExpanDrive tool to mount WebDAV as well and that tool isn't working with TransIP's OwnCloud either. Strange that Silex is working like a charm now, without any change.

**Comment by singchan** [comment]
:+1:
