### ISSUE TITLE
Silex template "Landing page with slideshow" (18$)

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#458]
## Silex template "Landing page with slideshow" (18$)

A landing page is used to capture user data, such as a name and email address. The purpose of the page is to collect information to and connect with prospects. 

This template is an ideal "lead capture" with **a form, a connection to google analytics, and a dynamic design to advertise what you’ll get in return for submitting your personal data**.

It is made with <a href="http://www.silex.me">Silex</a>, and can be hosted anywhere. It is **responsive to fit any screen size** with the maximum reach.

• <a href="http://www.templamatic.com/templates/4502">Download</a>
• <a href="http://www.templamatic.com/templates/4502/preview">Preview</a>

<a href="http://www.templamatic.com/templates/4502">
<img src="https://cloud.githubusercontent.com/assets/6483546/17512530/91ae74be-5e28-11e6-9e34-9c4166cac634.jpg">
</a>

This template is proposed by @ceubri, [freelance designer at your service for Silex related works](http://www.whynotprod.com/)

To make your own website based on this template, <a href="http://www.templamatic.com/templates/4502">download the archive here</a>, unzip and open the file editable.html with <a href="http://editor.silex.me">Silex editor</a> (online).

Then edit the texts, replace the images, change the links and publish your site (file menu, then "publish")

**Comment by TheVince** [comment]
I just purchased this template and there is no editable.html file could you provide the file for me please?

**Comment by ceubri** [comment]
Hello,
can you give me your email ?

**Comment by TheVince** [comment]
vicante23@gmail.com

**Comment by ceubri** [comment]
ok
