### ISSUE TITLE
dns problem

### ISSUE THREAD

**Issue by integralconsulto** [silexlabs/Silex#461]
I have a problem with my page that I cant solve. 
I made my web with silex, it was working great but when my host provider change the dns and i migrate to the news I cant sing in the silex manager and i cant modify my web because I am using the WYSIWYG editor. Is there something that i have to change when i change my dns? thanks

**Comment by singchan** [comment]
Hello
You were using Silex with FTP?
Can you give more info about thé DNS change please?

**Comment by integralconsulto** [comment]
Hello singchan, thanks for your answer, I will tell you more about my problem, I use WYSIWYG editor by silex for make my web, Im not a web expert, it was working OK but my host provider tell me that I have to migrate to the news dns; 
ns1.midnsargentina.com
ns2.midnsargentina.com
when I migrate i cant use my silex editor because i cant log in, i send a picture of my loggin page.
![web](https://cloud.githubusercontent.com/assets/21038727/17666375/5506aa9c-62d6-11e6-825b-0ee020dca6d2.png)

**Comment by singchan** [comment]
I do not see why you could not login after this change. Can you send me the URL of your admin?

Also, this is a very old version of Silex (v1), the new version (v2) is here: www.silex.me
Unfortunately the two versions are not compatible (you can not open a website made with v1 in the v2)

**Comment by integralconsulto** [comment]
yes of course, the first is for modify directly the web and the second is the silex manager.
http://www.integralconsultores.com.ar/?/enterprise&autologin=1#/index.html/home
http://integralconsultores.com.ar/silex/?/manager#/start/login.flag
do you need my user and pass? 
when i enter in cpanel public_html/silex/conf/pass.php i have this,
<?php
$authentication['LOGINS']['rodrigo'] = '0ad54e429b2b6238550f24701541130b978e4640';
$authentication['LOGINS']['gabriel'] = 'd4baf648630b37de3a4ffb282f25a40e511d1e47';
?>

**Comment by singchan** [comment]
very nice website, congratulations :)
you can try to delete `public_html/silex/conf/pass.php`, then it will ask you for a new pass

**Comment by integralconsulto** [comment]
thanks for your answer and for your patience, i did what you told me, and the sistem ask me for a new pass. when i change it, i have the same problem, i cant login. maybe the problem is in other file like 
admin_config.ini, default_website_conf.txt, index.php, log.ini, plugins_server.php,silex.ini silex_server.ini.
thanks again!

**Comment by singchan** [comment]
Hi
I found this exception in response to the request when I try to login:
```
<pre>uncaught exception: <b>Non-static method AMFException::throwException() should not be called statically (errno: 2048) in /home/integralconsulto/public_html/silex/cgi/amf-core/app/php5Executive.php at line #76Non-static method AMFException::throwException() should not be called statically</b><br /><br />in file: /home/integralconsulto/public_html/silex/cgi/amf-core/app/php5Executive.php line 76<br />#0 /home/integralconsulto/public_html/silex/cgi/amf-core/app/php5Executive.php(76): _hx_error_handler(2048, 'Non-static meth...', '/home/integralc...', 76, Array)
#1 /home/integralconsulto/public_html/silex/cgi/amf-core/app/php5Executive.php(76): AMFException::throwException()
#2 /home/integralconsulto/public_html/silex/cgi/amf-core/app/Actions.php(216): Executive::doMethodCall(Object(AMFBody), Object(data_exchange), '_authenticate', Array)
#3 /home/integralconsulto/public_html/silex/cgi/amf-core/app/Filters.php(115): securityAction(Object(AMFBody))
#4 /home/integralconsulto/public_html/silex/cgi/amf-core/app/Gateway.php(170): batchProcessFilter(Object(AMFObject))
#5 /home/integralconsulto/public_html/silex/cgi/gateway.php(176): Gateway->service()
#6 {main}</pre>
```
maybe the php version has changed? There was a "check install" page somewhere I remember, do you know about it?

I'm sorry, but this is an old version of Silex... Maybe you should start from scratch with Silex v2, it is even easier than the v1

**Comment by integralconsulto** [comment]
Singchan thanks for your time! 
I will ask to my host provider if there any change in the php version, I dont remember the check install page, sorry. I think i will follow your advice and start from scratch with silex v2.
Thanks again for your time.

**Comment by singchan** [comment]
:+1:
