### ISSUE TITLE
Not really ftp compatible?

### ISSUE THREAD

**Issue by Valyre** [silexlabs/Silex#470]
When I try to open my saved file in a new session to further edit my website, I get stuck on "Loading..." while it tries to access my ftp.  I have to clear my browser history (cookies) and reenter my ftp information for it to work.  Once I have access to my files, I open my saved file (the one with all of the editing info, not my published version).  The very first graphic will load and the rest of the graphics on every page will come back "broken" even though nothing has moved on my server.

I'm not sure what to do differently.  I need to be able to edit my website.

**Comment by lexoyo** [comment]
hello, can you provide a link to the broken version please?

**Comment by lexoyo** [comment]
@Valyre do you need help?

**Comment by Valyre** [comment]
Here is a link to my saved version, not my public version:  http://www.facepullctr.com/_old/Temp2/

**Comment by lexoyo** [comment]
hmm I see all the images there :-/

**Comment by lexoyo** [comment]
So you managed to get it working right?

**Comment by paulbrowncod** [comment]
Hi.  I too am having this same problem.  When i try and revisit my site it gets stuck on loading.   i have to clear cookies and cache for it to work.  I am also having problems when i click on preview ... it just states loading then "proxy error".  Any ideas please??

**Comment by singchan** [comment]
hello, can you provide links please?

**Comment by singchan** [comment]
and details on your browsers also

**Comment by paulbrowncod** [comment]
Hi.

 

I have only just started building my site.

 

It can be found here http://www.lrcpipeband.co.uk/NEW2016/new%20Web%20Site.html#!page-home

 

The problems are:

 

When ever i click preview it crashes and just says Loading

 

I sometime struggle to save it

 

And every time i log in i have to clear cookies and cache, or it will just crash on loading.

 

I am using google chrome, but have also tried Microsoft edge.

 

Many Thanks

 

 

Paul

**Comment by lexoyo** [comment]
Hi @paulbrowncod 
This is not at all what it is supposed to do. Can you try with firefox?
And is it the latest version of chrome? I suppose you are using windows, which version please?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
