### ISSUE TITLE
Probleme de centrage de site

### ISSUE THREAD

**Issue by jtrland** [silexlabs/Silex#471]
Bonjour à tous,

je sais que le problème a déjà été abordé à différents endroits mais malgré les infos que j'ai pu trouver j'ai toujours des soucis!
Mon but: centrer mon site! 
Je suis sur un site de type vitrine de 5 pages mais je n'ai pas gardé le container par defaut lors de la création. Il y a donc un container par page. 
J'aimerai donc que chaque page soit centrée dès lors que la résolution en largeur (1366px) est dépassée.

j'ai donc essayé sur le css du container:

margin: auto;

mais ça ne fonctionne pas

Merci de votre aide!

[index.txt](https://github.com/silexlabs/Silex/files/455409/index.txt)

**Comment by lexoyo** [comment]
ah c'est intéressant, tu te passes du container principal? je me demandais si ca se faisait ou pas..
en fait pour centrer un container comme le container principal tu as 2 options
* mettre dessus la class css `background` (tu vois comment faire?)
* appliquer les memes styles que sur le container principal : 
```css
.background-bis {
position: relative !important;
left: 0;
top: 0;
margin-left: auto;
margin-right: auto;
z-index: 1;
}
```

La différence c'est que dans le 1er cas, ton container devient "spécial" pour silex, et tu ne peux plus le supprimer ni changer sa visibilité et je ne sais plus trop quoi d'autre

**Comment by jtrland** [comment]
Super! Ca fonctionne! J'ai utilisé ta deuxième solution. 

C'est justement pour éviter le coté "spécial" du container par défaut que je ne l'utilise pas. Je ne sais pas si c'est judicieux mais comme je voulais des hauteurs de pages différentes j'ai crée un contenair par page en background. J'imagine qu'il existe d'autres moyens mais bon, je suis en mode noob ;-))

En tous les cas merci beaucoup!!

**Comment by lexoyo** [comment]
> J'imagine qu'il existe d'autres moyens mais bon, je suis en mode noob ;-))

en fait non, et j'ai vu que @Stuff31 fait ca dans ses sites, donc je vais coder une version "automatique" de cette méthode :)

well done pour un noob :+1:

**Comment by antosilex** [comment]
trop cool ça fait 2 ans que j'essaye de faire des pages de taille différentes avec silex et y'avait tjs un souci, je viens de tester le background bis c'est de la baaaaaalllle
merci les gars :+1:

**Comment by lexoyo** [comment]
haha :dancers:
