### ISSUE TITLE
Image Docker

### ISSUE THREAD

**Issue by jtrland** [silexlabs/Silex#475]
Bonjour,

je voulais utiliser Silex avec Docker (problème de disponibilité/stabilité adsl, et oui.....:-( ) mais l'image à disposition n'est pas la même version que celle qui est accessible en ligne. Existe-t-il une version de l'image Silex pour Docker à jour?

Merci pour votre aide.

**Comment by lexoyo** [comment]
Bonjour
Utiliser Silex en local c'est une bonne idée :+1: 
Je pense que tu peux cloner le repo Silex et créer l'image docker à partir de là:
```sh
$ git clone  --recursive git@github.com:silexlabs/Silex.git # ou git clone  --recursive https://github.com/silexlabs/Silex.git
$ cd Silex
$ docker build .
```
Après ca tu devrais avoir l'image prête à l'emploi... C'est pas du super testé mais je viens de le faire et ca a marché chez moi :)

**Comment by jtrland** [comment]
rrooooooohhh la la la ça fonctionne nickel!!!

Encore une fois, un ÉNORME merci à toi pour tes solutions efficaces et ta disponibilité!!

....j'ai encore une question: comment puis-je être au courant des nouvelles version online pour que je puisse mettre à jour mon image docker en suivant?

**Comment by lexoyo** [comment]
haha de rien! c'est sympa d'avoir des retours et des gens aventureux qui testent des trucs

> comment puis-je être au courant des nouvelles version online pour que je puisse mettre à jour mon image docker en suivant?

j'essayais de maintenir [le change log de silex](https://github.com/silexlabs/Silex/blob/master/docs/change-log.md) mais c'est plus trop ca... 

le mieux c'est de clicker sur "suivre" en haut de la page, tu recevras des notifs quand on fait des pull request et qu'on ajoute du code... sur master c'est la version stable et sur develop le dev en cours

tu peux aussi vérifier la date des [commit sur master](https://github.com/silexlabs/Silex/commits/master)

**Comment by jtrland** [comment]
Ok c'est bien noté!

Merci encore.
