### ISSUE TITLE
Feature: offer free photos in Silex? what do you think?

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#477]
Hello,

Do you know [Unsplash](https://unsplash.com/)? It is a bank of "Free (do whatever you want) high-resolution photos."

They have an api and it is really simple to do searches programmatically, so we could add a way to search and insert images in Silex, like they have in Wix and other website builders, or in [Froont](http://froont.com/) which is a website builder who uses unsplash...

![screenshot from 2016-09-08 15-44-27](https://cloud.githubusercontent.com/assets/715377/18351604/3057bf66-75db-11e6-9919-adf8c8f991f5.png)

What do you think about it, is it a must have or a nice to have? 

Does it conflict with the free software spirit (the service is closed source, but the pics are creative commons)?

Are there other services like these to do the same?

How would you integrate it in Silex?

Links:
- [request to search for "silex" with unsplash api](https://api.unsplash.com/photos/search?page=1&client_id=702a299decf22f4e7048227b8287c8345aaac9c412ec706270eca0298284d803&query=Silex)
- related issue: [Help fund this feature: fonts in Silex](https://github.com/silexlabs/Silex/issues/154)

**Comment by JbIPS** [comment]
I like the idea! This one step forward to have a full Integrated Prototype Environment (a.k.a. IPE)

**Comment by ceubri** [comment]
Cool !
there is also https://visualhunt.com
Left sidebar seems to be a good idea.

**Comment by lexoyo** [comment]
Unfortunately visualhunt has no API for developers ...

**Comment by felixgouin** [comment]
it's an really nice idea ! 👍 💯

**Comment by lexoyo** [comment]
I had another thought about this

Just like we did with cloud explorer, a separate project to manage files from cloud storage, for silex or other uses, we should create a separate project to import media from
* unsplash or alternatives (flicker, wikimedia...)
* Youtube or alternatives (vimeo, framatube...)
* slideshare or alternatives

This would be a dialog you can import in any app, to find and import media from these sources. The API could be like this
* selectMedia() => FileInfo
* getEmbed(fileInfo) => HTML

Useful links
* https://www.npmjs.com/package/simple-media-manager
 * [framatube api](https://framagit.org/RyDroid/framatube/blob/master/doc/dev/api.rst)

**Comment by lexoyo** [comment]
Hi guys
I am back to this feature. And I found several alternatives to unsplash such as pixabay.com. So I think I will add a way to add image banks in CE2

On the server side, I will probably add a method `addImageBank(name, callback)` on CE2 router. For example, with unsplash it would be used like this:

```js
ceRouter.addImageBank('unsplash', (query) => request(`https://api.unsplash.com/photos/search?client_id=vnasoinjofne&query=${query}`))
```
Concerning the UI, I need to do this when CE2 is opened to select an **image**:

* [ ] display buttons or tabs to switch from the "Your files" view to the available image banks: `Your Files | Unsplash Photos |  ...`
* [ ] add a search box which will refresh the file "while you type"
* [ ] download button stays, delete and rename do not
* [ ] the button bar should be removed (refresh, new folder, list/icons view)
* [ ] unlike the normal files view, there is no need to select a files so should I keep the double click to select or switch to single click?
* [ ] bonus: pagination (load when scroll)

I have no idea how to design this for now :)
cc @suddenheroes @ceubri

**Comment by JbIPS** [comment]
Can't help with the design but look out for license! Unsplash images are often CC-By, which means you have to name the author.

Maybe create a small text box under the image with the name (if provided by the API)

**Comment by lexoyo** [comment]
Yes that is right @JbIPS 
Also we are supposed to notify them when the user chooses an image :-/


> Maybe create a small text box under the image with the name (if provided by the API)

I return this info from CE but what now in silex what to do with it
Remember that the user may be importing a background image or an image inside a text box, or any other image in a component

**Comment by JbIPS** [comment]
Is it possible to have a dynamic footer with all the credits? 

Or, CE2 shows a warning about CC-BY and let the user do WTF they want. The least we have to do is to inform the user.

**Comment by lexoyo** [comment]
> Is it possible to have a dynamic footer with all the credits?
> Or, CE2 shows a warning about CC-BY and let the user do WTF they want. The least we have to do is to inform the user.

nice ideas !!! that were exactly what i was thinking about :)
i guess the footer could be a component... 
but the message is really the best option according to me, with an option to copy the attribution, and event a "Add in a text box" button?

**Comment by lexoyo** [comment]
any idea on this @ceubri ?

**Comment by ceubri** [comment]
Credit is often in a subfooter (a line under the footer).
It'll be cool to have the possibility to replace a photo...

**Comment by ceubri** [comment]
and pexel is also great for photos https://www.pexels.com/api/

**Comment by lexoyo** [comment]
ok @ceubri thx
pexels should be easy to add now... and wow it is very nice !!

**Comment by lexoyo** [comment]
this is live on preprod.silex.me
feedbacks welcome !
cc @ceubri @felixgouin @baguetteagile @clemos

**Comment by ceubri** [comment]
**Oh yeah ! cool.**
2 comments : 
- when i add an image there is no property to edit it, ie keep proportional (only for BG images), the only thinks i can do is double click to reload permute. 
![BG-images](https://user-images.githubusercontent.com/7302680/68190990-cbcb4700-ffae-11e9-9505-2a9cb9273058.JPG)
- when i select a new photo (on an image or bg image container) it will be nice to keep the same size of the previous image / container....

I see you made some new components, well done !
