### ISSUE TITLE
flexbox / responsive / fluid layouts

### ISSUE THREAD

**Issue by devoldski** [silexlabs/Silex#481]
Hi 

Im trying to set up a silex site which is responsive and following mobile first design. I find it a bit hard to define non-fixed layouts. I manage to do CSS tweaks for width and text using % and ems, however i find it hard to build nested fluid divs that is not using pixel based heights. 

in example how can I set up a simple flexbox layout in silex?

I would appreceiate some info or a simple example on how this can be done.

Br
devoldski

**Comment by lexoyo** [comment]
Hello

You have examples here
http://templates.silex.me/

And I believe that the way to go with Silex, is to make the desktop version first, then customize the mobile version. But there might be other ways...

In desktop version, everything is fixed / absolute / px, and in mobile version it goes positioned / relative / %

I am in the process of developing a new element type which is positioned even in desktop version, but it will contain absolute elements

**Comment by devoldski** [comment]
Ok Thank you, i have downloaded the templates, and will look into it. Thank you!

**Comment by lexoyo** [comment]
:+1: feel free to reopen the issue if needed
