### ISSUE TITLE
What can be the reason why I can not print my page, only half of it?

### ISSUE THREAD

**Issue by Fieroman** [silexlabs/Silex#483]
I just started learning the Silex editor and made a nice page with it but now I´m baffled with a strange printing problem?
The page would fit nicely to 2 full A4 pages when printed but when I press "print" on the browser and look at the view, it only shows me about 45% of the first part of my web page. 
Ie. the first page is displayed almost correctly but the next page is completely white and the about 55% of my whole web page material is missing ? The page 2 does print out, but it comes out as white page, only the www address on the bottom?

IF: I change the printing size to be only 10% in the browsers printing properties, then the whole web page is actually printed on one A4 but it is so small on one A4 paper that the text can not be read.

I have used other editors and done html pages but never had an issue like this ?

Any help would be highly appreciated.

**Comment by lexoyo** [comment]
Hello

I have tried to print this website and it worked :-/
http://templates.silex.me/templates/fictional-studio/index.html

Can you provide a link to the website? Also tell me which browser and OS you have...

**Comment by RayPylant** [comment]
i have also tried  this link [](http://templates.silex.me/templates/fictional-studio/index.html) and it works real good

**Comment by lexoyo** [comment]
Can you provide a link to the website? Also tell me which browser and OS you have...

**Comment by RayPylant** [comment]
it works just have to be patient it will load. us humans have low patients to some things.

**Comment by lexoyo** [comment]
:+1:

**Comment by Fieroman** [comment]
Dear Alex

Unfortunately I have been really sick (hospitalized) so I was unable to see
these messages. Now I´m getting back to normal rhytm...   :)

Anyway, the problems seems to be only in Firefox browser. The multiple
pages long page prints normally on all other tested browsers. In Firefox
the page ends to the first page beeing printed and then there is nothing at
the page 2. If the "fit page" option is used and I scale the page to 10%
size of original - then it will print the whole page om one paper but so
small that it can not be read ?

BR.  Mika - Finland




2016-09-25 18:26 GMT+03:00 Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
ok thank you for the details
