### ISSUE TITLE
new UI design for Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#485]
Hello
I have been working on the UI of Silex recently, what do you think?
http://preprod.silex.me/

**Comment by pierreozoux** [comment]
There was a not related popup right away (top right)

But yes, it looks nicer :)

Good job!

**Comment by lexoyo** [comment]
> There was a not related popup right away (top right)

fixed thanks
will be online shortly

**Comment by AndreaMonzini** [comment]
For me it seems a great work about a more clear organization of the elements.

**Comment by lexoyo** [comment]
ladies and gentlemen, the new UI is live! :dango: 
http://editor.silex.me/

**Comment by pierreozoux** [comment]
\o/

**Comment by lexoyo** [comment]
I've also added the page name in the context menu [on preprod](http://preprod.silex.me/), see [the code changes here](https://github.com/silexlabs/Silex/pull/495)
