### ISSUE TITLE
Bugs with Silex new version

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#490]
When i open my existing file with Silex i have a lot of problem with the Z index.
Several elements desepears behind the main container, even after clicking on the "bring forward"  button.

The size of some elements also changed.

I also have a problem with the video in the HTML Box, the size of the video is not the same and when i try to do it again and change the height and width by 100% it doesn't work anymore (cf picture attached)

![capture d ecran 2016-09-28 a 19 46 36](https://cloud.githubusercontent.com/assets/6757106/18925468/699e01ac-85b4-11e6-8d32-e1fa2ef62d98.png)

**Comment by lexoyo** [comment]
Can you share a link plz?

**Comment by antosilex** [comment]
Done on your intmdia address (dropbox sharing)

**Comment by lexoyo** [comment]
> Several elements desepears behind the main container, even after clicking on the "bring forward" button.

I do not see that, can you tell me more?

> The size of some elements also changed.

I do not see that, can you tell me more?

> I also have a problem with the video in the HTML Box, the size of the video is not the same and when i try to do it again and change the height and width by 100% it doesn't work anymore (cf picture attached)

there is a bug with iframes which have 100% height, I will fix it
meanwhile you can set a height on the iframe (`<iframe height="300"` instead of `<iframe height="100%"`)

> Done on your intmdia address (dropbox sharing)

feel free to use netlify to make it easier

**Comment by myke4416** [comment]
* Several elements desepears behind the main container, even after clicking on the "bring forward" button.
    I see this happening at editor.silex.me  - starting with 'new website' and add a container ... I can drag the new container around on the screen, but if I resize it... it drop behind the Container created as 'New Website' with the Powered by Silex' logo at the bottom.   Also, what I noticed is that if I create the Containers - placing one over the other...it works as it should....

**Comment by lexoyo** [comment]
oh ok, I can reproduce :(
will fix this today
thank you

**Comment by lexoyo** [comment]
thank you so much for the bug report, I fixed it ([this code changed](https://github.com/lexoyo/Silex/commit/2c358cf2c75283c744d8cdbb07a76be995908fad)) and it is live on editor.silex.me

please confirm that your issues are fixed?

**Comment by myke4416** [comment]
Man YOU ARE AWESOME !! THANKS!

**Comment by antosilex** [comment]
Sorry but for me it's worse, when i open existing Silex website i can't see a lot of existing elements.
I shared you the files with dropbox (the one i already sent you is also "broken")

**Comment by antosilex** [comment]
Sorry it was on chrome only, on firefox everything seems to be OK (except the Html 100%), but i guess it would be nicer if it works on chrome.
I noticed also that when i add an element it appears at position (100;100)  but from the background corner (before it was (100;100) in the meta container), on both Firefox and Chrome.

**Comment by lexoyo** [comment]
@antosilex I can not reproduce your bugs, I tried in firefox and chrome and it does the same thing
did your reload silex and try again? maybe emty your cache?
what is your version of firefox?

**Comment by coph** [comment]
I have the same issue on Chrome and Firefox (with a cleaned cache) - "Several elements desepears behind the main container, even after clicking on the "bring forward" button." - And cannot select them.

**Comment by antosilex** [comment]
Indeed i was using Chrome (49.0) and Firefox (48.0.2) latest downloadable versions on my OS 10.7.5  :/
Now i will use Silex only on my laptop with ubuntu ;)

There is still the Html box bug and the new elements position even on ubuntu

**Comment by antosilex** [comment]
When i resize the "metacontainer" width  the X value is changing and when i change the value nothing is happening, it's not really a problem to work but i think the metacontainer's X and Y values should stay at "0" or "-" isn't it ?

![capture du 2016-10-04 20 20 59](https://cloud.githubusercontent.com/assets/6757106/19086852/21b73c12-8a70-11e6-8179-c6ea4ae1a212.png)
![capture du 2016-10-04 20 20 41](https://cloud.githubusercontent.com/assets/6757106/19086853/21be4908-8a70-11e6-8919-2de595d33b45.png)

**Comment by antosilex** [comment]
Hey it's me again ;)
As you can see there is also a problem with the metacontainer's Height and Width values (Position and size)
When i open a new website the values are W:0 and H:100 but the true values are W:960 and H:600
When i change the value the W is ok but the H is not exact it add automatically 50px without changing the value, and each time i select the metacontainer the H value is back to 100 without changing the value

**Comment by lexoyo** [comment]
> When i resize the "metacontainer" width the X value is changing and when i change the value nothing is happening, it's not really a problem to work but i think the metacontainer's X and Y values should stay at "0" or "-" isn't it ?

This I reproduce so I will fix this minor bug soon, thx

**Comment by coph** [comment]
On the right hand side ,'**Visible on**' menu is showing a maximum of 11 values (including 'all pages' choice). If more pages configured than this, it's hard to make choice without reordering pages. 

![image](https://cloud.githubusercontent.com/assets/22616906/19131421/5cdb1810-8b1d-11e6-8d79-b59d65cfc84d.png)

**Comment by lexoyo** [comment]
fixed and released online (preprod and editor.silex.me)
see [the code changed here](https://github.com/silexlabs/Silex/commit/1cfc148652168c56b0a4b21bdd09f033263333e8)

**Comment by coph** [comment]
I have the problem mentionned by autosilex _"Sorry but for me it's worse, when i open existing Silex website i can't see a lot of existing elements.I shared you the files with dropbox (the one i already sent you is also "broken")" 

How can I share a dropbox with developer only ?

**Comment by lexoyo** [comment]
> How can I share a dropbox with developer only ?

the easiest way is to put your site with the bug online, with https://www.netlify.com/
and give me the adress so that I can check

**Comment by lexoyo** [comment]
@antosilex the issues you reported should be fixed on http://preprod.silex.me
Please check and open separate issue for each remaining issue
I have fixed the height of the sections and now force https to prevent firefox's "blocked suspicious URL" which breaks the "save" of a website on windows
Also I have added a "loader" for a better look & feel when Silex starts
[The change log is here](https://github.com/silexlabs/Silex/pull/497/commits)
@all please test http://preprod.silex.me and if it looks good to you I will push to editor.silex.me

**Comment by lamynes** [comment]
Using https://editor.silex.me/

I am not able to open the site I created using the editor above,

Loaded on https://lamynes.github.io/silexvette/

Works, just can't reopen.

Thank you

**Comment by lexoyo** [comment]
@lamynes I answered your question on your other issue #520
