### ISSUE TITLE
LLN, a new website made with Silex

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#493]
[Here is a minimalist and elegant 1 page website](http://chesslln.be/) by @Hildepont for a chess players community.

<a href="http://chesslln.be/"><img src="https://cloud.githubusercontent.com/assets/6483546/19040769/c673fdb2-8985-11e6-8f1f-5f1e8e63d9e3.png"/></a>

It is made with [Silex website builder](http://www.silex.me) with [this template](http://templates.silex.me/templates/perso2/index.html) by @lexoyo and with the widget provided by [open street map](http://www.openstreetmap.org/)

**Comment by lexoyo** [comment]
@Hildepont your website seem down?

**Comment by Hildepont** [comment]
thank you for notifying me ! I fixed that…

**Comment by lexoyo** [comment]
you can use [Monitoshi](http://lexoyo.me/monitoshi-website/) to get notified by email when your site is down

**Comment by lexoyo** [comment]
The website seems down? Feel free to reopen the issue if it comes back up
