### ISSUE TITLE
Fonts not displaying if not installed on computer

### ISSUE THREAD

**Issue by pl3bbles** [silexlabs/Silex#499]
I have recently created a website using Silex.me, and in the editor I am using the default font (Abel, san serif) but after publishing the website and viewing it by opening the published website from my dropbox (DB) all the fonts default to Arial. I was able to fix the problem by installing Abel on my computer but my question is; because it is failing to import the font, will any computer that doesn't have the font installed not correctly display the font? 
I also have some additional issues with the editor, but I have summarized below all the issues I am having.

Summary:
- Font used in editor not showing up in published website because font is not installed on computer
- installing font on viewing computer fixed issue, but fonts should be importing from google fonts regardless
- tested by loading the published website from DB on multiple computers
- concerns that anyone viewing website without font installed will be displayed website with incorrect fonts
- wondering if this will fix itself when hosting from a server, or whether I need to fix something in the website's files / code to help it import / display the font properly.

Additional Concerns:
- Website takes 1 - 2 minutes to load, but that may be because I'm loading it from DB or because it is trying and failing to import fonts repeatedly. This is major issue if not caused by slow DB servers.
- Also in editor it refuses to let me change the font from Abel when editing text boxes and other elements, meaning if this issue is not solved I can't adjust my website to suit a font that is installed on most machines by default.

Cheers, Adam

**Comment by lexoyo** [comment]
Hi Adam

Why do you say that Abel is the default font? I see `font-family: sans-serif;` by default in text boxes...

Also what do you mean by "viewing it by opening the published website from my dropbox (DB)". You open it by double clicking on the html file in your local file explorer?

In case this is useful to you, [here is how to import fonts from google fonts](https://github.com/silexlabs/Silex/issues/46). Please note that google fonts are used by google to track you and your users.

> Website takes 1 - 2 minutes to load, but that may be because I'm loading it from DB or because it is trying and failing to import fonts repeatedly. This is major issue if not caused by slow DB servers.

this is of course not the case when you load from a "normal" host, try [netlify](https://www.netlify.com/) for free (see instructions in silex wiki or ask here if you need)

**Comment by lexoyo** [comment]
hello?

> Why do you say that Abel is the default font? I see font-family: sans-serif; by default in text boxes...
> Also what do you mean by "viewing it by opening the published website from my dropbox (DB)". You open it by double clicking on the html file in your local file explorer?
