### ISSUE TITLE
Bug Silexnew version : File format name

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#501]
When i tried to import elements in silex (from dropbox) it doesn't woirk when the  File format name is in upeercase
a photo.png works but a photo.PNG doesn't work
It's the sameproblem with JPG jpg

**Comment by lexoyo** [comment]
Hi @antosilex thank you for the bug report
We are working with @JbIPS and @clemos on the new file explorer so this will be fixed with its release in a few months
