### ISSUE TITLE
Bug new version : resizing elements with border

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#502]
It's way better but there is still a problem (even on preprod) when you try to reduce the element from the top right  corner, the element is moving.

**Comment by lexoyo** [comment]
duplicate of #500

**Comment by lexoyo** [comment]
I reopen it since the other issue is closed
I would not rate this bug as a priority, if someone wants to back it up please vote! or help me fix it

**Comment by lexoyo** [comment]
fixed and live on editor.silex.me
