### ISSUE TITLE
My Help Wanted

### ISSUE THREAD

**Issue by An12440h** [silexlabs/Silex#505]
Ok. First thing, how to have different colour/background image on different pages? I tried to chnage it from the visible on thing but I cant change it. I don't understand how to use Animate.css on the wiki page. I tried to add the code to the JS editor and there's errors. I'm sorry I can't code :C

**Comment by singchan** [comment]
Hi @An12440h 
I believe it is not possible in Silex to change the background without code. But the code can be simple
You want the background on the whole website or just a section?

**Comment by An12440h** [comment]
Emm each page have different background. And about the Animate.css. How can I use it on silex?

**Comment by singchan** [comment]
did you follow these instructions?
https://github.com/silexlabs/Silex/issues/87

if you did, please share the result so we can see what you did ([use [netlify for example if you want to share a website, see this tutorial](https://github.com/silexlabs/Silex/wiki/publish-on-Dropbox-and-then-host-your-website-online))

**Comment by An12440h** [comment]
ok about the animate.css is done. Now about having separate background on each pages?

**Comment by An12440h** [comment]
and I see there's like the extra width, how can I change it? Sorry I'm new to silex
![image](https://cloud.githubusercontent.com/assets/16334962/19709489/8ba723cc-9b59-11e6-91de-3f0c16c65838.png)

**Comment by singchan** [comment]
you should share your website live with netlify or other, so that I can check

for the content to be centered, you need to put all your elements in a "section" (menu "+" and then "section" and set the background to transparent)

**Comment by singchan** [comment]
for the background image, there is the answer in this issue
https://github.com/silexlabs/Silex/issues/378

> A more complex method is to use css to change the background image of an element (or the body or the main container) depending on the page, for example
> 
> ```
> BODY.page-[your page name] {
>     background-image: url('[your image name]') 
> } 
> ```
> 
> More about [css in Silex here](https://github.com/silexlabs/Silex/issues/184)

**Comment by An12440h** [comment]
![image](https://cloud.githubusercontent.com/assets/16334962/19726267/a2719bba-9bbc-11e6-9e48-08ee08643df4.png)
is this right?

**Comment by lexoyo** [comment]
almost

replace `[Home]` with `"home"` and it should work

**Comment by An12440h** [comment]
now more problem comes up
![image](https://cloud.githubusercontent.com/assets/16334962/19728702/01049c7c-9bc7-11e6-8824-fb7058569044.png)

**Comment by lexoyo** [comment]
sorry my bad
replace`"home"` with `home`

**Comment by An12440h** [comment]
ok that's it. Tq maybe later you can make a better code editor for each element
like in the code menu and I better learn to code ":V

**Comment by An12440h** [comment]
emmm the code doesn't apply https://youtu.be/sD9CwQ8yjtw

**Comment by lexoyo** [comment]
you removed `BODY` from the code?

**Comment by An12440h** [comment]
![image](https://cloud.githubusercontent.com/assets/16334962/19748663/d893a658-9c15-11e6-9914-9e418ee35567.png)
added the `BODY ` back but still not working. it say "Element (BODY.page-home) is overqualifed, just use .page-home without element name.

**Comment by An12440h** [comment]
ok another last question. I've a PHP file for Minecraft server status how to use it?

The code:

```
<?php
/**
 * @author Kristaps Karlsons <kristaps.karlsons@gmail.com>
 * Licensed under MPL 1.1
 */

function mc_status($host,$port='40914') {
    $timeInit = microtime();
    // TODO: implement a way to store data (memcached or MySQL?) - please don't overload target server
    $fp = fsockopen($host,$port,$errno,$errstr,$timeout=10);
    if(!$fp) die($errstr.$errno);
    else {
        fputs($fp, "\xFE"); // xFE - get information about server
        $response = '';

        while(!feof($fp)) $response .= fgets($fp);
        fclose($fp);
        $timeEnd = microtime();

        $response = str_replace("\x00", "", $response); // remove NULL

        //$response = explode("\xFF", $response); // xFF - data start (old version, prior to 1.0?)
        $response = explode("\xFF\x16", $response); // data start

        $response = $response[1]; // chop off all before xFF (could be done with regex actually)

        //echo(dechex(ord($response[0])));
        $response = explode("\xA7", $response); // xA7 - delimiter

        $timeDiff = $timeEnd-$timeInit;
        $response[] = $timeDiff < 0 ? 0 : $timeDiff;
    }
    return $response;
}

$data = mc_status('149.202.69.132','40914'); // even better - don't use hostname but provide IP instead (DNS lookup is a waste)

print_r($data); // [0] - motd, [1] - online, [2] - slots, [3] - time of request (in microseconds - use this to present latency information)

```

**Comment by singchan** [comment]
You need a PHP hosting to host this somewhere (see gandi.net and indie.host for example)

And when this script is online somewhere I will be able tell you how to put it in an HTML Box in Silex

**Comment by An12440h** [comment]
what about the new changes I made for the background change problem?

**Comment by singchan** [comment]
Oh I see [in the docs here](https://github.com/silexlabs/Silex/issues/200) that you need also to paste this code in your page
```
$(function() {
  // this will be executed when the page is loaded
  var current = $('body').pageable('option').currentPage;
  $('body').addClass(current + '-opened');
  $('body').on('pageChanged', function (event, pageName) {
    // this will add a css class on the body, with the name of the page + '-opened'
    // e.g. open the page `page-test1` will add the css class `page-test1-opened` to the body
    $('body').addClass(pageName + '-opened');
    // remove previous one
    $('body').removeClass(current + '-opened');
    current = pageName;
  });
});
```

and you css code would then be
```
BODY.page-home-opened {
    background-image: url('http://www.aviatorcameragear.com/wp-content/uploads/2012/07/placeholder_2.jpg') 
} 
BODY.page-staff-list-opened {
    background-image: url('http://www.aviatorcameragear.com/wp-content/uploads/2012/07/placeholder.jpg') 
} 
```
Note that I have added `-opened` to the css classes

**Comment by singchan** [comment]
I have tested it and it works for me

**Comment by An12440h** [comment]
ok the background I've done changed it. tq. about the PHP file I've uploaded it here http://soulcraft.hanisirfan.rf.gd/mcstatusphp.php

**Comment by An12440h** [comment]
how to add favicon??

**Comment by singchan** [comment]
> ok the background I've done changed it. tq. about the PHP file I've uploaded it here 
> http://soulcraft.hanisirfan.rf.gd/mcstatusphp.php

oh ok, it returns data... then you will need to program to display something
the use of HTML Box in silex I was talking about is to embed code or web pages in silex, not raw data like this

> how to add favicon??

look in the settings panel, you can select a favicon

**Comment by An12440h** [comment]
so what should I do about the PHP file?

**Comment by singchan** [comment]
what do you want to do?
where did you have that from?

**Comment by An12440h** [comment]
emm ok forget about the PHP file. I'm not gonna use it. Thanks for helping me out. I've a few suggestions for new update. I've to learn how to code right now :P
1.Better layering-section,element layering and also the colour because the colour from section and element mix up(idk why)
2.Custom fonts-users able to use custom font(maybe upload to the file explorer
3.Better code area for element-maybe make same as the Code Menu
4.Better options for element for non coders-Have like hover events stuff etc and make it easier for them who don't know how to code.
5. Maybe separate the pages file-I think it would be better to separate it because maybe each pages can have different backgrounds easily.
That's all. Thanks

**Comment by An12440h** [comment]
You may close this issue rn

**Comment by An12440h** [comment]
eh wait XD last questions how can I use tawk.to

here's the HTML code
```
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/58143614c7829d0cd36d2785/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
```

**Comment by An12440h** [comment]
http://soulcraftmy.rf.gd/
this is the final product of a website that I made.

**Comment by lexoyo** [comment]
nice!
i don't know how you did these animations, it looks good and smooth

**Comment by An12440h** [comment]
oh I did it with animate.css and also hover.css :D

**Comment by An12440h** [comment]
![image](https://cloud.githubusercontent.com/assets/16334962/19885223/707bfe20-a058-11e6-980a-bcc39b27100a.png)
![image](https://cloud.githubusercontent.com/assets/16334962/19885231/7924884e-a058-11e6-9aa1-6433a91c656e.png)
Ok I'm making a new site. I've made a folder in the same directory of the index.html and I've added hover.css and animated.css to the css folder but the animations is not showing up. idk y. I've already added the classes to. emm after I export it doesn't put the CSSs files in the css folder. Maybe there's a bug? I think I'm just gonna add the CSS files manually
![image](https://cloud.githubusercontent.com/assets/16334962/19885359/1f6d9cae-a059-11e6-8368-3ba412662b8d.png)

**Comment by lexoyo** [comment]
did you add a reference to the css file in your site in the head editor?

**Comment by An12440h** [comment]
oh XD i forgot about that

**Comment by lexoyo** [comment]
Hello
I will close this issue but feel free to open a new one if you have questions
