### ISSUE TITLE
Share buttons widget

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#51]
Customize your widget here
http://www.sharethis.com/

Grab the embed code and paste it into Silex HTML box

**Comment by lexoyo** [comment]
FYI I use these share buttons, they are better (no js)
https://simplesharingbuttons.com/

**Comment by lexoyo** [comment]
This widget is now the share bar component. Add it from the "+" menu in silex.

Documentation : https://github.com/silexlabs/Silex/wiki/editor-ui#share-bar
