### ISSUE TITLE
Clikable texte element on safari macOS

### ISSUE THREAD

**Issue by Rom25** [silexlabs/Silex#510]
Hello every body, 

I'm a beginner with Silex (excellent tool :-) ) i try to make a texte element clikable (not the text, the text element him self), it’s work for Firefox, IE, Safari on iOS but not with safari MacOS.

The only solution i find is to make the texte clikable, but i think it’s not the good solution, because it’s less maintainable and a less beautiful

Someone know how can i do for have the texte element clikable on safari MacOS?

By advance thank you for your help :-)

Rom

**Comment by lexoyo** [comment]
Hi @Rom25 
You can make any element clickable and link it to a page or external link:
![screenshot from 2016-11-11 19-50-03](https://cloud.githubusercontent.com/assets/715377/20226357/16068f8a-a848-11e6-8910-61eae1769346.png)

**Comment by Rom25** [comment]
Hi @lexoyo 
Thank you for your answer, I try this way, but it doesn't work with safari on macOS, it work for other browser, but not this one, i don't understand why...

**Comment by lexoyo** [comment]
oh ok
you mean that the drop down list does not work when editing a website on safari ? or is it not working when viewing the site on safari?

**Comment by Rom25** [comment]
Hi @lexoyo, 

it's not working when viewing the site on Safari, 

I find a solution, 

If i use this way: 

BOBY.container-element > DIV.container-element > DIV.container-element > DIV.container-element > DIV.container-element > DIV.container-elment > DIV.container-element.CSS> DIV.text-element
It doesn’t work on Safari (text element not clickable )

If I use this way (with on less DIV.container-element)  : 
BOBY.container-element > DIV.container-element > DIV.container-element > DIV.container-element > DIV.container-element > DIV.container-element.CSS> DIV.text-element
It work’s on Safari.

I don’t no why, but it works…

Rom

**Comment by lexoyo** [comment]
I do not manage to reproduce this bug, can you share something online? (use [Grrhost](https://grrhosting.herokuapp.com/) or [netlify](https://www.netlify.com/) to put a temporary test website online)

**Comment by lexoyo** [comment]
feel free to reopen if you can share the bug to me
