### ISSUE TITLE
CSS styles in apollo non-responsive

### ISSUE THREAD

**Issue by ContourGeographic** [silexlabs/Silex#514]
Hello,
The styles editor in Apollo mode does not behave consistently.  Text styles do not update on the screen when applied, and when selecting different elements with different styles (that have css defined) their respective styles do not appear in the styles section (only the most recently applied style).  This is true even when I close and reopen a project.  Could this be a browser issue on my end? Or am I missing something?

Thanks!

**Comment by singchan** [comment]
Hi
I am not sure what you mean exactly but I do not use this panel, I set css class here
![screenshot from 2016-11-22 15-25-02](https://cloud.githubusercontent.com/assets/6483546/20527252/e3676a4e-b0c7-11e6-90fd-9bb537d42d30.png)

And the in the css editor (menu "code" then "CSS editor") to add styles
![screenshot from 2016-11-22 15-23-49](https://cloud.githubusercontent.com/assets/6483546/20527207/c1b4b7d0-b0c7-11e6-8c47-6348c4b0927f.png)
![screenshot from 2016-11-22 15-24-48](https://cloud.githubusercontent.com/assets/6483546/20527259/ebbb140c-b0c7-11e6-82e7-ec5fe7c26dfd.png)

**Comment by ContourGeographic** [comment]
Yes.  That makes sense.  I'll try to explain more clearly.  Let's say I select an existing text box on my page, and assign it a "heading1" style (which is already defined in my CSS-editor).  Assigning it a "heading1" style does not change the text on the screen.  Also, if I select a totally different container (not a text box), the CSS-classes window (the location in your first picture) still says "heading1" as if that style is also applied to the container.  I would think that the css-window would not display that particular class any longer, when selecting a different element.  Am I incorrect? 

Perhaps there is a proper order of events to adding styling?  In other words, should I define the style first in the css-class window, then add it to my CSS-Editor?  Or, could I go the other way around (add it first in the Editor, then assign it in the css-classes window)?

Thanks!

**Comment by singchan** [comment]
> Let's say I select an existing text box on my page, and assign it a "heading1" style (which is already defined in my CSS-editor). Assigning it a "heading1" style does not change the text on the screen. 

You mean you put "heading1" in the "css classes" text field where I have "my-css-class"? I believe "heading1" is a class of silex, see #184. Also how did you define it in the css editor? 

> Also, if I select a totally different container (not a text box), the CSS-classes window (the location in your first picture) still says "heading1" as if that style is also applied to the container. I would think that the css-window would not display that particular class any longer, when selecting a different element. Am I incorrect?

Yes you are correct, this looks like a bug to me. But I do not reproduce this, what is your browser please?

> Perhaps there is a proper order of events to adding styling? In other words, should I define the style first in the css-class window, then add it to my CSS-Editor? Or, could I go the other way around (add it first in the Editor, then assign it in the css-classes window)?

Well this is supposed to work either way

**Comment by ContourGeographic** [comment]
"You mean you put "heading1" in the "css classes" text field where I have
"my-css-class"? I believe "heading1" is a class of silex, see #184. Also
how did you define it in the css editor?"

Yes. It is defined as a google font that I embedded using code from google
fonts "@import...". That code came with classes .title, .heading1,
.heading2, etc.

Perhaps I should change the class name in the editor so as not to conflict
with the "heading1" of silex?

"Yes you are correct, this looks like a bug to me. But I do not reproduce
this, what is your browser please?"

I'm using Chrome- sorry I can't tell you which version. I'm responding from
my mobile while traveling. But will do so asap.

Thank you!

**Comment by lexoyo** [comment]
> Perhaps I should change the class name in the editor so as not to conflict
with the "heading1" of silex?

yes please

**Comment by ContourGeographic** [comment]
"Yes you are correct, this looks like a bug to me. But I do not reproduce
this, what is your browser please?

Sorry for the delay!  It appears my browser is up to date.  Chrome Version
54.0.2840.99 m


*Trevor Hobbs*



*address:* 6704 Timberview Dr. | Traverse City, MI 49685
*mobile:* 231.944.8859
*email: *info@contourgeographic.com
*website: *www.contourgeographic.com

**Comment by lexoyo** [comment]
did you try to change the class name in the editor so as not to conflict with the "heading1" of silex?

**Comment by lexoyo** [comment]
hi did it work?

**Comment by ContourGeographic** [comment]
Hi Alex,

My apologies for the lack of response... I've been dealing with some
serious computer issues the last few weeks, and my web effort to a back
seat. I understand why you closed the thread.

Cheers,

Trevor

*Trevor Hobbs*



*address:* 6704 Timberview Dr. | Traverse City, MI 49685
*mobile:* 231.944.8859
*email: *info@contourgeographic.com
*website: *www.contourgeographic.com

**Comment by lexoyo** [comment]
:+1:
