### ISSUE TITLE
Is there any auth plugin for the Silex site

### ISSUE THREAD

**Issue by jiangytcn** [silexlabs/Silex#516]
Hi, 
first of all, the project is so cool and i just deployed the site into a cloud provider, and designed my first site. But the question is that i didn't find any auth entry to access the silex, which means anyone logged in could see the content within my dropbox or any other cloud drive.
is that means i miss some configuration ?

**Comment by lexoyo** [comment]
Hi, glad you like it! :)

Only you can see the files from your cloud. You need to deploy your site ([after publish](https://github.com/silexlabs/Silex/issues/238)) to a web host like github pages or gandi or indie hoster... You can do that from inside silex using FTP or you download the published files and send them to your host

Is that clear?

**Comment by jiangytcn** [comment]
@lexoyo  Got it. and just verified using another browser to visit the [silex site i deployed](http://yadesigner.au-syd.mybluemix.net) but there's no github cloud drive, do i need to another config ?

**Comment by lexoyo** [comment]
oh ok!! you have a self hosted silex, I thought you use the editor.silex.me instance

to activate github service you need to define the env vars `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` ([create a github app here](https://github.com/settings/applications/new))

**Comment by jiangytcn** [comment]
Thank you, i'll give it a shot.

**Comment by yacloud** [comment]
@lexoyo  I just wrote the procedure of how to host an instance of Silex in Bluemix, would you mind announce it to the users? is that ok if i make a PR ?

**Comment by lexoyo** [comment]
This is great
I have made a change request to you
After that I will definnitely announce it
