### ISSUE TITLE
Lost the ability to open site from GitHub Again

### ISSUE THREAD

**Issue by lamynes** [silexlabs/Silex#522]
I can't open the site after making a background image change and viewing it.  I don't remember how to open again from github without losing my work.

![lost again](https://cloud.githubusercontent.com/assets/24372761/21191900/82d1ef40-c1db-11e6-92d5-166d6eed10d9.PNG)

**Comment by lamynes** [comment]
No matter how many times I develop my site, after some time (hours) go by.  This interface decides to not like it's own site.  

Please fix this issue.  It's not usable this way.

**Comment by lexoyo** [comment]
Did you publish your website?

**Comment by lexoyo** [comment]
when you publish it creates index.html, and overwrites the existing index.html with the published website, which can not be edited or opened with silex anymore

you should name your website with an other name than index.html. I call it editable.html usually

**Comment by lamynes** [comment]
I see, Does that cause any issue for publishing?

**Comment by lexoyo** [comment]
what do you mean?

**Comment by lexoyo** [comment]
I believe this was more a documentation issue than a bug, fee free to [add content to the wiki](https://github.com/silexlabs/Silex/wiki/) 

Thank you
