### ISSUE TITLE
Endless loading...not able to work anymore with silex?

### ISSUE THREAD

**Issue by marendoebler** [silexlabs/Silex#528]
I worked already on my sites, but now after pressing "add picture" or "open website" the attached window appeares and the loading last endless... I tried different browsers, but at the moment safari, mozilla and chrome is all the same... Any ideas? Thanks for helping me!

![unbenannt](https://cloud.githubusercontent.com/assets/24899654/21618212/1f39105c-d1ea-11e6-9751-942dc7e11433.JPG)

**Comment by lexoyo** [comment]
strange, I see it working now, can you try again plz?

**Comment by marendoebler** [comment]
Thanks for your fast reply - I tried it again, still the same....

**Comment by lexoyo** [comment]
if it is still the case today can you open the web developer console and tell me if you see javascript errors?

**Comment by marendoebler** [comment]
Still the same...this is what I get from the console:

![unbenannt](https://cloud.githubusercontent.com/assets/24899654/21645674/629dd00e-d293-11e6-9e51-1d2ce1cb8b05.JPG)

**Comment by lexoyo** [comment]
Please click these links and retry
https://editor.silex.me/api/1.0/dropbox/logout
https://editor.silex.me/api/1.0/webdav/logout

**Comment by marendoebler** [comment]
Still the same: 
1st link --> successful logged out
2nd link --> was not logged in

**Comment by lexoyo** [comment]
oh ok, the 2nd link was wrong then, try https://editor.silex.me/api/1.0/ftp/logout
you can try http://preprod.silex.me 
or you can run silex locally

**Comment by marendoebler** [comment]
How to run silex locally?

**Comment by lexoyo** [comment]
you need to read the instruction here
https://github.com/silexlabs/Silex#installation-on-your-local-computer

did you try the links I have sent?

**Comment by marendoebler** [comment]
Thanx, with the links above I get it done. Merci beaucoup!

**Comment by lexoyo** [comment]
haha nice :)
de rien mon ami!

**Comment by TheVince** [comment]
Hey guys I am running Silex on my **local machine** (MacOS Sierra) and I have the very same problem I worked on my site but when I press "open website" I get an endless loading screen and when I refresh I get a blank page with the message "Internal Server Error"  I've tried different browsers as well safari, firefox and chrome is all the same. Could you guys help getting it to work on my locally?
![screen shot 2017-01-16 at 12 03 16 pm](https://cloud.githubusercontent.com/assets/9653652/21979496/c05ab22c-dbe7-11e6-89f0-2864234e3e15.png)
![screen shot 2017-01-16 at 12 12 51 pm](https://cloud.githubusercontent.com/assets/9653652/21979499/c06eab60-dbe7-11e6-98df-499150ca8906.png)
![screen shot 2017-01-16 at 12 13 18 pm](https://cloud.githubusercontent.com/assets/9653652/21979497/c0607978-dbe7-11e6-83a0-2f5d9f1deec3.png)
![screen shot 2017-01-16 at 12 28 18 pm](https://cloud.githubusercontent.com/assets/9653652/21979498/c0671c2e-dbe7-11e6-8486-2e8451dbf5db.png)

**Comment by singchan** [comment]
hello
how do you run silex on your local computer, do you use docker?
if you do, you will need to display silex logs in order to understand what is happening (looks like the server crashes)

**Comment by TheVince** [comment]
I'm not familiar with docker unfortunately I use node.js and installed following the instructions from this section" https://github.com/silexlabs/Silex#installation-on-your-local-computer

**Comment by lexoyo** [comment]
Is there an error message in the console?

**Comment by lexoyo** [comment]
In the terminal I mean

**Comment by TheVince** [comment]
No errors

![screen shot 2017-01-16 at 1 17 12 pm](https://cloud.githubusercontent.com/assets/9653652/21980957/f506aa16-dbed-11e6-8837-b2618c7636cf.png)

**Comment by JbIPS** [comment]
Hi, 
To see the errors, you should enter `pm2 logs Silex` and reproduce the error (if you can). You should see the logs flow while you're using Silex.

**Comment by lexoyo** [comment]
You may need to do "node_modules/.bin/pm2 logs" 

or to install pm2 globally with "npm install -g pm2" and then "pm2 logs"

Or start silex without pm2 with "node dist/server/server.js" which prints the logs in the terminal

**Comment by singchan** [comment]
I start silex with `npm run start:debug` instead of `npm start`, this will display the logs

**Comment by TheVince** [comment]
This is what I have on the logs:
 
![screen shot 2017-01-16 at 3 56 58 pm](https://cloud.githubusercontent.com/assets/9653652/21985617/53b8ae4a-dc04-11e6-965f-f62e7c97d945.png)

**Comment by singchan** [comment]
sometimes I delete `dist/sessions/*` to reset my cookie (and in your logs it says cookie somewhere)
not sure though

**Comment by singchan** [comment]
did you manage to get it working?

**Comment by TheVince** [comment]
I couldn't get it done on **local machine** so I deployed to heroku and is working fine, thank you for the support and amazing response time!

**Comment by singchan** [comment]
great!!

**Comment by singchan** [comment]
Don't forget to show us what you do with the tool!!!
And please test the next version on preprod.silex.me :)
