### ISSUE TITLE
How to make element (image) activate email inc specified email address? (UPDATED)

### ISSUE THREAD

**Issue by travex99** [silexlabs/Silex#533]
Hello Silex users, I'm a newbie.
Can anyone help and advise how to activate an element (image) so that when clicked it opens the default email app - with a specified email address?
Similarly, I would like to know how to setup the same functionality so that when a specified element (image/button) is clicked then a default phone app is dialed (using specified phone number).
Thanks in advance for help on this.

UPDATE:  Solved with a little more searching!  Sorry this was a simple issue - for the benefit of other similarly inexperienced users:  
 1. select/highlight the element/image 
2.  under LINK (menu right side) choose "external link"  then in the field that opens below this simply enter:  mailto:email@address.com 
3.  For dialer/phone activation:  instead of "mailto:emailaddress"    enter:   tel:+123456789"    substituting your complete phone number.

**Comment by lexoyo** [comment]
nice one, thx! :+1:
