### ISSUE TITLE
Silex not loading fully/not working

### ISSUE THREAD

**Issue by K3Productions** [silexlabs/Silex#534]
Every time I try to load 'editable.html' it loads but then stops, and silex becomes unresponsive. I'd naturally assume it to be a problem with size, since it was fine up until a certain point in editing and saving. I've tried several seperate computers to see if I can avoid the issue, but it still persists.

All of the options and pop-out bars are unresponsive too. But once again, only with this specific file...

#528

**Comment by singchan** [comment]
hi
what is the service you use? (dropbox, github...)
can you share the website?

**Comment by K3Productions** [comment]
@singchan I use Dropbox to host the website files. 
I can share it to you on dropbox via email.

**Comment by singchan** [comment]
sure
please share it with billy321 [at] im-paris.fr

**Comment by K3Productions** [comment]
@singchan Done

**Comment by singchan** [comment]
ok, so this is what I see: I can open the website `SILEX SIte/fictional-studio/editable.html` but not open the pages in it

you have added HTML boxes and you put code in it with several versions of jquery, so you should remove it. but this will not fix the issue of the pages...

is it the right website? you still can not open it?

**Comment by singchan** [comment]
> but this will not fix the issue of the pages...

I was wrong, it was the problem, you should remove the other versions of jquery since there is already jquery in silex sites

**Comment by singchan** [comment]
you can try with the site I have created in the same folder

**Comment by K3Productions** [comment]
It seems to be working. Thank You @singchan

**Comment by K3Productions** [comment]
@singchan it appears that your html site cannot be used in 'preview mode' any further than the 'Home' Page. It doesn't change over when clicked.

**Comment by singchan** [comment]
I believe you need to save it on your dropbox or ftp or github and then the preview works?
