### ISSUE TITLE
error opening site once the new version released

### ISSUE THREAD

**Issue by lamynes** [silexlabs/Silex#538]
Error opening site once the new version released, it deosn't let me open anything.  Stuck as soon as it loads the page.
![silex err](https://cloud.githubusercontent.com/assets/24372761/22186800/82387074-e0b0-11e6-9d05-5f567d687b6f.PNG)

Recorded Steps.

[silex err.zip](https://github.com/silexlabs/Silex/files/722322/silex.err.zip)

**Comment by lexoyo** [comment]
Hi
I forked your site and opened it and it worked (at least aacorvette.html)
Please try again, it may be caused by the release I did today, warmup of the server or reboots

**Comment by lamynes** [comment]
Yeah,  I  figured it would be ok. Give it some time.  Thank you

**Comment by lamynes** [comment]
I was also able to verify that everything is working as before.

Thank you again,

Paul

**Comment by lamynes** [comment]
New issue, I can't get past the gh-pages selection to open my site.


​

**Comment by singchan** [comment]
what do you mean?
you see the gh-pages folder but can not browse into it?

**Comment by lamynes** [comment]
Correct,  I select the folder and it hangs

**Comment by singchan** [comment]
it works here.. maybe try again in a moment

![screenshot from 2017-02-03 18-16-39](https://cloud.githubusercontent.com/assets/6483546/22600916/f42515c6-ea3c-11e6-929d-a16d50bb8eda.png)

**Comment by lamynes** [comment]
No go.... No matter how I try it never gets past trying to open gh-pages.

**Comment by lexoyo** [comment]
I will have a look tomorrow
In the meantime you can download it from github and put it on dropbox?

**Comment by lamynes** [comment]
No worries

**Comment by lexoyo** [comment]
Ok it looks like you reach the maximum number of commits in github! Congrats! ;) 
What I did, I used the command line `git reset $(git commit-tree HEAD^{tree} -m "squash all commits into one")` to make one single commit from all your commits. This is the same as downloading all files and making a new repo in github
You can either do this like I did, or delete your repo and I will transfer mine to you
This issue with max number of commits in github should be fixed when we switch to @JbIPS 's new version of [unifile](https://github.com/silexlabs/unifile/)

**Comment by lexoyo** [comment]
https://github.com/lexoyo/silexvette

**Comment by lamynes** [comment]
Wow, too easy. Thank you Sir
