### ISSUE TITLE
Can't open my ftp

### ISSUE THREAD

**Issue by cielartisan** [silexlabs/Silex#539]
An error occured, I could not open the file. Unknown error with HTTP status 502

**Comment by singchan** [comment]
hi @cielartisan 
i just tried and got connected to my ftp (from ovh)
can you try again please?

**Comment by cielartisan** [comment]
I just have to save the websit quitt firefox and open again regularly. It works as it...

**Comment by lexoyo** [comment]
thank you for the tip!
