### ISSUE TITLE
Text Boxes - justified text (align both left and right)

### ISSUE THREAD

**Issue by ghost** [silexlabs/Silex#540]
Hi, thanks for great Silex tool.
I am asking about text alignment in text boxes.
Silex text boxes have "align left", "align centre" and "align right".
Is it possible to add "justified" as another option for text alignment in the text box editor?
Thanks.

**Comment by singchan** [comment]
Hello
It is possible but you need to use css, see this doc and ask questions here if you need
https://github.com/silexlabs/Silex/issues/184
Oh, and here is the CSS style you need to use
`text-align: justify;` as explained here https://developer.mozilla.org/en/docs/Web/CSS/text-align

**Comment by lexoyo** [comment]
This is live now on editor.silex.me
So I'll close this now

Any comment about this new release is welcome here #690
