### ISSUE TITLE
How to set width (to remove space each side in website)

### ISSUE THREAD

**Issue by travex99** [silexlabs/Silex#542]
Hi again,
I have a problem in setting website width (w).  I don't want my website to have clear space each side.  I must be doing something badly wrong but can't take off all the vacant space sitting each side of the website content.

I have tried setting section widths and overall default (w) and each element to 800px - or less - but nothing seems to change the final result.

Please see the attached web page (published and attached as zip file) that indicates my webpage example and the unwanted white space each side.

Help!  Any advice and tech tips on how to bring the overall width in to about 800px would be appreciated.

[Silex-testsite-publish.zip](https://github.com/silexlabs/Silex/files/735210/Silex-testsite-publish.zip)

**Comment by lexoyo** [comment]
hi @travex99 

in desktop mode, you can set the website width in the [settings panel](https://github.com/silexlabs/Silex/wiki/settings)

in mobile mode the website is 100% width

**Comment by travex99** [comment]
Thanks and I don't mean to be difficult, but I don't have a problem setting the width to 800px in the settings panel.  I ahev already done that.   

The problem is that when published is still adds heaps of clean space either side - rather than letting the website show out to the width of the text/images/content.  

To put it another way, I don't want the white space that shows each side of the content in the published version  - I actually just want the website to show out to the width of the content/text.  (see example previously attached which still includes setting panel at 800px ....)

It may be a limitation - but I would really appreciate any help with this issue.

**Comment by lexoyo** [comment]
oh ok
you are right, it is not good to have this space around the site
it is there to make it possible to access the background of the site while editing, but when viewing the site it should not be there
i will fix this soon, but meanwhile you can add this in the [CSS editor](https://github.com/silexlabs/Silex/issues/184):
```
.silex-runtime .website-min-width {
    min-width: 0;
}
```

**Comment by fernandammoutinhobarros** [comment]
Hi, I'm having the same problem. 
This  solution works for stage side spaces?

Thank you for this wonderful editor!!

**Comment by travex99** [comment]
Sorry guys, I’m still having trouble with using and applying the suggested  CSS expression  fix.
I have played around with trial and error in the Styles / CSS Editor … but no luck.
I am a complete novice to HTML / CSS etc syntax and expressions.  :-(

My two questions about how to apply the fix in the Styles / CSS Editor menu  are:

**1**   When I insert this exact expression - do I need to change  min-width: 800;  ??  or leave this value as 0  ??

**2**   Is it necessary to select a section or element to insert this  expression  into a specific position   OR  where can I apply this  expression  to apply it to the whole website ??

Any help with these  2 questions  much appreciated.  This is a great tool by the way – I’m just a novice!

**Comment by lexoyo** [comment]
> 1 When I insert this exact expression - do I need to change min-width: 800px; ?? or leave this value as 0 ??

you are supposed to leave the `0` as is
it will remove the blank space and the width of your website will be the one you specified in the settings

> 2 Is it necessary to select a section or element to insert this expression into a specific position / line number ???? 

no you did good and the CSS editor is for the whole site

> Can you see anything wrong with how I have inserted this in the attached screen shot???

yes, I feel like the syntax highlighting is strange, and there is a warning (the `!` in the margin)
here is what I have when I paste the code into the css editor
![screenshot from 2017-01-28 13-17-17](https://cloud.githubusercontent.com/assets/715377/22396530/233b09c8-e55c-11e6-95d7-10d3efff2dbc.png)

my questions:
* what does the warning say?
* can you try moving the code fix higher in the CSS editor to avoid the errors you might have higher in the CSS code
* are you aware that this code is supposed to change the website in the preview, not in the editor itself?

**Comment by travex99** [comment]
Thanks again - unfortunately still have the same problem (after publishing) in "published" version with those changes.  Sorry  :-( 
.  see attached / screen shot with 2 x warnings and 1 x info remarks;
.  have moved higher in CSS editor code lines - see image.
.  yes.

![silex-css-infos](https://cloud.githubusercontent.com/assets/25174557/22402339/a3f0b126-e62e-11e6-9fb3-5e5cf18a8bb3.jpg)


I hope the screen-shot gives clues to what is happening to make the webpage add that extra space each side in both preview and published pages.
I'm sorry this is a continuing issue.  Grateful for all your suggestions and advice.  Cheers.

**Comment by lexoyo** [comment]
Ok, very useful screenshot
The strange part is "unknown property min-width"
Could you copy paste it back from your css editor to here please? Maybe there is a strange character or something...
In fact you can copy/paste your whole CSS?

**Comment by travex99** [comment]
OK thanks - I'm sure we'll find a solution soon ...  thanks again!
Below is cut-paste of all CSS  then below is a screenshot of complete CSS Editor - all lines.

**Cut-paste CSS:**

        @import url('//fonts.googleapis.com/css?family=Oswald:200,300');
        
        /* define a style for Title, Headings and Normal texts */
        .title,
        .heading1,
        .heading2,
        .heading3,
        .normal {
          color: black;
          font-family:'Oswald',sans-serif;
          margin: 0;
          font-weight: normal;
        }
        /* force element height to be smaller than sections can be in silex */
        .editable-style.small-height {
            min-height: 10px;
            height: 10px;
            max-height: 10px;
        }
        /* title style */
        .title {
          font-size: 60px;
          color: rgb(73, 187, 204);
        }
        .heading1 {
          font-size: 24px;
        }
        .editable-style.right {
            left: initial;
            right: 0;
        }
        .grey-text .normal{
            color: grey;
        }
        .small-text .normal{
            color: grey;
            font-size: 10px;
        }
        .silex‐runtime .website‐min‐width {
            min‐width: 0;
        }
        .product-details .heading1 {
            color: rgb(73, 187, 204);
        }
        .product-details .heading3 {
          color: white;
          background-color: rgb(73, 187, 204);
          float: right;
          padding: 2px 25px;
        }
        .in-front {
            z-index: 1000;
        }
        .link-menu .normal{
            padding-top: 5px;
            color: #000000;
        }
        /* animated colors widget
            https://github.com/silexlabs/Silex/issues/138
        */
        .link-menu .page-link-active {
            background-color: rgb(73, 187, 204);
            transition: background-color 0.5s ease-in;
        
        }
        .link-menu .page-link-active .normal {
            color: #FFFFFF;
            transition: color 0.5s ease-in;
        }
    

**Screenshot all of CSS:**
 
![silex - all css screen](https://cloud.githubusercontent.com/assets/25174557/22404405/51ee1f34-e66b-11e6-9132-cdcfa51bc2d1.jpg)

**Comment by lexoyo** [comment]
It looks like your version of min-width (`min‐width`) and mine (`min-width`) are different, the `-` is not the same
Just delete your `-` and type it with the keyboard and it should work

**Comment by travex99** [comment]
Hi there again! Thanks.  The problem with syntax in CSS for the “min-width” expression was fixed - but the problem still remains.    :-(  

I thought maybe the problem is in the original template I built this from ... so I made a complete new one page website using the "blank" layout" from the dashboard.  Then I "published".

The website is one page, inserted 3 sections and I set the width to 600px. (in settings menu).  I added random blue colour to outside of top and bottom sections and all other elements are transparent.

I used clean and new directories to store the working file and another new directory to store the published page – so no corruption of files etc.  Browser s Chrome.

:-(       I still have the problem that the website doesn't zoom in to eliminate the white space on both sides.  So the web page just zooms into be only the wiDTH of the webpage content.

Here is a screenshot of the CSS Editor -   very clean.
![silex-new testpage 600w-csseditor30jan](https://cloud.githubusercontent.com/assets/25174557/22415984/5b2fe5d2-e706-11e6-9f19-dec10e7fe0a1.jpg)

Here is the full screenshot of the actual published page result as it appears on my 13” laptop screen:
![silex-pubpage-600w-pub30jan-1](https://cloud.githubusercontent.com/assets/25174557/22415996/73a386c8-e706-11e6-8b9a-41a80b053bdc.jpg)


THEN I had a brainwave – maybe putting the colour in the side parts of the top and bottom sections (wings / far sides of the stage) is the problem – so I set the whole section and all elements to transparent then just set the middle part of the top and bottom sections with the blue colour – setting the side parts (as they appear on the stage) as transparent.  Problem still there – so much white space just sitting on each side ….

Here is the full screen shot of the published result - problem still exists:
![silex-pubpage-600w-pub30jan-2](https://cloud.githubusercontent.com/assets/25174557/22416016/879bf4ee-e706-11e6-909d-a10da19978cd.jpg)


I would be really grateful for help with this.

**Comment by singchan** [comment]
I think that lexoyo is right, this is a problem with the "-". Yours are not real dashes, see my experiment here:

![ezgif com-df0c6425dc](https://cloud.githubusercontent.com/assets/6483546/22427604/23d77142-e704-11e6-8199-202356835d8c.gif)

**Comment by travex99** [comment]
Ok thanks for that - but I think that problem with the (-) had already been fixed.   See post "The problem with syntax in CSS for the “min-width” expression was fixed ..."  See also the clean copy of the CSS editor posted above - there is no (!) error warning which I think also confirms min-width (-) issue is fixed in this case.

But the original problem with extra white space added to each side of published content width in the published website - it is still there.

Any suggestions to fix the original problem would be great.  Thanks again.

**Comment by singchan** [comment]
> Ok thanks for that - but I think that problem with the (-) had already been fixed. See post "The problem with syntax in CSS for the “min-width” expression was fixed ..." See also the clean copy of the CSS editor posted above - there is no (!) error warning which I think also confirms min-width (-) issue is fixed in this case.

the issue is not with the "!" but with the syntax highlighting (the color of what is after the fake "-"
if you fix this the problem will be solved

to be sure that I am right (or wrong) you can host your website somewhere (like netlify) and share the link

**Comment by singchan** [comment]
or just save the page in github

**Comment by travex99** [comment]
Hi thanks heaps for your help - yes this fixed the errors in the CSS editor.  see attached screenshot.

![12silex testsite-csseditor](https://cloud.githubusercontent.com/assets/25174557/22494784/6764fef8-e875-11e6-82fe-15d71e3c5cca.jpg)

Here is how the simple Test website now displays after publishing:
**1**   Laptop Full Screen  (black border added to image after screenshot just to show actual displayed screen limits):
![12silex testsite-laptopfullscreen](https://cloud.githubusercontent.com/assets/25174557/22494859/35ccd07c-e876-11e6-991a-999b0f88fb99.jpg)


**2**  Responsize.org "Desktop":  white space both sides
![12silex testsite-responsize-desktop](https://cloud.githubusercontent.com/assets/25174557/22494886/798ea948-e876-11e6-9443-3b0714057e58.jpg)

**3**  Responsize.org "Mobile":  - notice all the white space below (shown by position of side slider)
![12silex testsite-responsize-mobile](https://cloud.githubusercontent.com/assets/25174557/22494894/86959958-e876-11e6-904f-d0359cf5e919.jpg)


Sorry but I'm beginning to think I must have a misunderstanding about how websites are correctly displayed.  Doesn't zoom in to automatically remove excess white space at the sides after publication???  But it seems a bit funny if all the white space is added below in "Mobile" view.

**Comment by travex99** [comment]
and here are the sites published files for ref:
[aSILEX-NEWTEST-PUBLISH.zip](https://github.com/silexlabs/Silex/files/743849/aSILEX-NEWTEST-PUBLISH.zip)

**Comment by lexoyo** [comment]
the white space bellow the website in the mobile version is a bug, i am in charge of fixing it asap

the white space on the side of the website in the desktop version is a choice you make. if you want the color to be 100% width, you should apply the color to the background of the section, not the container which is centered. let me know if you need help with that

**Comment by travex99** [comment]
Ok.  thanks.
