### ISSUE TITLE
blank body space below content in mobile view

### ISSUE THREAD

**Issue by soundservice** [silexlabs/Silex#544]
When mobile view is displayed on browser or mobile device, the blank body container extends over 3600 pixels, double the actual content height.  Chrome inspector lets me set body class: min-height to zero, and works for the moment.  Is there some css I can plug in?  
Great editor by the way!
Alan Phillips

**Comment by lexoyo** [comment]
Hi
I saw that already yes
I will try to fix it, I think it comes from the script in dist/client/js/front-end.css which computes the website height in desktop mode (because elements are position:absolute in desktop)... there is a bug there
Thank your for the bug report

**Comment by soundservice** [comment]
Hi Alex: 
any progress on the blank mobile body space?

**Comment by lexoyo** [comment]
Hi Alan
I fixed it on my fork of Silex
Next step is to deploy it on preprod.silex.me and then test the new version and then deploy it on editor.silex.me

**Comment by singchan** [comment]
you can take this script and replace your version of js/front-end.js
https://raw.githubusercontent.com/lexoyo/Silex/b99348dfeb6594067cee427aee4c0ea5790bb032/static/2.7/front-end.js

**Comment by soundservice** [comment]
Thank you singchan, that worked!

**Comment by lexoyo** [comment]
Hello
I am about to [merge this PR](https://github.com/silexlabs/Silex/pull/554) and deploy it to editor.silex.me
It should fix this issue and several minor bugs, could you test before I proceed please? It is now on preprod.silex.me
For example you can use it to edit a template, move things around and publish... Thank you in advance

**Comment by soundservice** [comment]
Alex the preproduction versions are running great with the body space issue, even in the editor!

**Comment by singchan** [comment]
thx @soundservice for the feedback
