### ISSUE TITLE
Page width is diferent on some computers

### ISSUE THREAD

**Issue by fernandammoutinhobarros** [silexlabs/Silex#548]
Hi can someone help me.

I have a webpage that has 800 px with, I can see it on my chrome browser (win 7) very well, but on another computer using also chrome (win 7) it shows a smaller size or the text larger it doesn't fit on the sections. The screen is large so I don't think that's not the problem...

I forced each text element with a size on .css  with font-size: ...pt

Also I have this on css editor

```

        /*
        Eliminar margens laterais da página
        */
      
       
        .silex-runtime .website-min-width {
            min-width: 0;
        }
          
         
    
    
   /* here is a rule to change texts in mobile version only
   https://github.com/silexlabs/Silex/issues/454
   */

 @media (max-width: 480px) {
        p, h2 {
            text-align: justify;
            padding: 10px;
        }
    }

```

Thanks for the help.

**Comment by lexoyo** [comment]
Are you talking about the font size?
Can you provide a screenshot please?

**Comment by singchan** [comment]
you should embed the font you use (Arial by default in Silex)
see these instructions to embed a font: #46

**Comment by fernandammoutinhobarros** [comment]
Hi, thanks for the help.


So this is how it should be.

[image: Imagem intercalada 3]




And this is how it shows on another computer with same browser (chrome in
win 7)

It looks like its enlarging the font, or shrinking the page with...
[image: Imagem intercalada 2]


Melhores cumprimentos,



          *Fernanda Moutinho Barros*

*_______________________________________________________________*

        *CONSULPAV **Consultores e Projectistas de Pavimentos, Lda.*



Rua da Zona Industrial, N.º 6 A, Casais da Serra
2665-305 Milharado – Mafra – Portugal
Telef.: (+351) 219 757 003        Fax: (+351) 219 757 014

www.consulpav.com     www.facebook.com/consulpav







2017-02-08 8:46 GMT+00:00 singchan <notifications@github.com>:

**Comment by lexoyo** [comment]
please share the website so that we ban understand better

**Comment by fernandammoutinhobarros** [comment]
Hi Alex, thank you very much for the help.

The website is www.rar2018.net

I just know a the baics of html coding. 

I followed the instructions that singchan recomended, to embed fonts
"see these instructions to embed a font: [#46](https://github.com/silexlabs/Silex/issues/46)"

I think I did it wright.

I've placed on css editor the fonts i chose on googlefonts
 @import url('https://fonts.googleapis.com/css?family=Anton%7CMuli%7CPlay'); 


then for each element i defined the font-family on css classes
        font-family: 'Anton', sans-serif;         
        font-family: 'Muli', sans-serif;    
        font-family: 'Play', sans-serif;    

Is this wright or  not?

I can see everything ok on my machine, but don't know if everyone sees what I see...


thank you again for the help

**Comment by lexoyo** [comment]
Hi @fernandammoutinhobarros 
Sorry about the delay, it looks like we forgot about your issue
Your site looks really good! I have tested with the latest firefox and chrome
You can use [Browserstack](https://www.browserstack.com/) to test on many real browsers for free
Things I see you could make better
* the domain name is an "iframe" redirect, this is not good for search engines
* you may want to add an "alt" attribute for images for search engines too
* your favicon is not working
Tell me if there is something else?

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo,

Thank you again for your help.


_- the domain name is an "iframe" redirect, this is not good for search engines_
I now, but I can't change that :(

_- you may want to add an "alt" attribute for images for search engines too_
great thanks for the tip

_- your favicon is not working_
the adress was wrong :P 


When I open it on a mobile phone the background shrinks, is there a workaround?
The mobile version is activated.

![bs_realdroid_mobile_samsung galaxy note 4-4 4-1440x2560 1](https://cloud.githubusercontent.com/assets/25388113/23133335/a2e275f6-f788-11e6-8322-d978067b7e0d.jpg)

**Comment by lexoyo** [comment]
i do not see that, what is your os / browser?
here is what i see on http://consulpav.com/rar2018/

![screenshot from 2017-02-21 11-50-45](https://cloud.githubusercontent.com/assets/715377/23161879/1e34c81e-f82c-11e6-87fc-1a48dba9e090.png)

**Comment by fernandammoutinhobarros** [comment]
Hi @lexoyo,

Samsung galaxy note - The image I sent was from the simulator you sent me.
But on my Samsung S7 the same happens... 

I've tested others on browserstack

iphone 5
![bs_ios_mobile_iphone 5-6 0](https://cloud.githubusercontent.com/assets/25388113/23162734/61210b1a-f827-11e6-98a5-8df014e26cca.jpg)


Nokia Lumia
![bs_winphone_mobile_nokia lumia 930-8 1-1080x1920](https://cloud.githubusercontent.com/assets/25388113/23162751/731fdc56-f827-11e6-9765-49a81c8c1a52.jpg)

**Comment by fernandammoutinhobarros** [comment]
On windows is where it works best.

**Comment by lexoyo** [comment]
oh ok... so the buggy behavior is mainly on iOS ?

**Comment by fernandammoutinhobarros** [comment]
And on android

**Comment by lexoyo** [comment]
ok i think that these are different bugs
in [this stackoverflow thread here](http://stackoverflow.com/questions/14876035/background-size-cover-not-working-in-portrait-on-android-tablet) they say there is a bug of android browsers, so I did as they say and added this code to the CSS editor
```
html{
 height:100%;
 min-height:100%;
 }
body{
 min-height:100%;
 }
```
it fixes the background on android
can you confirm?

**Comment by FranGamer1892** [comment]
@lexoyo Hey there,

I'm new to this subject (and github, whatever.) I had the exact same problem. I pasted 

`html{
 height:100%;
 min-height:100%;
 }
body{
 min-height:100%;
 }`

alone in the css editor (at the last line) but i did not work.

**Comment by lexoyo** [comment]
@fernandammoutinhobarros did it work for you?

**Comment by fernandammoutinhobarros** [comment]
Hi Lexoyo,

It works for me.

**Comment by FranGamer1892** [comment]
Oh boy @lexoyo Are you sure the code has to be pasted alone in the CSS editor? I can send you my webpage's editable.html

**Comment by FranGamer1892** [comment]
Hold on, due to my server my last 2 changes (including HTML) might not been uploaded. I'll check tomorrow.

**Comment by FranGamer1892** [comment]
Hmm...still the same. I deleted all it was in this setting (http://prntscr.com/jss1x8)

Do I need to type in something specific? (http://prntscr.com/jss1x8)

**Comment by lexoyo** [comment]
Oh really? Odd...
You do not need this setting. All it does is force sections width.

**Comment by lexoyo** [comment]
@FranGamer1892 I thought your problem was fixed!
Please take the time to explain exactly what is wrong

**Comment by FranGamer1892** [comment]
my site looks weird on every different browser or screen resolution
[editable.zip](https://github.com/silexlabs/Silex/files/2113282/editable.zip)

**Comment by FranGamer1892** [comment]
i tried the css code already @lexoyo

**Comment by FranGamer1892** [comment]
what do you mean of screenshots? the web's?

This are screenshots of Firefox Android (I just can use this browser right
now)

**Comment by FranGamer1892** [comment]
Let's continue at my issue.

**Comment by lexoyo** [comment]
this is now fixed (different website width)
