### ISSUE TITLE
Make HTML box Scrollable

### ISSUE THREAD

**Issue by K3Productions** [silexlabs/Silex#549]
I'm making a 3 Month HTML-Based Calendar, and I want to make it scrollable. But HTML, CSS and jQuery do not work in helping me to make it scrollable. 

I'm using this HTML:
[Calendar2017.txt](https://github.com/silexlabs/Silex/files/774138/Calendar2017.txt)
 and I'm unable to make it vertically scrollable. Any help would be much appreciated

**Comment by singchan** [comment]
I could do it like this:

* add html box on the stage and put your code in it
* add the css class "cal" on it
* add this css code in the css editor:
```
.cal {
    height: 0;
}
.cal .silex-element-content {
    overflow: auto;
}
```

Then you can resize the calendars and there is a scroll bar like this
![screenshot from 2017-02-14 18-05-14](https://cloud.githubusercontent.com/assets/6483546/22939921/89dcb5e6-f2e0-11e6-953e-d2183b83d0a3.png)

**Comment by K3Productions** [comment]
@singchan I've tried this and it makes no difference.

**Comment by K3Productions** [comment]
@singchan would it be possible for you to access the html file and make the change? As it appears I might be doing it wrong-

**Comment by singchan** [comment]
sure, you can share it on dropbox with bill321 at im-paris.fr

**Comment by K3Productions** [comment]
Will do. It should show up in a few minutes

**Comment by singchan** [comment]
did not receive it yet, normal?

**Comment by K3Productions** [comment]
I'll send it again.

**Comment by K3Productions** [comment]
@singchan I've found out there's a glitch with dropbox. I'll try send it again, from a separate interface.

**Comment by singchan** [comment]
@K3Productions I got the shared folder but there is no HTML page in it?

**Comment by K3Productions** [comment]
@singchan check the sub-folder 'fictional-studio'

**Comment by singchan** [comment]
i have added an html file in your folder
here is what i did: 
![scrollable-calendar-issue-549](https://cloud.githubusercontent.com/assets/6483546/23406264/5def7412-fdbe-11e6-88c0-512f6a0fd37e.gif)

**Comment by K3Productions** [comment]
Okay. I understand now, Turns out I was making a small error each time I did it. Many Thanks.
