### ISSUE TITLE
mobile view on iPad?  

### ISSUE THREAD

**Issue by soundservice** [silexlabs/Silex#551]
My full site loads correctly on an iPad2 and iPad Air 2 as long as it's horizontal.  Turn the iPad to vertical, and it's fine.  When you refresh the browser however, the mobile site loads.  Turn horizontally again, stays mobile, as expected.  
It seems to me the 480 px breakpoint falls below the iPad's 768 px vertical size, correct?  
my site is here: [http://soundservice.us] when you get a chance.     
Thanks again!

**Comment by singchan** [comment]
This is a strange behaviour, mobile version is triggered by media queries
so it should switch when you turn the ipad...

Is it really an issue yoy think ?

**Comment by soundservice** [comment]
is for me...  it appears to happen on other sites as well.  Site width is 1024px, I'd think it would load the full site on a vertically oriented iPad.

**Comment by lexoyo** [comment]
>  it appears to happen on other sites as well

what do you mean? other silex sites or normal websites?

>  Site width is 1024px, I'd think it would load the full site on a vertically oriented iPad.

you are right, it should load the desktop version for resolutions higher than 480px (this value is hardcoded [here](https://github.com/silexlabs/Silex/blob/develop/static/2.7/front-end.css#L115) and [here](https://github.com/silexlabs/Silex/blob/develop/src/js/model/property.js#L76) and also [in this file](https://github.com/silexlabs/Silex/blob/develop/static/2.7/front-end.js))

it is probably due to the retina "x2" resolution... I tried to find better media queries today and will continue soon??

**Comment by soundservice** [comment]
Alex I noticed Wordpress sets two media queries at 600 and 768 to account for iPads

**Comment by lexoyo** [comment]
Interesting! Good idea to look at it this way...
I can not find it though, where did you see the rule? I need the whole media query to test it on a silex site

**Comment by soundservice** [comment]
My apologies Alex, it wan't Wordpress, but here: [https://www.w3schools.com/css/css_rwd_mediaqueries.asp](url) midway down the page

**Comment by soundservice** [comment]
Alex I played around with front-end.js some more and changed the breakpoint:   if(winWidth <960)  to 768
My site now loads the full site in portrait on an iPad.  Still working on the viewport, but at least it displays!  
// bellow 960, the window width will be seen as 480
 if(bodyEl.hasClass('silex-runtime')) {
 var winWidth = win.width();
 if(winWidth < 768)
 
 
Alan Phillips
Sound Service
828-713-7232
 
http://soundservice.us
 
 
 
--------- Original Message --------- Subject: Re: [silexlabs/Silex] mobile view on iPad? (#551)

**Comment by lexoyo** [comment]
so it looks better on ipad and also good on other devices?

**Comment by soundservice** [comment]
don't have other devices to test it on, only iPads and iPhones.  I chose 768 for winWidth for the iPad because that is the lowest portrait resolution.  Below that mobile is fine...  
Am having a viewport issue however, initially it loads the full 1024px wide site, but goes outside of portrait.  Pinch the page and it zooms out to full screen.

**Comment by lexoyo** [comment]
this should be fixed now
