### ISSUE TITLE
Silex new version: test the latest features before they are released

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#553]
There will be a new version of Silex soon and It is a big step forward for UX. <a href="https://github.com/silexlabs/Silex/issues/187">Help me test the new publication mechanism ! Help me make it easy to use</a>.

**Comment by JbIPS** [comment]
Can we close this one?

**Comment by lexoyo** [comment]
Sure go ahead
Or maybe replace the content? Because this issue has the label "tip of the day" so it appears in Silex dashboard and publication dialog

**Comment by JbIPS** [comment]
What do you want to write instead? 
Or just close it and remove the label? Use the live announcement instead

**Comment by lexoyo** [comment]
Yes let's close it
It will disapear from Silex dashboard it's good
