### ISSUE TITLE
Unable to save text or 

### ISSUE THREAD

**Issue by codegirlchicago** [silexlabs/Silex#556]
Hi, new user here. When I try to save my text as a website, I get an error message. How can I save my HTML and CSS in the editors?

**Comment by lexoyo** [comment]
Hi i do not see what you mean?
You type html in an html box? In the head? 
To save a website you can do ctrl+s and type the file name in the input text at the bottom then click save

**Comment by codegirlchicago** [comment]
When I click save, I still get an error saying the text can't be saved when I type HTML in a text box.

**Comment by codegirlchicago** [comment]
I think I'm able to save my files in Dropbox. Thanks anyway!
