### ISSUE TITLE
Inserting Video (from Dropbox) onto Website in Silex Editor

### ISSUE THREAD

**Issue by K3Productions** [silexlabs/Silex#558]
I've noticed there is no possible way (to my less experienced mind) in the UI Menu to insert any sort of video format. Is there a way I can insert an .mp4 or .flv file onto my site that will still work (audio too) after publishing?

**Comment by singchan** [comment]
for this you can use the HTML box and paste the code you like into it
you can use a [video HTML tag](https://developer.mozilla.org/en/docs/Web/HTML/Element/video) (be careful with browser compatibility) or audio tag or a service like soundcloud or youtube which propose an "embed" for each sound or video

**Comment by K3Productions** [comment]
@singchan I've tried that already, but it does not seem that I can get it to recognise the Videofile within the dropbox folder without linking it using a URL, but I need the whole site to be able to perform in an offline environment, which means I cannot use URL's or any internet-reliant parts.

**Comment by K3Productions** [comment]
Scratch that, I managed to force it to search and select automatically. 

Thank You for the Assistance
