### ISSUE TITLE
My Silex website

### ISSUE THREAD

**Issue by daofficiel** [silexlabs/Silex#562]
Here is a link to a website I did with Silex: `https://dieudomtechnelectronics.blogspot.com`

**Comment by lexoyo** [comment]
well it is a blog made with blogger... wrong link or spam?

**Comment by daofficiel** [comment]
je souhaite avoir un nom de domaine propre svp

**Comment by lexoyo** [comment]
ce site n est pas fait avec silex, je ferme l issue
