### ISSUE TITLE
imagesak - anybody else getting these? 

### ISSUE THREAD

**Issue by soundservice** [silexlabs/Silex#566]
I noticed an odd spawning of this line: 
<script type="text/javascript" src="http://imagesak.secureserver.net/gomezxfmonitor/gtagb4.js"></script>
seemingly every time I save in editor.  I have deleted the associated references to these in the editor index, however they return and carry on to the published site.  Currently I'm using html batch editor to clean it up.  
Please see attached jpg screenshot.  
Any ideas?  
![imagesak-spawning](https://cloud.githubusercontent.com/assets/15841566/23823823/b2311166-0638-11e7-9656-34306249cd01.jpg)

**Comment by lexoyo** [comment]
Hello
It must be a script inserted by the code you put in an HTML box. Do you have HTML boxes in your site?
Also silex should prevent scripts execution in HTML boxes, I am aware of the feature / bug

**Comment by soundservice** [comment]
Finally got rid of the source in the backend.  Not sure what caused it other than a possible icon I had gotten off the internet. 
Thanks!
