### ISSUE TITLE
Hash in URL prevent switching pages

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#572]
Hi,

I don't know exactly why, but sometimes when editing my website, the URL becomes `editor.silex.me/#!page-home` and when it does, I cannot switch between pages anymore.

I'll give you more info if I manage to reproduce conscientiously.

**Comment by singchan** [comment]
aouch indeed, thx for this bug report!

**Comment by lexoyo** [comment]
It is fixed on preprod
