### ISSUE TITLE
Hex color in CSS crash editor

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#573]
I tried adding a `background-color: #D3B04E` in the css box at the bottom of the element menu and saved. On the next loading, the website doesn't appear and Silex seems stuck in a loading loop. 

In the browser console, I got `Error #D3B04E is not a valid color string`

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.

**Comment by lexoyo** [comment]
it has been solved, thank you @JbIPS
