### ISSUE TITLE
Won't Save.

### ISSUE THREAD

**Issue by KuramaSusano** [silexlabs/Silex#577]
It won't save and it says an error has occured.

**Comment by singchan** [comment]
hi @KuramaSusano 
can you give a screenshot of the error plz?
which service are you using? (dropbox, github...)

**Comment by lexoyo** [comment]
is this solved?

**Comment by RayPylant** [comment]
If person still has this problem , he has to clear his cache only files then try again .. sometimes the cache gets to over whelmed so we have to clear it so pc run better. hope this helps remember always clear your cache every few hours this will help from having a lot of errors
