### ISSUE TITLE
Silex should check user is logged in before publishing

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#578]
I use Dropbox as a workspace and a FTP as a publish target. I frequently forgot to log in my FTP server (with CloudExplorer) before publishing.

Once the button hit, everything goes as usual (number of assets decreasing and so on) and at the end I get an error for not being logged. This verification should happen first.

**Comment by lexoyo** [comment]
this follows the issues  #187

**Comment by lexoyo** [comment]
done
