### ISSUE TITLE
buttons, text input boxes, radio buttons, etc?

### ISSUE THREAD

**Issue by David1platt** [silexlabs/Silex#587]
I'm new to the project so I might be looking at things from the wrong angle, but I was wondering about input tags like input type="button" and input type="text" input type="radio" it would be really useful to be able to drag and drop these elements

**Comment by lexoyo** [comment]
Hi David
I am working on a component system. The first components will be a slideshow, a contact form, an interactive map and animated components. This should be released in less than a month

Then we can decide which components are needed... I made some tests and it looks like higher level components are easier to deal with.. for example a form with customizable fields. 

What do you plan to do with these components?

In the mean time you can use HTML boxes to do that

**Comment by lexoyo** [comment]
(you can test the components on preprod.silex.me)

**Comment by lexoyo** [comment]
Something like this?
https://github.com/silexlabs/Silex/issues/277#issuecomment-268921167

**Comment by David1platt** [comment]
Yeah a lot of people like to use buttons and check boxes as links. It seems really easy to just use the html blocks. You've put quite a bit of work into the project so its up to you.

**Comment by lexoyo** [comment]
Thank you !
Let us know what you do with silex please :)
