### ISSUE TITLE
a dead gandi in my way

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#588]
Since the latest update of Silex, the preprod server is down
When it starts, it says
`Error: Cannot find module '/srv/data/web/vhosts/default/Silex/node_modules/unifile/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'`
I don't manage to reproduce it locally... @JbIPS any idea?

May be useful?
```
$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ node -v
v6.5.0
$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ npm -v
3.10.3
$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ echo $SILEX_DEBUG

$ 
```

**Comment by JbIPS** [comment]
I told you to get rid of open pages and sqlite3! 

We'll look at it Monday 
-- 
Jean-Baptiste Richardet

**Comment by lexoyo** [comment]
Sure no hurry
In unfile you mean? We need to publish a new old version? ;)


On Apr 21, 2017 10:01 PM, "Jean-Baptiste Richardet" <
notifications@github.com> wrote:

I told you to get rid of open pages and sqlite3!

We'll look at it Monday
-- 
Jean-Baptiste Richardet

On April 21, 2017 9:06:03 PM GMT+02:00, Alex Hoyau <notifications@github.com>
wrote:
>Since the latest update of Silex, the preprod server is down
>When it starts, it says
>`Error: Cannot find module
>'/srv/data/web/vhosts/default/Silex/node_modules/
unifile/node_modules/sqlite3/lib/binding/node-v48-linux-
x64/node_sqlite3.node'`
>I don't manage to reproduce it locally... @JbIPS any idea?
>
>May be useful?
>```
>$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ node -v
>v6.5.0
>$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ npm -v
>3.10.3
>$ hosting-user@paas_42493:/srv/data/web/vhosts/default$ echo
>$SILEX_DEBUG
>
>$
>```
>
>--
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/silexlabs/Silex/issues/588

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/silexlabs/Silex/issues/588#issuecomment-296292642>, or mute
the thread

**Comment by JbIPS** [comment]
It should be possible to fix it since unifile did not change recently, but a new version would definitely fix this.

**Comment by lexoyo** [comment]
I have made a new version of the old unifile and it works now :)

**Comment by JbIPS** [comment]
:clap: but we'll still need to go to the new Unifile one day :wink:
