### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by IsaacCruz** [silexlabs/Silex#589]
Hello,

I'm trying to run the project, but I get this error when I run: `npm install`

<details>
  <summary>Error stack</summary>

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you can switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you can switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Cloning into bare repository '/Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c'...
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Permission denied (publickey).
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: 
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c: and the repository exists.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/isaaccruz/.npm/_git-remotes/_templates --mirror git@github.com:silexlabs/silex-templates.git /Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c
npm ERR! Cloning into bare repository '/Users/isaaccruz/.npm/_git-remotes/git-github-com-silexlabs-silex-templates-git-2107872-a989834c'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/isaaccruz/Documents/ProyectosITC/Silex/npm-debug.log
```

</details>

**Comment by JbIPS** [comment]
The first errors happen because you modified the templates and that would overwrite it all. Remove (or stash) your changes to make it disappear. 

The other ones about permission are weird since you don't need any to clone Silex. 

Could you tell me the install command you ran and more about your configuration (OS version, node version and any information that could help us reproduce)?

**Comment by IsaacCruz** [comment]
Thanks for your answer. 

I solved the access rights error. 

But I continue having the local changes error.

I just cloned this way: 
`git clone --recursive https://github.com/silexlabs/Silex.git`

Then:
`cd Silex/`
Finally 
`npm install`

And the error still appears: 

`npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you can switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you can switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: error: Your local changes to the following files would be overwritten by checkout:
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	online-service/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Facebook.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 	tech-tools/assets/Twitter.png
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Please commit your changes or stash them before you can switch branches.
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: Aborting
npm ERR! git checkout 210787247d01522bd9a69dececd4322bc03e762e: 
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code 1

npm ERR! Command failed: git checkout 210787247d01522bd9a69dececd4322bc03e762e
npm ERR! error: Your local changes to the following files would be overwritten by checkout:
npm ERR! 	online-service/assets/Facebook.png
npm ERR! 	online-service/assets/Twitter.png
npm ERR! 	tech-tools/assets/Facebook.png
npm ERR! 	tech-tools/assets/Twitter.png
npm ERR! Please commit your changes or stash them before you can switch branches.
npm ERR! Aborting
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/isaaccruz/Documents/Proyectos/Silex/npm-debug.log`

I'm on macOS Sierra 10.12.4

With these versions: 
{ Silex: '0.8.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.4',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.89',
  zlib: '1.2.8' }

**Comment by JbIPS** [comment]
I'm unable to reproduce with a fresh install... Did you modify those files before `npm i`?

**Comment by IsaacCruz** [comment]
No, that's the weird part.

I just followed the installation manual.

**Comment by JbIPS** [comment]
Could you send me the result of `git status` in the Silex dir please?

**Comment by IsaacCruz** [comment]
Of course: 
```
MacBook-Pro-de-Isaac-2:Silex isaaccruz$ git status 
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```

**Comment by lexoyo** [comment]
nom install is not even supposed to git pull, is it?

**Comment by JbIPS** [comment]
> npm install is not even supposed to git pull, is it?

It is, since `silex-templates` is a GitHub dependency. What's weird is that I don't find the commit SHA on the repository.

@IsaacCruz Can you confirm you're doing a fresh & clean install: the Silex folder doesn't exist before the `git clone` and you have read/write access for the parent folder?

**Comment by IsaacCruz** [comment]
@JbIPS  & @lexoyo thanks for your support, I deleted all the project, cloned it, and finally ran npm install and IT WORKED!!

It was like the fourth time I deleted all and started fresh, the important part is that it worked. 

Thanks again.

Isaac Cruz

**Comment by JbIPS** [comment]
Good news! Hope it won't happen again. 

Thank you for using Silex and have fun creating your website!
