### ISSUE TITLE
Big step forward for Silex, help wanted

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#591]
Hello

I am very happy to announce the soon to be released new version of Silex. Now we need a final test, with real people to create a small website to test it in real conditions!

[Go to this instance of Silex](http://preprod.silex.me) and test these new features:
* slideshow component
* contact form component
* share bar component
* new [beauty template](https://silex-templates.silex.me/beauty/)

Please take 10 to 20 minutes to test the components, make a small website from a template or from a blank page, and publish the result on github pages or netlify (ask here if you need help)

Also there is a work in progress on [the documentation](https://github.com/silexlabs/Silex/wiki) and an effort to make [an offline version of Silex](https://github.com/silexlabs/Silex/issues/568) which can be tested if you are willing to play with the terminal/command line :)

Thank you in advance!

![screenshot from 2017-04-29 14-12-36](https://cloud.githubusercontent.com/assets/715377/25555417/9b5ac2aa-2ce6-11e7-8e0a-4f223c9908d9.png)

**Comment by lexoyo** [comment]
[This is this template I did to test these features](http://lexoyo.me/GrrHost/96793/studio/) (I might include it in silex templates if I have positive feedback)

Found some small bugs in the slideshow... Will fix it before release..

![screenshot from 2017-05-02 20-35-42](https://cloud.githubusercontent.com/assets/715377/25633314/fdb6d186-2f76-11e7-9afc-eb2743a08f79.png)

**Comment by JbIPS** [comment]
I'm trying the new "Share buttons" widget but I'm unable to configure it. I think I'm supposed to look at the tool bar on the right, but the field must be missing.

![image](https://cloud.githubusercontent.com/assets/2248473/25639148/14030748-2f8b-11e7-982f-207e216e073d.png)

**Comment by JbIPS** [comment]
Actually that's the same thing for the contact form too. Did I missed something?

**Comment by singchan** [comment]
I see the params... did you have js errors? firefox and chrome?
can you try again now?

**Comment by lexoyo** [comment]
i have fixed several small issues in components
especially on slideshow and form components
it is live on preprod.silex.me

**Comment by JbIPS** [comment]
It's better now! I tried the share bar and have some concerns:
* Filling the Twitter field with `@JbIPS` (since it was `@silexlabs` by default) give a tweet with `via @@JbIPS`
* Hovering the Twitter button give 'Share on Tweeter' (instead of 'Twitter')
* I was a bit confused by the field name and what they do (at first I though it purpose was to follow me on those networks):
  * twitter -> Twitter account
  * url -> URL you want to share
  * title -> Post title
* I can't add back a network: maybe checkboxes would be more appropriated

And in a more general way, fields label must start with an uppercase

**Comment by JbIPS** [comment]
About the contact form: very nice!

I'm just not sure what the `onsubmit` field do and what I'm supposed to put in. Code ? How? What's the context? Which variables do I have access to?

**Comment by JbIPS** [comment]
Also, on Firefox 52.0.2 (64-bits), Fedora 25, the cursor change to the 'text insertion curosr' when hovering the '+' button (which should be bigger BTW)

**Comment by singchan** [comment]
> Filling the Twitter field with @JbIPS (since it was @silexlabs by default) give a tweet with via @@JbIPS

ok fixed (i removed the "@" from the default value)

> Hovering the Twitter button give 'Share on Tweeter' (instead of 'Twitter')
> Title default is 'Yout site title'
> Reddit share give me a double 'http://' in the URL field

fixed

> I was a bit confused by the field name and what they do (at first I though it purpose was to follow me on those networks):
> twitter -> Twitter account
> url -> URL you want to share
> title -> Post title

yes we should add a displayName field in Silex components' yaml files 

> I can't add back a network: maybe checkboxes would be more appropriated

yes you have to know the name of the network
in prodotype the "enum" type should have an option to allow multiple selection

**Comment by singchan** [comment]
> About the contact form: very nice!
> I'm just not sure what the onsubmit field do and what I'm supposed to put in. Code ? How? What's the context? Which variables do I have access to?

yes javascript
I think there is the `event` object, since it is like `<div onclick="your code here"`

> And is there a way to have the name we gave to the field in the mail sent?

it should be the case already

**Comment by JbIPS** [comment]
> it should be the case already

Then we have a problem 😆. Here's what I received:

field1 	|Doe
----------|-----------
field2 	|ad@doe.fr
field3 	|Hello !

And of course, yes I set other value to those field (name, email, message)

**Comment by lexoyo** [comment]
Thx JB, but I could not reproduce the form component bug, could you give it a try again?
I have fixed other bugs (copy paste of sections, move with arrow was strange...)
Almost there, I will push to editor.silex.me soon

**Comment by JbIPS** [comment]
Tried it again, same thing.

But I took a closer look at the component console and see you set a label, not the field name. And I think the later is sent to the mail service.

**Comment by lexoyo** [comment]
Can you confirm that this submission:
![screenshot from 2017-05-28 15-12-43](https://cloud.githubusercontent.com/assets/715377/26529015/32fc8822-43b8-11e7-87c6-0c834581dc62.png)

Will give this params sent as POST data:
![screenshot from 2017-05-28 15-12-55](https://cloud.githubusercontent.com/assets/715377/26529019/3f28cda4-43b8-11e7-8a88-fb99becd0dfd.png)

**Comment by JbIPS** [comment]
Exactly! My point was "please send `Nameqqq` instead of `field1` and so on" 😄

**Comment by lexoyo** [comment]
Released: "Component system, right click and bug fixes"
https://framagit.org/silexlabs/Silex/merge_requests/10
