### ISSUE TITLE
CSS editor + Style / CSS classes windows at the same time

### ISSUE THREAD

**Issue by ceubri** [silexlabs/Silex#593]
Hello,

is it possible to have CSS editor + Style / CSS classes windows at the same time ?
It would be usefull to edit the code and to rename the classes at the same time...

Thx

**Comment by singchan** [comment]
we could add a text field in the css editor with the current selection's css classes...
maybe the tagName too

**Comment by lexoyo** [comment]
Or maybe put the CSS window at the bottom as suggested before in another issue

**Comment by ceubri** [comment]
Yes bottom or in a tab.
