### ISSUE TITLE
Help: auto redirect page to another page after a delay

### ISSUE THREAD

**Issue by IOU4something** [silexlabs/Silex#597]
Hello I need help Making one of my pages auto redirect to another page on my site I need it to redirect after about 3 sec but not instantly. Any help would be appreciated.

**Comment by lexoyo** [comment]
hi @IOU4something 
this should do the trick:
```


$(function() {
  // here the page is loaded
  $('body').on('pageChanged', function (event, pageName) {
      // here a page has changed
      checkRedir(pageName);
  });
  // check at start
  var current = $('body').pageable('option').currentPage;
  checkRedir(current);
});
function checkRedir(pageName) {
  if(pageName === 'page-page-2')
  setTimeout(function() {
    window.location.href = "#!page-page-1";
  }, 2000);
}
```
you need to change the name of the pages (from and to)
if there is something not clear in this code, feel free to ask

**Comment by IOU4something** [comment]
Im sorry Im new to programming does this go in css, html,or javascript? and could you explain what each section does in the code?. Thank you for the information

**Comment by lexoyo** [comment]
ok :)
this is javascript code so you need to paste it in the JS code editor
and you need to replace:
* `page-page-1`: the name of the page you want to open, + the "page-" at the beginning like in the address bar so in this example my page was called "Page 2"
* `page-page-2`: the name of the page on which you want to redirect (from which your user will be redirected)
* `2000` is the delay before the user is redirected, in milliseconds, so 2000 means 2s

try this and tell me if it fits your need?

**Comment by IOU4something** [comment]
@lexoyo Thank you so much it work exactly as I need it to. Thank you for your assistance!
