### ISSUE TITLE
Better lorem ipsum, easy task for a developer to dive in Silex

### ISSUE THREAD

**Issue by singchan** [silexlabs/Silex#600]
This is an easy task for a developer to get to know Silex, I can provide help for each step and it represents approximately 2 hours of work (javascript code, server or client side depending on the chosen solution)... Let's do it together, leave a comment here!

In the text editor there is a button to insert lorem ipsum. This useful for demos, templates and tests... Currently it uses bacon ipsum which has strange words in it. This is because at that time baconipsum was the only service to provide an API for lorem ipsum

Nowadays there are several alternatives which we should use to replace bacon ipsum:
* this [lorem ipsum service](http://loripsum.net/) which has an API which works like bacon ipsoom, e.g. `http://loripsum.net/api/1/medium/plaintext`
* make our own service in Silex using [one of the many libs which provide lorem ipsum in nodejs](https://www.npmjs.com/browse/keyword/ipsum)

**Comment by lexoyo** [comment]
this is solved by today's release
see the new inline text editor, the style editor, the font manager
and the [related docs](https://github.com/silexlabs/Silex/wiki/editor-ui#text-editor)
