### ISSUE TITLE
Add cancel/close option to cloud authorization prompt

### ISSUE THREAD

**Issue by jennparker** [silexlabs/Silex#604]
**Issue:**
There is no way to cancel or back out of cloud authorization prompt

**Repro:**
Open Silex Editor
Start a new website
Select file menu > Save Website 
Select a cloud storage option you haven't previously given permission for access

**Outcome:**  
Authorization prompt (attached) opens, but there is no way to back out/cancel prompt and return to the previous screen. 
![screen shot 2017-05-14 at 7 25 50 pm](https://cloud.githubusercontent.com/assets/22356441/26040698/5c820168-38dc-11e7-92cd-f63b2c857dd1.png)

**Comment by lexoyo** [comment]
Hello
Thank you for this bug report
I am starting a new work on the file explorer (Cloud Explorer) so the fix for this bug will definitely be part of it

**Comment by jennparker** [comment]
Great! Thanks!
