### ISSUE TITLE
help wanted: move widget docs

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#605]
We have decided to move the [issues with the label "widget"](https://github.com/silexlabs/Silex/labels/widget) to a page named "widgets" in the wiki.

For each widget this is to do
* Move the content from the issue to the wiki page (all widgets in 1 page @jennparker ?)
* Add the widget name to the table of content of the wiki page
* Remove the content from the issue and replace it with a link to the wiki for archive and searches
* close the issue

**Comment by jennparker** [comment]
Great! Yes, let's add the widgets to the Editor UI page of the wiki. I have added "Widgets" to the page table of contents and created the anchor and the section title. Please add the content here: https://github.com/silexlabs/Silex/wiki/Editor-UI#widgets

**Comment by andreamussap** [comment]
Hi all
I might be able to help with this - just need more info.
I can see the list of widget issues but I don't get what exactly you mean by '**moving**' them.
Take for ex the first issue o the list: 'Side menu widget for Silex'.
How do I 'move' this to the 'Editor UI'? Should I 'edit' the issue page and copy its content? If this is the intention, there's no EDIT button for this issue.
So, can you please explain, maybe give an example of how this is to be done?
= = = =
One more question, lexoyo says: 'move the issues with the label "widget" to a page named "widgets" in the wiki'. However, jennparker 'add(ed) the widgets to the Editor UI page'- so, there's no page for the widgets, they'll be part of the Editor UI page. Right?

![silex-widgets](https://user-images.githubusercontent.com/10401080/34104044-d2046d8a-e3e6-11e7-97f8-a1b47af4566a.png)

**Comment by lexoyo** [comment]
Thx for helping @andreamussap !
@jennparker and me did agree that we should move all these issues over to https://github.com/silexlabs/Silex/wiki/Editor-UI#widgets

> How do I 'move' this to the 'Editor UI'? Should I 'edit' the issue page and copy its content? If this is the intention, there's no EDIT button for this issue.

You are right, you can just add a comment with a link to the widget and then I will close the issue

**Comment by lexoyo** [comment]
Also you may be interested in this info: there is a new "component system" in silex, and this kind of "widget" should probably be ported (yet to be discussed for each widget) to the new system. This means to add 2 files for each widget, [see these components for an example](https://github.com/silexlabs/Silex/tree/develop/src/components).
Then the widget will be a component, accessible in silex UI, in the "+" menu and with params in the panel on the right

If you are able to do this, please let me know :)

**Comment by andreamussap** [comment]
> You are right, you can just add a comment with a link to the widget and then I will close the issue.

@lexoyo I've updated section ['Widgets'](https://github.com/silexlabs/Silex/wiki/Editor-UI#widgets) with two widgets. Please let me know if this is what you and @jennparker have in mind, so I can continue from there.

**Comment by andreamussap** [comment]
There's a typo in the description of [Side menu widget for Silex](https://github.com/silexlabs/Silex/issues/659):  "A **dropown** menu or hamburger menu...". The word 'dropdown' is misspelled. As the page/issue is not editable I can't fix this. 

How should I proceed when I find tiny issues, typos, etc and the content is not editable? How do I inform this to ye?

**Comment by stache1draht** [comment]
@andreamussap, that's what you have to do:
1. Open an issue with the **widget** label.
2. Copy the text and images.
3. Go to https://github.com/silexlabs/Silex/wiki/Editor-UI#widgets.
4. Press **Edit** and paste the copied text from the issue into the corresponding section of the page. (Keep formatting of the original text.)

It is best to copy the text from the issue to the Editor UI page piece by piece as it is more accurate than copying the whole text and then trying to format it.

You can use MarkdownPad. Copy the text from the original issue piece by piece and paste it into MarkdownPad. This will allow you to see in real time how the text will look like on the Wiki page. (Keep in mind that MarkdownPad and GitHub interpret some Markdown marks differently.) Then cut the text out of MarkdownPad and paste it into the corresponding section of the Editor UI page.

**Comment by stache1draht** [comment]
After you have copied the text from the issue and pasted it on the Editor UI page, add the widget name to the table of contents. Then leave a comment in the original issue and **lexoyo** will close it.
