### ISSUE TITLE
Is Collaborative Design Possible

### ISSUE THREAD

**Issue by BigMacSauce** [silexlabs/Silex#609]
I am newer to the whole drop box thing, and am used to working with Dreamweaver to tinker with html and such. I found your site on a top 10 list, and immediately fell in love with the simplicity. But, quickly I wondering about collaborative real-time design capabilities of your site. I have been working on a personal project, and like would like to work in real time with a friend on the project. Is this already possible with your program, and if not is it possible to incorporate something like that with the cloud-storage thing you already use? I have only found one other free web design program/site that allowed for this, but their site was extremely hard to use and had far to many unnecessary options and menus. If you would be able to get something working that allows for that, you would make me and a large number of other newer webdesigners and tinkerers very happy. If this is already possible, let me know! I would love to utilize it

**Comment by lexoyo** [comment]
Hi @BigMacSauce 
Thank you for the comments about silex, this is a volunteer effort you know :)
About the real time collaboration, it is not possible in silex, and it is a lot of work to develop it so there is no plan to add it. But this is open source so you never know
You can still collaborate with Dropbox or Github, there is documentation on this subject
Keep us posted!
