### ISSUE TITLE
Can't see the bottom of a html box

### ISSUE THREAD

**Issue by Pucci00** [silexlabs/Silex#612]
I wanted to inser a google form by html code in silex, but even if I put all height settings at higher values than it really need, I can't see the bottom of the HTML (in this case, the rest of the form)
I don't know why I have this issue, I don't know html so well, but I just copy the code from google to silex.. It should
![immagine](https://cloud.githubusercontent.com/assets/29070538/26599638/97f87098-4579-11e7-9c32-245f2bfa2584.png)
 work, right?

**Comment by lexoyo** [comment]
it should work yes
what is the html code you insert?
maybe there is an iframe with hard coded dimensions?

**Comment by Pucci00** [comment]
This is the code: 
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSedxamTnzgd3jYujb9Si6gYYI8TKF7cwxpxFZ3uKBqu5O_I7w/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Caricamento in corso...</iframe>

"Caricamento in corso" means "loading" in Italian

**Comment by lexoyo** [comment]
Ok, you see the width and height are hard coded, change them in the code

**Comment by Pucci00** [comment]
I did, bit it still not work :(

**Comment by singchan** [comment]
I tried with your code and it seems to work with height="1500":

![screenshot from 2017-05-31 11-50-45](https://cloud.githubusercontent.com/assets/6483546/26626407/76954b1e-45f7-11e7-97a0-6c668f4164ae.png)

![screenshot from 2017-05-31 11-50-05](https://cloud.githubusercontent.com/assets/6483546/26626408/769b630a-45f7-11e7-8286-6101263a4e89.png)

**Comment by Pucci00** [comment]
Ok, it works, thanks
