### ISSUE TITLE
Silex next: please test

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#617]
Hello
A new version of Silex is on [preprod.silex.me](http://preprod.silex.me)

As asked many times by many people, there is a real color picker everywhere:
* background color
* border color
* text editor's text colo

Also several UI improvements compared to [editor.silex.me](https://editor.silex.me) (design and behavior of property editors)
 
Please help me test this, so that we can go for a next step (mobile version fixes and then publication problems and file browser)

**Comment by singchan** [comment]
I have found these bugs (nothing to do with the new features)
* background image buttons are not actual buttons anymore
* "enable mobile" check box has disappeared (in settings)

**Comment by JbIPS** [comment]
Everything seems good! I checked all the color picker and they're all 👌 

Aside from that, I've got a strange behavior of the image container: I added an image but it looks like it center is on the right border of the div
![screenshot from 2017-06-21 15-00-47](https://user-images.githubusercontent.com/2248473/27385367-b2a667b8-5692-11e7-8a21-e25a5c47fbe5.png)

Moving the side handles resize the image but I cannot center it.

**Comment by JbIPS** [comment]
Bad news, I tried to publish (GH or FTP) but it hang every time (around `15 left`). I shared the folder with you so you can reproduce it.

_Fedora 25, Firefox 53_

**Comment by singchan** [comment]
So now here are the current bugs I can reproduce
* background image buttons are not actual buttons anymore
* "enable mobile" check box has disappeared (in settings)
* publish
  * an iframe appears in the corner
  * error in one of the URL to load makes the server crash (@JbIPS in your case `http://localhost:6805/moz-extension://d52fa3d7-bb67-430b-9ac2-83d974890295/skin/socialwidgets/socialwidgets.css`)

**Comment by JbIPS** [comment]
Thanks @singchan! And now that you mention it, I too saw an iframe in the upper left corner

**Comment by lexoyo** [comment]
all these issues should be fixed, could you please test that they are?

**Comment by JbIPS** [comment]
> all these issues should be fixed, could you please test that they are?

They are! Nice job! 👏
