### ISSUE TITLE
Using html to go from one page to another

### ISSUE THREAD

**Issue by Kevin160210** [silexlabs/Silex#619]
I am having a bit of a problem using html when trying to get from my home page to another page: 
                    <style>
                        .button {
                            background-color: black;
                            border: none;
                            color: white;
                            padding: 10px 18px;
                            text-align: center;
                            text-decoration: none;
                            display: inline-block;
                            font-size: 16px;
                            margin: 4px 2px;
                            cursor: pointer;
                        }
                    </style>

                    <a https:="http://[my website name].getforge.io/#!page-shortstories" class="button">Short Stories</a>

The first part is creating a button but the at the bottom is where I am having problems with the hyperlink. I didn't want to reveal my website name so I replaced it with [my website name]. What should I do to create the hyperlink. Thank you.

**Comment by lexoyo** [comment]
It is supposed to be "href=" instead of "https:="

I think this might be a bug in silex, you can try this
<a href="//[my website name].getforge.io/#!page-shortstories" class="button">Short Stories</a>

**Comment by Kevin160210** [comment]
Oh thank you for catching my mistake, I didn't realize I put http:= instead of href=
I seem to still be having a problem though, when I click the button now it states

I have another problem that came up but I'll see if I can figure it out first. Thank you for your help.

**Comment by singchan** [comment]
Looks like it works for me:

![screenshot from 2017-06-23 10-09-59](https://user-images.githubusercontent.com/6483546/27472585-2af12da6-57fc-11e7-9e61-ac27e7aa5332.png)

![screenshot from 2017-06-23 10-09-47](https://user-images.githubusercontent.com/6483546/27472586-2b0bd502-57fc-11e7-8dfb-c3c0dc0879fc.png)

**Comment by lexoyo** [comment]
is it resolved @Kevin160210 ?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
