### ISSUE TITLE
Open a new tab/window when you click on a link

### ISSUE THREAD

**Issue by tariqbenezza** [silexlabs/Silex#621]
When you're using the text editor you can add a link.

![image](https://user-images.githubusercontent.com/4911564/27595487-1a1528ac-5b5d-11e7-89a6-d95bb05bc6dd.png)

The problem is that you can not configure it to open a new tab/window like you can do in HTML with :

`target="_blank"`

**Comment by lexoyo** [comment]
this is done for text, but still needs to be the same for links on elements

**Comment by lexoyo** [comment]
Done
