### ISSUE TITLE
Issue with editing site

### ISSUE THREAD

**Issue by MissRenegade** [silexlabs/Silex#622]
Hey, wondering if anyone can help me with this (hopefully) easy issue.  I published my site last night and realized I forgot to enable mobile; so I went back in, enabled mobile and re-published.  Now, I went to add a photo, but cannot edit anything (except for moving via the arrow keys on my keyboard) and when the site opens it will only open to one page despite the links directing to the other pages (eg. About displays the home page information).  Thankfully I had a backup of the good site (minus mobile optimization) saved to revert back to on my own domain, but I cannot edit this site through silex even after disabling mobile view.  Hopefully I explained that so it's easy to be understood.

**Comment by JbIPS** [comment]
Hello!
We're sorry you experienced such issue but everything's gonna be ok!

First, could you give us some information about your site:
* What's your cloud storage (FTP, GitHub, Dropbox,...) for publication and backup?
* What's your browser and your OS?
* Finally, which version of Silex do you use? editor.silex.me or your own instance?

Thank you for using Silex and helping it becoming greater!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MissRenegade** [comment]
Thanks for the reply, I'm sure it's something simple, I just can't figure out what. 

I'm using Dropbox for publication and backup and then an FTP to my personal domain. 

Browser is chrome, OS is windows 10. 

Editor is silex.me

**Comment by lexoyo** [comment]
Could you please share the 2 versions of your html page?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
