### ISSUE TITLE
Google analytics embed code breaks my site

### ISSUE THREAD

**Issue by antosilex** [silexlabs/Silex#624]
All the sites i've done with silex since 2 years are broken even the last one done 3 months ago.
I'd like to modify the site http://www.clairiere-epona.com/ but here is what i see on my editor
![capture du 2017-06-29 14 53 59](https://user-images.githubusercontent.com/6757106/27688509-13965e04-5cdb-11e7-8685-1b3f75df3515.png)

**Comment by lexoyo** [comment]
Hello
Does it display the "update warning" when you open the site?
If you click "preview", is the preview broken too?

**Comment by antosilex** [comment]
Hi
Yes i saw the "update warning" and i saved as a new version but it doesn't change anything.
The preview is broken too
![capture du 2017-06-30 15 05 02](https://user-images.githubusercontent.com/6757106/27736760-db5c739a-5da5-11e7-85fb-cb384551ca30.png)

**Comment by lexoyo** [comment]
Can you please share the website somewhere?

**Comment by antosilex** [comment]
You already are the owner of the shared folder
I sent you an email
Tks

**Comment by singchan** [comment]
There is an [issue with google analytics embed code in this method](https://github.com/silexlabs/Silex/blob/2d95ee981d25b56d4e966642fde21db6ba3b4f0a/src/js/utils/url.js#L217)

1- please remove this code from your sites `(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');`
2- we should remove these crazy regexp

**Comment by antosilex** [comment]
Tks for your answers
I've tried to remove the Google Analytics JS code  i'm not sure to do it properly  but it doesn't change anything, i really need some help to solve this problem it's urgent to update the website with the new planning for 2017, i don't know what to do all my assets disapeared and all the container are broken, and i really need to give some answers to the website owners, is there hope to save my previous work ?

**Comment by lexoyo** [comment]
is this issue resolved @antosilex ?
