### ISSUE TITLE
Impossible to access to my github directory

### ISSUE THREAD

**Issue by tariqbenezza** [silexlabs/Silex#628]
Since one day I cannot access to my github repo. I just wanted to add a picture and the interface doesn't list the content of my directory anymore.

Here is the message I've got :

```
GET https://editor.silex.me/api/1.0/github/exec/ls//myCV/master/ 503 (Service Unavailable)
(anonymous)
ls @ cloud-explorer.js:1589
cd @ cloud-explorer.js:899
state.onCurrentLocationChanged @ cloud-explorer.js:742
currentLocation.onChanged @ cloud-explorer.js:1266
set_path @ cloud-explorer.js:1147
application.onFileClicked @ cloud-explorer.js:471
fileBrowser.onFileClicked @ cloud-explorer.js:1972
fli.onClicked @ cloud-explorer.js:2290
(anonymous) @ cloud-explorer.js:2395
VM575:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.ce_core_parser_unifile_Json2UnifileError.parseUnifileError (cloud-explorer.js:1450)
    at XMLHttpRequest.req.onload (cloud-explorer.js:1571)
ce_core_parser_unifile_Json2UnifileError.parseUnifileError @ cloud-explorer.js:1450
req.onload @ cloud-explorer.js:1571
XMLHttpRequest.send (async)
(anonymous)
ls @ cloud-explorer.js:1589
cd @ cloud-explorer.js:899
state.onCurrentLocationChanged @ cloud-explorer.js:742
currentLocation.onChanged @ cloud-explorer.js:1266
set_path @ cloud-explorer.js:1147
application.onFileClicked @ cloud-explorer.js:471
fileBrowser.onFileClicked @ cloud-explorer.js:1972
fli.onClicked @ cloud-explorer.js:2290
(anonymous) @ cloud-explorer.js:2395
admin.js:484 GET https://editor.silex.me/js/admin.js.map 503 (Service Unavailable)
```

**Comment by JbIPS** [comment]
Hello @tariqbenezza, could you point us to your repository? It could be something special with it because I couldn't reproduce with one of my repo.

Thank you for the report

**Comment by tariqbenezza** [comment]
Here is my repo :

https://github.com/tariqbenezza/myCV

**Comment by lexoyo** [comment]
I can reproduce, and it is probably due to this repo's number of commits :-(
I have squashed all commits into 1 on [my fork](https://github.com/lexoyo/myCV) as you can see in the commits, and now I can use the repo normally
This is strange since it usually displays another error on save only

To do like me and squash all commits into 1 on your fork, you can do this in the terminal

```
$ git clone git@github.com:lexoyo/myCV.git
$ cd myCV/
$ git reset $(git commit-tree HEAD^{tree} -m "initial commit")
```

Note: [This commands come from this thread on SO](https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one)

**Comment by tariqbenezza** [comment]
Great ! It works perfectly !
Thank you @lexoyo !

P.S : maybe you should force this kind of commands after ~100 commit in the same project

**Comment by lexoyo** [comment]
👍

**Comment by lexoyo** [comment]
@JbIPS what do you think about this idea? 
Will it be the same with unifile 1.0 ?

**Comment by JbIPS** [comment]
The limitations will be the same but a publication will create less commits, thus reducing the need of this.

Anyway, I'll look a way to squash everything with the API.
