### ISSUE TITLE
Impossible d'insérer une fonction javascript précise

### ISSUE THREAD

**Issue by butathermix** [silexlabs/Silex#629]
Bonjour,
lorsque je veux insérer ce code en passant par le javascript editor comme par le bloc html 
function replaceImage(imgid, source, mapid)
{
  var image = document.getElementById(imgid);
  image.src= source;
  var newmap = document.getElementById(mapid);
  var origin = document.getElementById("mapgeneric");
  origin.innerHTML = newmap.innerHTML;
}

j'obtiens après validation

function replaceImage(imgid, source, mapid)
{
  var image = document.getElementById(imgid);
  image.src=%20source;%0D%0A%20%20var%20newmap%20=%20document.getElementById(mapid);%0D%0A%20%20var%20origin%20=%20document.getElementById("mapgeneric");
  origin.innerHTML = newmap.innerHTML;
}

c'est le .src qui est l'origine du dysfonctionnement si je retire cette ligne tout s'édite normalement... mais évidemment la fonction ne marche pas 
Quelqu'un sait il pourquoi ?
Merci

**Comment by tariqbenezza** [comment]
Bonjour @butathermix  !

Avez vous essayé de le faire en jQuery ?

**Comment by butathermix** [comment]
non, je vais regarder comment on fait et essayer... Merci

**Comment by tariqbenezza** [comment]
jQuery est supporté par Silex de façon "native".

Pour le changement de source de l'image il vous suffit de faire quelque chose comme suit :

`$('#imgid').attr('src','source');`

N'hésitez pas si vous avez des questions

**Comment by butathermix** [comment]
Merci :) vous venez juste de répondre à la question que je recherchais sur le net

**Comment by JbIPS** [comment]
Je ferme ce ticket qui me semble résolu, n'hésitez pas à le rouvrir si besoin.

**Comment by butathermix** [comment]
Merci pour vos réponses et désolé de pas avoir répondu plus tôt; malheureusement je n'ai pas réussi à faire tourner cette fonction; mais je suis pas un "cador" je ne fais que recopier ce que je vois sur le net .De toute façon je me suis aperçu après que je ne pouvais pas vraiment m'en servir avec des images "silex" vu qu'il y a un appel à l'ID qui n'est pas référencé dans les propriétés de l'objet image. Je suis donc revenu à la confection d'un site "classique"
