### ISSUE TITLE
Issues with "Visible on" section

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#630]
I added a text box in my website and wanted it to be on every page. First thing I saw, it's not, when I looked closer, it appeared the section might have some problems:  
 ![screenshot](https://user-images.githubusercontent.com/2248473/28224151-54760628-68ce-11e7-8f26-46de81910ea4.png)

I'm on Windows 10, FF 54, on preprod.silex.me with the Ipsoom Center template

**Comment by JbIPS** [comment]
Actually, I'm having that too on editor.silex.me

**Comment by lexoyo** [comment]
I saw that too, but when I refresh it goes away... I suppose you tried already?

**Comment by lexoyo** [comment]
bump

**Comment by JbIPS** [comment]
I'm sorry I didn't had time to retry that. Do you have any idea of what's causing it?

**Comment by singchan** [comment]
No hurry this is not a critical issue
I really don't know and I can not reproduce anymore

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
