### ISSUE TITLE
how can i add i new font option?

### ISSUE THREAD

**Issue by zelo-23** [silexlabs/Silex#631]
I'm limited with several different font options and i'm having some difficulties trying to figure out to add a new one of my own.
And this is what it looks like,
![font1](https://user-images.githubusercontent.com/30077613/28529580-34566098-7091-11e7-9068-874b93e1877c.png)

**Comment by singchan** [comment]
Hello
Here you have some useful info
https://github.com/silexlabs/Silex/issues/46
