### ISSUE TITLE
How to make object only show on mobile?

### ISSUE THREAD

**Issue by IOU4something** [silexlabs/Silex#633]
I need a container or section to only appear when the site is accessed using a mobile device. Is this possible?

**Comment by lexoyo** [comment]
hello
someone asked for a dedicated panel to do that, you can support it or ask questions about it in this issue #623
but for now, this is what you can do:
```
@media only screen and (max-width: 480px), only screen and (max-device-width: 480px){
  /* your CSS for mobile here */
}
```

**Comment by tariqbenezza** [comment]
I'm using what @lexoyo described for my websites @IOU4something til the #623 is done.

Do you think we can close the issue @IOU4something ?

**Comment by IOU4something** [comment]
That seems to be working for me I do appreciate the help you can close the issue.

**Comment by tariqbenezza** [comment]
Thank you @IOU4something !
