### ISSUE TITLE
Linking to anchor tags on the same page

### ISSUE THREAD

**Issue by lslochov** [silexlabs/Silex#634]
Hi, I've been having a lot of fun with Silex, but I've come across a feature I want for my website that I haven't been able to fully figure out. I have one page with a lot of text, so I decided to break it up into sections, and have a table of contents at the top of the page with links to those sections (similar to Wikipedia). I've added anchor tags for all the section headings, but when I set up the anchor links and tested them in the site preview, the view jumps to the right section, then switches to the Home page. Everything's correct, except for that last part—how do I keep from switching to the Home page?

**Comment by tariqbenezza** [comment]
Hi there !

Great to hear that you have fun !

Do you have any URL where I can see it ?
In the meantime I'm trying to reproduce it.

Thank you

**Comment by lslochov** [comment]
Hi, I have the site available at moat.gersteinlab.org

Right now, only the first section in the Table of Contents is linked, but it's sufficient to demonstrate the issue.

Any help you can offer is appreciated.

**Comment by lexoyo** [comment]
Hi @lslochov 
Maybe you should link to `#!page-usage#prereq`
If it does not work, try opening and saving you website with the next version of silex on http://preprod.silex.me

**Comment by lslochov** [comment]
Hi @lexoyo , I tried using #!page-usage#prereq as well as using the preproduction Silex editor. Neither of those things worked.

**Comment by lexoyo** [comment]
Oh ok, I see you updated your site and it does not work

I tried and replace the name `prereq` of your anchor with `!page-usage#prereq` and it seems to work... 

You can do that for now but the best thing to do is to [change the code here](https://github.com/silexlabs/Silex/blob/35e5480a54d28beebab3f92bc51d9ef0c646c173/static/2.7/pageable.js#L76) and add a call to jquery to [scroll to the anchor, like I did in this widget](https://github.com/silexlabs/Silex/issues/417) (look for the phrase "check if there is a hash in the URL to scroll to the anchor at start")

**Comment by lslochov** [comment]
@lexoyo thanks so much, everything's working great now!
