### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by wealthyagainorg** [silexlabs/Silex#635]
![2017-08-27 20_40_59-untitled - paint](https://user-images.githubusercontent.com/31395596/29756336-a0e44788-8b68-11e7-8a13-e4e287d19381.png)
like this or something in the same spirit.

**Comment by lexoyo** [comment]
Hi @wealthyagainorg
Thank you for the proposal!

We have chosen a logo recently, it is the one in the wiki section. So I close this issue now

We would love you to contribute to Silex communicate: https://github.com/silexlabs/Silex/milestone/7
