### ISSUE TITLE
Cannot open editor online

### ISSUE THREAD

**Issue by tommy-qiu** [silexlabs/Silex#637]
![screen shot 2017-09-03 at 1 20 29 am](https://user-images.githubusercontent.com/26195773/30000798-1956e0f4-9046-11e7-96f0-9835160ae62a.png)

**Comment by lexoyo** [comment]
Hello
Thank you for letting me know
The hosting company said they erased the SSL certificate instead of renew it...
I'll take care of this asap. In the mean time you can use preprod.silex.me

**Comment by lexoyo** [comment]
I regenerated the certificate, it is fixed now
