### ISSUE TITLE
My Silex website

### ISSUE THREAD

**Issue by aswathyachu1996** [silexlabs/Silex#639]
[silex-templates.zip](https://github.com/silexlabs/Silex/files/1290745/silex-templates.zip)
Here is a link to a website I did with Silex:

**Comment by aswathyachu1996** [comment]
![google](https://user-images.githubusercontent.com/31824490/30251430-da9ebb42-967c-11e7-9e5c-388091888a75.png)
![linkedin](https://user-images.githubusercontent.com/31824490/30251431-dae432d0-967c-11e7-98e2-41b6e703f49c.png)
![pinboard](https://user-images.githubusercontent.com/31824490/30251432-db0c9a40-967c-11e7-85e0-81dfc9171693.png)
![pinterest](https://user-images.githubusercontent.com/31824490/30251434-db4b17d4-967c-11e7-8e9f-83f5ea81d5f3.png)
![pocket](https://user-images.githubusercontent.com/31824490/30251435-db7f67f0-967c-11e7-95d0-1d551146b8f5.png)
![reddit](https://user-images.githubusercontent.com/31824490/30251436-dba6d2a4-967c-11e7-8861-15af12060964.png)
![stock-vector-school-lesson-little-students-and-teacher-classroom-with-green-chalkboard-teachers-desk-pupils-322062854](https://user-images.githubusercontent.com/31824490/30251437-dbd907ba-967c-11e7-8b55-a82b7d873c23.jpg)
![tumblr](https://user-images.githubusercontent.com/31824490/30251438-dbf02f80-967c-11e7-80bd-bcdaad8fa933.png)
![twitter](https://user-images.githubusercontent.com/31824490/30251439-dc14e44c-967c-11e7-88b2-4680591df492.png)
![wordpress](https://user-images.githubusercontent.com/31824490/30251440-dc34f660-967c-11e7-82c7-0d304d08ec22.png)

**Comment by aswathyachu1996** [comment]
[https://editor.silex.me/api/1.0/dropbox/exec/get/designp.silexsite.com.html#!page-design](url)

**Comment by lexoyo** [comment]
> https://editor.silex.me/api/1.0/dropbox/exec/get/designp.silexsite.com.html#!page-design

this link is visible only by you
