### ISSUE TITLE
Silex next version UI

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#640]
Hello
I have changed the dialogs implementation to cleanup the code
While I was at it I made all dialogs "full screen", what do you think about this change?
Test it online here
http://silex-editor.herokuapp.com/

**Comment by AndreaMonzini** [comment]
Hello, i prefer full screen options like in the  website settings and publishing settings !

I have some questions:
-What about GrapesJS implementations? It could be interesting to merge projects.
-What about integrate Silex into an Electron like  desktop app? sometimes i prefer to manage files locally.

Anyway thank you for your work !

**Comment by lexoyo** [comment]
ok thank you @AndreaMonzini for your support (again 😄)
good to know thx

> -What about GrapesJS implementations? It could be interesting to merge projects.

There was [a discussion here](https://github.com/artf/grapesjs/issues/13) and I also began to split silex into smaller pieces but people would have to integrate them into grapesjs
* the [next version of Cloud Explorer](https://github.com/lexoyo/CloudExplorer2/issues) is separate and made from scratch with cleaner code and components
* [Stage is a "stage" component](https://github.com/lexoyo/stage) meant to replace Silex and grapes' drag drop selection functionality, it is a prototype to show that absolute and relative positioning can be mixed

> -What about integrate Silex into an Electron like desktop app? sometimes i prefer to manage files locally.

I let @JbIPS answer that, he has a working prototype
