### ISSUE TITLE
Unable to connect to Dropbox

### ISSUE THREAD

**Issue by tommy-qiu** [silexlabs/Silex#643]
I click connect to dropbox and no popups show me that lead me to sign in to dropbox.
![screen shot 2017-10-01 at 8 14 20 am](https://user-images.githubusercontent.com/26195773/31054453-d478e7d8-a680-11e7-933b-0a39768a8f8c.png)

**Comment by whitehat91430** [comment]
Hi, I get the same problem since Thursday...

**Comment by lexoyo** [comment]
Me too and I don't understand why :(
I'll probably hurry to release the new version which does not have this bug, instead of loosing so much time on this... and nothing changed on my end for months, see the changes here https://github.com/silexlabs/Silex/commits/master

There are things you can do
* help me test the new version when I call for help like this #640 
* use @jbips offline version, it can read from your hard drive directly, no need for Dropbox then

Thank you, sorry about that

**Comment by felixtkn** [comment]
Same problem! Can't connect to Dropbox! What happened?....

**Comment by lexoyo** [comment]
> Same problem! Can't connect to Dropbox! What happened?....

I don't know dropbox stop working, see my message above

**Comment by lexoyo** [comment]
Ok I found why, dropbox deprecated something we use from the begining of Silex
https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

So the only solution is to release the new version... Working on it. Support welcome

**Comment by lindstromscott** [comment]
I have the same problem but cannot wait for a new release because I am applying for job positions and need to be able to update my CV on my page. Does anyone have a work-around where I can take my site from dropbox and somehow edit it offline?

**Comment by lexoyo** [comment]
Try with the new version (backup everything before)
http://silex-editor.herokuapp.com/

**Comment by Chnoe1502** [comment]
Hi Alex! 

If i try the new version and load my page they write following
![unbenannt1](https://user-images.githubusercontent.com/32568068/31273406-c5e9e796-aa8e-11e7-9657-ebe585623465.png)

**Comment by Chnoe1502** [comment]
@lindstromscott you can edit it with visual studio from Microsoft quick to do the changes and reupload it! please do backups if anything went wrong!

**Comment by fernandammoutinhobarros** [comment]
Same problem here!! What can I do?

**Comment by fernandammoutinhobarros** [comment]
The new version show the same error when I open the files...
I don't have visual studio, how can I solve this?

![image](https://user-images.githubusercontent.com/25388113/31305933-0c2f1d76-ab3d-11e7-8a14-a462ee6b244f.png)

**Comment by fernandammoutinhobarros** [comment]
what hapened to the prepod version, it doesn't work anymore also?
can't load files to the new version with this error... please help!!

**Comment by lexoyo** [comment]
Hi

preprod.silex.me is down because I tried to deploy the new version on it, and the hosting (gandi simple hositng which is free because silex is a "supported project") has an outdate version of some lib that we use in the new version

I'm on it but it  is complicated, sorry about that

**Comment by Chnoe1502** [comment]
Working trough the ftp Client is working now!! You and your team have done so a great work!!! I hope the new version online soon :)

**Comment by lexoyo** [comment]
thx @Chnoe1502 this is greatly appreciated in these time of crisis for silex :)
cc @JbIPS

**Comment by lexoyo** [comment]
@fernandammoutinhobarros there is a new  "new version" deployed on http://silex-editor.herokuapp.com/
Could you test if you still have this message, and [please report the test results here](https://github.com/silexlabs/Silex/issues/646)

**Comment by ocharbon45** [comment]
Hi. This "new version" allow me to conenct on my dropbox, but I can't load pictures from it. There is this error message:
![capture du 2017-10-10 12-56-43](https://user-images.githubusercontent.com/32670669/31383247-9bd45688-adba-11e7-9add-0ef13d91d887.jpg)

**Comment by whitehat91430** [comment]
Hi,same problem as ocharbon45 got... And I cannot access to main web file cause no scroll down possible in window.
Thanks !


 

    Le mardi 10 octobre 2017 à 12:57:55 UTC+2, ocharbon45 <notifications@github.com> a écrit :  
 
 
Hi. This "new version" allow me to conenct on my dropbox, but I can't load pictures from it. There is this error message:

**Comment by lexoyo** [comment]
I'm on it thx

**Comment by soundservice** [comment]
Hi lexoyo and all:  thank you for your efforts in getting Silex back up!  
I managed to connect herokuapp to Dropbox, edit and Save As (although I have to create a new file name each time), publish and preview, however the files are no longer saved to my local Dropbox?

**Comment by goonsoul** [comment]
Hello? Any update? Dropbox is still not letting me sign in and load my website...

**Comment by lexoyo** [comment]
Hello
Yes we work on it
Everything seems to work except publication for now
Can you try and open an issue for each bug you find here please?
https://preprod.silex.me

**Comment by lindstromscott** [comment]
It appears to me to be catastrophically broken. My site was working just
fine and then sometime in the last couple of days it became scrambled like
someone took a blender to it <https://carma.newcastle.edu.au/scott/>. I did
not make any changes to the site, so the change is somewhere in Silex's
files. When I edit it on prepod, it all still looks correct, and then when
I hit "preview" I see the post-food-processor version.

**Comment by lexoyo** [comment]
Aouch this looks like it was broken by an e-tsunami 
As soon as it looks good in the editor it must be something simple
Let me take a look at it soon and get back to you

**Comment by lexoyo** [comment]
@lindstromscott the site https://carma.newcastle.edu.au/scott/ is broken because some of its static assets come from https://silex-editor.herokuapp.com/
And it looks like it is down now. 

Please open the site from https://preprod.silex.me and simply save it. This should fix the bug?

**Comment by lexoyo** [comment]
@lindstromscott I restored the test app https://silex-editor.herokuapp.com/ and your site is back to life
So this was it. Now please open it and save it from preprod as i told you. Then you will need to publish it before you put it online, you know that?

**Comment by lexoyo** [comment]
Everybody with this issue should now follow up here
https://github.com/silexlabs/Silex/issues/646

**Comment by lindstromscott** [comment]
Thanks! This solution worked for me!

**Comment by lindstromscott** [comment]
My website has been scrambled again, and https://preprod.silex.me/ is down
and gives me an error when I try to go there:

"The server is temporarily unable to service your request due to
maintenance downtime or capacity problems. Please try again later."

This is a *very bad time* for my website to be screwed up because I have
multiple job applications out. I can't afford to have my website going down
every day. Can you suggest a different editor or platform which will be
stable? I'll have to make a new website.

-Scott

**Comment by lexoyo** [comment]
Preprod is down, we are close to fix all bugs and release the new vversion. A few days...

But your website is not supposed to be impacted by this. If it is you probably did not publish it? Did you put the editable version online?

**Comment by Chnoe1502** [comment]
Hi  Alex i have published the editable Version of my what can i do that is working in the right way?

http://www.kreativbewegen.at/WinterBearbeitung/Winter.html

Best regards


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Alex Hoyau <notifications@github.com>
Gesendet: Thursday, November 23, 2017 8:35:12 AM
An: silexlabs/Silex
Cc: Chnoe1502; Mention
Betreff: Re: [silexlabs/Silex] Unable to connect to Dropbox (#643)


Preprod is down, we are close to fix all bugs and release the new vversion. A few days...

But your website is not supposed to be impacted by this. If it is you probably did not publish it? Did you put the editable version online?

**Comment by lexoyo** [comment]
In my comment 4 days ago I asked you

> Then you will need to publish it before you put it online, you know that?

I'll do my best to fix preprod today, then you need yo publish your website - read the doc about this

> Can you suggest a different editor or platform which will be stable? 

None is perfect otherwise I would not bother maintaining silex

Wordpress is the most common choice by far
Jekyll is my favorite but it is quite complex

**Comment by lexoyo** [comment]
preprod is back
please publish your websites before puting them online
ask any questions about publication please

**Comment by lexoyo** [comment]
there is a problem with save
i had to shut down preprod

**Comment by Chnoe1502** [comment]
I have done a publish with Opera and ftp today with editor.silex.me was working for me fine!



Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by lexoyo** [comment]
preprod will be back in 2 min
I hope everything will work fine
I already know that publish with dropbox does not work

**Comment by s2065722** [comment]
Meanwhile the Dropbox connect does not work (anylonger?):

After Dropbox login I get the message: "This app is unable to link additional users because it has been frozen pending review."

**Comment by lexoyo** [comment]
Oh boy 🤕 
I requested more users to dropbox, this should work now. Unless I did it on the wrong dropbox app...
Please let me know if it worked?

**Comment by s2065722** [comment]
Nope, not by now:

**Comment by s2065722** [comment]
![unbenannt](https://user-images.githubusercontent.com/34240861/33563423-35717b3a-d918-11e7-9460-c5259d6cac94.JPG)

**Comment by lexoyo** [comment]
do you see the name of the app?

**Comment by s2065722** [comment]
Dropbox shows just this after login. But I guess you can see from the URL,,,

The URL for login is:

https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=ckixgyo62obeo05&state=heknxqjxhpk3xr&redirect_uri=https://preprod.silex.me/dropbox/oauth_callback

After logging in (when the message above is displayed) the URL is:
https://www.dropbox.com/oauth2/authorize?client_id=ckixgyo62obeo05&redirect_uri=https%3A%2F%2Fpreprod.silex.me%2Fdropbox%2Foauth_callback&response_type=code&state=heknxqjxhpk3xr

**Comment by lexoyo** [comment]
Ok, I had to submit the dropbox app for production
I wait for Dropbox dev team to validate it

**Comment by lexoyo** [comment]
> Congratulations, your app's been upgraded to production status! You may now use your app key to make your app available to Dropbox users. Please keep in mind your app must follow the Dropbox branding guidelines.

👍

**Comment by s2065722** [comment]
PERFECT - works fine ;-)

T H A N K S  A   L O T

**Comment by sureshbabue** [comment]
Hi,

Looks like this issue still exists. Please look into this.

**Comment by lexoyo** [comment]
Please use preprod.silex.me for now

**Comment by choufractal** [comment]
Hi, everything worked well until I had to sign in to Dropbox again. I cannot do it and I see no sign in pop up. I tried from preprod.silex.m but it did not help. Any workaround is welcome as I cannot update my professional website anymore.

**Comment by lexoyo** [comment]
Hi
Can you please give more details: do you reconnect by clicking a button in the alert or from the list of services? What happens when you login again?
