### ISSUE TITLE
Predefined namespaces?

### ISSUE THREAD

**Issue by MichalVales91** [silexlabs/Silex#644]
Hello! 

My problem is little complicated: I created my own little custom validator and assigned it to its little den at `$app['validator']` where it's being called from many places in my code. Yup, your web claimed I can use any variables/namespaces I want! (And I didn't know about the existence of _Validator_. And even I do now, I'm totally allright with my own!) Why is it problem?

After some time of development, I "composed" Security Service. Then the scary hell-oops appeared, just on the line 666 of the _SecurityServiceProvider.php_. 

Why is there check `if (isset($app['validator']))` but `if (isset($app['validator.validator_service_ids']))` not? For me - who did not compose validator and only uses this namespace - it's really a hell because _UnknownIdentifierException: Identifier "validator.validator_service_ids" is not defined_ freaks me out.

Well, yeah, I know why and how to solve this, but maybe... Maybe this is much bigger issue: why does some service presume existence of any other just by its most probable location? Going further: why does some service presume existence of any other at all? 

IMHO there should be absolute granularity and user should handle all these interoperative thing himself/herself. 

If it's higher issue and I should write this to Symfony devels, tell me and I'll do. If you think this is just an offtopic complaining, I'm sorry in advance.

Thank you

MV91

**Comment by lexoyo** [comment]
Hi @MichalVales91 
I believe this is the other open source project called Silex
Here this is about Silex website builder, not the php microframework
Sorry about the confusion (and we were there first ;)

**Comment by MichalVales91** [comment]
@lexoyo Omg, doublefacepalm, I'm sooo sorry. :-D

**Comment by lexoyo** [comment]
No, not a problem at all :)
