### ISSUE TITLE
Issue with cloudexplorer to connect on dropbox

### ISSUE THREAD

**Issue by ocharbon45** [silexlabs/Silex#647]
sur/working on: PC linux, Ubuntu 16.04 64bits

Bonjour. Je souhaiterais créer un site internet pour mon association avec l'éditeur Silex. Malheureusement, lorsque je souhaite me connecter à mon compte dropbox, cloud explorer ouvre une fenêtre pour me demander mon autorisation, et lorsque je clique sur "autoriser" rien ne se passe. Comment résoudre ce problème ? Merci par avance pour votre aide.

--

Hi. I would want to create a website for my association with Silex editor. Unfortunately, when I would connect it to my DropBox account, Cloud explorer open a window to ask my authorization, and when I allow it nothing happens. Could you explain me how to resolve this issue ? Thank you by advance for your help !

**Comment by JbIPS** [comment]
A change in Dropbox broke Silex ability to save on it.

You can find workaround in this issue https://github.com/silexlabs/Silex/issues/643

**Comment by ocharbon45** [comment]
Thanks for your answer. I just test this workaround, it conenct to Dropbox but there is an issue with downloading pictures. I'll explain it on #643 ;)

**Comment by lexoyo** [comment]
great thx
