### ISSUE TITLE
[Mobile] [Hamburger] Hide pages in the hamburger menu?

### ISSUE THREAD

**Issue by Tyrael84** [silexlabs/Silex#650]
Is it possible to pick and choose which pages are displayed in the 'hamburger' menu on the mobile version of the site. I would assume it would involve some sort of JS or CSS.

**Comment by lexoyo** [comment]
closing this one as it is a duplicate of #651

**Comment by lexoyo** [comment]
this component is now live on preprod.silex.me for you to test please
