### ISSUE TITLE
Implementing dropdown menu with formspree

### ISSUE THREAD

**Issue by GingerDragon7** [silexlabs/Silex#653]
I am trying to Implement dropdown menu with formspree but it's not happening.
If it's possible please reply anyone.

**Comment by lexoyo** [comment]
Hello
I'm not sure to understand what you want to do exactly?

**Comment by lexoyo** [comment]
hello
I did this widget recently, maybe you can use it instead of the default menu
https://github.com/silexlabs/Silex/issues/659
I will close this issue but feel free to reopen it if you still need answers
