### ISSUE TITLE
Problem with images on FTP

### ISSUE THREAD

**Issue by MarcelloCavallo** [silexlabs/Silex#656]
Using ftp, silex editor load the site's scripts but not the images, and when i tri to upload new images from the silex editor folder it hangs on "loading" and does notgo to work

**Comment by lexoyo** [comment]
Hi @MarcelloCavallo 
So I understood that you use editor.silex.me which is the stable version of silex
I suppose your website with the "broken" images is online? Can I see it please?

**Comment by MarcelloCavallo** [comment]
My site is www.istitutoaden.eu , The problem is not in the online site. The problem is on the copy site I use to update it before I publish it. When I call the site copy with silex editor, silex shows me all the images that are loose in the image folder, but not those that are in other folders divided by topic (you can see "event" menus those photos are divided by topic, each event is a folder) . When I try to work silex editor does not make me see the photos of the "events" menu, i need help because i'm still with the job, i have difficulties even with github and webdav, the dropbox now does not work, thank you for the help you give me .

**Comment by lexoyo** [comment]
Ca you share the site with me on Dropbox or a zip file please? (a.hoyau at im-paris.fr)

**Comment by MarcelloCavallo** [comment]
ok site share, tank you.

**Comment by lexoyo** [comment]
...sorry I have had a hard time working on Silex this week... this week end hopefully will be more productive

**Comment by lexoyo** [comment]
could you tell me if it is still the case on https://preprod.silex.me today please?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
