### ISSUE TITLE
Import not functioning

### ISSUE THREAD

**Issue by dolson89** [silexlabs/Silex#657]
Is anyone having issues with the import function not working? I am truing to use a project saved on dropbox and it failed to work on safari and chrome.

**Comment by lexoyo** [comment]
Hello
Yes there is a problem with Dropbox in Silex, we are working on it. Here is more info and ways to help
https://github.com/silexlabs/Silex/issues/646

**Comment by trevoriancox** [comment]
I am unable to import from dropbox, github or webdav. After attempting github import, I have to clear cookies otherwise the import goes directly to the github screen every time. webdav gives me an error for valid URL & credentials. dropbox does not do anything.

**Comment by lexoyo** [comment]
Hello
Please try on https://preprod.silex.me

**Comment by 27aume** [comment]
I am trying to upload a basic html file and I get the message: 
```
This operation failed with the following error message:

I did not manage to upload the files:

- index.html
<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Internal Server Error</pre> </body> </html> ()
```

**Comment by lexoyo** [comment]
It happens sometimes, the server goes down. Please try again later

Also if you plan to edit an arbitrary html file with silex please read the docs, it explains that it is not possible

**Comment by 27aume** [comment]
Great I'll take more time to dig into it.
Thank you very much for contacting me.
