### ISSUE TITLE
Official silex website is wrong: Wordpress is foss

### ISSUE THREAD

**Issue by diogocsc** [silexlabs/Silex#658]
On http://www.silex.me/, in the comparison table, Wordpress shows as "oss". It has GPLv2...why you say is oss and not foss? Is it a mistake or something else?

**Comment by lexoyo** [comment]
Hello
It is indeed a mistake. It comes from the Wikipedia page here
https://en.m.wikipedia.org/wiki/Silex_website_builder
We should fix it thank youso much

**Comment by diogocsc** [comment]
I managed to create an image with this fixed, but can't find the file in the source code... where is it ?
![silex-tableau-03](https://user-images.githubusercontent.com/1706650/51909403-6f564e00-23c4-11e9-8464-1cfd04f89f57.png)

**Comment by lexoyo** [comment]
Nice!!!
The source of the website is here
https://github.com/silexlabs/www.silex.me

**Comment by lexoyo** [comment]
Hi
Do you need help to fix this?
