### ISSUE TITLE
github error

### ISSUE THREAD

**Issue by MarcelloCavallo** [silexlabs/Silex#664]
`success:false, code:400, message:'Error while calling GitHub API. Error: API rate limit exceeded for MarcelloCavallo.`

**Comment by lexoyo** [comment]
aouch
on preprod?

**Comment by MarcelloCavallo** [comment]
I found the error, the problem is firefox, now i used chrome, and finally silex has worked out the site with all components, assets, css, images, index.html and js, anyway I will do other tests, thanks !!!
