### ISSUE TITLE
Webdav without SSL

### ISSUE THREAD

**Issue by s2065722** [silexlabs/Silex#666]
I am trying to get a webdav connection but I am always getting "Invalid access codes"

When trying the same on https://preprod.silex.me/ I get the Server message: "Cannot GET /cloud-explorer/Internal%20Server%20Error "

What am I doing wrong?

**Comment by JbIPS** [comment]
Hello!  
It looks like your WebDAV server is sending an "Internal Server Error". Could you tell us more about it? Is it a private WebDAV server or a hosted one?

Can you have access to the server log?

**Comment by lexoyo** [comment]
is this solved @s2065722 ?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.
