### ISSUE TITLE
Close a drop down menu

### ISSUE THREAD

**Issue by Rom25** [silexlabs/Silex#667]
Hello, 

I try to make drop down menu, it’s works, but I can not make the menu closed 
Is someone have an idea to help me?

By advance thank you for your Help.

Rom25

HTML: 

                            <ul id="menu-accordeonJ">
                                <li>
                                    <a href="#!page-accueil" class="page-link-active">accueil</a>
                                    <ul>
                                        <li>
                                            <a href="#page1">page1</a>
                                        </li>
                                        <li>
                                            <a href="#!page2" class="">page2</a>
                                        </li>
                                        <li>
                                            <a href="#!page3" class="">page3</a>
                                        </li>
                                        <li>
                                            <a href="#!page4" class="">page4</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                      
CSS

/*menu-accordeon Jaune*/

#menu-accordeonJ {
    padding: 0;
    margin: 0;
    list-style: none;
    /*text-align: center;*/
    text-align: left;
    /*width: 142px;*/
    width: 180px;
}

#menu-accordeonJ ul {
    padding: 0;
    margin: 0;
    list-style: none;
    text-align: center;
}

#menu-accordeonJ li {
    background-color: #565656ff;
}

#menu-accordeonJ li li {
    max-height: 0;
    overflow: hidden;
    transition: all .5s;
    border-radius: 0;
    background: #444;
    box-shadow: none;
    border: none;
    margin: 0
}

#menu-accordeonJ a {
    display: block;
    text-decoration: none;
    color: #fff;
    padding: 8px 0;
    font-family: verdana;
    font-size: 1.2em
}

#menu-accordeonJ ul li a,
#menu-accordeonJ li:hover li a {
    font-size: 1em
}

#menu-accordeonJ li:hover {
    background: #ffcc00
}

#menu-accordeonJ li li:hover {
    background: #ffcc00;
}

#menu-accordeonJ ul li:last-child {
    border: none;
}

#menu-accordeonJ li:hover li {
    max-height: 15em;
}

**Comment by Rom25** [comment]
A  precision, I would like to drop down thé menu after a click on one of his item.

**Comment by lexoyo** [comment]
Hi @Rom25 
There is no javascript? Where did you get this code?

**Comment by Rom25** [comment]
I find a solution with using javascript. i used "onmouseover", "onmouseout" and "onclick".

http://www.frogweb.fr/menu-deroulant-vertical/
