### ISSUE TITLE
Popup not allowed on Chrome

### ISSUE THREAD

**Issue by tariqbenezza** [silexlabs/Silex#668]
Dear all,

I'm using Chrome  62.0.3202.94 with Mac OS El Capitan 10.11.1

It seems that when I want to open my project through preprod.silex.me popups are not allowed.

Here is a preview of what I got : 

<img width="1280" alt="capture d ecran 2017-12-10 a 20 30 22" src="https://user-images.githubusercontent.com/4911564/33808587-955cec66-dde9-11e7-8127-fbe2ad30d748.png">

And here is the error message I caught in error console : 

```
cloud-explorer.js:75 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at XMLHttpRequest.req.onload (cloud-explorer.js:75)
```

It's not a big deal, you just have to let Chrome display this kind of message but for a new user it could be awful.

Thank you in advance.

**Comment by lexoyo** [comment]
Good catch
Did you double click on github or pressed enter?

**Comment by tariqbenezza** [comment]
Thank you for the quick answer @lexoyo 

Both are not allowed by default. And I got the same message for ftp, sftp & dropbox

**Comment by lexoyo** [comment]
Aouch ....
We'll have to investigate that before we can release the new version
This may be why we use to have a 'click here' button in the previous version, displayed after we have the auth url

**Comment by lexoyo** [comment]
Ce bug est fixé
Merci de tester sur preprod
A+
