### ISSUE TITLE
flash to your website

### ISSUE THREAD

**Issue by firewars74** [silexlabs/Silex#669]
Can i add flash (swf) to my website ?

**Comment by lexoyo** [comment]
Hi @firewars74 
It is possible with the HTML box. 
It would be great if you could try and answer more in depth @Tyrael84 @MarcelloCavallo @AndreaMonzini @MissRenegade @arasexyz @parkadia @fernandammoutinhobarros @bialyjerozy @parkadia @bialyjerozy @Chnoe1502 @clemos ?

**Comment by JbIPS** [comment]
This issue seems inactive, feel free to reopen if it's not resolved.

**Comment by lexoyo** [comment]
Sorry @firewars74 
Our ~robot~human friend @JbIPS has shut down the discussion 🗡 
 Feel free to ask for help again, people sometimes need some tears to react
