### ISSUE TITLE
Toggle items visibility on/off when clicking a button ?

### ISSUE THREAD

**Issue by Barbolux** [silexlabs/Silex#670]
Hi Silex Team! first of all THANKS and congratulations for the app, i wish all the best for the prosperity of this project. We are using it to develop a very important website of educational purposes in the department of computer science where I belong. Please c'mom for a visit https://barbolux.github.io/eletronica/ (content in portuguese).

Let me explain the feature which i'd like to learn about. In the bottom of all pages I want to put a single button that, when clicked, turns "on" or "off" some elements that could be found on all pages, like an extra layer of information. We want to include question balloons with some doubts or reflections for the visitors, but this shall not be visible all the time. When he wants to enter the "questions mode", a button will display these images and texts that were hidden.

How can I achieve this? thx in advance,
Stefano (Barbolux Developer)

**Comment by JbIPS** [comment]
Hello @Barbolux !

Thank you for your support, it means a lot and we're very hyped that Silex is used for educational purpose! If you're ok with that (and @lexoyo too) we can add your website in our showcase.

About your feature, I'd make use of CSS classes:
* Add a class like `extraInfos` on each element you want to hide (use the "Styles"->"CSS Classes")
* In the CSS editor, add a rule for your class
```css
.extraInfos {
  visibility: hidden;
}
.extraInfos.show {
  visibility: visible:
}
```
* In the JS editor, create a function that will overwrite this rule:
```js
function toggleInfos() {
  document.getElementsByClassname('extraInfos').forEach((elem) => elem.classList.toggle('show'));
}
```
* Add a click listener on your button that will call the function `toggleInfos`.

Let me know how that went 😉

**Comment by Barbolux** [comment]
Hi JbIPS & lexoyo, we appreciate the invitation. It's cool for us to be part of such showcase, but first we need to reach at least the first "release version" of our site, which will happen in a month or so. Then, I will send a message to you, thanks!

As for solving the question, I could easily add the classes to the elements and they disappear when I did add the CSS rule (so I need to comment the rule to see the elements again if I need to edit something, but that's ok). I did create the JS function in the editor.

But I didn't managed to add the click listener to a button. I searched on the internet some different ways of doing that but I could not learn how to make none of them work. Please help me.

Thanks, Stefano.

**Comment by JbIPS** [comment]
You should use the `.onclick` property of your button, like:
```js
myButton.onclick = function() {
  toggleInfos();
};
```

I recommend you to look at [DevDocs.io](http://devdocs.io/dom/globaleventhandlers/onclick) for a complete HTML/CSS/Dom reference 😉

**Comment by lexoyo** [comment]
and feel free to ask for more help with a specific example, a website you share online or something specific

**Comment by lexoyo** [comment]
I'll close this issue but feel free to reopen it
