### ISSUE TITLE
PHPBB/XenForo sur mon site silex

### ISSUE THREAD

**Issue by starvecraft** [silexlabs/Silex#671]
Pourrais je faire un forum sans iframe sur silex ?

**Comment by JbIPS** [comment]
Bonjour,

Désolé, cela est impossible. Un forum PHPBB a besoin d'un hébergement sur un serveur PHP et une base de données.

Silex ne fait que des pages HTML statiques, ce qui ne sera pas d'une grande aide pour un forum.

**Comment by lexoyo** [comment]
Cela dit si vous avez un phpbb, il y a probablement une API qui permettrait a un script js de charger les infos et de les mettre dans une HTML box qui est juste une div pas une iframe
Est ce que tu cherches?
