### ISSUE TITLE
impossible d'accéder à la dropbox :(

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#673]
Bonsoir,
je découvre tout juste Silex,
je crois que je trouve ça super, 
je lance un tutoriel quand même pour débuter
(je ne suis paaaaaaas du tout programmeuse ou informaticienne!) et...
... impossible de connecter la dropbox à l'interface Silex :(
(entre temps : je lis les commentaires en anglais qui ont eu le même problème mais je ne comprend toujours rien... entre temps : je télécharge github et alors là c'est carément le découragement quasi total...).
Pourriez vous m'aider ?
Je vous remercie bien... :(

**Comment by Lea75** [comment]
Bonjour et merci beaucoup de votre réponse. Je trouve votre démarche tellement cool...!!!
Ce week-end, j'avais réussi avec l'ancienne version silex et github à faire ça : https://auxcouleurs.netlify.com/ (création de la première page seulement : ACCUEIL)

Puis j'avais passé des heures pour faire les 3 autres pages... mais là ce fût le drame au moment de le passer sur github puis sur netlify donc (je crois) que j'ai perdu tout le travail que j'avais fait dans silex :(
Je viens de ré-essayer ce soir de créer mon site, à partir de la version test de silex et la dropbox :)
Je suis arrivée à ça en quelques heures : https://auxcouleursduyoga.netlify.com/
Je ne suis pas (tout à fait) satisfaite : entre autre, je trouve le fond pas super, je préférais le ciel bleu que j'avais mis la première fois (mais je n'ai pas réussi à mettre une photo de fond cette fois) et je n'ai pas pu modifier la 4ème page (REMERCIEMENT) qui semble associée à la 3ème (VINIYOGA).
J'ai noté plusieurs questions/remarques à propos de la version test : si vous le souhaitez je peux vous les envoyer ou passer vous voir pour vous en parler.

De toute manière, je trouve votre activité tellement super que je souhaiterais aussi m'investir dans votre association. A quel niveau je ne sais pas : à voir en fonction de vos besoins, de mes disponibilités (qui sont assez réduites!) et de mon niveau informatique (qui n'est pas du tout énorme!!).
Concernant mon site, c'est un site que je diffuserais cet été donc j'ai largement le temps de le paufiner.

Merci en tout cas et à bientôt
Léa




 

    Le lundi 18 décembre 2017 à 13:28:05 UTC+1, Jean-Baptiste Richardet <notifications@github.com> a écrit :  
 
 
Bonjour @Lea75 ! Merci pour ton soutien et désolé de ces quelques accroches lors de ton premier essai.

Depuis la dernière version de Dropbox, Silex ne peut plus s'y connecter. Mais pas d'inquiétude, une nouvelle version sortiratrès bientôt. Tu peux la tester dès maintenant sur http://predprod.silex.me 😉
 
Pour ce qui est de GitHub, nous serions ravi de t'aider mais peux-tu préciser ton problème ?

**Comment by JbIPS** [comment]
Bonjour,

Le timing est parfait, jeudi (21 décembre) c'est notre meetup mensuel de l'association (https://www.silexlabs.org/event/aperopensource-46-edition-de-noel/), ce sera le moment parfait pour rencontrer les membres et échanger avec eux. Nous avons tous des parcours très différents, je suis sûr que tu trouveras ta place ! Et en plus tu pourras rencontrer les développeurs de Silex comme @lexoyo ou @tariqbenezza pour parler améliorations :wink:
-- 
Jean-Baptiste Richardet

**Comment by Lea75** [comment]
C'est noté. Je serais la jeudi. Merci!!
--------------------------------------------
En date de : Mar 19.12.17, Jean-Baptiste Richardet <notifications@github.com> a écrit :

 Objet: Re: [silexlabs/Silex] impossible d'accéder à la dropbox :( (#673)
 À: "silexlabs/Silex" <Silex@noreply.github.com>
 Cc: "Lea75" <lea.orellana@yahoo.fr>, "Mention" <mention@noreply.github.com>
 Date: Mardi 19 décembre 2017, 8h51
 
 Bonjour,
 
 
 
 Le timing est parfait, jeudi (21 décembre) c'est notre
 meetup mensuel de l'association
 (https://www.silexlabs.org/event/aperopensource-46-edition-de-noel/),
 ce sera le moment parfait pour rencontrer les membres et
 échanger avec eux. Nous avons tous des parcours très
 différents, je suis sûr que tu trouveras ta place ! Et en
 plus tu pourras rencontrer les développeurs de Silex comme
 @lexoyo ou @tariqbenezza pour parler améliorations :wink:
 
 -- 
 
 Jean-Baptiste Richardet
 
 
 
 On December 19, 2017 12:11:24 AM GMT+01:00, Lea75
 <notifications@github.com> wrote:
 
 >Bonjour et merci beaucoup de votre réponse. Je trouve
 votre démarche
 
 >tellement cool...!!!
 
 >Ce week-end, j'avais réussi avec l'ancienne
 version silex et github à
 
 >faire ça : https://auxcouleurs.netlify.com/ (création
 de la première
 
 >page seulement : ACCUEIL)
 
 >
 
 >Puis j'avais passé des heures pour faire les 3
 autres pages... mais là
 
 >ce fût le drame au moment de le passer sur github puis
 sur netlify donc
 
 >(je crois) que j'ai perdu tout le travail que
 j'avais fait dans silex
 
 >:(
 
 >Je viens de ré-essayer ce soir de créer mon site, à
 partir de la
 
 >version test de silex et la dropbox :)
 
 >Je suis arrivée à ça en quelques heures :
 
 >https://auxcouleursduyoga.netlify.com/
 
 >Je ne suis pas (tout à fait) satisfaite : entre autre,
 je trouve le
 
 >fond pas super, je préférais le ciel bleu que
 j'avais mis la première
 
 >fois (mais je n'ai pas réussi à mettre une photo
 de fond cette fois) et
 
 >je n'ai pas pu modifier la 4ème page (REMERCIEMENT)
 qui semble associée
 
 >à la 3ème (VINIYOGA).
 
 >J'ai noté plusieurs questions/remarques à propos
 de la version test :
 
 >si vous le souhaitez je peux vous les envoyer ou passer
 vous voir pour
 
 >vous en parler.
 
 >
 
 >De toute manière, je trouve votre activité tellement
 super que je
 
 >souhaiterais aussi m'investir dans votre
 association. A quel niveau je
 
 >ne sais pas : à voir en fonction de vos besoins, de mes
 disponibilités
 
 >(qui sont assez réduites!) et de mon niveau
 informatique (qui n'est pas
 
 >du tout énorme!!).
 
 >Concernant mon site, c'est un site que je
 diffuserais cet été donc j'ai
 
 >largement le temps de le paufiner.
 
 >
 
 >Merci en tout cas et à bientôt
 
 >Léa
 
 >
 
 >
 
 >
 
 >
 
 > 
 
 >
 
 >Le lundi 18 décembre 2017 à 13:28:05 UTC+1,
 Jean-Baptiste Richardet
 
 ><notifications@github.com> a écrit :  
 
 > 
 
 > 
 
 >Bonjour @Lea75 ! Merci pour ton soutien et désolé de
 ces quelques
 
 >accroches lors de ton premier essai.
 
 >
 
 >Depuis la dernière version de Dropbox, Silex ne peut
 plus s'y
 
 >connecter. Mais pas d'inquiétude, une nouvelle
 version sortiratrès
 
 >bientôt. Tu peux la tester dès maintenant sur
 http://predprod.silex.me
 
 >😉
 
 > 
 
 >Pour ce qui est de GitHub, nous serions ravi de
 t'aider mais peux-tu
 
 >préciser ton problème ?
 
 >
 
 >—
 
 >You are receiving this because you were mentioned.
 
 >Reply to this email directly, view it on GitHub, or mute
 the thread.
 
 >    
 
 >
 
 >-- 
 
 >You are receiving this because you commented.
 
 >Reply to this email directly or view it on GitHub:
 
 >https://github.com/silexlabs/Silex/issues/673#issuecomment-352587624
 
 
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by lexoyo** [comment]
should I close this discussion? 
ou bien on parle du prochain apéro? ;)

**Comment by Lea75** [comment]
Bonjour, j'ai encore du mal a comprendre "de quelle conversation" on parle. J'ai compris il n'y a pas longtemps que les mails qu'on s'envoie a partir de notre boîte mail perso s'affichent en fait sur le "forum" (s'il s'agit bien d'un forum?!). Bref je remercie pour la dernière réponse, a laquelle je n'avait pas répondu. J'aimerai savoir si je peux parler a quelqu'un de silex en privé? Je suis vraiment intéressée pour rendre la création de site via silex d'avantage accessible a des gens comme moi, je suis prête a m'investir mais je crois que ça nécessite une rencontre parce qu'autant je ne comprends pas bien comment est structurée votre "service" autant je pense qu'il est aussi bien difficile pour vous de situer les incompréhensions des (ultra)néophytes comme moi et que sans se rencontrer a nouveau et même sans ordinateur, ça sera difficile pour moi d'apporter une quelconque contribution  :) j'aimerai aussi vous demander quelques petites choses par rapport a mon site pro, que je dois bientot mettre en ligne, si c'est possible. Bref : quelqu'un est-il disponible pour une rencontre dans les prochains jours afin de parler de tout ça?
Sur ce roman, je vous laisse et vous remercie a nouveau de ce que votre association met en place.
À bientôt.
Lea
--------------------------------------------
En date de : Dim 7.1.18, Alex Hoyau <notifications@github.com> a écrit :

 Objet: Re: [silexlabs/Silex] impossible d'accéder à la dropbox :( (#673)
 À: "silexlabs/Silex" <Silex@noreply.github.com>
 Cc: "Lea75" <lea.orellana@yahoo.fr>, "Mention" <mention@noreply.github.com>
 Date: Dimanche 7 janvier 2018, 13h20
 
 should I close this discussion?
 
 ou bien on parle du prochain apéro? ;)
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by lexoyo** [comment]
Hello
Qqn a répondu a tes questions léa?
Tu es la bienvenue sur le chat pour fixer des rdv, discuter de l'asso et de silex
https://framateam.org/signup_user_complete/?id=x1ay4zdjdffh5j67xzkfsofpyw
J'ai de nouveau besoin de testeurs
En attendant je ferme cette issue
