### ISSUE TITLE
Can't add video using html5

### ISSUE THREAD

**Issue by deffciu** [silexlabs/Silex#674]
Hey, I can easily add a video using that jquery plugin, but if I try to do this by the simple method, only the psoter shows up.
![image](https://user-images.githubusercontent.com/25335702/34184257-08a52530-e51f-11e7-8c05-a08e3a9a7357.png)

![image](https://user-images.githubusercontent.com/25335702/34184290-26e1f244-e51f-11e7-9024-8de4a317aecb.png)

I tried using the same files on my local machine (not github) and it worked.. Any ideas?

**Comment by deffciu** [comment]
All the files are in the same folder as html file

**Comment by lexoyo** [comment]
yes I think we have trouble with the URLs being re-written by silex
if you re-open your site, did the HTML change?
could you try on https://preprod.silex.me please?

**Comment by lexoyo** [comment]
I will soon start to work on several problems concerning URLs in Silex
Let me know if you can test
