### ISSUE TITLE
Impossible de publier mon site Silex bug (French)

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#679]
Bonjour à tous, cela fait quelques semaines que je bosse sur mon site,
 hier je décide donc de le publier .
je vais donc dans les paramètres afin de sélectionner le dossier pour publier.
Je lance la publication, Silex commence à faire son travail, puis message d'erreur

Voici une capture d’écran.
Je précise que je suis sous DropBox.

Merci d'avance pour vos solutions.

![capture du 2018-01-19 13-53-53](https://user-images.githubusercontent.com/35597855/35152331-4fe8c224-fd22-11e7-8867-71e36b22111e.png)

**Comment by PTslx** [comment]
Try to compress your images or the material you use. If there are a lot of pictures with the size of > 2 MB you can't publish it.

Try to compress using this: http://webresizer.com/resizer/

**Comment by lexoyo** [comment]
Ca dit de réessayer plus tard, tu as réessayé?

Nice @PTslx webresizer.com

**Comment by lexoyo** [comment]
Tu peux me partager ton site sur dropbox (a.hoyau at im-paris.fr)

**Comment by PTslx** [comment]
I've had multiple problems with my site too. However i found a solution for me by building my site somewhere else...

But do you want me to send you the site for bugfix-analysis?

**Comment by lexoyo** [comment]
Yes please

**Comment by BaguetteAgile** [comment]
J'ai compressé toutes mes photos et le problème reste le même.
@lexoyo j'ai bien essayé une dizaine de fois, toujours le même message ...

Peux tu me donner la marche à suivre pour partager mon site avec toi @lexoyo 

Merci .

**Comment by lexoyo** [comment]
dans dropbox tu peux partager le dossier dans lequel tu as le site et les images
utilises mon adresse a.hoyau at im-paris.fr

**Comment by PTslx** [comment]
How big is your assets folder now?

**Comment by BaguetteAgile** [comment]
Sa avance, seulement quelques fichiers non chargés ...
![capture du 2018-01-21 17-12-53](https://user-images.githubusercontent.com/35597855/35196183-f00225fe-fece-11e7-95ce-fe60c5a538a5.png)

**Comment by PTslx** [comment]
I can take a look at your site. But I am limited to 20-30mins that i can spend on that.
Additionally I am not a staff member so if there is a problem on the server-side i wont be able to fix it. But I think it is the website size and the filenames.

You may send me your project with pictures via mail: chris@wegwerfemail.info - This is just some temporary mail address and not my private one. I will reply you via my private email address

**Comment by PTslx** [comment]
Or better you send me the links of the dropbox folders as you said you publish on dropbox

**Comment by PTslx** [comment]
I have received your project. See my respond i sent to your email

**Comment by lexoyo** [comment]
Thank you @PTslx for your help, you should check these images probably don't exist or something
Baguette agile, peux tu voir avec Monsieur qui se propose d'aider... Les warnings ne sont pas trop graves

**Comment by BaguetteAgile** [comment]
Je viens de partager un dossier Complet via Dropbox...
@PTslx   @lexoyo

**Comment by lexoyo** [comment]
@PTslx Did you have a chance to test?

**Comment by BaguetteAgile** [comment]
I think we can solve it because now it works.
Some photos of the site were superior to 2Mo.

Thanks for your help .

I have a Flickr gallery in the site, the problem is that I have to manually reload the page to see the photos, otherwise we only see the HTML container, an automatic solution to the loading of the page?

***************************************************

Je pense que l'on peut mettre en résolu, car maintenant cela fonctionne.
Certaines photos du site été supérieur à 2Mo.

Merci pour votre aide .

J'ai une galerie Flickr dans le site, le soucis est que je doit recharger manuellement la page pour voir les photos, sinon on aperçois que le container HTML, une solution automatique au chargement de la page ?

**Comment by lexoyo** [comment]
Ok super! Thank you @ptslx to have tried

Tu peux partager un lien avec nous vers ton site en ligne ? Je ne comprends pas l'histoire du rechargement
