### ISSUE TITLE
Having major problems with mobile version

### ISSUE THREAD

**Issue by PTslx** [silexlabs/Silex#680]
Hey,

I have built a website for days and when i wanted to publish it i experienced major problems with the website on big windows tablets and on mobiles (even if the mobile version is activated).

I did not manage to fix it. It is a total chaos. Is there some Silex Developer who can help privately?
I'd appreciate this a lot. Even with research I could not fix it. Maybe there are multiple bugs...

Best regards

**Comment by lexoyo** [comment]
Hi
There are people who can help, but first can you put it online somewhere or take screenshots so that I see what happened?

**Comment by PTslx** [comment]
I wrote you an E-Mail to the mail address in your profile

**Comment by lexoyo** [comment]
can you please put it online somewhere or take screenshots so that I see what happened?
