### ISSUE TITLE
Problème chargement de page Flickr

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#682]
Voici le lien vers le site
 https://justfriends.netlify.com/
au chargement de la page Diaporama, le container HTML reste blanc...
il faut Recharger la page manuellement pour voir les photos.

une idée pour résoudre ce petit problème ?

Merci

@lexoyo 

**********************************************************

Here is the link to the site 
https://justfriends.netlify.com/
when loading the Slideshow page, the HTML container remains blank ...
you have to reload the page manually to see the pictures.

an idea to solve this little problem?

Thank you

**Comment by lexoyo** [comment]
Ok, il se passe un truc étrange, qui doit etre fait par le diaporama que tu utilises
Il rajoute plein de `<script async="" src="https://widgets.flickr.com/embedr/embedr-4110feef4aefd18270192d8aeba3ff41.js"></script>`
Tu peux en dire plus sur le diaporama que tu utilises?

**Comment by BaguetteAgile** [comment]
Ben en faite j'ai suivis le tuto que tu as fais via Webinar ...  je copie coller le code et voila le résultat.. rien de plus...
a mon avis le site Flickr ajoute des demandes via le css...
(je ne suis pas développeur ...)

**Comment by lexoyo** [comment]
ah :-/
tu ne veux pas utiliser le composant diaporama inclus dans silex ? (menu +)

**Comment by BaguetteAgile** [comment]
Oui oui, j'y ai jeter un œil, mais j'ai environ 50 photos à diffuser sur le site et certainement d'autre qui vont suivre, et il me semble que l'on doit sélectionner les photos une par une ?
Existe t'il une solution pour sélectionner mon dossier directement sur Flickr, comme cela je n'alourdis pas trop mon site...
ou alors inclure un lien vers mon dossier Flickr aprés quelques clics par exemple...

Je me penche sur le sujet demain, et je reviens vers toi @lexoyo

**Comment by lexoyo** [comment]
Ah ok je comprends
Je vais debuguer ton code alors

**Comment by lexoyo** [comment]
Quelques remarques et questions:

* La photo "photogroupe" de l'accueil, il faut la mettre en "background image" plutot qu'une "image", pour que ca se redimmentionne correctement quand tu l'étires en css. Et la photo contient des caracteres chelous que tu devrais enlever, car visiblement silex n'aime pas (c'est un bug, je le note). Tu peux tester avec la preview "responsize" 
![screenshot from 2018-02-03 16-09-43](https://user-images.githubusercontent.com/715377/35768471-adfc0782-08fc-11e8-91a9-f930525a0ab0.png)

* tu n'as pas utilisé de sections, tu as tout fait a la main, j'aimerais savoir si c'etait galère et pourquoi ne pas utiliser de sections? Peut etre est-ce mal documentéo ou pas pratique?

**Comment by lexoyo** [comment]
J'ai fix un probleme dans silex qui changeait l'iframe en partant du principe qu'elle avait un src
https://github.com/silexlabs/Silex/commit/2ccc59f271284c364846cbd982cbac94580586e7

Et j'ai changé ton code pour que le script de flickr soit ajouté uniquement quand on arrive sur la bonne page, et pas 2 fois, et seulement quand on est en "silex-runtime" (en dehors de l'éditeur) :
```
            <script>
                // remove useless scripts previously created by flickr (last time the file was opened)
                $('script[src^="https://widgets.flickr.com/"]').remove();
                $('script[src^="https://embedr.flickr.com/assets/embedr-loader.js"]').remove();
              var pagedContainer = document.currentScript.closest('.paged-element');
              var flickrDone = false;
              $('body.silex-runtime').on('pageChanged', function (event, pageName) {
                if(!flickrDone && (!pagedContainer || $(pagedContainer).hasClass(pageName))) {
                  $('body.silex-runtime').append('<script async="" src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></scr' + 'ipt>');
                  flickrDone = true;
                }
              });
            </script>
            <p>Diaporama Just-Friends 2017</p>
            <a data-flickr-embed="true" href="https://www.flickr.com/photos/141930347@N02/albums/72157688805882072" title="Just-Friends en 2017">
                <img src="https://farm5.staticflickr.com/4735/39350048281_bd20945d13_z.jpg" alt="Just-Friends en 2017" width="100%">
            </a>
```

Par contre toutes plein d'images sont introuvables car silex les cherche dans "Images" alors qu'elles sont a la racine du site... Tu as du les déplacer, je te suggere de les remettre dans "./Images/"

N'hésites pas si tu as des questions

PS: ca serait bien de mettre ce nouveau code ou un lien vers cette issue là ou tu as trouvé un tuto?

**Comment by BaguetteAgile** [comment]
Bonjour Mr Alex ;)

tout d'abords Merci pour ton projet de malade qui tiens super bien le route ...

en faite, le groupe de musique ( dont je fais parti) a besoin d'un site internet, comme c'est moi le plus jeune, j'ai dit Ouai je le fait... bon bref... étant débrouillard en informatique, pas peur, mais aucune connaissance en CSS et HTML, alors je cherche cherche et un jour je tombes sur Silex .) je regarde tes tutos et je me lance...

tout ça pour te dire que j'ai commencer le projet sur page blanche et ainsi de suite le site c'est construit , car j'avais pas trop envie de commencer le site via une Template.
Pour la mise en page du site pas de problème majeur avec Silex, en suivant tes tutos sa passe pour les codes CSS  ;)
par contre, je rencontre des soucis sur la mise en page pour les Tablettes ( pour les Smartphones via Silex OK ) donc je regarde sur le net les "Medias Query" , ben là, je n'arrive pas avec les "Points de ruptures" ( différents écrans ) ... je rencontre également des soucis avec les ( z-index: ... ; )

Ton Débugage pour le diaporama fonctionne super Merci. ( Si dans l'avenir je remets un diaporama via Flickr est-ce que je dois faire appel a toi ? )

Tu ma conseillé, de mettre la "photodegroupe" en Container, ce que j'ai fait ( j'ai du retravaillé la photo ... ) mais il me semble que lors de la "Réduction d'écran pour simuler  le "Responsive" , le bloc Container ne s'adapte pas a la page, arrivé un moment donné, la photo reste fixe et je perds un partie de l'image.

Encore Merci pour ton engagement, c'est cool ;)

A bientôt pour la suite du développement du projet.

BaguetteAgile  ;)

Tel: 0498/492 022
[carte de visirte Facebook.png]

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------
