### ISSUE TITLE
Cannot sync drop box insilex

### ISSUE THREAD

**Issue by drtoutdoors** [silexlabs/Silex#683]
I keep clicking the drop box icon to add an image, but it wont do anything

**Comment by drtoutdoors** [comment]
to clarify i click the icon and the "CLICK HERE" pops up, but does nothing

**Comment by lexoyo** [comment]
Hi this is a known bug
https://github.com/silexlabs/Silex/issues/646

Please use another service or test the beta version here 
https://preprod.silex.me
