### ISSUE TITLE
How to add the code in silex site

### ISSUE THREAD

**Issue by promarketer2018** [silexlabs/Silex#684]
Hi ,
How is it possible to add following code in silex based site?

<div id="_TC_PB_BANNER"></div>
<script type="text/javascript">
_TRIPLECLICKS_PB_BANNER_URL="//www.tripleclicks.com/pbBanner.php?sfiid=13591009&view=T&curr=USD";
</script>
<script type="text/javascript" src="//www.tripleclicks.com/common/pbBanner.js"></script>
regards

**Comment by lexoyo** [comment]
Oh my! Ads are coming ;)

Hi @promarketer2018 
You should add it to an HTML Box, see the [HTML Box docs here](https://github.com/silexlabs/Silex/wiki/editor-ui#html)
