### ISSUE TITLE
Authorize dropbox

### ISSUE THREAD

**Issue by yeders** [silexlabs/Silex#685]
Using the editor:https://editor.silex.me/
I am attempting to load one of the templates obtained from here: http://templates.silex.me/
I load the template folder (unzipped) to my dropbox.
in the editor I then attempt to open this from my dropbox, but clicking on the "authorize" CLICK HERE to authorize Cloud Explorer to use your Dropbox account. doesn't actually do anything?

Whilst attempting to authorise GitHub does work.

Further, dragging and dropping the folder from my windows folder also gives me an error:
"The request has failed. Continue"

Unless I'm not doing it correctly, or I am not dragging the folder in the right way?

**Comment by yeders** [comment]
If I click on the import function, then find "editable.html" as instructed, I then get the error: This folder can only contain folders. Files can go in sub-folders. Continue.

**Comment by lexoyo** [comment]
Hi @yeders 
Many questions here ;)

1- Dropbox changed its API recently and it broke the integration in Silex. We are working on the next version of Silex and it will fix this issue. You can test the new version and probably start using it with Dropbox: https://preprod.silex.me

2- The templates are now integrated in Silex, no need to import a zip file, just click the template you want on the Dashboard, see [the docs for the Dashboard here](https://github.com/silexlabs/Silex/wiki/editor-ui#dashboard)

3- The error "This folder can only contain folders." is when you try to write in Github at a path which can not contain files. In github, you can put files only in the 3rd level: `/github/repo/branch/*`, let me know if it is not clear (we probably need a wiki page about that)

**Comment by yeders** [comment]
thanks for replying to my many questions! I was kind of lost (clearly).
