### ISSUE TITLE
Dropbox not working

### ISSUE THREAD

**Issue by Raj2032** [silexlabs/Silex#689]
For some reason when I want to save my work, when I am presented with a bunch of options as to which cloud provider I want to use, when I click on Dropbox, nothing happens at all. I have tried using different browsers but it does not make a difference.

**Comment by lexoyo** [comment]
Hi @Raj2032

It is a known bug, we are working on it. You can use the version in development here it will work: https://preprod.silex.me

And here is more info about the bug and how to help testing it
https://github.com/silexlabs/Silex/issues/646

**Comment by Raj2032** [comment]
Thanks man :)

Also is it possible to include more cloud providers such as Google Drive?

**Comment by lexoyo** [comment]
I would love to see Google Drive, and yes it is possible. It involves 
Javascript and here is more info (Silex uses unifile to access cloud 
services): https://github.com/silexlabs/unifile#add-a-service

Let us know if you can help with this, we will guide you

**Comment by Raj2032** [comment]
Thanks man you're the best =D

**Comment by Raj2032** [comment]
Hey man, do you know how to add taskbars such as menus and stuff, and how
to add buttons that take you down a page?

**Comment by lexoyo** [comment]
taskbars? like the skill bars in the "+" menu?

most of the things like these are widgets, which we will eventually make components in the "+" menu
for now most of them are still widgets
click on the "?" menu ![screenshot from 2018-02-15 11-12-41](https://user-images.githubusercontent.com/715377/36251335-2c29651c-1241-11e8-8607-70f7572de7b7.png)

...and then "download widgets"

**Comment by Imerion** [comment]
This is a very cool and useful program. Just discovered it and I really like what you have done.
I too encountered this bug, but will test the next version and see if it works. However, I was wondering if it would be possible, especially for the desktop version, to make it possible to just save everything as it is locally, on my harddrive? I would much prefer to have my whole page structure in a local folder and then upload that to my server manually.

**Comment by lexoyo** [comment]
> I was wondering if it would be possible, especially for the desktop version, to make it possible to just save everything as it is locally, on my harddrive? 

Yes you can, the desktop version has a "fs" service which is you hard drive, you can save or open or publish to/from your hard drive
![screenshot from 2018-02-17 20-19-06](https://user-images.githubusercontent.com/715377/36344795-da93a538-141f-11e8-862b-ff0915acdd25.png)

![screenshot from 2018-02-17 20-19-13](https://user-images.githubusercontent.com/715377/36344794-da434610-141f-11e8-9af1-8bd0714409c2.png)

**Comment by Imerion** [comment]
That seems perfect! But whenever I click save, save as or publish I get a Cloud Explorer dialog that only has Dropbox, Web Server, FTP and Webdav. I got the version called 1.0.0 RC1 and I'm using Ubuntu Linux 17.10.

**Comment by Raj2032** [comment]
I never knew that there was a desktop version of it. Do you know any
widgets that add the menu bar and other buttons?

**Comment by Raj2032** [comment]
Also how do I download the software?

**Comment by lexoyo** [comment]
> I never knew that there was a desktop version of it. Do you know any widgets that add the menu bar and other buttons?

did you see the widgets? you can copy-paste code to have menu bar

> Also how do I download the software?

I guess you are talking about the desktop version? 
You can download the current version for linux here https://github.com/silexlabs/Silex/releases

> That  seems perfect! But whenever I click save, save as or publish I get a  Cloud Explorer dialog that only has Dropbox, Web Server, FTP and Webdav.  I got the version called 1.0.0 RC1 and I'm using Ubuntu Linux 17.10.

If you want a newer version (or the windows or mac versions), you need to follow the instructions here "[Installation on your local computer](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#installation-on-your-local-computer)" and here ["Silex desktop version"](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#silex-desktop-version)

**Comment by Imerion** [comment]
Ah, then I get it. Thanks!

**Comment by Raj2032** [comment]
Thanks man :) But I can't find any good widgets

**Comment by lexoyo** [comment]
Can you give me an example of a widget you would like?

**Comment by Raj2032** [comment]
Like menu bars for example, do you know any?
