### ISSUE TITLE
Feature request: text styles editor 

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#690]
Following [the issue about Silex text editor](https://github.com/silexlabs/Silex/issues/662) which is bugguy and has many limits

I think we should add a toolbox to customize text styles (base, h1, h2, h3, and custom ones). A bit [like they do it on typography.js website](https://kyleamathews.github.io/typography.js/)

**Comment by lexoyo** [comment]
Here is where I am today cc  @budislav

![screenshot from 2018-03-26 21-58-42](https://user-images.githubusercontent.com/715377/37929668-e64bba08-3140-11e8-93ab-5002164378c8.png)


### Done and soon to be tested

Style editor
* edit style for these tags: H1, H2, H3, A, P
* edit the style for different states: mobile+desktop, mobile only, hover, visited...
* most of the css styles for text are editable: letters/words/lines spacing, right to left direction, paragraph 1st line indentation, ...
* one can select a text box or a container and edit the styles for the texts inside it (multi selection does not work because it is not clear to me how it could work)
* one can give a name to the current style, and apply it to other elements 

### Use cases

I want to design an existing template without knowing what is a style
* select the body and change the style for all texts
* select specific texts and change their styles

I want a big font size on mobile
* select the body, change the "visibility" to "mobile only"
* edit the font size, change the unit in "em", change the value

I would like to create a template with a theme, i.e. a set of styles which will change all the site aspect
* drop a section for the first content section of your site, add text boxes and images
* select the section background, edit the text style to design your section, let's say with white text and black background
* in the style editor click on "give a name to this style" and call it "White on Black"
* continue with your site
* let's say you need another section with white text on black background
* create a new section, add texts and images
* in the style editor select the style called "White on Black" and this will apply the style on the section - it will also delete the previous style of the section if you changed it before you apply the new style

Something is wrong, I want to check every element with a custom style
* in the style editor select every styles, one after the other
* when the editor asks wether you want to apply the style or select all the elements with this style, click "select"
* browse all your pages and check the selected elements
* note that if a style has a name, it may be applied to many elements, but a style without a name is only on the selected element

### to do

* hover, click, visited states
* docs
* test and debug
* design UI

**Comment by budislav** [comment]
very good progress @lexoyo !
Is this somewhere on the internet so we can try?

**Comment by lexoyo** [comment]
Thx @budislav !!
It will be very soon, a matter of days
The design will not be ready but this is on purpose so you can tell me how to make it understandable

**Comment by budislav** [comment]
Sure, I will need to try it and see everything how it works.
At the moment I am overloaded with some work I need to finish but after that I will be available.

**Comment by lexoyo** [comment]
The new text styles manager is live on editor.silex.me
So I'll close this now

Any comment about this new release is welcome here
