### ISSUE TITLE
My Silex website for sushi shop

### ISSUE THREAD

**Issue by bluehawana** [silexlabs/Silex#693]
Here is a link to a website I did with Silex:
[![screenshot from 2018-02-24 18-16-02](https://user-images.githubusercontent.com/715377/36633044-d6a3a47c-198e-11e8-802f-7c6b959fecd6.png)](http://www.ichiban-sushi.se)

**Comment by lexoyo** [comment]
Nice!

**Comment by lexoyo** [comment]
As [said here](#694), I thought it could be useful to you, let me know if you want to know how to display your instagram pictures on your website

I just tested the instagram widget "Light widget", here is a test
http://lexoyo.me/silex-slideshow-tests/light-widget.html

You can view it at several sizes here
http://www.responsize.org/?url=http://lexoyo.me/silex-slideshow-tests/light-widget.html

**Comment by lexoyo** [comment]
this website has been closed right?
