### ISSUE TITLE
Gros problèmes de serveur et sauvegarde...

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#698]
@lexoyo 

Bonjour Alex,

il y a des problèmes de connexions et sauvegarde dans le cloud, je pense que le serveur est saturé.

sa fait 3 fois que je recommence mon projet car suite aux sauvegardes douteuse, je perd une grosse partie de mon projet, et cela toujours quand j'ai terminé...

je te laisse un accès a ma dropbox pour que tu puisse voir le résultat. ( justfriendsMars et justfriendsMarscopie)

Si tu sais faire en sorte que je récupère le site se serai MERVEILLEUX !!!

BaguetteAgile

**Comment by BaguetteAgile** [comment]
J'ai l'impression que tout mon code CSS ,HTML, JS, Background, est perdu ...

**Comment by lexoyo** [comment]
Hello
Je vais regarder mais pas aujourd'hui
Tu es sur preprod toi?

**Comment by BaguetteAgile** [comment]
Sur silex.me problème avec Dropbox. donc OUI je suis sur preprod .

![capture du 2018-03-03 16-04-53](https://user-images.githubusercontent.com/35597855/36935833-032f5c66-1efd-11e8-99bb-f6350768d80a.png)

**Comment by BaguetteAgile** [comment]
![capture du 2018-03-03 18-19-10](https://user-images.githubusercontent.com/35597855/36937165-72dcbbe6-1f0f-11e8-824c-92b6aebf4d3e.png)

**Comment by lexoyo** [comment]
J'ai pas compris désolé :-/
Tu bosses sur preprod.silex.me (auquel cas pas de problème avec Dropbox normalement) ou editor.silex.me ?

**Comment by BaguetteAgile** [comment]
Je suis sur, https://preprod.silex.me/
;)

**Comment by lexoyo** [comment]
Ah :(
Il y a peut etre trop de monde sur preprod... C'est juste un serveur de test
C'est toujours le cas maintenant?
Quelques stats qui montrent qu'un pic de trafic et un manque de mémoire a eu lieu entre le 1er et le 4 mars
![screenshot from 2018-03-05 18-33-17](https://user-images.githubusercontent.com/715377/36990095-db9c4bb6-20a3-11e8-852b-b01b08bc09e2.png)
![screenshot from 2018-03-05 18-32-07](https://user-images.githubusercontent.com/715377/36990096-dbba6380-20a3-11e8-9aef-80e226990ae2.png)
![screenshot from 2018-03-05 18-31-16](https://user-images.githubusercontent.com/715377/36990097-dbd7de38-20a3-11e8-9439-565f2220d7d0.png)
![screenshot from 2018-03-05 18-30-55](https://user-images.githubusercontent.com/715377/36990098-dbf1a52a-20a3-11e8-926a-9efda1ea18ad.png)

**Comment by lexoyo** [comment]
Pendant ce temps sur la prod (serveur plus gros)
![screenshot from 2018-03-05 18-36-52](https://user-images.githubusercontent.com/715377/36990219-486918aa-20a4-11e8-9e01-50643c292105.png)
![screenshot from 2018-03-05 18-36-26](https://user-images.githubusercontent.com/715377/36990220-48860514-20a4-11e8-9519-b4c1fee44f14.png)
![screenshot from 2018-03-05 18-35-59](https://user-images.githubusercontent.com/715377/36990222-48a7f0fc-20a4-11e8-9986-ebbcd7bb33c2.png)
![screenshot from 2018-03-05 18-35-46](https://user-images.githubusercontent.com/715377/36990223-48c20672-20a4-11e8-85af-ce35545700c5.png)

**Comment by lexoyo** [comment]
Les pics de trafic sur preprod sont juste énormes... Je ne comprends pas bien

**Comment by BaguetteAgile** [comment]
Je viens d'avoir un problème de connexion aujourd'hui, pas grave en soit, le plus gênant c'est lors de sauvegarde du projet, car dans mon cas, j'ai perdu une grosse partie de mon code css, des images, les positionnement des div ... 
As-tu pris le temps de regarder ce qu'il reste de mon projet ?
(je recommence un nouveau projet... l'avantage c'est que le codage css commence à rentré dans ma tête  ...  ;) )

**Comment by lexoyo** [comment]
> As-tu pris le temps de regarder ce qu'il reste de mon projet ?

non pas encore 
la solution est peut etre d'utilser la version installable de Silex faite par @JbIPS mais pas à jour avec la toute derniere version puisqu'elle n'est pas officiellement en prod (une question de jours je pense)

**Comment by BaguetteAgile** [comment]
@lexoyo 

Bonjour, encore un problème ERROR 502 cet après midi.
Mon site ressemble une fois de plus à rien du tout.

Par contre, j'ai inclus hier soir le code analytique de google puis sauvegardé, avant cela pas de problème pour récupérer mon site et continuer mon travail.

J'ai remarqué ceci dans la fenêtre JS de silex: ( hier soir j'avais simplement le code d’intégration de Google anal ) ( peut-être un rapport avec le problème que je rencontre )


    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)%0A%7D)(window,document,'script','//www.google-analytics.com/analytics.js','ga');%0Aga('create',%20'UA-********-
*',%20'auto')
;%0Aga('send',%20'pageview');%0A%0A/*%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*%5C%0A%20%20%20Google%20analytics%20widget%0A%5C*%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20*/%0A//%20notify%20google%20when%20page%20change%0Afunction%20onPageChangeGA(newUrl)%7B%0A%20%20%20%20var%20currentPage%20=%20newUrl.substr(newUrl.indexOf('#!page-')%20+%207);%0A%20%20%20%20ga('send',%20'pageview',%20%7B%0A%20%20%20%20%20%20'page':%20'/'%20+%20currentPage,%0A%20%20%20%20%20%20'title':%20currentPage%0A%20%20%20%20%7D);%0A%7D%0A$(window).bind(%20'hashchange',%20function%20(e)%7B%0A%20%20%20%20onPageChangeGA(e.originalEvent.newURL);%0A%7D);%0A//%20track%20links%20and%20form%20submissions%0A$(function()%7B%0A%20%20%20%20$('a,%20%5Bdata-silex-href%5D').click(onClick);%0A%20%20%20%20$('form').submit(onSubmit);%0A%20%20%20%20function%20onSubmit()%20%7B%0A%20%20%20%20%20%20%20%20onClick.call(this,%20true,%20'submit');%0A%20%20%20%20%7D%0A%20%20%20%20function%20onClick(opt_doNotPrevent,%20opt_link)%20%7B%0A%20%20%20%20%20%20%20%20var%20text%20=%20($(this).text()%20%7C%7C%20this.tagName).trim();%0A%20%20%20%20%20%20%20%20var%20link%20=%20this.getAttribute('href')%20%7C%7C%20this.getAttribute('data-silex-href')%20%7C%7C%20opt_link%20%7C%7C%20'';%0A%20%20%20%20%20%20%20%20var%20target%20=%20this.getAttribute('target')%20%7C%7C%20this.getAttribute('data-silex-target')%20%7C%7C%20'_self';%0A%20%20%20%20%20%20%20%20trackLink(text,%20link,%20target);%0A%20%20%20%20%20%20%20%20if%20(!opt_doNotPrevent)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20false;%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20function%20trackLink(text,%20url,%20target)%7B%0A%20%20%20%20%20%20%20%20ga('send',%20'event',%20'outbound',%20'link',%20text%20+%20'%20('%20+%20url%20+')',%20%7B'hitCallback':%0A%20%20%20%20%20%20%20%20%20%20%20%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(!target%20%7C%7C%20target%20===%20'_self')%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20document.location%20=%20url;%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D);%0A%20%20%20%20%7D%0A%7D);%0A%20%20%20%20%3C/script%3E%0A%20%20%20%20%3Cstyle%20class="silex-inline-styles" type="text/css">
        .body-initial {
            background-color: rgba(255, 255, 255, 1);
            background-image: url('image/Fond%20ecran%20partition.png');
        }
        
        .silex-id-1519721725357-3 {
            width: 1386px;
            min-height: 80px;
            top: 0px;
            left: 0px;
            background-color: rgba(114, 114, 114, 1);
            border-radius: 0 0 50px 50px;
        }
        
        .silex-id-1519946608807-3 {
            width: 25px;
            background-color: rgb(255, 255, 255);
            min-height: 25px;
            top: 28px;
            left: 821px;
            background-image: url('image/Bouton%20Facebook.png');
            background-size: cover;
            background-position: top center;
        }
        
        .silex-id-1519721882821-4 {
            width: 20px;
            background-color: transparent;
            min-height: 600px;
            top: 80px;
            left: 0px;
            background-image: url('image/Photogroupecompresser.jpg');
            background-position: top center;
            background-repeat: no-repeat;
            background-size: contain;
        }
        
        .silex-id-1519722636933-6 {
            width: 100px;
            background-color: transparent;
            min-height: 850px;
            top: 1455px;
            left: 0px;
            background-image: url('image/Carte%20de%20visitecompress.jpg');
            background-size: contain;
            background-position: top center;
            background-repeat: no-repeat;
        }
        
        .silex-id-1519807741738-0 {
            width: 100px;
            background-color: rgb(255, 255, 255);
            min-height: 100px;
            top: 185px;
            left: 425px;
            opacity: 0.6;
        }
        
        .silex-id-1519723657718-8 {
            width: 111px;
            top: 814px;
            left: 0px;
            background-color: transparent;
            min-height: 35px;
            background-image: url('image/Copyrightjustfriends.png');
            background-position: center center;
            background-repeat: no-repeat;
            background-size: contain;
        }
        
        .silex-id-1519722384277-5 {
            width: 1401px;
            min-height: 500px;
            top: 681px;
            left: 0px;
            background-color: rgba(252, 207, 153, 1);
        }
        
        .silex-id-1519729986386-10 {
            width: 100px;
            background-color: rgb(255, 255, 255);
            min-height: 22px;
            top: 80px;
            left: 0px;
        }
        
        .silex-id-1519723335941-7 {
            width: 100px;
            min-height: 20px;
            top: 2302px;
            left: 0px;
            background-color: rgba(254, 254, 254, 1);
        }
        
        .silex-id-1519811744171-2 {
            width: 100px;
            background-color: rgb(255, 255, 255);
            min-height: 100px;
            top: 524px;
            left: 599px;
        }
        
        .silex-id-1519812557684-3 {
            height: 400px;
            width: 400px;
            background-color: transparent;
            top: 100px;
            left: 417px;
        }
        
        .silex-id-1519856533083-2 {
            width: 100px;
            min-height: 100px;
            top: 100px;
            left: 0px;
            background-color: rgba(255, 217, 151, 1);
        }
        
        .silex-id-1519857528777-3 {
            width: 100px;
            background-color: rgb(255, 255, 255);
            min-height: 800px;
            top: 110px;
            left: 0px;
            background-image: url('image/En%20travaux.png');
        }
        
        .silex-id-1519858906274-4 {
            width: 100px;
            min-height: 51px;
            top: 106px;
            left: 0px;
            background-image: url('image/Bois%20laque.jpeg');
        }
        
        .silex-id-1519859110235-5 {
            width: 100px;
            background-color: transparent;
            min-height: 700px;
            top: 246px;
            left: 0px;
            background-image: url('image/guitaristefondecran.jpeg');
            background-size: cover;
            background-repeat: no-repeat;
            background-position: top center;
        }
        
        .silex-id-1519859398172-6 {
            width: 1169px;
            min-height: 645px;
            top: 51px;
            left: 0px;
        }
        
        .silex-id-1519891586053-0 {
            width: 100px;
            background-color: rgb(255, 255, 255);
            min-height: 700px;
            top: 1010px;
            left: 0px;
            background-image: url('image/publicfondecran2018.jpeg');
            background-size: cover;
        }
        
        .silex-id-1519891781484-1 {
            width: 1199px;
            min-height: 627px;
            top: 33px;
            left: 0px;
        }
        
        .silex-id-1519892246206-2 {
            width: 650px;
            background-color: rgb(255, 255, 255);
            min-height: 100px;
            top: 1803px;
            left: 554px;
        }
        
        .silex-id-1519942583606-0 {
            width: 1076px;
            min-height: 59px;
            top: 1714px;
            left: 0px;
            background-color: rgba(255, 255, 255, 1);
            background-image: url('image/route%20americaine.jpeg');
            background-size: contain;
            background-attachment: scroll;
            background-position: top center;
            background-repeat: repeat-x;
        }
        
        .silex-id-1519895261267-0 {
            width: 549px;
            background-color: rgba(255, 255, 255, 1);
            min-height: 318px;
            top: 219px;
            left: 463px;
        }
        
        .silex-id-1519943778498-1 {
            width: 100px;
            min-height: 100px;
            top: 157px;
            left: 0px;
            background-color: rgba(255, 86, 86, 1);
        }
        
        .silex-id-1519944924098-2 {
            width: 400px;
            height: 400px;
            background-color: rgba(255, 86, 86, 1);
            top: 200px;
            left: 334px;
        }
        
        .silex-id-1519981328247-1 {
            width: 1190px;
            min-height: 2051px;
            top: 119px;
            left: 0px;
            background-color: rgba(255, 237, 160, 1);
        }
        
        .silex-id-1519982850172-2 {
            width: 100px;
            min-height: 20px;
            top: 104px;
            left: 0px;
            background-color: rgba(179, 179, 179, 1);
        }
        
        .silex-id-1519893438700-3 {
            width: 429px;
            background-color: rgb(255, 255, 255);
            min-height: 374px;
            top: 180px;
            left: 311px;
        }
        
        .silex-id-1519729372162-9 {
            position: fixed;
            width: 100px;
            top: 0px;
            left: 0px;
            background-color: transparent;
            min-height: 80px;
        }
        
        .silex-id-1520083625265-1 {
            width: 100px;
            min-height: 100px;
            top: 106px;
            left: 0px;
            background-color: rgba(114, 114, 114, 1);
        }
    </style>
    <title>Just-Friends Belgique</title>
    <script type="text/javascript" class="silex-json-styles">
        [{"desktop":{"body-initial":{"background-color":"rgba(255,255,255,1)","background-image":"url('image/Fond%20ecran%20partition.png')"},"silex-id-1474394621032-2":{"min-height":"600px","background-color":"transparent","width":"1200px"},"silex-id-1474394605264-1":{"min-height":"100px","width":"100px","top":"100px","left":"100px"},"silex-id-1474394605263-0":{"min-height":"100px","background-color":"transparent"},"silex-id-1442914737143-3":{"min-height":"53px","width":"349px","top":"29px","left":"430px"},"silex-id-1478366444112-0":{"min-height":"100px","background-color":"transparent","width":"1200px"},"silex-id-1478366450713-2":{"min-height":"100px","background-color":"transparent","width":"1200px"},"silex-id-1519721318837-0":{"width":"","background-color":"","min-height":"100px"},"silex-id-1519721352213-2":{"width":"1410px","top":"-35px","left":"0px","min-height":"80px","background-color":"rgba(69,69,69,1)","border-radius":"0 0 50px 50px "},"silex-id-1519721725357-3":{"width":"1386px","min-height":"80px","top":"0px","left":"0px","background-color":"rgba(114,114,114,1)","border-radius":"0 0 50px 50px "},"silex-id-1519721882821-4":{"width":"20px","background-color":"transparent","min-height":"600px","top":"80px","left":"0px","background-image":"url('image/Photogroupecompresser.jpg')","background-position":"top center","background-repeat":"no-repeat","background-size":"contain"},"silex-id-1519722384277-5":{"width":"1401px","min-height":"500px","top":"681px","left":"0px","background-color":"rgba(252,207,153,1)"},"silex-id-1519722636933-6":{"width":"100px","background-color":"transparent","min-height":"850px","top":"1455px","left":"0px","background-image":"url('image/Carte%20de%20visitecompress.jpg')","background-size":"contain","background-position":"top center","background-repeat":"no-repeat"},"silex-id-1519723335941-7":{"width":"100px","min-height":"20px","top":"2302px","left":"0px","background-color":"rgba(254,254,254,1)"},"silex-id-1519723657718-8":{"width":"111px","top":"814px","left":"0px","background-color":"transparent","min-height":"35px","background-image":"url('image/Copyrightjustfriends.png')","background-position":"center center","background-repeat":"no-repeat","background-size":"contain"},"silex-id-1519729372162-9":{"position":"fixed","width":"100px","top":"0px","left":"0px","background-color":"transparent","min-height":"80px"},"silex-id-1519729986386-10":{"width":"100px","background-color":"rgb(255, 255, 255)","min-height":"22px","top":"80px","left":"0px"},"silex-id-1519807741738-0":{"width":"100px","background-color":"rgb(255, 255, 255)","min-height":"100px","top":"185px","left":"425px","opacity":"0.6"},"silex-id-1519811744171-2":{"width":"100px","background-color":"rgb(255, 255, 255)","min-height":"100px","top":"524px","left":"599px"},"silex-id-1519812557684-3":{"height":"400px","width":"400px","background-color":"transparent","top":"100px","left":"417px"},"silex-id-1519856533083-2":{"width":"100px","min-height":"100px","top":"100px","left":"0px","background-color":"rgba(255,217,151,1)"},"silex-id-1519857528777-3":{"width":"100px","background-color":"rgb(255, 255, 255)","min-height":"800px","top":"110px","left":"0px","background-image":"url('image/En%20travaux.png')"},"silex-id-1519858906274-4":{"width":"100px","min-height":"51px","top":"106px","left":"0px","background-image":"url('image/Bois%20laque.jpeg')"},"silex-id-1519859110235-5":{"width":"100px","background-color":"transparent","min-height":"700px","top":"246px","left":"0px","background-image":"url('image/guitaristefondecran.jpeg')","background-size":"cover","background-repeat":"no-repeat","background-position":"top center"},"silex-id-1519859398172-6":{"width":"1169px","min-height":"645px","top":"51px","left":"0px"},"silex-id-1519891586053-0":{"width":"100px","background-color":"rgb(255, 255, 255)","min-height":"700px","top":"1010px","left":"0px","background-image":"url('image/publicfondecran2018.jpeg')","background-size":"cover"},"silex-id-1519891781484-1":{"width":"1199px","min-height":"627px","top":"33px","left":"0px"},"silex-id-1519892246206-2":{"width":"650px","background-color":"rgb(255, 255, 255)","min-height":"100px","top":"1803px","left":"554px"},"silex-id-1519893438700-3":{"width":"429px","background-color":"rgb(255, 255, 255)","min-height":"374px","top":"180px","left":"311px"},"silex-id-1519895261267-0":{"width":"549px","background-color":"rgba(255,255,255,1)","min-height":"318px","top":"219px","left":"463px"},"silex-id-1519942583606-0":{"width":"1076px","min-height":"59px","top":"1714px","left":"0px","background-color":"rgba(255,255,255,1)","background-image":"url('image/route%20americaine.jpeg')","background-size":"contain","background-attachment":"scroll","background-position":"top center","background-repeat":"repeat-x"},"silex-id-1519943778498-1":{"width":"100px","min-height":"100px","top":"157px","left":"0px","background-color":"rgba(255,86,86,1)"},"silex-id-1519944924098-2":{"width":"400px","height":"400px","background-color":"rgba(255,86,86,1)","top":"200px","left":"334px"},"silex-id-1519946608807-3":{"width":"25px","background-color":"rgb(255, 255, 255)","min-height":"25px","top":"28px","left":"821px","background-image":"url('image/Bouton%20Facebook.png')","background-size":"cover","background-position":"top center"},"silex-id-1519981328247-1":{"width":"1190px","min-height":"2051px","top":"119px","left":"0px","background-color":"rgba(255,237,160,1)"},"silex-id-1519982850172-2":{"width":"100px","min-height":"20px","top":"104px","left":"0px","background-color":"rgba(179,179,179,1)"},"silex-id-1520083625265-1":{"width":"100px","min-height":"100px","top":"106px","left":"0px","background-color":"rgba(114,114,114,1)"}},"mobile":{},"componentData":{"silex-id-1519812557684-3":{"name":"slideshow1","templateName":"slideshow","slides":[{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/Jo_opt.jpg","lastModifiedDate":null,"name":"Jo_opt.jpg","size":25439}],"text":"\"JO\" chant et petites percussions","link":"#!page-construction"},{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/Angelo_opt.jpg","lastModifiedDate":null,"name":"Angelo_opt.jpg","size":27575}],"text":"\"Angelo\" Guitare Rhytmique, Solo et Chant","link":"#!page-construction"},{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/Lucien_opt.jpg","lastModifiedDate":null,"name":"Lucien_opt.jpg","size":31707}],"text":"\"Lucien\" Guitare Rhytmique et Chant","link":"#!page-construction"},{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/Ahmed_opt.jpg","lastModifiedDate":null,"name":"Ahmed_opt.jpg","size":27329}],"text":"\"Ahmed\" Basse","link":"#!page-construction"},{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/Michel_opt.jpg","lastModifiedDate":null,"name":"Michel_opt.jpg","size":18843}],"text":"\"Michel\" Claviers","link":"#!page-construction"},{"image":[{"url":"https://preprod.silex.me/dropbox/get/Site Just-Friends/image/BaguetteAgile_opt.jpg","lastModifiedDate":null,"name":"BaguetteAgile_opt.jpg","size":27719}],"text":"\"Jean-Philippe Vinet\" alias \"Baguettes Agile\" Batterie","link":"#!page-presentation-jp"}],"autoplay":true,"speed":"1000"},"silex-id-1519944924098-2":{"name":"form1","templateName":"form","sendTo":"justfriends@protonmail.com","submitButtonLabel":"Envoyer","buttonBackgroundColor":"#1200ff","buttonBorderColor":"#ffffff","label1":"* Just-Friends Belgique","placeholder1":"Votre Nom","label2":"* Votre adresse mail","placeholder2":"votre@mail.com","label3":"* Votre message","placeholder3":"Ce que vous avez à dire ..."}}}]

**Comment by lexoyo** [comment]
Salut Baguette
Bon j'ai mis sur preprod.silex.me une version qui supporte google analytics, et tout autre markup HTML
Je te suggere de supprimer l'ancien code google anal et de remettre celui d'origine donné par google

Pour les 502 je ne l'explique pas vraiment, mais @JbIPS a fix des trucs qui faisaient planter le serveur donc ca a peut etre corrigé ca (c'etait en rapport avec le ftp il me semble). Tu peux me dire si tu en as encore? Ca va devenir critique puisque cette version est en prod maintenant... Tiens d'ailleurs tu as eu des 502 sur la prod?

Merci pour ton aide et ta patience

**Comment by BaguetteAgile** [comment]
15h42 le 27 Mars,  voici le message d'erreur.
Hier après midi, j'ai eu un message erreur 502.


![capture du 2018-03-27 15-42-17](https://user-images.githubusercontent.com/35597855/37971358-09deb958-31d6-11e8-9bdb-c152ef00e667.png)

Je test la nouvelle version dés que possible ;)

**Comment by BaguetteAgile** [comment]
@lexoyo 
Bonjour Alex, suite au message "503" ci dessus, j'ai donc testé si sur "https://editor.silex.me/"
sa fonctionné.
Belle surprise en voyant que je peux me loggé avec mon comptes DropBox ;)

Je passe donc au test, j'insert le code Google Anal dans JS et je sauvegarde, quand je ré-ouvre le projet Nickel sa fonctionne, je récupère toutes mes pages et le reste ( code CSS; HTML et JS)

Seulement, j'ai remarqué un truc à propos du code Google Anal. 
Suite à la sauvegarde, dans JS, il manque une partie du code ( disparu) voici 2 captures d'écran ...

ci-dessous, le code de Google que j'ai copier dans Silex "JS"

![code google](https://user-images.githubusercontent.com/35597855/38035806-7aa6abb2-32a5-11e8-8727-9b971e2dd687.png)

Ci-dessous, le résultat dans Silex JS après sauvegarde

![code silex apres sauvegarde](https://user-images.githubusercontent.com/35597855/38035819-83a14c5e-32a5-11e8-92b3-4b0d35c0a934.png)

La balise script, n'est pas fermé.

Maintenant, je sais pas si Google Analytic reçois et analyse le site ...

**Comment by lexoyo** [comment]
ouch je viens de voir la suite de ton bug report...
peux tu me dire si tu as bien les stats dans analytics? et ouvrir une autre issue stp?
