### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by fresnizky** [silexlabs/Silex#699]
Related to #697 
Tried again from a fresh clone of the repo and still fails but with a different error.
```
> Silex@0.8.0 build:prodotype /silex
> prodotype src/components dist/client/libs/prodotype/components/

Building /silex/src/components to /silex/dist/client/libs/prodotype/components in current dir: /silex
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/silex/dist/client/libs/prodotype/components'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at /silex/node_modules/prodotype/bin/prodotype:33:8
    at Array.forEach (native)
    at Object.<anonymous> (/silex/node_modules/prodotype/bin/prodotype:30:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm info lifecycle Silex@0.8.0~build:prodotype: Failed to exec build:prodotype script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prodotype"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build:prodotype: `prodotype src/components dist/client/libs/prodotype/components/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build:prodotype script 'prodotype src/components dist/client/libs/prodotype/components/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prodotype src/components dist/client/libs/prodotype/components/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log

npm info lifecycle Silex@0.8.0~build: Failed to exec build script
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! Silex@0.8.0 build: `npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Silex@0.8.0 build script 'npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Silex package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Silex
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Silex
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /silex/npm-debug.log
```

**Comment by lexoyo** [comment]
if you do `mkdir dist/client/libs/prodotype` it seems to work (which is why it used to work on my computer already) but then it lacks the folder and files in `dist/client/libs/templates`

I think the docker image is broken, I am not sure why... Would you debug this with me?

**Comment by cdlm** [comment]
I get the same…

**Comment by lexoyo** [comment]
hi @cdlm 
thx for the bug report
I finally managed to [fix this with this commit](https://github.com/lexoyo/Silex/commit/aaa407111512255185d91cecdb15fb812a6a0a82), but it is on a branch I'm working on, so for now you need to do this to test:
```
$ git clone https://github.com/lexoyo/Silex.git
$ cd Silex
$ git checkout publish_to_hosting
$ docker build . -t silex-image
$ docker run -p 6805:6805 -t silex-image
```
It will take a while and it should run Silex on `http://localhost:6805/`
Let me know if you have a chance to test this, that would be helpful

**Comment by lexoyo** [comment]
argh it works for me :-/
thanks a lot for trying
are you on linux? 
just to be sure: you did try on my fork and the branch publish_to_hosting right?

**Comment by cdlm** [comment]
No: macOS, Docker 18.06.1-ce

I did what you said, the differences shouldn't be meaningful (changed image name to `silex` not `silex-image` and killed/restarted the docker build (npm seemed to take a really long time and didn't use any resources so I suspected some kind of network fail…)

**Comment by InfinityPhase** [comment]
On Arch Linux, Docker version 18.06.1-ce, this was successful in building and executing for branch publish_to_hosting. However, whenever opening a file explorer dialog, such as the import project dialog, it is completely blank aside from the background grey colour.

**Comment by lexoyo** [comment]
hi
glad it works now :)
this is a new bug due to us merging something without enough tests in CloudExplorer
@JbIPS should take care of this very soon
to make it work now, you can simply fix the cloud explorer version [here in your package.json file](https://github.com/silexlabs/Silex/blob/develop/package.json#L45). just replace `github:silexlabs/CloudExplorer2#master` with `github:silexlabs/CloudExplorer2#43824820ad62c33b42fb83ba3af2c1a951d02c5a`
then `npm install` again (you may need to remove package-lock.json)

**Comment by lexoyo** [comment]
Hi @InfinityPhase @fresnizky and  @cdlm 
We marged several long term dev branches, could you give it a try again with the master branch? 
I tried it on fedora and it works fine
