### ISSUE TITLE
Error: I did not manage to save the file

### ISSUE THREAD

**Issue by dhubbard-ic** [silexlabs/Silex#700]
Hi

I am just trying to get started with Silex and, after trying to Save to DropBox (but hitting #689) I tried Github - but now get "Error: I did not manage to save the file".

I have authorised Silex to Github, created a repo and signed out of Github - with same result. Have tried on Chrome and FireFox.
 
Is there some Github setup I am missing ?

**Comment by lexoyo** [comment]
Hi
In what folder are you trying to save ? I mean the path..

**Comment by dhubbard-ic** [comment]
Ok -  I was trying to save into a bare repository.  

Taking your hint - I added a top level folder and pushed that to central github - and I can now save to that folder.

Thanks

**Comment by lexoyo** [comment]
Cool! :+1:

**Comment by lexoyo** [comment]
Cool! :+1:
