### ISSUE TITLE
Would someone help create an icon from the existing logo?

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#709]
Hello
The github app has icon which looks like this
![screenshot from 2018-03-21 18-16-48](https://user-images.githubusercontent.com/715377/37726052-b43c1d06-2d34-11e8-9d2a-736fcfc38ec7.png)
And github says
> Your logo should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend an image size of at least 200px x 200px. See "Tips for logo and badge images" for more guidance on customizing badges.

**Would someone help create a Silex icon from the existing logo?** @ceubri or @budislav maybe?

Here is the current official logo
https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Silex_website_builder_logo.png/1200px-Silex_website_builder_logo.png

**Comment by budislav** [comment]
Done :)

![silex_website_builder_logo_github](https://user-images.githubusercontent.com/3619927/37743906-b0698208-2d6c-11e8-8a58-99904ca98550.png)

**Comment by lexoyo** [comment]
thank you @budislav !!!
