### ISSUE TITLE
Update Node.js version

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#712]
Currently, Silex requires Node.js 6.X, which is now deprecated.

We should move to the new LTS (8.X). This will also let us use new features for Silex, CloudExplorer and Unifile.

Considering it should be retrocompatible, the upgrade won't break a thing be will gain some performances improvements :wink:

**Comment by lexoyo** [comment]
As a matter of fact I just did it on develop
https://github.com/silexlabs/Silex/commit/98a9ad74fc91e6db5525fad922e3dc1c6277b0aa

Is it ok like this? Or a hot fix would have been better maybe?

**Comment by JbIPS** [comment]
That's great news! I'll work on Unifile v3 that will use ES2017, but no rush for now.
