### ISSUE TITLE
Not saving to GitHub

### ISSUE THREAD

**Issue by dougp59** [silexlabs/Silex#715]
I want to save my draft site.  I created a folder in GitHub and when I try to save the editable.html file to it, I get an error: 

Error: I did not manage to save the file. This folder can only contain folders.

But if I repeat and then try to make ANOTHER folder, it says Git Repository is empty.

**Comment by lexoyo** [comment]
Hello

> Error: I did not manage to save the file. This folder can only contain folders.

This is because you can only put files in the 2nd level folder, e.g. /my-repo1/my-branch1/

> But if I repeat and then try to make ANOTHER folder, it says Git Repository is empty.

i see this repository is empty https://github.com/dougp59/mcfsl
you should delete it in github and create it as a folder in silex

**Comment by lexoyo** [comment]
Hello @dougp59 
Did you manage to save your website?
