### ISSUE TITLE
Issues ftp

### ISSUE THREAD

**Issue by permaculturearth** [silexlabs/Silex#721]
bonjours, la nouvelle interface de connexion ftp ne fonctionne pas pour faire des modifications sur les anciennes publications. 

Unifile would like access to your files and folders.

host  
port  
username  
password  

{"message":"Invalid credentials","name":"UnifileError","code":"EACCES"}

pour enregistrer un nouveaux projet ça ne marche pas non plus.

**Comment by lexoyo** [comment]
Ça suggère que les accès fournis sont faux... Tu es sur d'avoir les bons codes d'accès ?

@JbIPS tu as testé le FTP toi déjà non?

**Comment by JbIPS** [comment]
J'ai testé avec mon serveur FTP chez OVH en local, je viens de vérifier sur la prod, c'est toujours OK pour moi.

@permaculturearth Peux-tu vérifier que ces 4 champs (host / port / username / password) sont bien remplis ? Merci

**Comment by permaculturearth** [comment]
je viens de tenter une nouvelle connexion et quand je valide je retombe maintenant sur la page de sélection avec une roue au niveau du choix ftp. Après un longue attente, j'ai fermé l'onglet pour relancer l'opération à partir de https://www.silex.me et cette fois, je tombe sur le dossier /www . Et quand je rentre dedans, je retrouve bien le dossier de sauvegarde qui s'est bien ouvert. Devais-je déplacer le dossier de sauvegarde dans le dossier racine en amont du www pour que ça marche mieux?

**Comment by JbIPS** [comment]
Tu as dû tomber sur un bug lors de ton premier essai et la fermeture de la fenêtre a permis de remettre tout à zéro pour repartir sur le droit chemin! Meme pas besoin de déplacer ton dossier :wink:.

Pense à fermé ce ticket si tu considère que le problème est réglé et amuse toi bien avec Silex

**Comment by permaculturearth** [comment]
C'est une fausse alerte alors, merci pour votre réactivité rassurante.
