### ISSUE TITLE
Bug Template Food & Drink

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#726]
Hello la team, j'ai toujours du mal à suivre vos différentes activités mais j'espère que tout se passe comme vous le voulez. Je rencontre un bug sur le template Food & Drink : les pages 3 et 4 sont "collées" (on ne peut pas mettre de contenu différent sur chacune). Quelqu'un pourrait-il m'expliquer comment les décoller ?
J'ai toujours dans l'idée de faire une vidéo (complémentaire de la votre) pour montrer aux utilisateurs non informaticiens comment ils peuvent créer leur site... j'attends d'avoir un peu plus de temps pour ça.
Merci à vous, et à la communauté.
Léa

**Comment by BaguetteAgile** [comment]
Bonjour Lea75,

> les pages 3 et 4 sont "collées" (on ne peut pas mettre de contenu différent sur chacune)

dans Silex, il y a une fonction dans le menu de droite , " Visible on" en fait tu dois sélectionner ton élément et cocher sur quel page tu veux que cet élément apparaisse, sur la template par défaut c'est cocher "all pages" .

Si tu veux que l' élément "Nothing here yet. Waiting for your content..."

![capture du 2018-04-30 23-10-01](https://user-images.githubusercontent.com/35597855/39450454-a95b7902-4ccb-11e8-8527-414000c21f32.png)

 apparaisse seulement sur la page " Team", tu dois cocher dans le menu l'onglet "Team" , alors cet élément ne sera plus visible sur la page "info" 


![capture du 2018-04-30 22-58-18](https://user-images.githubusercontent.com/35597855/39449983-0115a05c-4cca-11e8-9db7-629830580fcf.png)

Ai-je bien cerné ton souci ?

**Comment by Lea75** [comment]
Bonjour BaguetteAgile, 
Merci bcp pour ta réponse. Je ne suis pas sûre qu'elle réponde à mon problème mais je vais essayer. Et je témoignerai ici de la solution ou de si ça ne fonctionne pas de mon côté.
En attendant, j'ai réussi à créer une page supplémentaire que j'ai renommé "4" et qui n'est pas "solidaire" de la page 3.



Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., avr. 30, 2018 à 23:11, BaguetteAgile<notifications@github.com> a écrit :   
Bonjour Lea75,


les pages 3 et 4 sont "collées" (on ne peut pas mettre de contenu différent sur chacune)


dans Silex, il y a une fonction dans le menu de droite , " Visible on" en fait tu dois sélectionner ton élément et cocher sur quel page tu veux que cet élément apparaisse, sur la template par défaut c'est cocher "all pages" .

Si tu veux que l' élément "Nothing here yet. Waiting for your content..."



apparaisse seulement sur la page " Team", tu dois cocher dans le menu l'onglet "Team" , alors cet élément ne sera plus visible sur la page "info"



Ai-je bien cerné ton souci ?

**Comment by lexoyo** [comment]
Bonjour, 
Je vais clore l'issue, @Lea75 n'hésite pas à donner des news ici quand tu as testé
