### ISSUE TITLE
Enregistrement impossible

### ISSUE THREAD

**Issue by Rom25** [silexlabs/Silex#727]
Bonjour, 

je développe un site grâce a Silex, la dernière mise à jour de mon site date de la fin d'année, j’essaie d'en refaire une nouvelle, j'arrive bien à ouvrir le site sur l'interface de développement mais il m’ait impossible d'enregistrer les modifications ( par dropbox ou FTP) , auriez vous une piste pour m'aider?

Par avance merci pour vos réponse. 
Romuald

**Comment by BaguetteAgile** [comment]
@Rom25 

Bonsoir Romuald,

quelle version de Silex utilise-tu ?

moi je viens de tester un enregistrement sur DropBox avec les 2 versions suivante:
https://preprod.silex.me/
https://editor.silex.me/

pas de soucis...

**Comment by lexoyo** [comment]
@Rom25 tu as réussi à faire ce que tu veux ?

(thx baguette ;)

**Comment by Rom25** [comment]
J'utilise cette version: 
https://editor.silex.me/
J'arrive bien a enregistrer un nouveau projet mais je n'arrive pas a enregistrer les modification d'un projet déjà existant (même en changeant de noms)

**Comment by JbIPS** [comment]
Hello @Rom25, quand tu essaies de sauvegarder, es-tu bien connecté à ton compte Dropbox?  Tu peux vérifier en utilisant l'explorateur

**Comment by Rom25** [comment]
oui, je suis bien connecté, le résultat est le même en utilisant une connexion FTP

**Comment by lexoyo** [comment]
J'ai testé ça fonctionne aussi
Peux tu détailler tes actions stp?
