### ISSUE TITLE
Color for links

### ISSUE THREAD

**Issue by alex7703** [silexlabs/Silex#728]
I tried changing the link colors by using this bit of code
a:link{
      color: red;
}
however this is not working. Can someone tell me what im doing wrong?

**Comment by lexoyo** [comment]
Hello

This will work after you publish

For some reason in the editor or preview, you need something like div[data-silex-href]

We should probably fix this or at least document it in the wiki 
https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor

**Comment by lexoyo** [comment]
I have tested, `div[data-silex-href] { }` is working in preview and `a { }` is working after publish
So for now you need to do
```
div[data-silex-href], a {
    color: red;
}
```
