### ISSUE TITLE
Seperate background pics.

### ISSUE THREAD

**Issue by alex7703** [silexlabs/Silex#729]
Ok another question. How do I make seperate background pictures?

**Comment by lexoyo** [comment]
Hi what do you mean?
Multiple bg images on 1 element?

**Comment by alex7703** [comment]
How do i make bg pics for each page

**Comment by lexoyo** [comment]
Oh ok
For this you will have to make a little of javascript
[As explained here](https://github.com/silexlabs/Silex/wiki/Silex-and-Javascript#page-events) you can detect page changes and set a CSS class on the body for each page:
```
$(function() {
  // this will be executed when the page is loaded
  var current = $('body').pageable('option').currentPage;
  $('body').addClass(current + '-opened');
  $('body').on('pageChanged', function (event, pageName) {
    // this will add a css class on the body, with the name of the page + '-opened'
    // e.g. open the page `page-test1` will add the css class `page-test1-opened` to the body
    $('body').addClass(pageName + '-opened');
    // remove previous one
    $('body').removeClass(current + '-opened');
    current = pageName;
  });
});
```
 Then you can add CSS (in the CSS editor) for each page. For example if your page is called "Home" you would add
```
.page-home-opened {
    background-image: url('./assets/my-image-for-home-page.jpg');
}
```

**Comment by alex7703** [comment]
What if the page namesz have spaces because it seems to be not working

**Comment by lexoyo** [comment]
You can see the "real" page name in the preview
"My Page 1" will end up with the name "page-my-page-1"
