### ISSUE TITLE
Better blank layouts

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#734]
Hello @all 
About the 3 blank templates that appear on the dashboard:
* desktop: wide sections (1200px), responsive mode disabled (in the settings)
* narrow: narrow sections  (950px), responsive mode disabled
* responsive: wide sections (1200px), responsive mode enabled

I think they are bad because:
* they should all be responsive by default, but then "desktop" and "responsive" are the same
* we don't need to name them, the pictures of @budislav are enough, so we should remove the confusing names on the dashboard
* the sections width is "forced" and one need to go in the settings to resize them, it is not possible to resize with the mouse on the stage

What blank templates should we offer? Just one maybe?

**Comment by budislav** [comment]
> Just one maybe?, they should all be responsive by default

Yes! :)
We need only one blank template. Many things are not good with responsive mod, but one responsive blank template is really enough.

**Comment by lexoyo** [comment]
Ok then I will delete the "silex-blank-templates" repository and add just 1 blank template to Silex "community templates"

**Comment by lexoyo** [comment]
This is live now on editor.silex.me
So I'll close this now

Any comment about this new release is welcome here
