### ISSUE TITLE
Option to save Silex document on user PC

### ISSUE THREAD

**Issue by budislav** [silexlabs/Silex#735]
Every time I want to see responsive mode Silex forcing me to save doc first which is ok, but I want to save it on my PC not on cloud. Why? Because it is faster and the most important I don't want to login on github or dropbox to do that.

In this video I am showing you a bug If I choose to cancel there is a trap, nothing will happen. I cant go back.

[vokoscreen-2018-05-12_21-47-18.zip](https://github.com/silexlabs/Silex/files/1997894/vokoscreen-2018-05-12_21-47-18.zip)

**Comment by lexoyo** [comment]
Hello @budislav 
I finally took the time to fix this bug (took me 45 min)
Here is what I did: https://github.com/silexlabs/Silex/pull/784/files
Thank you for your contributions!

**Comment by lexoyo** [comment]
Oh, and it might be better if you can test it so that I am sure that I covered your use case
Thx

**Comment by budislav** [comment]
@lexoyo  that's awesome! but can you send me a link to that version to test it, because https://silex-test-tmp.herokuapp.com/ is not fixed..
45min sounds a lot :D

**Comment by lexoyo** [comment]
Oh yes it's live on preprod and prod

Le 13 août 2018 18:49, à 18:49, Budislav <notifications@github.com> a écrit:

**Comment by budislav** [comment]
@lexoyo Yes it's working! Thanks! :)
