### ISSUE TITLE
offline mode

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#736]
@budislav you wrote

> Every time I want to see responsive mode Silex forcing me to save doc first which is ok, but I want to save it on my PC not on cloud. Why? Because it is faster and the most important I don't want to login on github or dropbox to do that.

For this we have @JbIPS offline standalone version of Silex, made with electron (and love)

The questions I have about that
* Where should we let people know about this? I was thinking on www.silex.me, under the link to access Silex?
* JB is it possible to create a new version every time Silex has a new version?

**Comment by JbIPS** [comment]
I think we should add a link under the 'demo/try' with a 'download' label.

And yes, with some automation we could publish a new version each time

**Comment by lexoyo** [comment]
As always that looks good @budislav 

The background is bit hard I think but it is still so much better than the current site
Would you help design the new website? Maybe @BaguetteAgile could help for the integration in Silex? I can help too of course... 

Feel free to open another issue about the new website

Concerning the offline version of Silex, do you think that you will be able to do the automatic deployment in the coming months @JbIPS ?

**Comment by budislav** [comment]
That's just example, don't know what background is best, I thought maybe that colourful gradient because of logo and it is a designer app so.. but yeah it would be good something different.
That is just one section, other section we can do at any time, later.
I think whole website should be wide, not in that box mode so if you can do that it would be good.

**Comment by lexoyo** [comment]
Yes we can do any layout...

**Comment by BaguetteAgile** [comment]
>  Maybe @BaguetteAgile could help for the integration in Silex?

I'm willing to try to help you, but I'll have to explain what you expect from me, because I'm not a computer scientist.
If you are patient ...
