### ISSUE TITLE
Heroku one-click deploy fails

### ISSUE THREAD

**Issue by pseudozach** [silexlabs/Silex#741]
In the section How to Host An Instance of Silex 
"For the lazy ones, there is the Heroku One-Click Deploy:" button fails because Heroku complains there are no app.json under https://github.com/silexlabs/Silex/tree/master.

**Comment by lexoyo** [comment]
Hello
Thank you for the report
Is it possible for you to add the app.json and submit a pull request?

**Comment by swakarm** [comment]
Here is an example of 'app.json'
https://devcenter.heroku.com/articles/app-json-schema#example-app-json

**Comment by lexoyo** [comment]
Hi @swakarm
Would like me to guide you to add it yourself to Silex code?

**Comment by swakarm** [comment]
I have submitted a pull request.
for app.json

**Comment by lexoyo** [comment]
It works great !

![screenshot from 2018-09-05 12-44-39](https://user-images.githubusercontent.com/715377/45088540-90fb2400-b109-11e8-9f6e-7af5316e546d.png)

There is still something to do for it to be perfect: [as stated in Silex wiki here, we need to define some environment variables for Silex to work properly](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#environment-variables). I think it is possible to tell heroku to ask for the values when a user deploys Silex

**Comment by lexoyo** [comment]
Also the build on heroku fails: `java: not found`
We need to add the java "toolbelt" if I remembeer correctly
@swakarm could you look into it?
The link to try it out is `https://heroku.com/deploy?template=https://github.com/silexlabs/Silex/tree/develop`

**Comment by swakarm** [comment]
I am still getting an error ,'No app.json located in the repo URL provided.'
Make sure that repo URL is true or not.
![capture](https://user-images.githubusercontent.com/22835653/45148648-62527b80-b1e5-11e8-979a-8d61ee894652.JPG)

**Comment by swakarm** [comment]
I am new to Silex . So I am observing your source code. My schedule is also too busy. So I will try to solve problems whenever I will be free. So do not expect from me for more support. I am sorry for that. Thanks for making Silex builder  opensource. Science is depended on selfless people like You, Who works without expecting  profit.

**Comment by lexoyo** [comment]
> I am still getting an error ,'No app.json located in the repo URL provided.' Make sure that repo URL is true or not.

Did you use this URL?
It is the one for develop branch
https://heroku.com/deploy?template=https://github.com/silexlabs/Silex/tree/develop

**Comment by swakarm** [comment]
oh, I clicked button for one click deploy. Now I have tried 'develop' branch. It works.

**Comment by swakarm** [comment]
**Observing package.json** 

"Java not found" error is because of heroku could not find files in directory, which are described in script- 'build:js:release' and 'build:js:debug' 

Also check at "dependency"
"google-closure-compiler": "20170218.0.0",
"google-closure-library": "20170218.0.1",
                    
I think there is a problem with Google closure complier at heroku. 
We have two options to solve this problem.

1.- Remove dependency of Google closure copmiler from source code of silex. (for heroku)
   OR
2.- Compiling code with java script version of Google closure compiler which does not require JAVA
https://github.com/google/closure-compiler-js

**Comment by lexoyo** [comment]
It is possible to add Java to heroku 
I don't know how but I know it is what we need

Le 7 sept. 2018 à 13:54, à 13:54, Jayesh Sindhav <notifications@github.com> a écrit:

**Comment by lexoyo** [comment]
Hi
@pseudozach and @swakarm 
I have added the env vars and buildpacks to app.json, it should work properly now
https://github.com/silexlabs/Silex/commit/8d6254864d0f907328e0ce9e660111a995c70965
Let me know if you find any bug
Thank you for your contributions!
