### ISSUE TITLE
Bootstrap container (proposal)

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#747]
This is a very easy easy component to do with Silex component system. It would be an easy step toward #655 and #387 

Note: it may be easy to use CSS grid instead of bootstrap? https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/

The "bootstrap container" component would add the bootstrap css class `container-fluid` to the body or a section, so it would be a 100% width container. All its children shoudl be containers with the bootstrap css class `row`. Their children will have the css classes like `.col-sm-`, `.col-md-`, `.col-lg-`, `.col-xl-` + the number of columns. See bootstrap docs

We will need to add to Silex the ability to get a set of CSS classes which are mandatory or optional on a component's childre. Let's say Silex could check if a function getChildrenClasses(context) is in the .md file of the component. it would return a set of optional and mandatory css classes with a selector to apply them:
`componentDef.getChildrenClasses({isMobile: true});` would return something like
```
[
  {
    name: 'Bootstrap row',
    className: 'row',
    mandatory: true,
    selector: ':scope > *',
  },
  {
    name: '12 columns',
    className: 'col-sm-12',
    mandatory: false,
    selector: ':scope > .row > *',
  },
  {
    name: '11 columns',
    className: 'col-sm-11',
    mandatory: false,
    selector: ':scope > .row > *',
  },
  ...
```

**Comment by budislav** [comment]
We need CSS grid rather than bootstrap, absolutely. CSS grid hasn't been invented at that time, so bootstrap is history for me.

**Comment by fullofcaffeine** [comment]
I think using Bootstrap makes sense. It's very popular and well-supported.
