### ISSUE TITLE
how do i set new page?

### ISSUE THREAD

**Issue by djjterror** [silexlabs/Silex#748]
I see option to add page but nothing happens... i still see my first page weather i click on first or on second one?  im confused!?

**Comment by djjterror** [comment]
if i select page 2 and delete something it gets delefed from page 1 aswell !???

**Comment by lexoyo** [comment]
Yes, you need to use "visible on" property, do not delete it
This way you can use it on multiple pages or not
-- 
Alex Hoyau
+33(0)676683806
Skype: alex.hoyau

**Comment by lexoyo** [comment]
Oh but the desktop site is all broken indeed... You'll have to put everything back in place, not sure why
