### ISSUE TITLE
Website aspect on different screens

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#750]
I have this exact problem, this leads to being unable to find and move elements on the mobile site. https://github.com/silexlabs/Silex/issues/548

**Comment by lexoyo** [comment]
I don't understand, please explain and provide screenshots

**Comment by FranGamer1892** [comment]
I meant the problem i mentioned at #548, my bad of using the words aspect ratio @lexoyo

**Comment by lexoyo** [comment]
Ok then, let's continue this discussion here

**Comment by lexoyo** [comment]
This is what I see, it looks ok to me
http://ami.responsivedesign.is/?url=http%3A%2F%2Fnotindie.pancakeapps.com

**Comment by FranGamer1892** [comment]
I'll check when I get on a PC. Meanwhile I have some Firefox Android pictures (Samsung Galaxy s5) 

https://www.dropbox.com/s/hnf3757frn2sg5w/Screenshot_2018-06-19-07-40-21.png?dl=0

https://www.dropbox.com/s/lrp77q01hettoia/Screenshot_2018-06-19-07-40-24.png?dl=0

Clicking redirects to Dropbox Inc., and their Terms and Policies.

**Comment by FranGamer1892** [comment]
http://prntscr.com/jwsln5
