### ISSUE TITLE
Website not working on Internet explorer

### ISSUE THREAD

**Issue by fernandammoutinhobarros** [silexlabs/Silex#751]
Hi,

My website is not working on internet explorer, I don't know if it's from web page code or if it's a problem with the server... 
It's working fine on chrome, opera and mozzila...

Can someone help me find out?

The website is
www.rar2018.net

Thanks for the help.

**Comment by fernandammoutinhobarros** [comment]
When I publish the website, it finishes but with these errors, could that be the problem?

![image](https://user-images.githubusercontent.com/25388113/41111149-1be678c2-6a73-11e8-9b80-94e326494191.png)

**Comment by FranGamer1892** [comment]
I don't have those. Could be an upload failure. Any broken link or corrupt file?

**Comment by FranGamer1892** [comment]
I don't know their location but the files are

Javascript: email.decode.min
Png:  circulo-grande  (big circle)

**Comment by lexoyo** [comment]
I believe these files have always been missing in your website, I think I saw them before

Can you explain what is not working plz? And maybe open the developer console and look for errors?

**Comment by lexoyo** [comment]
Hi @fernandammoutinhobarros any news about this?

**Comment by fernandammoutinhobarros** [comment]
I have an image inside a container with text on top. Could that be the problem?

![image](https://user-images.githubusercontent.com/25388113/41288164-4241c21a-6e3d-11e8-9d1c-6213fc0a8d86.png)


![image](https://user-images.githubusercontent.com/25388113/41288009-b1df25a0-6e3c-11e8-9196-add91187f777.png)



when I open the published file on internet explorer
![image](https://user-images.githubusercontent.com/25388113/41288370-fa0fc950-6e3d-11e8-948b-216b37a5c07e.png)
![image](https://user-images.githubusercontent.com/25388113/41288380-05b6d56e-6e3e-11e8-928a-f771d0199816.png)
![image](https://user-images.githubusercontent.com/25388113/41288384-0ba43764-6e3e-11e8-9010-591563ce69cc.png)

**Comment by fernandammoutinhobarros** [comment]
When I debugg on internet explorer

![image](https://user-images.githubusercontent.com/25388113/41288470-54ed0a0e-6e3e-11e8-9cec-39eedb341173.png)

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

**Comment by fernandammoutinhobarros** [comment]
Hi Lexoyo,
Still not working on Internet Explorer....

And when I publish I still get this error

![image](https://user-images.githubusercontent.com/25388113/43788413-3d70beea-9a65-11e8-85af-501847d0fcb6.png)

**Comment by fernandammoutinhobarros** [comment]
On IE

Blank page...



![image](https://user-images.githubusercontent.com/25388113/43788593-b8309b64-9a65-11e8-9533-f57308604d64.png)

**Comment by lexoyo** [comment]
I can see that you're opening the website with the protocol file://

Is in the same when you roasted online?

Le 7 août 2018 18:17, à 18:17, Azulinha <notifications@github.com> a écrit:

**Comment by fernandammoutinhobarros** [comment]
Yes

![image](https://user-images.githubusercontent.com/25388113/43791269-0ba3f6a4-9a6d-11e8-8c5d-9d40fd597f78.png)

**Comment by lexoyo** [comment]
I'll try to look at it this afternoon

**Comment by lexoyo** [comment]
Luckily I was working for a client today with windows! I could reproduce and fix
https://github.com/silexlabs/Silex/pull/775

It will be live on editor.silex.me in 10 min. I'm in a hurry so if it is not the case let me know, I would reboot the server

Thank you so much @fernandammoutinhobarros all the silex websites which have been published with the current version of Silex were broken in IE11, @ all please re-publish

**Comment by lexoyo** [comment]
Hello
I had to reboot the server, it is live now

**Comment by fernandammoutinhobarros** [comment]
Hello,


Working very good!!

Thank you Lexoyo!!

![image](https://user-images.githubusercontent.com/25388113/43891067-5b7fa99e-9bc0-11e8-87f5-b8e3cc14f455.png)
