### ISSUE TITLE
Favicon is not working.

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#753]
Why is not my favicon working? Website: http://notindie.pancakeapps.com

(can send you the link to the editable if you want)

**Comment by FranGamer1892** [comment]
(could also be my host's problem but I don't think so. May I also send ya the favicon?

**Comment by lexoyo** [comment]
Silex takes the path you give and put it in a link tag so this is about what the browsers expect

I believe every image format is good: PNG, jpg, ico

**Comment by FranGamer1892** [comment]
So everything should be OK...?

**Comment by lexoyo** [comment]
I don't know, it looks like the path is wrong

Can you screenshot the favicon setting plz?

**Comment by lexoyo** [comment]
I see the favicon for your site:
![screenshot from 2018-06-19 10-50-40](https://user-images.githubusercontent.com/715377/41587104-abba20ae-73ae-11e8-8239-c0ab003c823b.png)

Don't you see the same?

**Comment by FranGamer1892** [comment]
I now do. Thanks.
