### ISSUE TITLE
How to configure my page's SEO?

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#754]
I simply can't or don't know how...

**Comment by lexoyo** [comment]
In the settings you have an SEO tab
https://github.com/silexlabs/Silex/wiki/editor-ui#settings

Read the descriptions of each setting, is it clear?

**Comment by lexoyo** [comment]
Hi do you need help with this?

**Comment by FranGamer1892** [comment]
No I guess I'm done, I'll provide you the screenshots of the other issues
today afternoon.
