### ISSUE TITLE
Référencement

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#757]
Bonjour à tous,
a chaque fois que je veux faire évoluer mon site, je recharge la version comme un nouveau site sur netlify et je remet l'adresse de mon site. Savez-vous si cela annule le référencement dans les moteurs de recherche ou si celui-ci est associé à l'adresse et donc que cela ne change rien ?
Je vous remercie pour votre aide!
J'aurai aimé passé au prochain apéro Silex mais je ne pourrais pas.
Une prochaine j'espère.
Léa

**Comment by lexoyo** [comment]
Bonjour
Pourquoi crées tu un nouveau site? Tu peux simplement écraser l'ancien dans netlify
Dans tous les cas, pour le référencement
* l'adresse de ton site ne doit pas changer du tout
* il ne faut pas que google voit plusieurs version de ton site à différentes adresses car il l'interpretera comme du contenu dupliqué pour tricher

**Comment by Lea75** [comment]
Bonjour, Merci de ta réponse. Je ne sais pas comment écraser mon site sur netlify. A chaque fois je re-exporte un zip de silex, je le copie sur mon bureau, et je créer un nouveau site sur netlify ET APRES je remet l'adresse de mon site dessus en l'enlevant de l'ancienne version. Je vais essayer de trouver l'autre manière. Avec ma manière actuelle : je perds donc mon referencement ? Merci à nouveau et bon week-end 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., juin 22, 2018 à 15:50, Alex Hoyau<notifications@github.com> a écrit :   
Bonjour
Pourquoi crées tu un nouveau site? Tu peux simplement écraser l'ancien dans netlify
Dans tous les cas, pour le référencement
   
   - l'adresse de ton site ne doit pas changer du tout
   - il ne faut pas que google voit plusieurs version de ton site à différentes adresses car il l'interpretera comme du contenu dupliqué pour tricher

**Comment by lexoyo** [comment]
Non c'est bon si tu effaces l'ancien site après et si le nouveau est à la même adresse. C'est juste plus long...
