### ISSUE TITLE
Test the next version of silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#761]
Please test on <a href="https://preprod.silex.me">preprod.silex.me</a> before I release the next version which is:

> #760 new style editor and only 1 blank template

**Comment by lexoyo** [comment]
cc @ceubri @budislav @BaguetteAgile

**Comment by BaguetteAgile** [comment]
Bonjour Alex, 

je viens de tester la publication de mon site via [preprod.silex.me ](url) toujours le même problème qu'auparavant, certainement que tu dois fixer sur cette nouvelle version ?

Par contre sur [https://editor.silex.me/](url) sa fonctionne très bien. Merci d'avoir fixer ce problème.

Je continue de tester cette version...

**Comment by budislav** [comment]
Everything working nice, except that makes bunch of empty styles. Again I think you should release this, maybe is just my PC, if I am not only one even better you will get more feedback from users :)

**Comment by lexoyo** [comment]
> @BaguetteAgile: je viens de tester la publication de mon site via preprod.silex.me toujours le même problème qu'auparavant, certainement que tu dois fixer sur cette nouvelle version ?

Oui ca va etre bon sur preprod aussi d'ici 1h
:+1: 

> @budislav: Everything working nice, except that makes bunch of empty styles. Again I think you should release this, maybe is just my PC, if I am not only one even better you will get more feedback from users :)

Ok :+1: 

Thank you for your tests
I'll wait for some more tests, at least @ceubri

**Comment by ceubri** [comment]
yes je suis en train de tester...

**Comment by ceubri** [comment]
Mes commentaires :
- afficher la liste des styles par ordre alphabétique
- je n'ai pas trop compris ce que c'était (mettre un texte hover)
![image](https://user-images.githubusercontent.com/7302680/42081335-75db5564-7b85-11e8-8f95-bd8563aeab50.png)
- et peut-être (mais c'est juste pour dire qlq chose), lorsqu'on duplique le style d'un élément, appliquer ce style au bloc texte sélectionné
 
Sinon à part ça tout est ok pour moi, good job !

**Comment by FranGamer1892** [comment]
Hi, in https://preprod.silex.me/ and the latest version of Silex 

I can't use the cancel button on the file explorer, and if i click it, I am unable to use the OK button!

**Comment by FranGamer1892** [comment]
![screenshot_15](https://user-images.githubusercontent.com/13150712/43349957-0f6c14e2-91f3-11e8-9a46-895568d6d5b9.png)
Spelling mistake @lexoyo (it's "which")

By the way why does the page TALK IN FIRST PERSON?!

**Comment by budislav** [comment]
> I can't use the cancel button on the file explorer, and if i click it, I am unable to use the OK button!

yeah this is the old problem I noticed long time ago. This is really important to be fixed, otherwise you can loose your whole work each time.
