### ISSUE TITLE
"Preview" saves, "Preview in Responsize" shows old version

### ISSUE THREAD

**Issue by EiboThieme** [silexlabs/Silex#764]
Both in editor as well as in preprod the actions "Preview" and "Preview in Responsize" show strange behaviour. My expectation for a preview would be that I would be able to preview my changes, so that I could decide if I wanted to save my changes to the website. Neither action enables me to do this, "Preview" will immediately save my changes, possibly leaving me with a broken website, "Preview in Responsize" gives me a preview of the last saved state. Is this a bug or am I doing something wrong? Platform is Linux, Firefox ESR, Dropbox.

**Comment by lexoyo** [comment]
Hi sorry for the delayed answer
I think the preview could definitely be better, and I worked on a version where Silex changes the preview without saving or loading anything. I don't remember what was wrong with that but I didn't keep it :/

Both preview and responsize are supposed to work the same way

**Comment by lexoyo** [comment]
Unless someone is able to take over my old work on this, I'll close this issue :-/
