### ISSUE TITLE
The hint

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#765]
I accidentally put a hint in some of the properties but forgot what property was. I want to remove this hint from EVERYWHERE, help?? http://prntscr.com/k7qjbq

PS: Please answer my issues #750 #756

**Comment by lexoyo** [comment]
Ok I see
This hint comes from the title property, so select everything and check in the properties for the title ok?

**Comment by FranGamer1892** [comment]
Thx, solved. I just put a space.
