### ISSUE TITLE
Unable to install on CentOS 7

### ISSUE THREAD

**Issue by godzone** [silexlabs/Silex#767]
I am attempting to build Silex on a CentOS 7 virtual server and it fails.  I cloned the Git repo immediately before attempting the install

> cloud-explorer@2.0.0 build:sass /usr/local/Silex/node_modules/cloud-explorer
> node-sass --include-path src/sass --include-path node_modules/font-awesome/scss src/sass/style.scss dist/style.css

fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/Silex/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/usr/local/Silex/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/usr/local/Silex/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/Silex/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/Silex/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/Silex/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/Silex/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)

npm ERR! Linux 4.13.3-1.el7.elrepo.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:sass"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cloud-explorer@2.0.0 build:sass: `node-sass --include-path src/sass --include-path node_modules/font-awesome/scss src/sass/style.scss dist/style.css`
npm ERR! Exit status 1
npm ERR!

**Comment by lexoyo** [comment]
Is this error after npm install?

Le 23 juil. 2018 08:06, à 08:06, Glen Eustace <notifications@github.com> a écrit:

**Comment by godzone** [comment]
Not my day it would seem.  Now I get the following

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
[agree-38]Silex: npm run build

> Silex@2.2.7 build /usr/local/Silex
> npm run build:css && npm run build:html && npm run build:prodotype && npm run build:js:release


> Silex@2.2.7 build:css /usr/local/Silex
> lessc src/css/_styles.less dist/client/css/admin.css --source-map


> Silex@2.2.7 build:html /usr/local/Silex
> jade src/html/index.jade --out dist/client/ --no-debug


  rendered dist/client/index.html


> Silex@2.2.7 build:prodotype /usr/local/Silex
> prodotype src/prodotype/components dist/client/libs/prodotype/components/ && prodotype src/prodotype/styles dist/client/libs/prodotype/styles/

Building /usr/local/Silex/src/prodotype/components to /usr/local/Silex/dist/client/libs/prodotype/components in current dir: /usr/local/Silex
fs.js:932
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/usr/local/Silex/dist/client/libs/prodotype/components'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:932:18)
    at /usr/local/Silex/node_modules/prodotype/bin/prodotype:33:8
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/Silex/node_modules/prodotype/bin/prodotype:30:4)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

npm ERR! Linux 4.13.3-1.el7.elrepo.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:prodotype"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Silex@2.2.7 build:prodotype: `prodotype src/prodotype/components dist/client/libs/prodotype/components/ && prodotype src/prodotype/styles dist/client/libs/prodotype/styles/`
npm ERR! Exit status 1
npm ERR!

**Comment by lexoyo** [comment]
Ok so the previous error with cloud explorer vanished? Or maybe it is after building Silex ?

This error with mkdir could be linked to access right maybe... Does this folder exist?
/usr/local/Silex/dist/client/libs/prodotype/components


Le 23 juil. 2018 09:38, à 09:38, Glen Eustace <notifications@github.com> a écrit:

**Comment by godzone** [comment]
> On 23/07/2018, at 7:46 PM, Alex Hoyau <notifications@github.com> wrote:
> 
> k so the previous error with cloud explorer vanished? Or maybe it is after building Silex ?

I rebuild, the out I sent in my first reply, I thought all was ok so ran the ‘npm run build’ with no intervening commands and it failed, the output I included in the 2nd reply.

> 
> This error with mkdir could be linked to access right maybe... Does this folder exist?
> /usr/local/Silex/dist/client/libs/prodotype/components

The dir doesn’t exist.
[agree-38]Silex: ls -l /usr/local/Silex/dist/client/libs/prodotype/components
ls: cannot access /usr/local/Silex/dist/client/libs/prodotype/components: No such file or directory
[agree-38]Silex: 

I am running everything as root at the moment.

Glen

**Comment by JbIPS** [comment]
Hello Glen!

When running npm as root, it doesn't run the `postinstall` script.

Could you either:
 - run as an unprivileged user
 - run `npm run postinstall` manually

Thank you

**Comment by godzone** [comment]
All good, I now have a running instance.
Thanks.
