### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#772]
I saw it and it is pretty awesome but is there a way it lists? (the menu can be scrolled down if screen is small) #659

**Comment by FranGamer1892** [comment]
And a way interaction doesn't yet you to the beginning of the page?

**Comment by lexoyo** [comment]
For the vertical scroll, you can activate it like this: 
replace 
```
.navigation {
    /* critical sizing and position styles */
```
by this
```
.navigation {
    /* vertical scroll */
    overflow-y: auto;
    overflow-x: hidden;
    /* critical sizing and position styles */
```
also I see that for small window width, the horizontal scroll of the whole website disappears, it would be better to keep it I think, so you can remove this from the code
```
body {
    /* Without this, the body has excess horizontal scroll when the menu is open */
    overflow-x: hidden;
}
```
could you test it on small windows and tell me if I should change the widget for everybody to have these changes?

**Comment by lexoyo** [comment]
concerning the interaction I don't see how to prevent that scroll sory :(

**Comment by FranGamer1892** [comment]
Thanks, it is working so far.
