### ISSUE TITLE
Local installation on windows not working

### ISSUE THREAD

**Issue by bright-ic** [silexlabs/Silex#787]
I tried installing Silex as instructed on the installation page for windows, but i get this error and the app does not work on localhost:6805

This is the error displayed:

C:\page-designer\designer\Silex\node_modules\iconv>if not defined npm_config_nod
e_gyp (node "C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\npm
-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
 else (node "C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\ACER\AppData\Local\
Programs\Python\Python37-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\ACER\AppData\Roaming\n
pm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\ACER\AppData\Roaming\np
m\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\ACER\AppData\Roaming\npm\node_modules\npm\node_mo
dules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ACER\\AppData
\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
gyp ERR! cwd C:\page-designer\designer\Silex\node_modules\iconv
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2018-08-22T18_34_11_7
15Z-debug.log

Please how can i resolve this.

**Comment by lexoyo** [comment]
It looks like the python executable can not be found. Do you have python installed?

Please type "python" and see if it can be found

**Comment by bright-ic** [comment]
Please any help here would be really appreciated. 
Thanks.

**Comment by lexoyo** [comment]
In the error it says python can not be found
Did you try the command as I requested?

**Comment by lexoyo** [comment]
Oh sorry I just saw your previous message... Very odd 

Maybe @jbIPS can confirm it works with Windows?

**Comment by lexoyo** [comment]
Alternatively you can use Docker, would it be an option?

Why are you willing to build Silex locally?

**Comment by lexoyo** [comment]
I read on the web that this dependency requires python 2 maybe, could you try?
Also what's your nodejs version ?

**Comment by bright-ic** [comment]
I will try using Python 2 and see what happens.

My node version is 9.11.1.

Do I need to lower version of node too?

**Comment by lexoyo** [comment]
You can see what version it is tested with in the file .nvmrc 
Use nvm to switch (nvm i)

Le 23 août 2018 à 03:06, à 03:06, bright-ic <notifications@github.com> a écrit:

**Comment by bright-ic** [comment]
After installing python 2, this is the new error i am getting.


ACER@ACER-PC MINGW32 /c/page-designer/Silex (develop)
$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we re
commend using babel-preset-env now: please read babeljs.io/env to update!

> iconv@2.3.0 install C:\page-designer\Silex\node_modules\iconv
> node-gyp rebuild


C:\page-designer\Silex\node_modules\iconv>if not defined npm_config_node_gyp (no
de "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Pro
gram Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuil
d )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB6001: Invalid command line switch for "VCBuild.exe". Item ha
s already been added. Key in dictionary: 'Path'  Key being added: 'path' [C:\pa
ge-designer\Silex\node_modules\iconv\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:239:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\page-designer\Silex\node_modules\iconv
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2018-08-23T20_34_29_1
23Z-debug.log

What can i do.

**Comment by lexoyo** [comment]
Wow I never saw this one either

* Do you use the node version as defined in the .nvmrc file?
* Would you consider using Docker to run Silex ? (Depends on what you use it for locally)

Le 23 août 2018 à 22:39, à 22:39, bright-ic <notifications@github.com> a écrit:

**Comment by bright-ic** [comment]
I haven't used docker before, but i will give it a try. Any useful hint on how to use docker would be appreciated.

I want to create an online flyer, banner etc editor using html tags [elements] (just like how silex edits html pages) and silex provides a platform to do that. 
Silex is a powerful tool to be limited to just web page creation. It can do much more.

A client of mine needs it and am kind of out of time.
Your helps are very much appreciated

**Comment by lexoyo** [comment]
Ok then maybe you can use docker
You should follow these instructions: https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#recommended-with-docker
If you wat to talk about how you would tweek silex and how much work that represents, feel free to contact me by email and we can schedule a call maybe (a.hoyau at silexlabs.org)

**Comment by bright-ic** [comment]
Ok. Thanks.
I will sure contact you.

**Comment by lexoyo** [comment]
Hi @bright-ic any news about your install? Did it work with docker?
