### ISSUE TITLE
Default fonts in Silex, your opinion wanted

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#790]
Hello
Here is a question: what fonts should I allow in Silex UI by default?
In Silex the fonts need to be pixel perfect on all browsers because the users give precise size to text boxes

I am not sure what fonts I should include... For now on preprod.silex.me I've included
* Arial
* Courier New
* Georgia
* Times New Roman
* Trebuchet MS
* Verdana

They all behave differently in chrome and firefox...

What should I do?

1- only use embedded fonts for silex websites
2- find web safe fonts which display the same on all browsers? maybe svg fonts?
3- other ideas?

**Comment by BaguetteAgile** [comment]
Hi Alex,

the first solution seems good to allow Silex to stand out compared to other web font.

the second solution is certainly a way to view the font used on the browsers of our visitors.

As you say that Silex needs precise font, certainly the 1st solution is the best ...

**Comment by lexoyo** [comment]
Back to this subject as it is blocking for the release of the new text editor and style manager. Let's adopt the solution 1 as suggested by Baguette

The solution I have in mind is 

* Step 1: select a set of fonts and hard code it, which means the "font family" drop-down list will have these fonts and a font will be embedded in the website if the user selects it in a style somewhere
* Step 2: add a "fonts manager" somewhere, which is just a list of fonts, and let the user change the list of fonts wich are shown in the "font family" drop-down list, so the user can add fonts by adding a URL to the list
* Step 3: integrate a font provider such as http://open-foundry.com/ and let the user list, preview and select fonts

Open questions

* The 1st step may be enough?
* Where should I put the fonts dialog? In the settings as a tab like "publish settings"?
* Which font provider should we choose? Google font is ... Google... So I downvote it but let me know if it has to be it... I don't know any open and community driven font service

Thx again baguette, please continue contributing!! ;)

**Comment by lexoyo** [comment]
Hi
I went straight to step 2
![screenshot from 2018-09-21 13-45-41](https://user-images.githubusercontent.com/715377/45879432-c14aef80-bda4-11e8-8dfe-93273fe222b9.png)

**Comment by lexoyo** [comment]
Hi
Did someone test the new font manager?

**Comment by BaguetteAgile** [comment]
Hi, I tested on my site with these fonts 

http://typotheque.interstices.io/

and everything works fine.

Only, it is necessary to reload the web page of Silex with each addition of font.

Good job ;)
