### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#794]
Salut Alex,

Il y a un problème avec le Favicon, lors de la "Preview" c'est ok l'image apparaît bien, par contre lors de la publication le fichier semble ne pas être pris en compte.
Mon image fait 2,8 ko et un carré de 32Px.

Cela fait déjà un bon moment que le problème persiste.

**Comment by lexoyo** [comment]
c'est fix et en ligne sur editor.silex.me
https://github.com/silexlabs/Silex/pull/799

Merci @BaguetteAgile !!!

**Comment by lexoyo** [comment]
can you confitm @BaguetteAgile ?

**Comment by BaguetteAgile** [comment]
J'ai fait un test sur editor.silex.me ET sur preprod.silex.me et voici le message d'erreur pour le Favicon.


![capture du 2018-09-05 21-19-29](https://user-images.githubusercontent.com/35597855/45116141-2d491900-b152-11e8-8ad0-b1b42299fbcf.png)

**Comment by BaguetteAgile** [comment]
@lexoyo  

Malgré le message d'erreur ci-dessus, je te confirme que le Favicon fonctionne lors de la publication du site.Tester avec Firefox et Chromium.
