### ISSUE TITLE
Failing to publish site to webdav connection.

### ISSUE THREAD

**Issue by NaomiSangui** [silexlabs/Silex#795]
I have a webdav connection to my nextcloud server. I can save my site to the server but when ever I try to publish I always get this error: Error message: Cannot read property 'Symbol(Symbol.iterator)' of undefined

Any help on this would be appreciated.
Also as a side note I can publish my site to dropbox.

![chrome_2018-09-02_03-59-53](https://user-images.githubusercontent.com/41605707/44955217-b74c6580-ae64-11e8-92d4-ed6d9514df4c.png)

**Comment by mathieumassage** [comment]
Hello,
I have the same problem...

**Comment by lexoyo** [comment]
Hello
@JbIPS [fixes](https://github.com/JbIPS/CloudExplorer2/commit/a82cbf304be0f1034a93167248f796c4cc660d31) are now live on https://preprod.silex.me
Could you test and report if it fixes the issue please?

**Comment by mathieumassage** [comment]
Hello,
No sir because i don't understand ! I observe that i'm connected to my ftp server but i can't publish.
Sorry

**Comment by NaomiSangui** [comment]
I tried to log in to my nextcloud using webdav but i get this error. Cannot access server. Please check your credentials. Error: getaddrinfo ENOTFOUND https https:443. I am using the right credentials cause I can log in on the normal Silex editor here. https://editor.silex.me/

**Comment by jotakar** [comment]
I get same error, but I can publish using a "fs" service.

**Comment by jotakar** [comment]
I've been working with publish code and I've senn these lines in readOperations (PublishJobs.js)
`      if(err.code != 'ENOENT') {
        throw err;
      }`
Working in local (fs service) it's fine, but using FTP I got an err.code 'EIO' so the error message appears and publish is cancealed.
I've put this 
      if(err.code != 'ENOENT' && err.code != 'EIO') {
        throw err;
      }
And now it works.
I know this is not a solution, we can not ignore EIO (input output error), but it can be a temporary solution.
EIO appears for esample if I read/write from a disconnected device. I think, so.
Bye

**Comment by JbIPS** [comment]
Do you see your files on the server when the error occurs? That would be super weird

**Comment by jotakar** [comment]
Which files? Let's see: when the error appears the files are not sent through the FTP.  Perhaps it's a fault in FTP socket? ??

**Comment by JbIPS** [comment]
Clearly something is wrong with a connection. Dumb question: are you sure about the URL, the port and the credentials?

**Comment by jotakar** [comment]
of course. I repeat: if I made this change
if(err.code != 'ENOENT') { throw err; }
Working in local (fs service) it's fine, but using FTP I got an err.code 'EIO' so the error message appears and publish is cancealed.
I've put this
`if(err.code != 'ENOENT' && err.code != 'EIO') {
throw err;
}`
All works fine.

**Comment by lexoyo** [comment]
hi
is this issue solved? should we close it?

**Comment by jotakar** [comment]
The FTP connection works fine at this moment, so you can close.

**Comment by Bellusterra** [comment]
may we please re-open this, the webdav to Nextcloud per the original post does not function.
