### ISSUE TITLE
add custom unifile services

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#803]
@JbIPS @godzone what do you think?
This is where you would add custom services
https://github.com/silexlabs/Silex/pull/802/files#diff-f4e33cb9922134499ac778b8b3566937

I did not test this with a service, but it should work even if unifile and express are started already when you add services and routes for callbacks

**Comment by lexoyo** [comment]
Oh and I forgot to say that the use case is for a hosting company to have a separate repository, with Silex as a npm dependency

package.json
```
...
  "dependencies": {
    "silex": "github:silexlabs/Silex#master",
    "myunifileconnector": "github:you/yourunifileconnector#master"
  }
...
```

index.js file:

```
const SilexServer = require('./silex');
const config = require('silex/EnvVarsConfig');
const silex = new SilexServer(config);
// add unifile connectors
silex.ceRouter.addService(...)
// add custom routes
silex.app.get(...)
```

**Comment by godzone** [comment]
I like the way you have re-worked silex, to my mind it would make it much less invasive to extend.

It is a fairly major change but I think would make it easier for people like me to work with.

Glen

**Comment by lexoyo** [comment]
Silex is now an npm dependency, one can add it to a project and set the config and add custom services or hosting providers

would someone test this with me?
