### ISSUE TITLE
Cookies using

### ISSUE THREAD

**Issue by Rom25** [silexlabs/Silex#804]
is Silex using cookies ? shall I inform the visitors of my website for that?
French law is very strict for that
By advance thank you for you answer
kind regards

**Comment by lexoyo** [comment]
Hello
Who's Bob?! :))
Silex editor uses cookies
Website made with Silex do not use cookies for your visitors

**Comment by Rom25** [comment]
Hello, 
I have used "Bob" to be sure about my translation and I have made a to quick copy/paste :-)
Thank you for your answer.
