### ISSUE TITLE
Slideshow bug (Fr)

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#807]
Bonjour @lexoyo 

je viens de m’apercevoir que le menu `paramètre` du Slideshow n'est plus accessible en utilisant un site déjà créer.

En fait je voulais changer quelques photos de mon site sur lequel j'utilise le `Slideshow` et impossible d'ouvrir l'onglet `paramètre` aussi bien sur `preprod` que sur `editor`

Par contre si je crée un nouveau site vierge sur lequel j'insert un `Slideshow` vierge, le menu `paramètre` est bien accessible sur editor.silex.me et preprod.silex.me

**Comment by lexoyo** [comment]
Hi baguette 
merci pour le bug report
tu peux me partager un site qui bug stp?

**Comment by BaguetteAgile** [comment]
Salut Alex,
tu as toujours accès à ma Dropbox, pour le site Just-Friends.
justfriendsmars2018.html page " presentation des musiciens"

**Comment by lexoyo** [comment]
ok j'ai mis le temps mais j'ai fini par trouver
c'est assez proche de cette issue: #808
il semble qu'on peut "casser" son site avec certaines balises html
dans ton site, il manque une balise </script> ici
![screenshot from 2018-09-25 17-43-45](https://user-images.githubusercontent.com/715377/46026160-f039cc00-c0ea-11e8-99e3-855b62e747f8.png)
![screenshot from 2018-09-25 17-43-22](https://user-images.githubusercontent.com/715377/46026161-f039cc00-c0ea-11e8-8fa0-f2036b62556f.png)
il faut donc ouvrir le ficher avec un editeur de text et ajouter `</script>` apres `/* ------------------------------ */`
il faut aussi supprimer les infos que silex a re-créé puisqu'il ne les trouvait plus, il faut donc supprimer tout ca:
![screenshot from 2018-09-25 17-48-52](https://user-images.githubusercontent.com/715377/46026295-51fa3600-c0eb-11e8-94f4-515c746a0ede.png)

je vais tenter de fixer le probleme bientot
en attendant dis le moi si tu veux que je le fasse pour toi

**Comment by BaguetteAgile** [comment]
Salut Alex,
j'ai beau chercher après ce fichier JS, mais je ne trouve pas, ( enfin, je ne sais pas ou chercher exactement, dans Silex, dans ma Dropbox ou avec le débogueur du navigateur ???) 

Tu peux toujours fixer le problème pour moi, mais j'aimerai bien savoir ou trouver ce fichier, comme cela j'apprends encore des choses en informatique.

Merci d'avance.

**Comment by lexoyo** [comment]
> j'ai beau chercher après ce fichier JS, mais je ne trouve pas, ( enfin, je ne sais pas ou chercher exactement, dans Silex, dans ma Dropbox ou avec le débogueur du navigateur ???)

c'est dans le html, le seul fichier que tu édites avec Silex :)

> Tu peux toujours fixer le problème pour moi, mais j'aimerai bien savoir ou trouver ce fichier, comme cela j'apprends encore des choses en informatique.

je peux mais dis moi sur quel fichier le faire

**Comment by BaguetteAgile** [comment]
Merci pour ta réponse, j'ai bien trouvé le fichier mais pas réussi à trouver les quelques lignes à supprimer,

![46026295-51fa3600-c0eb-11e8-94f4-515c746a0ede](https://user-images.githubusercontent.com/35597855/46110819-252a4980-c1e5-11e8-9bbc-6c0a88597750.png)


 donc pour ne pas faire de boulette, je te laisse faire la correction.

Le fichier à corriger est le suivant: `Dropbox/nouveausitejustfriends/publication site/index.html`

Merci ;)

**Comment by BaguetteAgile** [comment]
Je pense t'avoir indiqué un mauvais fichier, le fichier que Silex ouvre pour faire le site est le suivant:

`Dropbox/nouveausitejustfriends/justfriendsmars2018.html`

**Comment by BaguetteAgile** [comment]
Salut @lexoyo 

Je viens de m'apercevoir de ceci:

quand j'ouvre Silex et le site de JustFriends, quand je sélectionne un élément il y a ceci dans la barre en bas de Silex, ce qui est normal:

![capture du 2018-10-09 14-18-04](https://user-images.githubusercontent.com/35597855/46669020-774c7100-cbce-11e8-990b-fa173d6e1cf8.png)

je me rend sur la page ou il y a le "Slideshow" je double clic dessus afin de pouvoir l'éditer, dans les paramètre du Slideshow, Rien ( normal c'est le souci ) par contre dans le bas de Silex, il n'y a plus les différentes Div...

![capture du 2018-10-09 14-15-18](https://user-images.githubusercontent.com/35597855/46669100-be3a6680-cbce-11e8-85a5-2535ac91ba76.png)

Ceci dans toute les pages du site, après avoir voulu éditer le "Slideshow" !

Je pousse mon investigation avec un autre site, ( je charge un autre site via le cloud ) le même phénomène sur toute les pages et éléments

![capture du 2018-10-09 14-15-18](https://user-images.githubusercontent.com/35597855/46669230-2426ee00-cbcf-11e8-8992-79a778335fa9.png)

Les Div semble, ne pas être sélectionnées, impossible de changer une photo, le texte editor reste vierge 

![capture du 2018-10-09 14-36-58](https://user-images.githubusercontent.com/35597855/46669834-d9a67100-cbd0-11e8-9855-337de98ec14d.png)


Je ferme Silex, le ré-ouvre et là, Silex fonctionne correctement 

![capture du 2018-10-09 14-18-04](https://user-images.githubusercontent.com/35597855/46669301-56385000-cbcf-11e8-92c4-696a6d19719e.png)

J'espère avoir été compréhensif ...

**Comment by lexoyo** [comment]
hmm :-/
ca doit etre une erreur JS qui fait tout planter... tu peux ouvrir ta console de debug et vérifier stp?

**Comment by BaguetteAgile** [comment]
Salut Alex,

je ne sais pas si cela peux t'aider, mais je n'ai trouver que cela comme erreur dans la console de degug

4 fois la meme erreur, il y a que ceci `3fdf4366-b2f0-4508-bc00-727c9b06795e` qui change dans le message de la console.

![capture du 2018-10-25 21-32-37](https://user-images.githubusercontent.com/35597855/47525504-b7ce0f00-d89d-11e8-9b4b-ef0471948db4.png)


`Erreur lors du chargement de cet URI : Could not load the source for blob:https://preprod.silex.me/3fdf4366-b2f0-4508-bc00-727c9b06795e.
[Exception... "Failed to open input source 'blob:https://preprod.silex.me/3fdf4366-b2f0-4508-bc00-727c9b06795e'"  nsresult: "0x805303f4 (<unknown>)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: mainThreadFetch :: line 644"  data: yes]
Stack: mainThreadFetch@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:644:5
_getSourceText/<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/source.js:417:29
Line: 644, column: 0`

**Comment by BaguetteAgile** [comment]
![capture du 2018-10-25 21-41-55](https://user-images.githubusercontent.com/35597855/47526024-ded91080-d89e-11e8-9367-27e1d8017803.png)

**Comment by lexoyo** [comment]
baguette tu as toujours ce bug de slideshow?

**Comment by BaguetteAgile** [comment]
Oui, j'ai toujours le même bug :(

**Comment by lexoyo** [comment]
ok ca aide merci

**Comment by lexoyo** [comment]
en fait je ne comprends pas, il y a encore le bug que j'avais corrigé
je peux re-corriger mais dis moi précisément quel fichier stp

**Comment by BaguetteAgile** [comment]
Voici l'adresse du fichier à rectifier.
`Dropbox/nouveausitejustfriends/justfriendsmars2018.html`

**Comment by BaguetteAgile** [comment]
@lexoyo 
Salut Alex,
je pense que tu peux fermer ce post, car j'ai supprimer mon ancien Slideshow et remplacer par un nouveau dans ma page.
Tout fonctionne parfaitement.
