### ISSUE TITLE
silex logo in the UI

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#809]
Hello
What do you think of how the logo looks when I put it in the UI?

![screenshot from 2018-09-18 11-16-56](https://user-images.githubusercontent.com/715377/45677406-64e19900-bb34-11e8-9315-8a3d6490bf6f.png)

cc @ceubri @clemos @budislav @baguette

**Comment by lexoyo** [comment]
![screenshot from 2018-09-18 11-56-15](https://user-images.githubusercontent.com/715377/45680136-6f9f2c80-bb3a-11e8-814d-83db3b27c93f.png)
 
Oh yes it look better? then maybe the favivon should stay black?

**Comment by budislav** [comment]
It's nice, but I already hinted the problem with color order, especially green and blue.

**Comment by ceubri** [comment]
I prefer the first. 
But without the title "Silex" it's look like a button.
Maybe try a different position ?
![screen](https://user-images.githubusercontent.com/7302680/45688274-3aea9f80-bb51-11e8-9cef-df9a4023b404.jpg)
[silex-logo-2018-alternative-white.pdf](https://github.com/silexlabs/Silex/files/2392677/silex-logo-2018-alternative-white.pdf)

**Comment by lexoyo** [comment]
> What happens if you click on it ?
> People may think it's a button, so maybe confusing.
> But without the title "Silex" it's look like a button.

For now it opens the "about menu", the same as the "?" in the menu bar

![screenshot from 2018-09-18 15-18-37](https://user-images.githubusercontent.com/715377/45690228-252ba900-bb56-11e8-86ac-df7f09206114.png)

> Maybe try a different position ?

Yes why not
What should we do?

> It's nice, but I already hinted the problem with color order, especially green and blue.

I did not understand :-/

**Comment by budislav** [comment]
Well look at the contrast between blue and orange, also green and blue together looks like the same color on that size, orange is dominating like crazy.

**Comment by budislav** [comment]
> Should I use a black and white version maybe

Definitely, if you don't want distracting attention with that rainbow.

**Comment by BaguetteAgile** [comment]
GREAT, the color logo looks attractive to me, but that's the first thing I saw when opening SILEX.

The logo attracts the attention of the user, which is a good thing in my opinion,
because the user discovers the part "About Silex" and can bring him to contribute with us and discover the WIKI ...

the explanation part of new software is important for a new user.

**Comment by budislav** [comment]
> The logo attracts the attention of the user, which is a good thing in my opinion,
> because the user discovers the part "About Silex" and can bring him to contribute with us and discover the WIKI ...

Yes, for the first time you open it, but not each time.

**Comment by lexoyo** [comment]
Let's try the black and white too and we talk about it then
I talked to @ceubri and he will provide a black and white logo for me to try
... To be continued ....
Thank you for helping me out one more time, we will manage to release this and Silex will be awesome again ;)

**Comment by ceubri** [comment]
![screen](https://user-images.githubusercontent.com/7302680/45817033-c133ec80-bcdd-11e8-8b14-a64cb51bbe28.jpg)
[silex-logo-2018.zip](https://github.com/silexlabs/Silex/files/2401154/silex-logo-2018.zip)
like this ?

**Comment by budislav** [comment]
I think it should be placed in top left corner.

**Comment by lexoyo** [comment]
@ceubri ok for you? top left corner?

@ all and what about the favicon? in black and white or in color?

![screenshot from 2018-09-26 12-58-51](https://user-images.githubusercontent.com/715377/46076187-19ab3400-c18d-11e8-99fb-d25460be79c5.png)

**Comment by budislav** [comment]
favicon should be in color, but with rearrange of colors and some pixel perfect improvement.

**Comment by ceubri** [comment]
i prefer the top centred versions (the top left version looks like a tool).

**Comment by lexoyo** [comment]
Ok :))
@clemos ? @bagueteagile ?

**Comment by budislav** [comment]
@ceubri if there is a text "silex" next to the icon it would look much better.

**Comment by lexoyo** [comment]
Oh so you are proposing a b&w logo with text but on the left?

**Comment by BaguetteAgile** [comment]
Hi 
i prefer Centred version.

**Comment by budislav** [comment]
@lexoyo exactly.

**Comment by lexoyo** [comment]
![screenshot from 2018-09-27 15-43-52](https://user-images.githubusercontent.com/715377/46150179-4a15cf80-c26c-11e8-978f-ff50424b7bfb.png)

This looks good ?

**Comment by ceubri** [comment]
great !

**Comment by BaguetteAgile** [comment]
Yes !!  Very Good 😉

**Comment by lexoyo** [comment]
Haha ok cool!!!!!
Thank you very much guys
