### ISSUE TITLE
CERT_UNTRUSTED

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#810]
I'm having install problems wit error message, In log I have several lines like:
`391 info trying registry request attempt 1 at 18:23:33
392 http GET https://registry.npmjs.org/cloud-explorer
393 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
394 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED`

Install process is too hard in my opinion
Is ther any kind of install by hand? I think it would be easier.

**Comment by lexoyo** [comment]
I agree for the install process, many sub-projects with too many different technologies... As always in free software :-/

What is your version of nodejs and npm please?

Le 19 sept. 2018 à 18:34, à 18:34, jotakar <notifications@github.com> a écrit:

**Comment by jotakar** [comment]
I've used skip cert and now
silex-blank-templates is not a valid repository name
github:silexlabs/silex-templates is not a valid repository name

????

**Comment by jotakar** [comment]
Versions (on Ubunto 14)
nodejs v0.10.25
npm  1.3.10

**Comment by lexoyo** [comment]
Oh these are very old versions not even supported by the nodejs community anymore ;)
Please see the file .nvmrc which tells you which nodejs version is needed

Le 19 sept. 2018 à 18:57, à 18:57, jotakar <notifications@github.com> a écrit:

**Comment by lexoyo** [comment]
No problemo
