### ISSUE TITLE
New Silex templates, your opinion wanted

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#813]
These are templates which I have made to test silex and never released yet. Which one(s) do you want to keep?
 
* [agency](http://lexoyo.me/GrrHost/21924/agency/)
* [air](http://lexoyo.me/GrrHost/21924/air/)
* [creative](http://lexoyo.me/GrrHost/21924/creative/)
* [perso3](http://lexoyo.me/GrrHost/21924/photo/editable.html)

**Comment by BaguetteAgile** [comment]
The most successful site is AIR without any doubt;)

for the other 3, I am of the same opinion that @jotakar  good job.

**Comment by lexoyo** [comment]
ok thank you for your feedback
