### ISSUE TITLE
Mobile menu making

### ISSUE THREAD

**Issue by rijschoolthomas** [silexlabs/Silex#814]
Hi there, my name is Michael and am a beginner in Silex and no experience in CSS or Java. 

So this is what I've fabricated so far with Silex : [My website](https://rijschoolthomas.github.io/website/) 

But i have 2 questions:

First:
In the desktop editor I've placed a section. Now i would like for this section to only be seen in the mobiel editor, but in such a way that it doen't take up any line-spacing in the desktop. <-- is this possible, and if yes how?

Second:
I have quit a few menu items in the desktop, some of which I don't want to be seen in the mobiel hamburger menu. What I would like is the mobiel menu showing menu items like here under:

Menu-items
A
B +  ----->  B1
C ..............B2
D...............B3
..................B4

Cheers,
Michael

**Comment by lexoyo** [comment]
Hi Michael and welcome in the web design world ;)

First question: if your section is empty (no element in it, just make it as small as possible, it will still be visible and take some space in the editor but will disappear in the live website and preview

Otherwise you will need a little piece of code I can provide. It is a common feature request, we should add a button somewhere to do that one day

**Comment by lexoyo** [comment]
Second : you will need to create your own hamburger menu. Here is a widget which is a bit tricky but does this
https://github.com/silexlabs/Silex/issues/659
Leave a comment there if you find it too complex we'll help you

**Comment by rijschoolthomas** [comment]
Thanks Alex.

Cheers,

Michael

Op za 29 sep. 2018 15:33 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
Hi Alex, won't #659 <https://github.com/silexlabs/Silex/issues/659> only
make a hamburger menu in the desktop editor and NOT in the mobiel editor?

Is there any way to edit the existing hamburger menu of the mobiel editor?

As i have a lot of menu items in the desktop editor, the hamburger menu in
the mobiel editor doesn't show all of my menu items. So I would like to be
able to create a categorised version. Like here under. So when I click the
main categorie only the sub categories can be clicked to open.

*HAMBURGER MOBIEL editor MENU*
*Main categories  /  Submenu categories*

*A                       *
*B + ...................... ** b1*
*C + ......................  **b2 .... **c1*
*                                         c2*
*                                         c3*


*Cheers, Michael*

Met vriendelijke groet,

*Michael Thomas*


Op za 29 sep. 2018 om 15:33 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
Hi Alex,
Yes could you please send me or point me to the code to make the menu
catagories as mention befor.

I have made a test site for the menu (
https://rijschoolthomas.github.io/test1/   ) so ik can play with the code
befor i implement it on my website:
https://rijschoolthomas.github.io/website/

Cheers,
Michael

Op zo 30 sep. 2018 02:26 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
Hi Alex,

I've found a mobiel menu that i would like to implement on my site. This is
were the code and the tutorial is:
http://mmenu.frebsite.nl/tutorials/mhead-plugin/
It's supposed to be easy, but i just don't understand what to do; were to
put the code or the plugins.

Could you please guide me through this proces?


Op zo 30 sep. 2018 om 10:58 schreef Michael Thomas <mtmail007@gmail.com>:

**Comment by lexoyo** [comment]
oh nice menu! but you need to pay if you activity is for profit :-/
so maybe this (free) one could be better ? https://mm.onokumus.com/mm-vertical.html

nevertheless i played with this menu you found and here is how i got it to work in silex:

1. in the "html head editor" from the code menu (</>) 
```
   <script src="//mmenu.frebsite.nl/mmenu/jquery.mmenu.all.js"></script>
   <link href="//mmenu.frebsite.nl/mmenu/jquery.mmenu.all.css" rel="stylesheet" />
```

2. in the "javascript editor"
```
jQuery(document).ready(function( $ ) {
    $(".menu").mmenu({});
      var API = $(".menu").data( "mmenu" );
      $(".open").click(function() {
         API.open();
      });
});
```
3. create a button to open the menu and put the css class name `open` on it
![screenshot from 2018-10-02 12-16-28](https://user-images.githubusercontent.com/715377/46343116-042a8400-c63d-11e8-8254-da0a236fdb87.png)


4. create the element containing the menu. here you have 2 options:
  4.1. create a text box and put a bullet list with your links to other pages in it - with this you can not have nested submenus so I think it is not what you need
![screenshot from 2018-10-02 12-17-52](https://user-images.githubusercontent.com/715377/46343177-33d98c00-c63d-11e8-95f4-b6cd5a8cd9b7.png)
  4.2. or create an html box with this HTML in it 
```
 <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About us</a>
       <ul>
          <li><a href="/about/history">History</a></li>
          <li><a href="/about/team">The team</a></li>
          <li><a href="/about/address">Our address</a></li>
       </ul>
    </li>
    <li><a href="/contact">Contact</a></li>
 </ul>
```
5. put the `menu` class name on the element containing the menu
![screenshot from 2018-10-02 12-26-54](https://user-images.githubusercontent.com/715377/46343561-76e82f00-c63e-11e8-9c0c-8f2655e20037.png)

If you need to show an element only in mobile mode, add this to your "css editor"
```
@media (min-width:481px) {
.hide-on-desktop {
display: none;
}
}
```
and then add the css class `hide-on-desktop` to the element you want to hide on desktop

**Comment by rijschoolthomas** [comment]
Hi Alex,
I tried the frebsite menu, but I can't get it to work. I am also not able
to hide the menu on the desktop. See
https://rijschoolthomas.github.io/test1/

I'm going to now try to do the menu you advised:
https://mm.onokumus.com/mm-vertical.html

Op di 2 okt. 2018 om 12:31 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
@rijschoolthomas in https://rijschoolthomas.github.io/test1/ i don't see the javascript code (step 2)

**Comment by rijschoolthomas** [comment]
The javascript is in there. see png



Op do 4 okt. 2018 om 11:56 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
What PNG?

**Comment by rijschoolthomas** [comment]
In the my reply email.

Op do 4 okt. 2018 14:37 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
![javascript code](https://user-images.githubusercontent.com/43305374/46478950-48a95180-c7ee-11e8-8bd0-6325ff5444f6.png)

**Comment by rijschoolthomas** [comment]
Hi Alex,
I've fabricated a hamburger menu (  https://rijschoolthomas.github.io/test2/  )by using Bootstrap: http://getbootstrap.com/docs/4.1/components/navbar/

Question:
1 - How can I remove the silex hamburger menu so only the bootstrap menu remains?
2 - How do I hide the bootstrap hamburger menu from the desktop?

**Comment by rijschoolthomas** [comment]
Hi Alex played around with it for a bit and got it to work. A bit
differently than you suggested. I needed to put al the code (the script
included) in a html container. I've hid the menu on the desktop and it stil
appears on the mobiel. Hoera!!!
I got rid of the silex menu. Hoera!!

But I can't get the Bootstrap menu to go top left hand corner as it did
when i put the code in the HTML head editor.
- Have you got any ideas how to put the mobiel menu in the top left hand
corner?




Op ma 8 okt. 2018 om 12:26 schreef Michael Thomas <mtmail007@gmail.com>:

**Comment by rijschoolthomas** [comment]
Here it is: https://rijschoolthomas.github.io/test2/




Op ma 8 okt. 2018 om 14:25 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
I see that it works in your example now, did you figure out how to do it?

Here are more tips: 
1- this should be removed completely as silex inserts it already:
```
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rijschool Thomas - Regio Amersfoort</title>
    <script src="js/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" type="text/javascript"></script>
```

2- this should be moved to the html head:

```
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="js/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous" type="text/javascript"></script>
    <script src="js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous" type="text/javascript"></script>
```

**Comment by rijschoolthomas** [comment]
Hi Alex, thanks for the adjustments.
Yes I worked it out myself but my solution was to dump everything in a html
element. And that's how I got the menu to work.

I have now applied your adjustments

But I'm afraid your adjustments didn't quit work. I had to tweak a bit to
get the menu to work. See the following remarks:

I could not remove the following script from the html element or else the
menu would not work. (<script src="js/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous" type="text/javascript"></script>   )

Also i couldn't move the following script from the html element to the HTML
Head editor either, because that also caused the menu not to work. So I put
it back were it was and that got the menu working again.

    <link rel="stylesheet" href="
https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous">

The rest of your adjustments I applied and as you can see are working as
they should: https://rijschoolthomas.github.io/test2/

Today I tried to put the menu code (not with your adjustments) into my
website. And it messed up a lot of my page. I had to put back a back-up to
sort the mess out. So when i have the time I try and implement the menu
code, with your (working) adjustments, in to my website and hope for the
best. I'll let you know how it went.

Michael






Met vriendelijke groet,

*Michael Thomas*


Op di 9 okt. 2018 om 16:09 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
Hi Alex,
Again I've tried putting the menu code in my website, but it doen't work. I also tried copying the mobiel menu code 1 to 1 from the https://rijschoolthomas.github.io/test2/ site to my website. It's just not working and it's also messing up the websit. I think there must be some code that is conflicting with the code already on my website. Any ideas? 

This is the website i'm trying to put the mobiel menu on:  https://rijschoolthomas.github.io/website/

By the way. The code to for hiding the menu on the desktop works like a charm.

**Comment by lexoyo** [comment]
@rijschoolthomas i have looked into it and it appears that you are including another version of jquery in the page: Silex has v2.2.4 and you include v3.3.1

silex should be compatible with v3.3.1, but the menu seems to require the v3.3.1

so could you please do this:
* remove the tag `<script src="js/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous" type="text/javascript"></script>` from your website
* replace the content of the script `https://rijschoolthomas.github.io/test2/js/jquery.js` with the content of `https://rijschoolthomas.github.io/test2/js/jquery-3.3.1.slim.min.js`

this should work but before i upgrade to v3.3.1 all silex websites, we will need to run some tests

**Comment by rijschoolthomas** [comment]
Hi Alex,

Made your changes to the "test2" site first and it worked. But then again it was working before I made the changes. I've also made the same changes to the "website" site and the menu worked. HOERA! 
Thanks :-)

A question: will I have to change any of my code when you upgrade silex to v3.3.1?

But now I have the following problem since I made your last changes. I'm not able to hide anything anymore, in either sites, with the code for the CSS editor you gave me and filling in "menu" in the CSS class: 
@media min-width: 481px, min-device-width: 481px {
.menu {
  display: none;
}
}  
--------------------------------------
Another problem I have (not related to the menu problem): I'm not able to fill in the Alt (images only) tekst. It keeps disappearing. Shouldn't the tekst be visible if the image is selected?

Cheers,

Michael

**Comment by rijschoolthomas** [comment]
Hi Alex, have you seen my reply/questions here above. Or are you a bit too busy at the moment to look in to the issue?

Michael

**Comment by lexoyo** [comment]
Hi @rijschoolthomas 
Yes I did see your reply
I'll look into it very very soon ;)

**Comment by lexoyo** [comment]
> A question: will I have to change any of my code when you upgrade silex to v3.3.1?

It should not need any change

> But now I have the following problems since I made your last changes. I'm not able to hide anything anymore, in either sites, with the code for the CSS editor you gave me and filling in "menu" in the CSS class:

I don't understand what you can not hide?
Change page you mean?

> Another problem I have (not related to the menu problem): I'm not able to fill in the Alt (images only) tekst. It keeps disappearing. Shouldn't the tekst be visible if the image is selected?

Oh that's a bug, good catch thx! 
I'll fix this soon

**Comment by rijschoolthomas** [comment]
Hi Alex, I got the mobiel menu working now: https://rijschoolthomas.github.io/website/

Next question.

I need to be able to put metadata on each page with the specific words I need google to find and a description of the page. Can you tell me how to accomplish this?

**Comment by rijschoolthomas** [comment]
I haven't seen any mention of it but I'm not able to use Silex today. Silex is not able to logging in to Github. And now i'm getting the following message:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by lexoyo** [comment]
Hi
Sorry about that I had to reboot the server

Le 22 oct. 2018 à 13:16, à 13:16, Michael Thomas <notifications@github.com> a écrit:

**Comment by rijschoolthomas** [comment]
Hi Alex, I got the mobiel menu working now: https://rijschoolthomas.github.io/website/

Next question:
I need to be able to put metadata on each page with specific words I need google to find and a description of the page. Can you tell me how to accomplish this in silex. 
Your documentation states: "The websites created on silex.me are search engine friendly, and Silex has all the options you need to optimize it for search engines". 
Can you tell me where I can find this information on Silex and SEO. So I know what to do and what not to do. 

What I've already done is put the following Meta code into the HTML Head Editor ( <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"> )
 because I don't want google to find my website here on GitHub yet until I've finished it. The reason is because it could clash (and could be punished by google for copying tekst) with my Word press site: **RijschoolThomas.com** . Once the site here on GitHub is completed, in a few months time. I want to place it under the here before mentioned domain.

Cheers,
Michael

**Comment by lexoyo** [comment]
> Hi Alex, I got the mobiel menu working now: https://rijschoolthomas.github.io/website/

Yeah, I tried it on mobile and desktop, that's really cool!!

> I need to be able to put metadata on each page with specific words I need google to find and a description of the page. Can you tell me how to accomplish this in silex.
> Your documentation states: "The websites created on silex.me are search engine friendly, and Silex has all the options you need to optimize it for search engines".
Can you tell me where I can find this information on Silex and SEO. So I know what to do and what not to do

The current state of silex is 
* options in the "SEO" section of the website settings, which are at a website level / for the whole website
* the title of each page is the website the name, so this is at a website level too
* images alt and elements title
* the new link editor has a "rel" option:
![screenshot from 2018-10-23 14-31-00](https://user-images.githubusercontent.com/715377/47360660-573da700-d6d0-11e8-912d-2575bf5fff51.png)

Next step is to develop these options at the page level, and I hope to do this before the end of this year (2018). Also I will make silex split the website into many pages to optimize the SEO, see these issues and give your opinion, and if you want to speed this up you can help me with the current developments (new style editor) :)
https://github.com/silexlabs/Silex/milestone/1
.
> What I've already done is put the following Meta code into the HTML Head Editor
> < META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW" >
> because I don't want google to find my website here on GitHub yet until I've finished it. The reason is because it could clash (and could be punished by google for copying tekst) with my Word press site: RijschoolThomas.com . Once the site here on GitHub is completed, in a few months time. I want to place it under the here before mentioned domain.

I see, that is good I think, but it is even better to add a robo.txt file at the root of your website (same folder as index.html)
https://moz.com/learn/seo/robotstxt

**Comment by rijschoolthomas** [comment]
Okay Alex,
I'm not really into code. It to complex for me. But I would like to
troubleschoot new elements in the in development of Silex. And maybe write
a help tekst for the tekst editor.

I have a question: I used to be able (a few days ago) to select tekst or
numbers by sliding the mouse over the tekst with my right mouse button
pressed. But now I can only select tekst by using the keyboard Shift and
arrows. This issue is not just in the tekst editor but also in the
right-hand side menu options and everywhere else were you are able to type.
This "problem" seems to be in both the preprod.silex.me and the
editor.silex.me

Let me know how I can help?

Cheers

*Michael*


Op di 23 okt. 2018 om 14:35 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
Hi Alex, another problem/issue.

If i now ad a section element in both production an normal silex, i am not
able to select the section when it has been put on the page. As a matter of
fact I can't select any div container elements at all.

Did you see my earlier issue?


Op wo 24 okt. 2018 om 00:56 schreef Michael Thomas <mtmail007@gmail.com>:

**Comment by rijschoolthomas** [comment]
It's only on my website. So I'll wil have to put back a back-up again to
get it right again.

Met vriendelijke groet,

*Michael Thomas*


Op wo 24 okt. 2018 om 11:15 schreef Michael Thomas <mtmail007@gmail.com>:

**Comment by lexoyo** [comment]
Hi Michael
So the selection of text problem is only on your website?
This is very strange... I will try to investigate if you tell me which website has that problem (link to html page in github)

**Comment by rijschoolthomas** [comment]
Hi Alex,

I've sorted the problem out already. I put back a backup of the of
editable.html file and that fixed the problem.
I see you have been having quit a few problems yourself over the last
couple of days with your server. And I think that that was the problem that
caused me not to be able to select Element sections any more on my website.
As I was saving my website: https://rijschoolthomas.github.io/website/
your server went offline probably half way through the saving process witch
I think caused a code mess-up.

In respons to your ealier post:
Okay Alex,
I'm not really into code. It's to complex for me. But I would like to
troubleschoot new elements in the in development of Silex. And maybe write
the help tekst for the new tekst editor. Let me know if/how I can help?

I have a issue/question: I used to be able (a few days ago) to select tekst
or numbers by sliding the mouse pointer over the tekst with my right mouse
button pressed. But now I can only select tekst by using the keyboard Shift
and arrows. This issue is not just in the tekst editor but also in the
right-hand side menu options and everywhere else were you are able to type.
This "problem" seems to be in both the preprod.silex.me and the
editor.silex.me




Op vr 26 okt. 2018 11:29 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
> I see you have been having quit a few problems yourself over the last couple of days with your server. 

You are right, I switched Silex Labs server to heroku and it stops working from time to time until I reboot the server... I've setup alerts in order to find out what is happening. I'll let you know how goes, please let me know if something changes

> I'm not really into code. It's to complex for me. But I would like to troubleschoot new elements in the in development of Silex. And maybe write the help tekst for the new tekst editor. Let me know if/how I can help? 

Nice! 
We have many needs I think... You can edit the wiki pages here: https://github.com/silexlabs/Silex/wiki/
If it is important changes we should discuss it before you do it, you can open an issue for such changes. There are several places where it is written "help wanted", feel free to open an issue for us to help you if you need guidance?

Also some tutorials (video or text would be cool :)
In that case I can check it out to be sure everything is "good practice"

> I have a issue/question: I used to be able (a few days ago) to select tekst or numbers by sliding the mouse pointer over the tekst with my right mouse button pressed. But now I can only select tekst by using the keyboard Shift and arrows. This issue is not just in the tekst editor but also in the right-hand side menu options and everywhere else were you are able to type. This "problem" seems to be in both the preprod.silex.me and the editor.silex.me 

If I understood correctly this is what is fixed now

**Comment by rijschoolthomas** [comment]
Alex the 
I have a issue/question: I used to be able (a few days ago) to select tekst or numbers by sliding the mouse pointer over the tekst with my right mouse button pressed. But now I can only select tekst by using the keyboard Shift and arrows. This issue is not just in the tekst editor but also in the right-hand side menu options and everywhere else were you are able to type. This "problem" seems to be in both the preprod.silex.me and the editor.silex.me

Your answer:
If I understood correctly this is what is fixed now        <---- No it's not

-----------------------------------------------------

And I have the problem again that i can't select the div containers (the lines have disappeared). The last time i had to put back a backup file to correct the problem. This time I wil leave it as it is so you can see if you can find the problem.

**Comment by lexoyo** [comment]
hi @rijschoolthomas 

### selection of text in text fields

I can not reproduce this bug, I'll need more details
can you tell me which browser and any more details? maybe open the javascript console of your browser and make a screenshot?
or even better a gif or video to show me the problem, maybe i did not understand

> And I have the problem again that i can't select the div containers (the lines have disappeared). The last time i had to put back a backup file to correct the problem. This time I wil leave it as it is so you can see if you can find the problem. https://rijschoolthomas.github.io/website/

I see nothing strange in this website
sometimes it happens when the server is slow or in bad shape, could you try again (i suppose you have)

**Comment by rijschoolthomas** [comment]
Hi Alex
Extra information on the disappearance of the div containers 
https://github.com/silexlabs/Silex/issues/814#issuecomment-433555522

**Comment by rijschoolthomas** [comment]
Hi Alex, i've made a video for you about the issue in the link here below:
https://github.com/silexlabs/Silex/issues/814#issuecomment-433555522

The video was 129mb so i put a link to it instead of placing the video file here:
https://photos.app.goo.gl/3wXLBT3UDnkpHsg96

I hope it clarifies the issue.
Cheers,
Michael

**Comment by rijschoolthomas** [comment]
Hi Alex,

Next problem....
I would like the page, when i click an **internal** link, to go to the top of the page without making a new tab in browser like a external link does?
Do you know a fix for this? 

Idea for new Silex:
Maby this could be implemented by placing a button so you can choose if you want the link to go to the top of the page or not.

Cheers, Michael

**Comment by lexoyo** [comment]
hi @rijschoolthomas 
the new link editor lets you choose if the link opens in a new tab or not (in beta, only on preprod.silex.me for now) 
soon I will change the publication mechanism and the internal links will scroll to the top of the page by default

**Comment by lexoyo** [comment]
i close this issue
feel free to open another issue for the links
