### ISSUE TITLE
Run from folder

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#815]
Hello
I've installed Silex in my local linux server and it works fine if running from my ip:6805 (192.168.1.90:6805). 
Even if I use an Apache server and create a local host it runs ok: mysite.local.loc:8000 if I set SERVER_URL="http://mysite.local.loc:6805". Even with proxy I can run it from http://mysite.local.loc
Thats fine, I don't have to edit any code, just env vars.
But if I  try to use it in a folder, like  http://mysite.local.loc:6905/builder/ or http://mysite.local.loc/builder/ it doesn't work. The app try to call pages in domain, like http://mysite.local.loc/libs/ or http://mysite.local.loc/website/... and forms are coded to root domain too. (form action="/ce....). 
After some days studing the code I see that the app throws calls to root domain, not to node server. 
The only solution I've found is modify some code in app (Dashboard, cloud-storage, app.js and some html related to forms). 
Am I in a right way or is there any other way to get Silex running in a folder?

**Comment by lexoyo** [comment]
Hello
It's an interesting use case!
You should not need Apache, just Silex
Could you try with the branch "Silex as a dependency" from my fork here? I'm working on similar issues on this branch, it would be great to collaborate on that and address your issues one by one
https://github.com/lexoyo/Silex/tree/silex_as_a_dependency?files=1

**Comment by jotakar** [comment]
I'll study if I can help.
I need Apache if I want to have a web in port 80 and silex under folder. 
Thanks.

**Comment by lexoyo** [comment]
Ok
But if Apache takes the port 80 then Silex will not be able to listen to it anymore
You want to serve static files or PHP?


Le 29 sept. 2018 à 20:27, à 20:27, jotakar <notifications@github.com> a écrit:

**Comment by jotakar** [comment]
I didn't explain my idea well, sorry.
My objetive is to host Silex in a dinamic website (html/php). It runs in port 80 and is served by Apache. 
Say:  http://main.server.com/, containing the html and php of the site.
Now I want to have Sliex builder  as a tool served in a folder of a subdomain, for example
http://main.server.com/editor/   (this must launch silex app)
In Apache, I can proxy  http://main.server.com/editor/  to port 6805 (port listening for node).Here there is not problem.
If I do so when I launch the editor (calling http://main.server.com/editor/ in browser) I get 404 errors when app uses urls like http://main.server.com/assets and other instead of  http://main.server.com/editor/assets. 
It looks like the app uses main domain (http://main.server.com/) as urlRoot instead of http://main.server.com/editor (of course enviroment SERVER_URL is set to http://main.server.com/editor).
I have tried  to set proxy in Apache, and rewrites, but I've not found a solution by this way. 
I'm looking your fork and studing how app and nodes work together to see a solution. 
Ah! I'm a newbie in node.js, so this app is a great oportunity to learn this tecnology. Thanks. :)
Bye.

**Comment by JbIPS** [comment]
Hello @jotakar! That's the first time someone's trying such a thing but the could actually be great for Silex.

How I see it, in Silex code, it should look at the 'root URL', that would be the URL of the home, and prefix all the URL with it.

This way, you'll have /editor/assets and so on. Would this work with you? If so, @lexoyo and I could point you to the URL in the codebase and you could try your hands on Node.js :wink:

**Comment by lexoyo** [comment]
Absolutely :)
We're here to help

**Comment by jotakar** [comment]
Well, I got it. 
I'm tring to understand all the @lexoyo request (https://github.com/lexoyo/Silex/tree/silex_as_a_dependency?files=1) but it's very dificult for me, it's too slow without any documented code. I understand something of the overall idea (or I think so) and yess it looks like is related wiht my idea, although it's deeper.
At this moment I got my objetive to run silex in any domain folder, like **http://site.domain.com/folder/**. But I've needed to modify some source code, of course, like : 
Dashboard (dist/srver/), cloud-storage and silex-tasks.js (cloud-storage.js), apps (js/).
In these files I added the whole base url  (http://site.domain.com/folder) where needed (where appear /get, /libs, /website). Except in silex tasks, I added just the folder.
Some html had url to root domain, I patched them to use relative to the folder.
And I added a global var `appRoot = window.location.href.replace(/\/$/, "");` to get the url where Silex is running. 
And I set a proxy in Apache (the server in port 80)
Now it works like I wanted, at least in my local net. The great test will be in real world.
Perhaps @lexoyo could consider these changes in his merge or could be included in the actual version.
Bye.

**Comment by lexoyo** [comment]
Hi
Yes that's very useful thx
If you do a pull request I will see where it need changes and I can try to make it use an env var instead of your hardcoded folder (is it hardcoded?)

**Comment by jotakar** [comment]
No, it's not hardcoded. It's is read in index.html in a script from window.location.href.
I'll try a pull request.

**Comment by lexoyo** [comment]
>  I can't make a fork for put a pull request :(

why not?

**Comment by lexoyo** [comment]
you need to fork the project, I see you didn't do it yet
https://github.com/jotakar?tab=repositories

**Comment by jotakar** [comment]
Ok, it was a mistake of mine
I made the fork. When I¡ve a bit of time I upload my suggestions.
Anyway I've got install and run the app in a real server managed with Plesk. And now it works fine in a folder without modify any source. It looks like Plesk uses a proper server that discrimine port 80 site and port node apps.  You can see it in [https://creatuweb.espaciolatino.com/editor/](url), although I need to test it. By now it looks like it works fine :)
Well, the only modify is the relative to FTP error (the EIO check).

**Comment by jotakar** [comment]
Ok, it was a mistake form mine. 
I'll upload my suggestion when I've a bit of time

**Comment by lexoyo** [comment]
hi
should i close this issue?

**Comment by jotakar** [comment]
Oh, yes.
