### ISSUE TITLE
New issue on installing

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#820]
Today I've cloned and install a new instance of Silex and I've found that when I visit the local page this error
```
debug.js:9 Uncaught ReferenceError: module is not defined
    at debug.js:9

Warning: KeyboardNav(...): No `render` method found on the returned component instance: you may have forgotten to define `render`.
uncaught TypeError: inst.render is not a function
    at cloud-explorer.js:17561
    at measureLifeCyclePerf (cloud-explorer.js:16841)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (cloud-explorer.js:17560)
    at ReactCompositeComponentWrapper._renderValidatedComponent (cloud-explorer.js:17587)
    at ReactCompositeComponentWrapper.performInitialMount (cloud-explorer.js:17127)
    at ReactCompositeComponentWrapper.mountComponent (cloud-explorer.js:17023)
    at Object.mountComponent (cloud-explorer.js:23358)
    at ReactDOMComponent.mountChildren (cloud-explorer.js:22741)
    at ReactDOMComponent._createInitialChildren (cloud-explorer.js:18484)
    at ReactDOMComponent.mountComponent (cloud-explorer.js:18303)
```
In the installation process I've get
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-ia32-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-ia32-57_binding.node": 

HTTP error 404 Not Found
```
It looks llike a problem with cloud-explorer,  and I suppose with node-sass
I've installed node-sass (npm install node-sass) and then installed the package again, But the results are the same: it doesn't work.
Older installation (from about September 1th) works fine
Perhaps it's a problem with installation process. 
System runs ubuntu 14.04, node 8.10, npm 6.42
Any suggestion?

**Comment by JbIPS** [comment]
The problem is with CloudExplorer and I don't think it has something to do with SASS or the installation.

I suppose something change in the source since your last install, presumably in the KeyboardNav class if I read the error.

Any idea of what this could be @lexoyo?

**Comment by lexoyo** [comment]
I didn't touch this one class recently, maybe the last merge?


Le 6 oct. 2018 à 00:44, à 00:44, Jean-Baptiste Richardet <notifications@github.com> a écrit:

**Comment by jotakar** [comment]
Then there are four issues, at least:  debug.js module, CloudExplorer, KeyboardNav and the 404 error downloading SASS
??

**Comment by JbIPS** [comment]
Actually, I think there is only one :
* the debug one is not an error, more like a debuging warning for the next error
* KeyNav, and thus CloudExplorer, is the real deal. To be sure, we just need to look at the line pointed by the stack trace
* the 404 is not an error. SASS is a bit to verbose-ish. I'm sure if you look couple lines under this error you'll see SASS compiling itself. The 404 just means it didn't find any prebuild binary for your architecture. If there was a real blocking error, NPM would have kill the install with a non-zero exit

**Comment by lexoyo** [comment]
Absolutely @JbIPS
I can't take a look at this now. I would probably start by compiling cloud explorer on its own first

**Comment by jotakar** [comment]
I've found two possibles errors 
KeyboardNav now declare render as static but is not called properly, i fdeclared no sttic this error dissapears
getServices in App.jsx is now declared as static but is not called propery, so throw an error getServices not declared.
I've stopped here. I hope this could be a bit of help.

**Comment by lexoyo** [comment]
good catch thx
i believe it comes from this PR
https://github.com/silexlabs/CloudExplorer2/pull/75

**Comment by lexoyo** [comment]
+1 for more documented code
for the popup / popin thing, it is a good idea for ftp and webdav but for third party services like github or dropbox we should keep a popup, so that the user can see that he is entering his creds on the third party website and not on our website

**Comment by jotakar** [comment]
Then th program must choose among two options, it'll depend on the service used: ftp/github, dropbox...
Anyway there is a post open about this question in CloudExplorer, (posted on Dec'17). O'll try to find a solution.

**Comment by lexoyo** [comment]
I think that you should add a property like "isOauth" in the unifile services, so that the front end knows if it should open a popup or a popin
