### ISSUE TITLE
Feature: templates organized

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#825]
I think it would be a good idea to get a page with templates, organized by categories and so. 
Then a user look for a template, select it and go to the builder. 
This could be built in the actual dashboard that became a multipage dashboard wit filter for templates, a select field.... 
It's just an idea. 
Bye.

**Comment by lexoyo** [comment]
Hi 
+1 good idea
but we have only 10 templates for now so maybe we try to have more before we organize them ? ;)
