### ISSUE TITLE
Issue: install fails

### ISSUE THREAD

**Issue by jotakar** [silexlabs/Silex#827]
How is it possible if silex is installed as root?
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.12.0"
:(
It happend when I try to install the very last version

Ah! and it keeps the sass http not found 
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-ia32-57_binding.node"
and then in try to installa sass and give error because is a version not valid for 32bits o for 64 bits. It's necesary to install by hand. 
(I've jsut seen that the last version is V4.9.4 and V3.13.1 noesn't exist it goes from v2.13.0 to V3.14.0)
And now I see build folder is empty

**Comment by jotakar** [comment]
First solution: dont install as root

**Comment by lexoyo** [comment]
hi
did you manage to do it?
did you try with the version of nodejs specified in .nvm file?

**Comment by jotakar** [comment]
Node version: 8.12.0
I got installed previous version of Silex without these problems. In this versión I had troubles even with post install scripts. 
Why try to download this version if in silex package-lock apears 4.9.4? I can't find the package that ask for node-sass 3.13.1.
Anyway I got this version of silex installed. :)

**Comment by lexoyo** [comment]
maybe you should delete package-lock.json and run npm i again

**Comment by lexoyo** [comment]
Hi is this resolved?
