### ISSUE TITLE
Tiptop organization template

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#83]
Here is [a template perfect for small organizations](https://www.templamatic.com/templates/2745), which I have made with [Silex](http://www.silex.me/), and which is hosted for free on github.

[![tiptop-screenshot](https://www.templamatic.com/images/templates/2700/template-2745-b.jpg)](https://www.templamatic.com/templates/2745)

To make your own website based on this template, [download the archive here](https://www.templamatic.com/templates/2745), unzip and open the file editable.html with [Silex editor](http://editor.silex.me/) (online).

Then edit the texts, change the links and publish your site (file menu, then "publish")

**Comment by wichox01** [comment]
Hello friend,
I have problem with this template, when i change the links names, then it brokes and give me result of page not found.  I am not a programer and i have just a little knowledge on html, please help me.

**Comment by lexoyo** [comment]
Hi @wichox01 
Can you share your folder with the broken site and all your files on dropbox? (a.hoyau [at] im-paris.fr)

**Comment by thoraf** [comment]
Hi, thank you for this template, i want to use it for a friends homepage.
Is it necessary to make any note on it where the template comes from or to make a link to silex or someone else?

**Comment by lexoyo** [comment]
No it is not required :)

**Comment by singchan** [comment]
Did you manage to customize the template?

**Comment by thoraf** [comment]
Yes, it worked very well, for its the first time i used it. There is only one problem i'm working on: If someone uses a. smartphone to visit the site he couldn't reach it. So i have to look for it.  I don't know, how to make it happen.  You can look at the finished site:  www.krieg-bestattungen.de

**Comment by lexoyo** [comment]
cool! that looks nice :high_brightness: 

> There is only one problem i'm working on: If someone uses a. smartphone to visit the site he couldn't reach it. So i have to look for it.

indeed, it displays another site when on mobile
i see that it is based on user agent (bad practice) and it is not made in js (i looked at the source of the website), so maybe in a `.htaccess` file? have a look in the FTP

**Comment by lexoyo** [comment]
This template was on templamatic and it is down permanently
Does someone have this template somewhere?
