### ISSUE TITLE
How to Enable template for users to select from, just like in demo

### ISSUE THREAD

**Issue by uche40** [silexlabs/Silex#833]
How do i enable or get the same template selection feature as in the demo https://editor.silex.me/ on my own install. Just like the demo i want my users to be abler to select a template to start.  I installed silex but did not find that feature by default. Thanks

e.g 
https://1ce.org/1#S1o7IuChm

**Comment by uche40** [comment]
Any Response?

**Comment by lexoyo** [comment]
Hi 
It is supposed to be the case, what do you see?
Do you have errors in the js debug console?

**Comment by lexoyo** [comment]
hi @uche40 
I am closing this issue, feel free to reopen it if you are still here

**Comment by uche40** [comment]
I tried runing it vai a normal install and via the docker image as well. but when silex comes up i do not see the select template screen or section. i must be missing something. here is my docker instance
http://173.193.125.11:32768

do i need to do something, to enable the template selection option?
