### ISSUE TITLE
How to Enable template for users to select from, just like in demo

### ISSUE THREAD

**Issue by uche40** [silexlabs/Silex#838]
How do i enable or get the same template selection feature as in the demo https://editor.silex.me/ on my own install. Just like the demo i want my users to be abler to select a template to start. I installed silex but did not find that feature by default. Thanks

e.g
https://1ce.org/1#S1o7IuChm

I tried it via a normal install and via the docker image as well. but when silex comes up i do not see the select template screen or section. i must be missing something. here is my docker instance
http://173.193.125.11:32768

do i need to do something, to enable the template selection option?

**Comment by uche40** [comment]
And It seems i don't have the dashboard enabled by default, how do i do enable it?

**Comment by uche40** [comment]
I tried it on all the major browser same thing. i guess its the docker master build that's the issue.

So i'm gonna try to do a fresh install on my centos 7 server
i have found the following instructions

https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex
local installation on linux or macos or cloud9
 but i want to know how to install it on a centos using yum and how to tell it to install the develop branch ?

**Comment by lexoyo** [comment]
> i have found the following instructions
> https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex
> local installation on linux or macos or cloud9 but i want to know how to install it on a centos using yum and how to tell it to install the develop branch ?

After the git clone, do this : `git checkout develop`

And then either the npm things or the docker things

**Comment by uche40** [comment]
i tried that but it is not working , the error is too many arguments. i must be doing it wrong.

can you give me a clearer instructions something like 

Clone this repo with git clone https://github.com/silexlabs/Silex.git and then cd Silex

Build the docker image for Silex

$ docker build -t silex-image .
$ docker run -p 6805:6805 -t silex-image

**Comment by lexoyo** [comment]
You need to do the git checkout develop after cd Silex

**Comment by uche40** [comment]
Ok got past that part. i was able to finish the install and when i go to my  url http://ip:6805/
i get a connection refused error

**Comment by lexoyo** [comment]
@jbIPS would you give it a try?

**Comment by uche40** [comment]
Any help or clear instructions would be helpful

**Comment by uche40** [comment]
Or maybe it would just be easier if the "dashboard and template feature were included in the stable master" branch or an updated working docker image provided.

**Comment by lexoyo** [comment]
did you manage to install silex properly?
