### ISSUE TITLE
Mobile Hamburger

### ISSUE THREAD

**Issue by Tomygg** [silexlabs/Silex#839]
Hello,

Thanks for super help that we get on here. One issue though - when I open Silex mobile hamburger of my website on my mobile phone, it only shows few pages, not all pages. Why is that? There is no ability to scroll to see all the pages in the hamburger menu. I didn't play with css so far.

**Comment by lexoyo** [comment]
hi @Tomygg 
sorry for the delay
it looks like you are the first to notice, i just checked and you are right, there is no scroll :(
here is the fix i did: https://github.com/silexlabs/Silex/commit/bd0c5cfa2db0b8bcb2303f39fb0cbe2d3c6ddbdb
now live on https://preprod.silex.me
please backup your site before you open it on preprod (this is the next beta version of silex)
then open your website and save it and it will be fixed
