### ISSUE TITLE
My driving school website made with silex

### ISSUE THREAD

**Issue by rijschoolthomas** [silexlabs/Silex#840]
Here is a link to a website I did with Silex:
[![rijschoolthomas.com](https://user-images.githubusercontent.com/715377/49097957-2243e780-f26e-11e8-9952-76927730c3e7.png)](https://rijschoolthomas.com/)

**Comment by lexoyo** [comment]
Thx @rijschoolthomas 
It is now on the front page of https://www.silex.me/

**Comment by rijschoolthomas** [comment]
Thanks Alex,

It looks great!!!

Met vriendelijke groet,

*Michael Thomas*


Op di 27 nov. 2018 om 18:01 schreef Alex Hoyau <notifications@github.com>:
