### ISSUE TITLE
"Error: I did not manage to open this file. Cannot set property 'type' of null"

### ISSUE THREAD

**Issue by gravinyl** [silexlabs/Silex#841]
Hello,

Before anything else, I want to show full appreciation for the great job being done with the development of this most valuable tool. Stuff of legends!

The subject of this submitted issue is the message I'm getting most of the time (if not every time..) I try to open a published website.

So, I make, I save, I publish... All good.
I upload it to my web host... Working fine.
Next day when I try to open it again in silex to edit and whatever...:
"**Error: I did not manage to open this file. Cannot set property 'type' of null**"

What am I doing wrong?
Thanks

**Comment by lexoyo** [comment]
New name your editable file "index.html"?

The publication process creates a file named index.html so it would overwrite it with file which is not editable anymore

**Comment by gravinyl** [comment]
> New name your editable file "index.html"?
> 
> The publication process creates a file named index.html so it would overwrite it with file which is not editable anymore

Ok, I was messing it up then... Thank you!
