### ISSUE TITLE
Latex and Silex

### ISSUE THREAD

**Issue by chaosmosis** [silexlabs/Silex#842]
Hello,
Bonjour, 

Déjà, merci beaucoup pour votre travail, c'est juste génial.
already thanks for your work, that's amazing !

Je souhaiterais ajouter aux pages crées par silex un article que j'ai écrit avec Latex et mis au format HTML via htlatex. 
I would like to add to my website-made with the silex editor- an html file i have made with htlatex ?

Could you tell me what is the easiest way to do it ?
Kind regards

Slavoy Xyzetc

**Comment by lexoyo** [comment]
hi @chaosmosis 
French or english are both fine
With the title I thought it is spam!!! so funny
Are the generated HTML pages self contained, i.e. with all the css and html inside the page? If they are you can copy paste the HTML into an HTML box
Or you could use an iframe in an HTML box... Do you need help for that?

**Comment by lexoyo** [comment]
I'll close this issue @chaosmosis if you are still there please reopen it
