### ISSUE TITLE
New silex

### ISSUE THREAD

**Issue by rijschoolthomas** [silexlabs/Silex#849]
Hi Alex,
I'm afraid the new silex seems to be messing up, luckely only, my test2 webpage as I'm working on it. 
Test2 is a copy of my rijschoolthomas.com to be able to play with it.
See picture.
1 - I've lost all my pages (they do come back into sight after i add a new page.
2 - Its showing my Home page
3 - But it's telling me I'm on my Proefles page.

![silex](https://user-images.githubusercontent.com/43305374/49510071-790d7a80-f887-11e8-8fc0-07c524eaa76d.png)

I still can't give a Image element a Alt description.

In the new text-editor I can't seem to give each letter another color like in the picture.
Cheers,
Michael

**Comment by lexoyo** [comment]
hi
thx for the bug report
what is your browser please? you are on editor.silex.me right?

**Comment by rijschoolthomas** [comment]
My browser is Google Chrome
Version 71.0.3578.80 (Officiële build) (64-bits)

Yes editor.silex.me




Op wo 5 dec. 2018 om 15:10 schreef Alex Hoyau <notifications@github.com>:

**Comment by rijschoolthomas** [comment]
My website including my test sites are on github. There's a copy of my
rijschoolthomas.com website at: https://rijschoolthomas.github.io/test2/ to
play around with.

I'll have to get back to you on firefox. I'm quite busy at the moment.



Op vr 7 dec. 2018 12:25 schreef Alex Hoyau <notifications@github.com:

**Comment by lexoyo** [comment]
I don't manage to reproduce the bug :-/
![peek 2018-12-07 17-12](https://user-images.githubusercontent.com/715377/49658882-52943e80-fa43-11e8-9a23-6f7317c481c9.gif)

**Comment by rijschoolthomas** [comment]
Hi Alex, 
I'm using silex now in Firefox and that seems to have done the trick for the first issue I had a the top of this page. But it it is still messing up other things. Most of I was able to sort out myself. My slideshow has stopped working on the mobile. I'll probably have to take it out and put it back. I've had that problem before with the old silex.
But the issue I have now is that a link is shown as I want in the preview, but once I publish it, the link has relocated itself and lost its color white). I'll add two pictures: 1 of the preview  and 1 of the published version. The name of the pictures tell you which is which: Preview of publish

![https --rijschoolthomas github io-test2- page-algemene-verklaring](https://user-images.githubusercontent.com/43305374/49699330-117d6500-fbd0-11e8-8f98-e92d9a49b280.png)

![https --editor silex me-ce-github-get-test2-master-editable html page-algemene-verklaring](https://user-images.githubusercontent.com/43305374/49699331-117d6500-fbd0-11e8-8ba5-2445598035fa.png)

This problem came about as I wanted to see if an internal link would open the selected page at the top of the page. I doesn’t. This seems only possible if you make it an external link.

**Comment by lexoyo** [comment]
> This problem came about as I wanted to see if an internal link would open the selected page at the top of the page. I doesn’t. This seems only possible if you make it an external link.

yes for now this is still the case, please use external links then (for now)

concerning the bug of the links, i need to be sure that you use the new text style editor: did you double click on the text field (which is supposed to remove any inline formatting. Then delete any css to syle links in your css editor. And then design the links with the style editor, this should work better

![screenshot from 2018-12-10 16-59-15](https://user-images.githubusercontent.com/715377/49744401-f4629800-fc9c-11e8-82cd-7de324ab291c.png)


> Because in the new silex my mobile logo was moved to high (a quarter hidden / see mobiel rijschoolthomas.com), I put in a new section so the logo was moved down https://rijschoolthomas.github.io/test2/ . And this messed up the site by moving different sections to other places (Home is Okay, the rest is messed up).

Oh yes that too :(
You can add a section, and make it visible only on mobile, then resize it to have the same behavior as before

![screenshot from 2018-12-10 17-04-37](https://user-images.githubusercontent.com/715377/49744722-ba45c600-fc9d-11e8-8c7e-e66a4921e3fa.png)


> I won't be using firefox because all the letters become larger than chrome and therefore the test elements differ in size. This means I would have to go through all my site to change things to fit.

the difference should be fixed too

1- you need to add a font with the new font manager
![screenshot from 2018-12-10 17-01-12](https://user-images.githubusercontent.com/715377/49744512-3986ca00-fc9d-11e8-8521-bddddaf7dd07.png)

2- give all your texts this font
![screenshot from 2018-12-10 17-01-58](https://user-images.githubusercontent.com/715377/49744565-56230200-fc9d-11e8-835d-c4a6318e05d0.png)

3- remove all the css imports of fonts in your css editor if you wrote some

> Alex, I still have got some work to do on my website but are not able to finish it this way. Is there a way I could revert to the last Silex until problems have been solved?

I created this server, maybe it is better for you?
It is the previous previous version, I can easily create a server with the version which just got out, please try and tell me if you need another one

http://old.silex.me/

but at one point you will need to upgrade your website, this is for your own good

**Comment by rijschoolthomas** [comment]
Hi Alex,
I'm now using the new Silex to finish off my rijschoolthomas/website <-- rijschoolthomas.com

Issue
I've got 2 arrows in a circle on my site that I can't find so I can't remove them. See jpg. I think they are a hidden leftover from a earlier slide element. 
![screenshot_20181214-235453](https://user-images.githubusercontent.com/43305374/50035158-dda3a480-0000-11e9-82d0-f053c7d58b00.jpg)

You can only see the arrows on the mobile. I putt the site on a testpage so I could through elements away 1 by 1 trying try to find were the arrow are hidden. But I'm not able to find them

Have you any ideas how to get rid of them?

**Comment by lexoyo** [comment]
ok i see them yes
they are slideshows, and they are hidden on desktop
so you need to enter mobile editor and delete them from there
ok?
