### ISSUE TITLE
SSL not working correctly on Centos 6 with Apache

### ISSUE THREAD

**Issue by Skybred** [silexlabs/Silex#851]
I installed a copy of Silex on my Centos 6 server with Apache and when accessing via http using ProxyPass it works, but when I force SSL I get redirected to the html folder of Apache instead of Silex. I get the following message when I use curl:

curl localhost:6805 -k
Moved Permanently. Redirecting to https://localhost/[root@... Silex]# 

How can I redirect to the correct folder? Changing the SSL port and accessing https://localhost with that port directly doesn't work either.

**Comment by lexoyo** [comment]
hi @Skybred 
1- how did you "force SSL"? 
2- do you use [silex env vars](https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#environment-variables) to serve the certificate?

**Comment by lexoyo** [comment]
Oh and I forgot to mention that Silex creates a webserver with nodejs, so Apache is not needed
