### ISSUE TITLE
Silex website, your opinion wanted

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#853]
Hi!!

I updated silex website
https://www.silex.me/

Any feedback for the design or ideas for the content?

**Comment by David1platt** [comment]
The animation and GIF are nice. Sorry I haven't been around much to help. I'll try to start contributing to documentation more over the next couple of weeks.

**Comment by scemail** [comment]
you should add 
	max-height: 7689px;
to your mobile's body in your CSS, to avoid blank space under your footer in mobile view.
Your "fork me on GitHub" rubber partially hides the under content on mobile in landscape mode.

**Comment by lexoyo** [comment]
thx @scemail and @David1platt 

> you should add
> max-height: 7689px;
> to your mobile's body in your CSS, to avoid blank space under your footer in mobile view.

the problem is the blank space size depends on the viewport width, i am looking for a solution

> Your "fork me on GitHub" rubber partially hides the under content on mobile in landscape mode.

ok thx, i'll probably remove the rubber

**Comment by lexoyo** [comment]
what do you think of these videos?
https://www.youtube.com/playlist?list=PL1YPyEPU8dDN2kjXCCFdDU5VI3NkW8ztq

1- should I publish it on the website?
2- would you have time to contriubte translations? (in the video player you can do settings > subtitles > contribute a translation)
3- what is missing? I talk mostly about style manager and text
4- would someone be able to contribute videos?

Thank you for your help!!

**Comment by David1platt** [comment]
I would combine the two video collections.
I would publish them on the website
There is a specific tool in Silex that allows users to make links between pages in there website. I might go over how to use that tool?
