### ISSUE TITLE
Menu hamburger (Bug )

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#863]
@lexoyo 
Bonjour Alex, il y a un bug avec le menu hamburger sur smartphone, c'est à dire que le menu s'ouvre bien mais impossible de sélectionner une page, la sélection prend toute la fenêtre du smartphone.

Sur preprod...

voici le lien du site

https://justfriends.netlify.com/

**Comment by lexoyo** [comment]
Oula! En effet mais c'est probablement lié à ton site, vu qu'on voit le code dans la page... Je vais regarder bientôt

**Comment by lexoyo** [comment]
alors ca c'est un autre probleme
je vais devoir fixer ca
tu as moyen de revenir a la version avant preprod qui bug?

**Comment by lexoyo** [comment]
le souci est que le menu mobile par defaut de silex n'a pas de href (?!)
donc le nouveau systeme de publication ne change pas les liens en version "plusieurs pages html"

**Comment by BaguetteAgile** [comment]
`tu as moyen de revenir a la version avant preprod qui bug?`

Oui, j'ai garder des anciens `publication.ZIP` au cas où ... j'ai bien fais.
Je viens de mettre en ligne une version sans bug.

**Comment by lexoyo** [comment]
Hi 
I have fixed this issue
It will be on preprod.silex.me in 1h or so
You will have to open your site as it was saved with editor.silex.me

**Comment by lexoyo** [comment]
fixed
https://github.com/silexlabs/Silex/pull/873
