### ISSUE TITLE
Gros bug avec editor.silex.me

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#865]
@lexoyo 

Toutes les pages sont mélangées ... voici une capture d’écran et un lien

sur la capture, il y a 3 pages de mélangées...

![capture du 2019-01-05 01-02-21](https://user-images.githubusercontent.com/35597855/50717149-a36c7680-1085-11e9-8f7f-9bc15edf5225.png)

https://keen-pare-501db2.netlify.com/

**Comment by lexoyo** [comment]
On voit encore du code dans la page c'est étrange
Toujours avec preprod? 
En précieux ça fonctionne normalement ?

**Comment by lexoyo** [comment]
En preview**

**Comment by lexoyo** [comment]
je vois que le site est maintenant sur github?
quelle version que je dois prendre?
https://github.com/BaguetteAgile/just-friends/tree/gh-pages

**Comment by BaguetteAgile** [comment]
`quelle version que je dois prendre?`
Prends la version qui se trouve sur Netlify

https://keen-pare-501db2.netlify.com/

La version sur GitHub est pour faire des essais de mise en ligne direct que tu m'as demandé ;)

**Comment by lexoyo** [comment]
@BaguetteAgile tu as toujours ce probleme?

**Comment by BaguetteAgile** [comment]
@lexoyo  Super sa fonctionne nickel ;)

J'ai du redéfinir dans Silex le Dossier de publication, sinon pas d'enregistrement dans ma Dropbox.

j'ai toujours le morceau de code qui est visible ( mais je sais le supprimer dans l'index.html )

**Comment by lexoyo** [comment]
Si tu sais le supprimer dans index alors tu dois pouvoir faire la même chose dans la version éditable

Le 25 janv. 2019 à 06:21, à 06:21, BaguetteAgile <notifications@github.com> a écrit:
