### ISSUE TITLE
A major release of Silex is live!!

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#877]
Hello

A major release of Silex is live!!

* New publication options including github pages and jekyll
* Sticky elements
* Silex customisation options
* Continued work on the docs: the [main editor UI docs](https://github.com/silexlabs/Silex/wiki/Editor-UI) (thx @David1platt) and the [Publication docs](https://github.com/silexlabs/Silex/wiki/Publishing-and-Releasing-Your-Website)

https://editor.silex.me

Let me know if you like it!!!

**Comment by rijschoolthomas** [comment]
Help new problem!

The desktop looks okay but all the text from the mobiel has gone. https://rijschoolthomas.com

Cheers, Michael

**Comment by lexoyo** [comment]
I'm on it

Le 31 janv. 2019 à 05:19, à 05:19, Michael Thomas <notifications@github.com> a écrit:

**Comment by lexoyo** [comment]
I don't understand what happened, but when I publish it, it works fine
http://lexoyo.me/website/

Could you try again please?

**Comment by lexoyo** [comment]
> In silex mobiel it whats to show the desktop version.

This I can reproduce thank you for the bug report, I'll fix this now
(it has nothing to do with the disappeared texts in mobile version)

**Comment by lexoyo** [comment]
> In silex mobiel it whats to show the desktop version.

Fixed: https://github.com/silexlabs/Silex/pull/878

**Comment by rijschoolthomas** [comment]
> I don't understand what happened, but when I publish it, it works fine
> http://lexoyo.me/website/
> 
> Could you try again please?

I tried again and tekst was back but there are still over problems even in your http://lexoyo.me/website/ 
I'll show you with a few photo's
In the first photograph you see silex mobiel to the left and my published site on the right. The silex mobiel is as it should be. 

Problem 1: The hamburger menu has moved down causing the blue area to be taller. The email addres and telephone number are stacked in stead of next to each other.
![img_20190131_224706](https://user-images.githubusercontent.com/43305374/52088305-ccf8bf00-25ab-11e9-87a9-8b557556d984.jpg)

Problem 2: Elements are not in the right places. The copyright text is now a different color.
![img_20190131_224820](https://user-images.githubusercontent.com/43305374/52088691-dd5d6980-25ac-11e9-9077-2aa771d55169.jpg)


Problem 3: The image on the mobiel is not filling the width of the page.
![img_20190131_225021](https://user-images.githubusercontent.com/43305374/52088924-8310d880-25ad-11e9-838c-786848e28715.jpg)

I see the mobiel page is not too long anymore. And I think that your efforts to clear this problem has cause conflicts in the scripting.

Cheers,
Michael

**Comment by lexoyo** [comment]
I pushed a fix so that the mobile version will always be pixel perfect (scaled depending on window width). This was supposed to be the case but in your case it wasn't. Can you refresh (empty browser cache maybe) and publish again? Let me know if some of these problems are still here?

Also, if you want a better behavior on small desktop screens you should set the "website width" setting to 960 (settings > general settings > website width)

![screenshot from 2019-01-31 17-12-18](https://user-images.githubusercontent.com/715377/52091848-63f95300-257b-11e9-9c34-b55a6f115392.png)

**Comment by lexoyo** [comment]
The fix is now live on editor.silex.me and preprod.silex.me

**Comment by rijschoolthomas** [comment]
Hi Alex,
Itś stil not working as it should. I've made a video for you (with sound) to illustrate the problems. I had to compress the video because the formum doesn't accept mp4 files.
Hope it helps. 
[mobizen_20190201_113041.mp4.tar.gz](https://github.com/silexlabs/Silex/files/2821201/mobizen_20190201_113041.mp4.tar.gz)

**Comment by lexoyo** [comment]
Ok thank you for the video, it is very clear
Let me check some things and get back to you very shortly

**Comment by lexoyo** [comment]
I traced the bug to this: in [editable.html](https://github.com/rijschoolthomas/website/blob/master/editable.html) many text elements have a css class `paged-element-hidden`. This class is supposed to be removed from any element when you save the website ([here in the code](https://github.com/silexlabs/Silex/blob/develop/dist/server/WebsiteRouter.js#L195))

So I did [this hot fix](https://github.com/silexlabs/Silex/commit/b4918a5a645bb29263533303d7c72fa50966868d) and it works much better. still I don't understand how it was working with other websites. It is live on editor.silex.me and preprod too

Thank you for your patience @rijschoolthomas 
Have a good day

**Comment by lexoyo** [comment]
so to be clear:

1- open your website
2- save it
3- publish it

And this will fix the missing texts

I'll take a look at the other issues

**Comment by lexoyo** [comment]
It looks like the other issues are fixed too, can you confirm?

Some buttons change color but it is complicated to investigate because in all these "cards" you have duplicated the style `<style>div.c {text-align: center;}div.b {text-align: right;}div.a {text-align: left;}h2 {color: white;}p {color: white;}`
![screenshot from 2019-02-04 19-04-06](https://user-images.githubusercontent.com/715377/52247484-aee2d580-28af-11e9-9cb5-c9f2753c32ba.png)

And the background color must be somewhere but I don't know where. The thing to do in this case is add a css class to all your "cards" and put the style in the style editor

**Comment by lexoyo** [comment]
It looks like the other issues are fixed too, can you confirm?

Some buttons change color but it is complicated to investigate because in all these "cards" you have duplicated the style `<style>div.c {text-align: center;}div.b {text-align: right;}div.a {text-align: left;}h2 {color: white;}p {color: white;}`
![screenshot from 2019-02-04 19-04-06](https://user-images.githubusercontent.com/715377/52247484-aee2d580-28af-11e9-9cb5-c9f2753c32ba.png)

And the background color must be somewhere but I don't know where. The thing to do in this case is add a css class to all your "cards" and put the style in the style editor

Also the menu with "home" which doesn't work on mobile it is because you should replace this
`<a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>`
with this
`<a class="nav-link" href="#!page-home">HOME<span class="sr-only">(current)</span></a>`

**Comment by rijschoolthomas** [comment]
Hi Alex,

Positives:
I fixed the home menu button as you advised. It works. Thanks
1 more positive thing is that all pages open up at the top of the page now. Fantastic...

Problems still remaining:
The background color you were looking for is in the CSS editor on line 1259 (.container)

The colors you have above (the round blue and rectangular red, all with white letters, is correct. So the colors in silex are correct but on the published mobile and desktop are not (the rectangular red is now light bleu on the published site. 

By the way, the preview button in silex shows up with an application error.

I now again have the large white area underneath the mobiel website (this was gone in the changes you made before the last one

The copyright text (in the footer of the website) is still a dark color (should be white) on all the pages except the 3 "Leerlingen Vertellen" pages. There it is white.

The 2 arrows turned up (  ≪ )  is still stuck at the bottom of the mobile but works as it should on the desktop. 

Cheers,
Michael

**Comment by rijschoolthomas** [comment]
Hi Alex, if the forum is any indication I see that you have been busy lately. But in your last message to me you asked me to confirm if other issues are also fixed. 
The answer is No...
Please check the issues I stil have in my answers to you question in the here above post I posted on the 5 of feb.

Cheers,
Michael

**Comment by lexoyo** [comment]
Hi Michael

Let's take the problems 1 by 1 please, you should create 1 separate issue and when closed you create 1 more ok?

I think some problems come from the fact that a lot of css is duplicated in the HTML boxes, or at least it makes it hard for me to troubleshoot what's happening in your website

**Comment by lexoyo** [comment]
I need you to select the most important thing and create an issue with it

Then I will either fix silex or tell you what to change in the website

Also if you prefer I can put the previous version online somewhere and you go back to the version saved with the older version of silex ?

**Comment by rijschoolthomas** [comment]
> Also if you prefer I can put the previous version online somewhere and you go back to the version saved with the older version of silex ?
>
That is very kind of you, but i think it's probably a better idea to follow the silex development. Because if I use an older version now to fix the problems, I'll probably have a problem in the future when I want to change anything on the site.

>  I need you to select the most important thing and create an issue with it 

> 
Okay, will do. Probably the next issue I will create in the next few days is the one concerning the blue balls.

Thanks Alex

**Comment by lexoyo** [comment]
@rijschoolthomas how are things going? Are the main issues fixed or did I drop the ball?

**Comment by rijschoolthomas** [comment]
I'm okay thanks. Business is going wel.

Main issue "blue balls" is as was a few monthes ago. Works on desktop not
on mobile.

I've been referring my mobile users to go to the desktop version of my site
to read the pupils reviews (blue balls).

I'm hesitant of updating my site in fear of more mobile problems arising. I
just haven't the time to keep problem solving. As you can imagine, I'm
looking around for other options.

Cheers,

Michael



Op za 27 apr. 2019 02:25 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
> Main issue "blue balls" is as was a few monthes ago. Works on desktop not on mobile.
> I've been referring my mobile users to go to the desktop version of my site to read the pupils reviews (blue balls). 

oh no that is bad :(
sorry to hear that

i identified the problem no ? was it a lot of duplicated html code in each "blue ball" ?
