### ISSUE TITLE
Error when publishing to FTP

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#883]
Hi,

I tried to publish to my FTP with the new version of Silex (on editor.silex.me). I logged in, created a new folder and when I hit "Publish", after the "Downloading" phase, it errored with:
```
An error occured.

I did not manage to publish the website. 553 Can't open that file: No such file or directory
```

I can create new folder and new file on the FTP but something must be missing. I check my user has all the permissions it need (apparently). 

FYI, I manually uploaded the output files and now I can publish so it must be something related to create new file/folder.

**Comment by MACscr** [comment]
I am having the same issue. Was able to save the project, but cant publish anything. CE allows me to create folders, so I know it has write access, but when trying to publish, it asks me to pick a folder, which i do, then get the a "Cannot get /undefined" error. Chrome console looks like so:

![image](https://user-images.githubusercontent.com/1404944/53789317-bf579180-3ee9-11e9-9e7b-8874a9b8b8b9.png)

**Comment by lexoyo** [comment]
I'll look into that after #908

**Comment by santomet** [comment]
This still happens on v3

**Comment by lexoyo** [comment]
Yes
Actually there are several things going wrong with ftp
@oliviermgx is working on it
Please upvote this issue if you use ftp (with a 👍)

**Comment by oliviermgx** [comment]
> This still happens on v3

@santomet 
I've made a new prototype with ftp working. Would you like to test ? it would be great for me if you agree :)
If yes, tell me, I will give you the link
thanks
Olivier

**Comment by santomet** [comment]
Definitely yes, since I've seen some of your patched merged to dev I'm still trying v3.silex.me :)

**Comment by oliviermgx** [comment]
> Definitely yes, since I've seen some of your patches merged to dev I'm still trying v3.silex.me :)

 @santomet  https://kpaste.infomaniak.com/noVMpeaToKSu7DEHaZ5yXwbZoaMqzSAP#8FdmRkumWqAcaFBzS5PdYn6XV943rnTKDkmqZ74vAww9

and tell me !

**Comment by santomet** [comment]
Perfect, it works for me :) Thanks
