### ISSUE TITLE
I did not manage to publish the website. Error when trying to attach a domain to "xxx". Error details: Not Found

### ISSUE THREAD

**Issue by justinechacko** [silexlabs/Silex#893]
When I try to publish site, I select github in silex.me and selected a folder and added a domain. Then I get "I did not manage to publish the website. Error when trying to attach a domain to "xxx". Error details: Not Found"

**Comment by lexoyo** [comment]
Hello
What is the repository?
You can create a CNAME file instead in GitHub

**Comment by justinechacko** [comment]
I didn't configured the folder early. Now working.
