### ISSUE TITLE
How to add more template to the project

### ISSUE THREAD

**Issue by justinechacko** [silexlabs/Silex#895]
I hosting an instance of silex. How to add more template to it?

**Comment by lexoyo** [comment]
Hello

Nice to hear that you are doing that! 

For now there is no clean way to do that (it should be a list in the config). So for now you need to copy your templates to `node_modules/silex-templates`. 

To host your instance, do you add silex as an npm dependency or do you use silexlabs/Silex directly?

**Comment by justinechacko** [comment]
Hi, thanks for responding. I used, heroku docker button to deploy.

**Comment by lexoyo** [comment]
Ok, this is the most basic/easy solution so you have only access to the options exposed through the environment variables, see this doc
https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#environment-variables

The more advanced solution to host silex is to create your own project and ad silex as an npm dependency like explained here (briefly, feel free to ask clarifications or edit the docs to make it better)
https://github.com/silexlabs/Silex/wiki/Silex-for-hosting-providers#silex-customization

An example of such a project is here
https://github.com/lexoyo/silex-for-hosting-company

As you can see there is a "components/" folder. All the files in there are copied to Silex module (node_modules/silex/src/components/) and compiled with the components provided with silex by default. This happens after silex is build and it triggers a rebuild of the components. See how this is done here, in the "script": { "build" section
https://github.com/lexoyo/silex-for-hosting-company/blob/master/package.json

It's not an ideal solution but it is easy. You can do the same for the templates: copy all your templates to the "node_modules/silex-templates" at build. No need to recompile anything I think. Note that I did not test it so feel free to tell me if you are stuck.

You could even add it to my demo repository here and make a pull request, that would be a great contribution

Have a nice day!

**Comment by lexoyo** [comment]
Hi
Did I answer your question?

**Comment by justinechacko** [comment]
Hi, Sorry for the delay, So I need to ssh to server and copy templates to node_modules/silex-templates?

**Comment by lexoyo** [comment]
this is one option but I prefere to do it like this:
* import silex in my project as an npm dependency
* create a folder with my new templates
* in the post build script of my project, add a command to copy all my templates to silex template directory

I have made [an example of this here](https://github.com/lexoyo/silex-for-hosting-company). Feel free to ask any question

**Comment by lexoyo** [comment]
this is a little gif to show how it look like
![customize-silex-add-template](https://user-images.githubusercontent.com/715377/53307090-caac1c80-385a-11e9-8d93-118a473d79a1.gif)

**Comment by justinechacko** [comment]
Ok, close it.
