### ISSUE TITLE
Blue info buttons are not working

### ISSUE THREAD

**Issue by rijschoolthomas** [silexlabs/Silex#896]
The blue info buttons work on the desktop but not on mobile:

This was your answer:
- Some buttons change color but it is complicated to investigate because in all these "cards" you have duplicated the style `<style>div.c {text-align: center;}div.b {text-align: right;}div.a {text-align: left;}h2 {color: white;}p {color: white;}`
![blue button](https://user-images.githubusercontent.com/43305374/52913807-c06da980-32c1-11e9-8e5b-fe62d4d1f925.png)

- And the background color must be somewhere but I don't know where.
The background color you were looking for is in the CSS editor on line 1259 (.container)
The colors you have above (the round blue and rectangular red, all with white letters, is correct. So the colors in silex are correct but on the published mobile and desktop are not (the rectangular red is now light bleu on the published site.
On the mobile the text doesn't show when you press the "LEES MEER" button except for the top (first) one. The desktop does show all blue button texts as it should.

- The thing to do in this case is add a css class to all your "cards" and put the style in the style editor
If so how do i do that?

**Comment by lexoyo** [comment]
Hi
I'll look at that today

**Comment by lexoyo** [comment]
on `opfriscursus.html` the colors are wrong
![screenshot from 2019-02-22 16-16-34](https://user-images.githubusercontent.com/715377/53274987-f72b3180-36be-11e9-9848-89854a886b67.png)

on `angsten.html` the colors are good
![screenshot from 2019-02-22 16-16-32](https://user-images.githubusercontent.com/715377/53274994-fbefe580-36be-11e9-9d9e-32e74cc67bc1.png)

this is because the class `.btn` is defined with the correct style in the button "Contactformulier"
![screenshot from 2019-02-22 16-30-24](https://user-images.githubusercontent.com/715377/53275056-38bbdc80-36bf-11e9-8782-f9e867274d79.png)

So only when the button is on a page, the style is correct. 

To fix this, I would remove all the css in each card. And add it only 1 time in the CSS editor. 

In this case, remove this style from the button "Contactformulier":
```
<style>.btn {background-color: #bf1a1a; border-radius: 20px 20px 20px 20px; ;color: white; padding: 12px 16px; font-size: 16px; cursor: pointer;}.btn:hover {background-color: Blue;}</style>
```
And add this to the css editor (I just removed the style tags): 
```
.btn {background-color: #bf1a1a; border-radius: 20px 20px 20px 20px; ;color: white; padding: 12px 16px; font-size: 16px; cursor: pointer;}.btn:hover {background-color: Blue;}
```

For each card, remove the css styles and add it to the css editor if it is not defined already

**Comment by lexoyo** [comment]
Here are other things i noticed and you should fix:

1- I just re-published the site (preprod chrome) and it fixed the page leerstijlen
![screenshot from 2019-02-22 16-09-51](https://user-images.githubusercontent.com/715377/53274280-5a679480-36bc-11e9-8c3d-9e9c5efab1ca.png)
![screenshot from 2019-02-22 16-07-56](https://user-images.githubusercontent.com/715377/53274282-5a679480-36bc-11e9-9c4c-bcb2f7289868.png)

2- this image is over the text on opfriscursus.html so just remove it and put it back in the text editor maybe, now that it is possible
![screenshot from 2019-02-22 16-11-51](https://user-images.githubusercontent.com/715377/53274397-bcc09500-36bc-11e9-9f4d-43b24f59931d.png)

**Comment by lexoyo** [comment]
When it is done and if it works you can close this issue and open a new one for the remaining issue?

**Comment by rijschoolthomas** [comment]
Alex, I'm afraid one problem is leading to another. 
I first tried your advice to  re-published the site with preprod chrome.  It did not fix the <iframe> problem. The problem just jumpes between contactformulier.html and leerstijlen.html every time I renew the <frame> code and publish it. At the moment both are not showing at all.

As advised I also removed the style from all the buttons "Contactformulier" and place it in the css editor. It ended up miss forming the Contactformulier buttons and also leaving the "LEES MEER" buttons light blue. 
![rijschool thomas - regio amersfoort - angsten](https://user-images.githubusercontent.com/43305374/53301299-5751dd00-3851-11e9-866d-27c10663fc12.png)

I then deleted all the Contactformulier buttons and replaced them with tekst links. Now of course the "Lees Meer" buttons on the blue info buttons are all light blue. 
As I made a new tekstlink my slideshow has again stopt working and also caused this, see picture
![screenshot_20190224-162115](https://user-images.githubusercontent.com/43305374/53301235-78fe9480-3850-11e9-94fb-d13a4640f135.jpg)
The ( . ) dot before the top slideshow means it's not working anymore.
 The false image, underneath it,  has appeared on the published mobile but not on the silex mobile so I am not able to find it to delete it. And I don't know how it appeared.

It seems to be one problem after another. At least with the mobile version.
I think it might be a good idea for me to go back to a stable version of Silex so i can put back a backup of the site. Because I don't want to be trouble shooting most of the time when I'm working on the website. I need it to be stable.

Michael

**Comment by lexoyo** [comment]
is this fixed?

**Comment by rijschoolthomas** [comment]
No...

It works on desktop but not on mobile.

Op za 27 apr. 2019 02:26 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
I don't find a bug in the mobile version... can you tell me which page?

**Comment by rijschoolthomas** [comment]
Blue balls work in the published desktop but not in the published mobile
version: https://rijschoolthomas.com/leerlingen-vertellen-1.html which  i
find very strange. So why do the blue balls, and the go to the top of the
page arrows on the right side, only work on the desktop ?
Click the LEES MEER on the desktop published version to see wat the blue
ball does.

Another problem in Silex: Desktop is visible / mobile is not visible. If
just found this out. But I haven't changed anything for a long time (weeks).
[image: Silex.png]
Mobile is empty
[image: Silex (1).png]


Met vriendelijke groet,

*Michael Thomas*


Op ma 29 apr. 2019 om 18:47 schreef Alex Hoyau <notifications@github.com>:

**Comment by lexoyo** [comment]
> Blue balls work in the published desktop but not in the published mobile version: https://rijschoolthomas.com/leerlingen-vertellen-1.html which i find very strange. So why do the blue balls, and the go to the top of the page arrows on the right side, only work on the desktop ? Click the LEES MEER on the desktop published version to see wat the blue ball does.

what i see is that the "popin" shows up but if the page is scrolled then the popin stays high in the page. one easy solution would be to scroll to top when the user clicks the button. let me know if you want the code for that, i'll have to check again your site to see how you did the code to open the popin 

> Another problem in Silex: Desktop is visible / mobile is not visible. If just found this out. But I haven't changed anything for a long time (weeks). [image: Silex.png] Mobile is empty [image: Silex (1).png] 

The images does not show up in your message, i don't see what you mean

**Comment by rijschoolthomas** [comment]
Another problem in Silex: Desktop is visible / mobile is not visible. If
just found this out. But I haven't changed anything for a long time (weeks).
[image: Silex.png]

Mobile is empty
[image: Silex (1).png]

![Silex](https://user-images.githubusercontent.com/43305374/56924530-69f4c680-6acd-11e9-85b8-a35168ba5445.png)


![Silex (1)](https://user-images.githubusercontent.com/43305374/56924545-724d0180-6acd-11e9-8b67-ce237e4d32b2.png)

**Comment by rijschoolthomas** [comment]
what i see is that the "popin" shows up but if the page is scrolled then the popin stays high in the page. one easy solution would be to scroll to top when the user clicks the button. let me know if you want the code for that, i'll have to check again your site to see how you did the code to open the popin.

This is not the solution. Opening the blueball popin has worked on both the desktop and the mobile published site when i first introduced them. Now it only works on the desktop.
