### ISSUE TITLE
Problème avec DIV.html

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#897]
Bonjour @lexoyo 

Il y a un souci avec les "DIV.html" c'est à dire qu'en Preview c'est ok, mais lors de la publication les "DIV" restent vides, les liens "html" semblent ne pas être chargés.

Exemple ici:

https://friendly-benz-3eaa5f.netlify.com/itineraire.html

je rencontre ce problème aussi bien sur editor.silex.me que sur preprod.silex.me

**Comment by lexoyo** [comment]
Désolé pour le délai, je regarde ça aujourd'hui

**Comment by lexoyo** [comment]
ok de ce que je comprends c'est le composant map qui a un bug

ajoute `&layers=S` à la fin de l'url de la map et ca devrait marcher
ou bien remplace ton composant map actuel sur preprod.silex.me ou j'ai fait ce fix:
https://github.com/silexlabs/Silex/commit/82ea2d97ede8aa733aa64f4527c428b8568c38d6

**Comment by BaguetteAgile** [comment]
Il faudrait peut être ré ouvrir le sujet.

Pour la map, c'est ok, j'ai remplacer le composant sur preprod.silex.me

Je rencontre le même souci avec un fichier .pdf ( héberger dans mon Drive de Google) sur cette page, sous "Itineraire concert"

https://distracted-jennings-6c2f9c.netlify.com/agenda.html

et avec une vidéo youtube  sur la page d'accueil du site ( Bizarrement la video n'est plus visible )

https://distracted-jennings-6c2f9c.netlify.com/index.html

![videoyoutubecachee](https://user-images.githubusercontent.com/35597855/53276131-26ad5e80-36fe-11e9-85d1-2e8e2a58c4d3.png)

**Comment by BaguetteAgile** [comment]
Pour la vidéo sur la page d'accueil c'est un problème de `z-index`

**Comment by lexoyo** [comment]
ok je vais regarder pour le pdf

**Comment by lexoyo** [comment]
J'ai enfin trouvé, il fallait sauver en ayant une autre page ouverte et ensuite publier
Le fix est sur preprod.silex.me
https://github.com/silexlabs/Silex/commit/153878d04588ce550a182f2be6d4877fe5b1fcc9

**Comment by lexoyo** [comment]
pour fix ton site, refresh preprod.silex.me, ouvre ton site, sauve le puis publie
