### ISSUE TITLE
My Silex website

### ISSUE THREAD

**Issue by Codeer12** [silexlabs/Silex#899]
Here is a link to a website I did with Silex:
https://games.ytbros.tk

**Comment by lexoyo** [comment]
Hi @Codeer12 
The nav bar seems to have problems in firefox

**Comment by Codeer12** [comment]
it is only html,  but will modifiy

**Comment by lexoyo** [comment]
You can do the same with text boxes and links (see properties link, then select a page)

**Comment by Codeer12** [comment]
Ok, but will it look like the buttons if I use text?

**Comment by lexoyo** [comment]
You can design it like buttons yes
For example you can put a text in a container and add a border and background color to the container
You can add rounded corner to the container too

**Comment by Codeer12** [comment]
Oh ok, well I will work on that.

**Comment by Codeer12** [comment]
I didn't do it because most of my users are on chrome.

**Comment by lexoyo** [comment]
Ok as you wish
If one day you want to do it or for your next website, it is really easy to do

**Comment by lexoyo** [comment]
1- add a text box
2- edit the text 
3- add a link on it: properties > link > choose the page in the list
4- add a border: properties > border > width > set it to 1px
5- add a background color: properties > background color > select a color

**Comment by lexoyo** [comment]
I close this issue as most of our users are on firefox (libre)
