### ISSUE TITLE
iframe doesn´t work when website is published

### ISSUE THREAD

**Issue by Codeer12** [silexlabs/Silex#900]

**Comment by lexoyo** [comment]
Can you share the website? Do you use Dropbox or github?

**Comment by Codeer12** [comment]
I use github

**Comment by Codeer12** [comment]
https://github.com/Codeer12/ytbrosweb/

**Comment by lexoyo** [comment]
Ok I found the bug, the fix is live on https://preprod.silex.me
https://github.com/silexlabs/Silex/commit/153878d04588ce550a182f2be6d4877fe5b1fcc9

Thx for the bug report

**Comment by lexoyo** [comment]
pour fix ton site, refresh preprod.silex.me, ouvre ton site, sauve le puis publie

**Comment by lexoyo** [comment]
> pour fix ton site, refresh preprod.silex.me, ouvre ton site, sauve le puis publie

sorry, in english: 

to fix your site, open in on preprod.silex.me, save it and publish again

**Comment by Codeer12** [comment]
For some reason, it still doesn’t work?

**Comment by Codeer12** [comment]
Nevermind, I found out it's a bug in my CDN.

**Comment by Codeer12** [comment]
Not the iframe bug

**Comment by lexoyo** [comment]
So the iframe works?

**Comment by Codeer12** [comment]
Yes.

**Comment by Codeer12** [comment]
I replied on Gmail, sorry for the extra crap.

**Comment by lexoyo** [comment]
:+1:
