### ISSUE TITLE
How to create a template for silex

### ISSUE THREAD

**Issue by bpmottathai** [silexlabs/Silex#903]
Can I Just add an html template from locally, or do I need a special files like editable.html? How to create an editable.html file?

**Comment by lexoyo** [comment]
You need to create the template in Silex. It has specific HTML markup for Silex to manage pages, drag/drop zones etc

Also I made a doc to describe what is a good template: https://github.com/silexlabs/Silex/wiki/Create-templates-for-Silex

**Comment by bpmottathai** [comment]
Thanks for responding.

**Comment by lexoyo** [comment]
Hi @bpmottathai did you manage to do a template? 
I close this issue, feel free to open an other once
