### ISSUE TITLE
dynamically set destination?

### ISSUE THREAD

**Issue by MACscr** [silexlabs/Silex#904]
Hmm, right now Im using a custom editor that i have made that stores/pulls the editable content from a mysql table, but then when published, creates the html from that. I need a more robust editor though and am looking to see if silex can be used instead. 

If I use a single sftp user/pass for multiple servers, would there be a way to dynamically set what server I need to connect to for storing the published html and even the page names its going to create? How would I then later come back to those created pages and edit them?

**Comment by lexoyo** [comment]
Hello

There is a concept of storage services in Silex. For example the GitHub service, ftp service etc.

If you implement a MySQL service you can store everything including images in a MySQL database. 

is this what you need to do?

**Comment by MACscr** [comment]
Oh, I was just stating how my existing system worked. I would be creating a new way to do it with Silex. What i wanted to be able to do is pass url variables to Silex to automatically set the storage destination and page file names, etc, so wondering if there are js functions in Silex that i can reference with js to set such things dynamically.

**Comment by lexoyo** [comment]
Oh ok
It is easy for storage services and hosting providers.

For example you could have a service which presents folders which are actually other things than folders

But I think that you would like to have a Silex without even a file browser?

If you just want to open a website passed in the URL you could use the "debug" script which is loaded before Silex starts

Look at this:
https://github.com/silexlabs/Silex/blob/develop/dist/client/js/debug.sample.js

It's a bit of a hack but we could clean it up and make it a real thing, with an exposed API for example
