### ISSUE TITLE
Custom Elements

### ISSUE THREAD

**Issue by MACscr** [silexlabs/Silex#905]
I need the ability to create custom elements. Lets say I want to have an html button with a predefined attributes, etc. I need to have quite a few different things like this such as another button for creating a input field, drop down list, etc. Right now you have something that creates a whole form, but Im wanting to be able to create the individual elements and with predefined attributes, so hoping I can I can create these option in the editor using js.

**Comment by MACscr** [comment]
Ah, looks like https://github.com/lexoyo/silex-for-hosting-company might be what I am looking for. Thanks!

**Comment by lexoyo** [comment]
Yes exactly
Feel free to create documentation and ask me for help

⁣WhatsApp : +33676683806
Skype : alex.hoyau​

**Comment by MACscr** [comment]
Should I be opening issues here in regards to that custom repo? It doesn’t seem to have its own issues.

- Mark

**Comment by lexoyo** [comment]
Yes please do that here

⁣WhatsApp : +33676683806
Skype : alex.hoyau​
