### ISSUE TITLE
Disparition du menu Hamburger

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#908]
Bonjour @lexoyo 

je viens de m’apercevoir que le menu " hamburger " n'est plus visible avec mon site, mais également avec les " templates " de Silex.
Donc le problème ne viendrai pas de mon site.
Certainement suite au fix de l'issue #897  153878d

**Comment by lexoyo** [comment]
aouch elle fait mal celle ci :(
je pense  que c'est depuis que les sites se resize pour etre pixel perfect
pour desactiver ce comportement tu peux enlever la largeur du site dans les params (le 1200 dans l'image ci dessous)
![Screenshot from 2019-03-08 18-02-45](https://user-images.githubusercontent.com/715377/54062564-68dda200-41cc-11e9-8280-6e67352779f8.png)

**Comment by lexoyo** [comment]
J'ai trouvé pourquoi et je vais retirer le hamburger des sites et ajouter un composant hamburger

**Comment by BaguetteAgile** [comment]
`je pense que c'est depuis que les sites se resize pour etre pixel perfect
pour desactiver ce comportement tu peux enlever la largeur du site dans les params (le 1200 dans l'image ci dessous)`
Cette solution ne fonctionne pas :(

**Comment by lexoyo** [comment]
Ah oui bien sûr j'avais oublié que la version mobile se resize dans ts les cas désolé

Je bosse dessus

**Comment by lexoyo** [comment]
tu peux voir ou je vais ici
https://silex-test-tmp.herokuapp.com

tous les retours sont les bienvenus

* ajouter le composant menu sur un sitte
* le mettre visible sur mobile uniquement par exemple
* paramétrer le composant : je me demande si c'est clair ses params

**Comment by BaguetteAgile** [comment]
1. En mode " Desktop " les 3 barres horizontales du menu disparaissent quand on clic sur paramètre "Fixed" 

2. Prévoir la possibilité de changer la couleur des 3 barres horizontales ( noir c'est bien mais suivant la couleur de fond du site, elles deviennent parfois plus visible ) 

3. J'ai l"impression que le paramètre "Fixed" ne fonctionne pas, le menu  " scrool" avec la page

4. Impossible de faire une "Preview" pas accès à Dropbox.

5. Les paramètres me semblent compréhensibles.

**Comment by BaguetteAgile** [comment]
Bon, voici la suite de mes essais...


**Navigateur Chromium**
 les points suivant ne fonctionne pas:

`En mode " Desktop " les 3 barres horizontales du menu disparaissent quand on clic sur paramètre "Fixed"`

`Impossible de faire une "Preview" pas accès à Dropbox.`

**A vérifier quand la connexion Dropbox sera ok.**

`J'ai l"impression que le paramètre "Fixed" ne fonctionne pas, le menu " scrool" avec la page`

**Navigateur Firefox**

`Connexion Dropbox ok`

`Le paramètre "Fixed" a l'air de fonctionner, j'ai un doute`

l'ouverture et fermeture du menu Hamburger OK les liens du menu fonctionne

**Comment by lexoyo** [comment]
Merci baguette pour tous ces tests
Tu as mis le doigt sur de vrais trucs je suis en train de tout refaire
Merci

**Comment by BaguetteAgile** [comment]
Suite des tests:

**Navigateur Firefox**

`Paramètre FIXED`

 Les 3 barres horizontales du menu reste bien FIXED, par contre si on utilise un  `Background` " et  ou " un `BORDER` de couleur ces derniers `SCROOL` avec la page.

Bon courage @lexoyo

**Comment by lexoyo** [comment]
merci baguette
j'ai tellement galéré, j'ai recodé la logique du "position: fixed"
peux tu tester de nouveau le composant menu?
https://silex-test-tmp.herokuapp.com

> Les 3 barres horizontales du menu reste bien FIXED, par contre si on utilise un Background
et ou un BORDER de couleur ces derniers SCROOL avec la page.

en effet, ca c'est chelou mais ca va rester je pense... laisse moi réfléchir a ce que je peux faire

**Comment by lexoyo** [comment]
this is now fixed
