### ISSUE TITLE
New hamburger menu

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#912]
As baguette found out in #908 the mobile menu bug in the latest version of silex and this is because of the new scaling mechanism used to have pixel perfect websites

I created a new component, the hamburger menu which is compatible with the scaling mechanism. [You can test it here](https://silex-test-tmp.herokuapp.com/). It is a work in progress, please make comments. Use the "+" menu to add it to a website, double click on it to edit params.

![hamburger menu component in silex](https://user-images.githubusercontent.com/715377/54463091-86b08700-4737-11e9-8c0a-44fe95a61e6c.png)

Also this component is different from the mobile menu:

* it has a parameter which needs to be used to list all the links you want in the menu, this is not automatically all the pages as before, please let me know if you understand this parameter
* it a parameter to make it "fixed" (stays in place when the user scrolls) or not (sroll with the page as a normal element)
* it has the same properties as any element so you can make it visible on mobile or desktop or both, and you can also decide to have one for mobile and an other one for desktop
* it can be styled with the text style editor

Here is what I am about to do now before releasing this as a new silex version, please tell me if it is a good idea

* when a site is opened, remove the old mobile menu 
* in all the templates, remove the old mobile menu and warn the user that he should add a hamburger component
* update the docs and maybe make a video
* in a next version maybe add different looks for the button like this: https://jonsuh.com/hamburgers/

This component will become the most important component in Silex I guess, please help me make it user friendly

PS: thank you @BaguetteAgile

**Comment by lexoyo** [comment]
![hamburger menu component](https://user-images.githubusercontent.com/715377/54467874-9b981500-474d-11e9-8cdb-e6d2ab5c6f62.gif)

**Comment by lexoyo** [comment]
I have updated all templates, tests needed on https://silex-test-tmp.herokuapp.com/

**Comment by lexoyo** [comment]
next steps: cleanup and release on editor.silex.me
you will need to update your wensites with the new hamburger menu because your old mobile menu will disappear

**Comment by lexoyo** [comment]
cleanup done, it is now on preprod, soon to be merged on the prod

**Comment by lexoyo** [comment]
hello 
@BaguetteAgile did you have a chance to test?

**Comment by BaguetteAgile** [comment]
Hi Alex,
 no time to test the new MENU, I test as soon as possible...
 you've already done a great job,

 count on me!

**Comment by lexoyo** [comment]
Great!
It's good that you don't have time as it probably means that your business is good ? Did you sell any Silex website?

**Comment by BaguetteAgile** [comment]
Hi Alex, here are the results of my tests:
Position "`fixed`" OK
"`button-background-color`" OK
"`button-border-color`" OK
"`background-color`" OK
"`links`" OK

On the other hand, there is a "`z-index`" problem: the menu is hidden behind some elements and is no longer accessible for editing, and it is no longer editable or repositionable, for example.

I also noticed that the menu is only visible on the home page even if "**Visible on**" "**Both**" is selected ( or the menu is hidden "z-index")

Otherwise nice work and I really prefer to be able to edit the "hamburger" menu

**Comment by lexoyo** [comment]
Thank you baguette this is really useful !!!

> On the other hand, there is a "z-index" problem: the menu is hidden behind some elements and is no longer accessible for editing, and it is no longer editable or repositionable, for example.
> I also noticed that the menu is only visible on the home page even if "Visible on" "Both" is selected ( or the menu is hidden "z-index")

in the editor, the menu button is like any other element. it is probably behind the sections of your website, this is a little bug in Silex. you can get it back in the mobile menu editor : drag it to a container, then back to the desktop editor you can move it again, and it will be in front of everything again


> Otherwise nice work and I really prefer to be able to edit the "hamburger" menu

good !!!
did you see you can change its style in the text style editor ?

**Comment by BaguetteAgile** [comment]
> you can get it back in the mobile menu editor : drag it to a container, then back to the desktop editor you can move it again, and it will be in front of everything again

this handling doesn't work with my test. I shared my test on Dropbox with you ( hamburger test.html)

> did you see you can change its style in the text style editor ?

couldn't get it to work... maybe a demo?

**Comment by lexoyo** [comment]
This feature is live, could you tell me if it works for you?
There is a documentation for the hamburger menu, did you see it @BaguetteAgile  ?
