### ISSUE TITLE
Way to export webpage to own PC

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#914]
Hi, is there a way, by hosting Silex on a server, or by downloading the desktop version, to select somewhere in the machine to publish at (e.g. at the machine the server is at)? 

The thing is I'm running Silex on my ubuntu server but now i don't really know much to do. What I wanted was to publish the project directly to the ubuntu server. Saw some env variable stuff but don't get it, at all really.

I could use SFTP, WebDAV or FTP but I am trying to make it the easiest (to publish) and because I use SCP (and as far as i'm aware it is not compatible).

As of now, what I do is to publish to dropbox, it gets downloaded to my local pc, and then through WinSCP manually upload it to the ubuntu machine (pretty slow process).

Hope anyone can help :)

**Comment by lexoyo** [comment]
Hello

If you define the env var ENABLE_FS=true you will see the file system of your server when you publish 

Is it what you want? If it is, do you need help setting the env var?

**Comment by JbIPS** [comment]
One tricky workaround could be to setup a FTP server on your machine and connect Silex to it :blush:

**Comment by FranGamer1892** [comment]
This is my default config, where env vars are set, right? I never modified it.
[DefaultConfig.zip](https://github.com/silexlabs/Silex/files/2982644/DefaultConfig.zip)
But it seems the option is already set to true, isn't it? Specifically on this line, under cloud explorer options
http://prntscr.com/mzw902
When I go to Silex, there is no way to enter the file system.
Maybe try to send me a ready .js or tell me a step-by-step way to do it?

**Comment by FranGamer1892** [comment]
What I see when I publish: 
http://prntscr.com/mzwd7c
http://prntscr.com/mzwdi8

**Comment by lexoyo** [comment]
Ok I understand now

You are not supposed to modify the DefaultConfig file. 

How do you start Silex on your server? You must do something like "mpm start" somewhere right? If you do then you just have to do this instead: "ENABLE_FS=true mpm start". 


PS: @JbIPS trick is interesting :)

**Comment by lexoyo** [comment]
Or you can use an FTP server on your server

**Comment by lexoyo** [comment]
I really like the face system service but it doesn't ask for any password so anyone will be able to write on your server

It is meant to be a service that runs on your local computer more than on a server I think

**Comment by FranGamer1892** [comment]
Thanks. Now I understand how to use env vars, as I start the server with
npm start.

Also, not everyone can access my Silex, you got to connect through SSH to
the Ubuntu server with a tunnel configured (127.0.0.1:6805). At least I
think that is how it works... I am new at this tunneling thing...actually
yesterday discovered this was a thing with PuTTY.

**Comment by FranGamer1892** [comment]
PS: Will try this afternoon if it works. And by the way, i tried to use
docker but it forced me to install OpenJDK-7-JRE, which is obsolete and
which I couldn't install manually (from oracle, etc). Don't know if it is
Silex's problem or Docker's (maybe my docker is outdated)

**Comment by lexoyo** [comment]
> PS: Will try this afternoon if it works. And by the way, i tried to use docker but it forced me to install OpenJDK-7-JRE, which is obsolete and which I couldn't install manually (from oracle, etc). Don't know if it is Silex's problem or Docker's (maybe my docker is outdated)

Oh yes I know, I am [working on this here](#906)

**Comment by FranGamer1892** [comment]
Working as of now! Closing
