### ISSUE TITLE
help me test the next version of silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#917]
The next version of Silex is available on https://preprod.silex.me
I will soon release it to editor.silex.me
It has a new "hamburger menu" component which you can use in the desktop and mobile versions

**Comment by lexoyo** [comment]
as asked by @ BaguetteAgile in #912, here is [a documentation for this component](https://github.com/silexlabs/Silex/wiki/Hamburger-menu#use-of-this-component)

**Comment by Codeer12** [comment]
This update won't save my changes. Every time I hit save or publish, it doesn't change my editable file or show new changes on my website.

**Comment by lexoyo** [comment]
Oh really?
Thank you for the test I will look into it
Which browser did you use?

**Comment by Codeer12** [comment]
Chrome

**Comment by lexoyo** [comment]
hi 
thx again for the test
i can not reproduce, everything works fine for me
can you give me more info please? what service do you save to, dropbox/github/... ?

**Comment by Codeer12** [comment]
I save to github. So  I tried saving a version of my website. I saved the editable on the editor and it didn't save the file at all. This is only a problem with https://preprod.silex.me. It always works on the other one.

**Comment by lexoyo** [comment]
Hi all 
I'll need more tests as I can not reproduce, I'll merge this and wait for users feedback :-/
I have a new very ambicious release comming, this one will need a lot of tests and has several very exciting features !!!
Thank you for your help, please keep rolling
