### ISSUE TITLE
entire website project disapeared...

### ISSUE THREAD

**Issue by gravinyl** [silexlabs/Silex#919]
Hello,

When I import the project from dropbox, basically the only thing that show up is the background image.
The rest is gone.
One thing to mention is that, the content actually shows up unformatted for a split second when loading the project, but in the end when it loads, the green notification box that briefly show up on the lower right corner says 'untitled website loaded'.
Which means that the editable.html didn't actually load...
Thanks in advance for your help.

**Comment by lexoyo** [comment]
Hello
Could you share the site with me please?
On Dropbox I am a.hoyau at im-paris.fr

**Comment by lexoyo** [comment]
hi
i don't know what happened, but the whole data which silex puts in the `<head>` tag was at the bottom of the `<body>` tag... 
i moved it back to head and it works now. please take a look at the file `test.html` in your dropbox folder and tell me if i am right?
i'll investigate further soon and try to find a way to detect this at least

**Comment by gravinyl** [comment]
Hello,

 

Yes, you're right is ok now.

Thanks for your help.

 

Anyway, I'm looking to contribute with a small donation for the great work you guys doing.

How should I proceed to make it?

 

Keep up with the good work!

Thanks again.

 

Kind regards

 

Flávio Trindade
 

 

 

Sent: Tuesday, April 23, 2019 at 12:54 AM

**Comment by lexoyo** [comment]
Thanks this is an appreciated encouragement!

We all support Silex Labs non profit org (only volunteer work). They do social work in Paris to bring diversity to the IT world, i.e. help people find jobs as UX, product owner, webmaster, programmer.... 

You can donate here, this is much appreciated thx!!

https://www.silexlabs.org/silexlabs/#about-silex-labs
