### ISSUE TITLE
Responsive mode not working in mobile

### ISSUE THREAD

**Issue by bpmottathai** [silexlabs/Silex#920]
In mobile I get editor like below image.

http://i64.tinypic.com/142yjib.png

But when resize desktop browser it goes responsive

**Comment by lexoyo** [comment]
That's interesting

You mean that you opened the editor on mobile?

**Comment by bpmottathai** [comment]
Yes

**Comment by lexoyo** [comment]
Ok I never thought about it. You would like to edit a website that way?

**Comment by bpmottathai** [comment]
If it is difficult to accomplish, leave it.

**Comment by lexoyo** [comment]
Yes it seems hard :)
Touch friendly would be great but hard too
