### ISSUE TITLE
New version is live

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#921]
As annouced in the issues #917 and #912 the new version is live :boom: and it includes a new [hamburger menu component](https://github.com/silexlabs/Silex/wiki/Hamburger-menu#use-of-this-component) which you need to include in your websites so that it keeps working as expected (the old mobile menu was buggy)

Let me know how it goes for you

![hamburger menu component in silex](https://user-images.githubusercontent.com/715377/54467874-9b981500-474d-11e9-8cdb-e6d2ab5c6f62.gif)

**Comment by BaguetteAgile** [comment]
Great for the documentation! I'm testing this weekend;)
