### ISSUE TITLE
Demande de fonctionnalitée "Pop-up"

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#933]
@lexoyo 

Bonjour à tous,

Est'il possible de créer un code pour Silex, afin de créer une fenêtre Pop-up cliquable sur une page afin de mettre en avant par exemple, un événement, une affiche de concert, promotion exceptionnelle... 
dans ce style. Merci d'avance.

![pop-up](https://user-images.githubusercontent.com/35597855/57392387-ecae0d80-71c0-11e9-85a2-94c58aa8b081.jpg)

**Comment by lexoyo** [comment]
Hello
Oui c'est très possible
J'ai pensé à une façon de le faire comme une page "overlay" dans silex, j'espère avoir le temps bientôt
En attendant tu peux utiliser des outils tiers, Cherche "lightbox jQuery" par exemple... Je vais essayer de chercher aussi

**Comment by lexoyo** [comment]
Hello 
Tu as réussi?
Je ferme cette issue en attendant puisque c'est un double de #885
