### ISSUE TITLE
CSS Editor

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#934]
Bonjour @lexoyo 

il y a un comportement étrange dans l'onglet `CSS Editor` de Silex.

Pour mon site, je doit avoir environ 180 lignes et seulement 126 lignes visibles...
mais si je fait un copier de la page et que je colle dans un éditeur de texte, tout le code CSS me semble juste.

PS: as tu reçus le `Pull Request` de ma `Template` ?

**Comment by lexoyo** [comment]
Hello Baguette

Désolé pour le temps de réaction, je suis a fond sur silex, mais plus sur la partie développeurs, pour attirer de nouveaux contributeurs et des boites qui pourraient avoir besoin de nous ensuite...
Tu as constaté ca sur preprod ou sur editor?

PS: oui j'ai bien vu, je te fais un retour sur la PR

**Comment by BaguetteAgile** [comment]
Bug constaté sur Preprod.
Sur Editor c'est OK ;)

**Comment by lexoyo** [comment]
Hello
Merci encore pour le bug report
C'est corrigé
