### ISSUE TITLE
Add a page problem

### ISSUE THREAD

**Issue by anleopa** [silexlabs/Silex#936]
I am using the Silex website builder online and when I add a new page it clones the existing one so each change I make on one page persist in the other. How can I design a new page with a different style?

**Comment by lexoyo** [comment]
Hello

To answer your question, I added info in the docs here: [Silex UI, "pages and links" section](https://github.com/silexlabs/Silex/wiki/Editor-UI#pages)

The idea is to use the `Visible on` property of elements to control which is on every page and which is only on 1 or some pages.

Does this answer your question?

**Comment by anleopa** [comment]
Yes! Thank you very much
