### ISSUE TITLE
Feature request: more text styles

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#938]
In the text styles we should add:

* [ ] padding
* [ ] margin

What else? 
cc @ceubri

**Comment by ceubri** [comment]
to create button : 
- [ ] border ?
- [ ] gradient bg color (linear) ?

**Comment by lexoyo** [comment]
Ok interesting
We are talking about text only or other elements too?
Maybe the text style editor should be used to style other elements too

**Comment by ceubri** [comment]
yes or just have the possibility to copy paste an appearance.

**Comment by lexoyo** [comment]
Thx @ceubri for the tests
I see that you need also
* [ ] transition for color and background color (a checkbox beside these in the text styles)

We could have these style applied to other elements too, not only texts

**Comment by lexoyo** [comment]
I have added all this, hoping that this is not too much for the user

Here is what you can do now just with the style editor:

![transitions](https://user-images.githubusercontent.com/715377/58523742-391ab680-818b-11e9-9324-4eea5825614b.gif)

And this is what it adds to the style editor

![Screenshot from 2019-05-28 20-58-11](https://user-images.githubusercontent.com/715377/58523800-62d3dd80-818b-11e9-8f32-48e8237b6f67.png)

**Comment by ceubri** [comment]
GREAT !!! (and i have noticed that the margin are very important in "mobile mode")
