### ISSUE TITLE
No images after publishing.

### ISSUE THREAD

**Issue by Cyberhuman6565** [silexlabs/Silex#939]
So, I don't think there is yet any clear answer to this. There are many images not showing up on my published website, but some of them do show up. I'm told by the program that "the following images could not be downloaded", but why so? Am I giving an address wrong or something? Note that I'm a total zero in all this coding - just started learning HTML recently.

**Comment by lexoyo** [comment]
Hello
I suppose that you are using https://editor.silex.me
Which cloud service do you use? Ftp/Dropbox/...

**Comment by Cyberhuman6565** [comment]
Yes, I'm using this tool. And my service is Dropbox.

**Comment by lexoyo** [comment]
Ok
Do you have the published version online?
I need more data to help you

**Comment by lexoyo** [comment]
Hi @Cyberhuman6565 
I can help you if you give me access to the site

**Comment by papasquat55** [comment]
was this ever resolved? I am having the same issue.

**Comment by lexoyo** [comment]
I don't think so
Is your site published online ?

**Comment by papasquat55** [comment]
yes

**Comment by lexoyo** [comment]
I'll need to access the files of the site too

**Comment by papasquat55** [comment]
https://www.dropbox.com/scl/fo/rgnppel8a5bcepni5il95/h?rlkey=d5pnk6uuqd2erufthsc8t5wg4&dl=0
