### ISSUE TITLE
CSS - Parallaxe

### ISSUE THREAD

**Issue by Stuff31** [silexlabs/Silex#94]
Bonjour,

Je suis entrain de faire un "Template-Parallaxe-Silex" mais j'ai deux questions : 
- les 3 lignes de codes suivantes sont dans une html-box et je ne sais pas mettre ces codes en js (se serai mieux que sur une html-box)

``` html
<script type="text/javascript" src="./js/jquery.parallax-1.1.3.js" />
<script type="text/javascript" src="./js/jquery.localscroll-1.2.7-min.js" />
<script type="text/javascript" src="./js/jquery.scrollTo-1.4.2-min.js" />
```
- et celui là qui permet de charger le script en l'insérant à la fin du document HTML, avant  `</body>`
  ce n'est pas obligatoire de le mettre mais c'est conseillé.

``` html
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js" />
```

tuto utilisé : http://www.alsacreations.com/tuto/lire/1417-zoom-sur-effet-parallaxe.html

**Comment by singchan** [comment]
ca semble réparé

**Comment by lexoyo** [comment]
this is obsolete, there is a widget for parallax in silex now
