### ISSUE TITLE
 Application error

### ISSUE THREAD

**Issue by taxcojimgithub** [silexlabs/Silex#946]
Depuis quelque temps j'ai souvent le message d'erreur suivant,
je pense que vous avez un idée, merci d'avance 

Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by lexoyo** [comment]
Bonjour
Merci de l'avoir signalé, je vais enquêter

**Comment by taxcojimgithub** [comment]
merci beaucoup

**Comment by EMREOYUN** [comment]
Same Issue Here

**Comment by lexoyo** [comment]
Ok, I'm on it
The issue is
* There is an error on the server side
* More and more people use silex

I'll fix the first one very soon

**Comment by EMREOYUN** [comment]
Glad we hear it. :)

**Comment by lexoyo** [comment]
What I notice first is that some people have probably put their unpublished silex website on relatively high traffic websites, and this means that a lot of requests are made to static file silex use in non published / non optimized version

Also the cdn I use on editor.silex.me seems to not do his job well when it comes to cache.. Probably my bad, I am investigating that. I changed some caching rules, let me know if you have strange new bugs please

**Comment by EMREOYUN** [comment]
Heroku doesn't let save or upload on FTP. I get error in Heroku app and it says needed to check logs.

**Comment by lexoyo** [comment]
Hi 
This is the error heroku gives when the app has crashed and is rebooting
Could you try again now?

**Comment by lexoyo** [comment]
I did try and it works right now, it is the same problem of regular crashes
I'm on it
![Screenshot from 2019-06-29 15-15-19](https://user-images.githubusercontent.com/715377/60389068-cf8b1200-9a80-11e9-9109-f62e78221199.png)

**Comment by EMREOYUN** [comment]
I'm gonna try when i free.

**Comment by EMREOYUN** [comment]
@lexoyo No errors get on testing.

**Comment by lexoyo** [comment]
i think this will be solved when we release the beta version (preprod.silex.me) to editor.silex.me
