### ISSUE TITLE
link problem / problème de lien

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#947]
Bonjour à vous, comment allez vous ? est-ce que l'asso va bien ?
J'espère que oui.
J'écris car j'ai refait mon site avec silex, tout est ok sauf... sauf que sur les pages secondaires quand je clique sur l’accueil, ça me renvoie à la page d'accueil mais comme "écrasée" (les différentes sections ne se voient plus) :(
Est-ce que l'un d'entre vous pourrais me donner une piste de là où je peux "vérifier" les liens ? J'imagine qu'il y a un problème dans le code du lien... je rappelle que je suis archi nulle en informatique.......... Tout les autres liens fonctionnent très bien.
En vous remerciant beaucoup par avance.
Léa

**Comment by lexoyo** [comment]
Hello Lea! 
Tú las mis en ligne qq part que je puisse voir?

**Comment by lexoyo** [comment]
Ou si c'est sur github ça marche aussi
Sur Dropbox tu peux le partager avec a.hoyau à im-paris.fe

**Comment by lexoyo** [comment]
:hand: 
sinon mets un sceenshot?

**Comment by Lea75** [comment]
Salut Alex,Merci de ta rapidité.Le beug expliqué ne beug plus : j'ai mis le site en ligne pour t'envoyer le lien et je remarque que ça beug uniquement sur le "visuel" a partir de silex.
Pour la découverte ou la reprise de cours réguliers - Aux Couleurs du Yoga - YOGA PARIS 13  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Pour la découverte ou la reprise de cours réguliers - Aux Couleurs du Yoga - YOGA PARIS 13
 
Bienvenue à Aux Couleurs du Yoga - YOGA PARIS 13 - Des cours en petits groupes
  |   |

  |

  |

  

Par contre du coup, un autre beug : en ligne, sur le smartphone (en version téléphone droit...), le menu s'affiche en arrière de la page et les titres des pages ne sont pas actualisés. Peux tu m'aider a corriger cela ?



Si c'est trop compliqué, je referai le site encore, a partir d'un template neuf 👌

Et une dernière question aussi : est ce que je peux mieux comprendre comment mettre de la couleur sur certaines phrases ? Avec la V2 de silex, quand je sélectionne une phrase pour la mettre en couleur a partir du menu a droite (le pinceau), ça met tout le reste du texte en couleur et pas la sélection...
Un grand merci !Léa 
PS : n'hésitez pas à me dire, si vous voulez on viens vous donner quelques cours a l'asso / ou dans vos ateliers de formation 🤸

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., juin 29, 2019 à 20:55, Alex Hoyau<notifications@github.com> a écrit :   
✋
sinon mets un sceenshot?

**Comment by lexoyo** [comment]
> PS : n'hésitez pas à me dire, si vous voulez on viens vous donner quelques cours a l'asso / ou dans vos ateliers de formation 🤸

merci merci :D
pour les massages (c'est bien ca le yoga?) je pense que @JbIPS @clemos et @tariqbenezza en parlaient justement ;D

> Par contre du coup, un autre beug : en ligne, sur le smartphone (en version téléphone droit...), le menu s'affiche en arrière de la page et les titres des pages ne sont pas actualisés. Peux tu m'aider a corriger cela ? 
Je regarde et je te dis rapidement
En général c'est mieux si tu fais une issue a part pour que je ne m'embrouille pas

> Et une dernière question aussi : est ce que je peux mieux comprendre comment mettre de la couleur sur certaines phrases ? Avec la V2 de silex, quand je sélectionne une phrase pour la mettre en couleur a partir du menu a droite (le pinceau), ça met tout le reste du texte en couleur et pas la sélection... 

Ok alors ca c'est l'utilisation du nouveau gestionnaire de style

Peut être que @ceubri l'expliquerait mieux, mais en gros tu dois select une text box (ou un autre élément) et faire "+" pour lui ajouter un style a lui (sinon c'est le style de tous les éléments du meme type que la sélection que tu modifies

![Screenshot from 2019-07-01 19-58-18](https://user-images.githubusercontent.com/715377/60474992-ab733080-9c3a-11e9-9a71-5cede9f27e21.png)

Pareil, n'hésite pas a faire une issue a part, on devrait en faire de la doc

**Comment by lexoyo** [comment]
Hello
En fait j'ai beau chercher je ne vois pas "le site en ligne" dont tu parles... pour ton bug de menu la

**Comment by Lea75** [comment]
Voici le site pour le bug sur le menu : https://atrois.netlify.com/
Je vais séparer les issues, dès que je récupère un peu de temps.
Un grand merci.
Le yoga c'est pas des massages 🙂 ce sont des séances guidées ou chacun fait et répète des mouvements au rythme de chaque respiration. Gardons l'idée, pour vos membres ou pour vos stagiaires de formation.

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., juil. 5, 2019 à 1:54, Alex Hoyau<notifications@github.com> a écrit :   
Hello
En fait j'ai beau chercher je ne vois pas "le site en ligne" dont tu parles... pour ton bug de menu la

**Comment by lexoyo** [comment]
ca c'est fixé si j'ai bien compris
