### ISSUE TITLE
error message not clear for github

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#949]
A good feedback from @stephantwarog
When you try to put a file in github, at the first level, the error message is not clear
It should you be:
`You can not add a file here, please create a folder and put your file in it`
What do you think? any other ideas?

**Comment by lexoyo** [comment]
Voici ce que j'ai mis, ok pour vous? ok pour @stephantwarog ?

```
You are trying to add a file to a folder of Github which does not support files.
You can not add a file here because Github allows only folders at this level.
Please create a folder and put your file in it. Github requires a folder to have at least 2 parents in order to accept files.
```

**Comment by stephantwarog** [comment]
nickel :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 22 juil. 2019 à 14:45, Alex Hoyau <notifications@github.com> a
écrit :
