### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#951]
Bonjour,
je ne trouve vraiment pas comment le menu, en version smartphone (écran vertical), peut être déroulé (quand on clique dessus) DEVANT le contenu de la page et non derrière ;(
Je vous met un screenshot pour mieux expliquer mon problème... J'utilise la template Food & Drink et en ligne, sur mobile, le bug est là même quand je ne modifie rien de la template de base - et ça me fait ça avec les autres templates aussi.
J'ai essayé de lire les autres issues sur les hamburger menu... et regarder les nouvelles vidéos mais je ne comprends toujours pas :(
Un grand merci,
Léa
![image](https://user-images.githubusercontent.com/34609544/61553877-ce377e80-aa5b-11e9-8106-ab4560cd58da.png)

**Comment by lexoyo** [comment]
Hello
Je le vois, c'est un bug
@ceubri a trouvé un fix temporaire je crois, je corrige ca cette semaine c'est sur

**Comment by Lea75** [comment]
Super. Merci de ta disponibilité.Voici le site en ligne (avec beug qui, au delà du pb esthetique, empêche d'acceder aux autres pages puisqu'il y a le titre en premier plan^^) : https://couleurs2019.netlify.com/index.html
J'ai aussi depuis regardé plus patiemment les nouvelles vidéos et j'ai mieux compris comment gérer les polices et couleurs.
Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., juil. 22, 2019 à 14:32, Alex Hoyau<notifications@github.com> a écrit :   
Hello
Je le vois, c'est un bug
@ceubri a trouvé un fix temporaire je crois, je corrige ca cette semaine c'est sur

**Comment by lexoyo** [comment]
fixé et live sur preprod.silex.me
peux tu update le composant hamburger menu (juste change une propriété) et me dire si ca fix bien ?

**Comment by Lea75** [comment]
Je m'y remets ce soir, mais je ne suis pas bien sûre de comprendre en quoi consiste ce que je dois faire...!
Uptader le composant ?
Je te tiens au courant, un grand merci

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., juil. 23, 2019 à 0:47, Alex Hoyau<notifications@github.com> a écrit :   
fixé et live sur preprod.silex.me
peux tu update le composant hamburger menu (juste change une propriété) et me dire si ca fix bien ?

**Comment by ceubri** [comment]
Yes fixé mais j'ai dû ajouter un nouveau hamburger menu pour que cela fonctionne

**Comment by lexoyo** [comment]
Ah ok bah @Lea75 c'est probablement ce que tu dois faire aussi, supprimer et remettre le composant

**Comment by Lea75** [comment]
C'est magnifique ! ça fonctionne parfaitement : le menu passe devant les autres choses.Je vais pouvoir peaufiner le site et le mettre en ligne officiellement.
Un grand merci.
Je reviens vers vous pour la proposition des cours découverte du yoga à la rentrée.Boonne soirée :)

    Le mardi 23 juillet 2019 à 13:24:27 UTC+2, Alex Hoyau <notifications@github.com> a écrit :  
 
 
Ah ok bah @Lea75 c'est probablement ce que tu dois faire aussi, supprimer et remettre le composant

**Comment by lexoyo** [comment]
Si tu as besoin d'ajouter du paiement en ligne ouvre une issue et je te guide ;)
