### ISSUE TITLE
Lighthouse score optimization

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#952]
I just checked my [Silex website](https://cameo.fr) with Lighthouse.

First, congratulations, scores are great (98 - 81 - 86 - 91)! Some issues are easily fixed (`alt` for images) but other should be taken care by Silex:
:small_red_triangle:  *<html> element does not have a [lang] attribute*: I didn't see anywhere the possibility to set that
:small_red_triangle: *Links to cross-origin destinations are unsafe*: too bad the one link causing the issue is the link to silex.me
:small_red_triangle: *Includes front-end JavaScript libraries with known security vulnerabilities*: the version of jQuery is one major late. This one will be painful but could have a huge impact
:warning:  *Serve images in next-gen formats*: Could be nice to convert picture when deploying

What do you think? Are some already under development? Which one should we do first?

**Comment by lexoyo** [comment]
hey @JbIPS thx :)
the google speed scores are great indeed, as fast as gatsby which claim to generate the fastest websites on earth :)

> element does not have a [lang] attribute: I didn't see anywhere the possibility to set that

There is a "lang" field in the website's settings

> Links to cross-origin destinations are unsafe: too bad the one link causing the issue is the link to silex.me

oh ok, you mean it is 

> Includes front-end JavaScript libraries with known security vulnerabilities: the version of jQuery is one major late. This one will be painful but could have a huge impact

Nice one! I found this doc:

> Add rel="noopener" or rel="noreferrer" to each of the links that Lighthouse has identified in your report. In general, when you use target="_blank", always add rel="noopener" or rel="noreferrer".

You can set the links to have `rel="noreferrer"` in the link editor (advanced params)

![Screenshot from 2019-07-30 11-33-48](https://user-images.githubusercontent.com/715377/62138371-ea3dea00-b2bd-11e9-8ee7-acce84e0a0dd.png)

Do you think we should use `rel="noreferrer"` on all external links?

> Serve images in next-gen formats: Could be nice to convert picture when deploying

Yes that would be great :)
There are probably a ton of libs on npm which can do that, and it is easy to add this feature in publication process, would you like to collaborate to add this?

**Comment by JbIPS** [comment]
Thank you for the tips! I'll fix what's fixable and sure I'll look at the image format this month 😉
