### ISSUE TITLE
Background image gone soon after publishing website

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#953]
Background image dissapears, and I got to compile/save & publish the website again, re-assigning the background image. Page's https://notindie.servegame.org and it's hosted there.

**Comment by lexoyo** [comment]
Hi @FranGamer1892 
Do you use editor.silex.me?

**Comment by FranGamer1892** [comment]
Now I've figured out it is probably my internet client, if I encounter anything weird I'll tell.
