### ISSUE TITLE
Questions à propos de Silex

### ISSUE THREAD

**Issue by FannySophie** [silexlabs/Silex#954]
Bonjour à l'équipe de Silex,

J'aimerais éclaircir quelques points à propos de Silex, j'ai décroché mon premier client et j'ai choisi Silex comme outil de développement (et j'espère m'en sortir bien et donner une contibution à l'outil Silex quand je serai payée !). 
Mon client soucrit à une offre Gandi simple hosting small+SSL et il aimerait (une fois le site fini) l'entretenir et le publier facilement. Or pour l'instant je n'arrive à publier mon site que par le biais le fillezilla (je télécharge les fichiers de mon site silex par dropbox ensuite je les transfère sur filezilla qui les transfère à gandi par sftp). Mais c'est fastidieux comme prodécude pour mon client, y aurait-il un moyen d'appuyer directement sur le bouton "publish" de silex et d'envoyer le site par sftp direcement vers l'hébergement gandi (j'ai essayé mais la connexion sftp ne marche pas pour l'instant). J'aimerais vraiment de l'aide pour ce point ça serait super.

Autre chose : mon client veut un espace membre (avec une petite base de donnée à gerer), l'utilisation de Silex pour créer mon site n'êmpechera pas cela ?

Encore autre chose : mon client s'inquiète de la durée de vie de Silex (il aurait eu plus confiance en wordpress) je l'ai rassuré en lui disant que dans le pire des cas on pouvait forker et heberger une instance Silex pour continuer à entretenir le site. Mais il me demande aussi si un site silex serait facilement porté vers wordpress en cas de problème. Que puis-je lui répondre ? 

En tout cas bravo pour cette outil vraiment génial, (j'éditerai des templates pour contribuer) mais si je peux faire quoi que ce soit pour aider n'hésitez pas à me demander.

Désolé pour ce texte... long ! Merci et à bientôt
Très bonne soirée,
Fanny.

**Comment by JbIPS** [comment]
Merci Fanny pour ta confiance, n'hésite pas nous tenir au courant de ton avancé 😃.

Pour répondre à tes questions (et celle de ton client) :
* la publication SFTP est (en théorie) possible car le backend utilisé par Silex (Unifile) le supporte. Après je sais que le SFTP d'OVH est un peu capricieux, je ferai quelques tests en août.
* Pour l'espace membre, il faut garder en tête que Silex gère mieux le statique, mais j'ai déjà fait des espaces privés avec une fonction JS qui déterminait si l'utilisateur avait le droit ou pas de la voir. Si tu n'as pas de mécanismes trop complexes, ça devrait passer.
* Pour la durée de vie, je ne suis pas très objectif mais avec @lexoyo à fond sur le projet, Silex a déjà quelques années et est parti pour au moins autant ! Après, le code que tu publies est du pur HTML/CSS/JS que tu peux utiliser de n'importe où. Tu seras donc moins bloqué que dans WP 😉. D'ailleurs, je ne sais pas si tu peux importer du HTML dedans... Par contre, la nouvelle version de Silex s'oriente sur Jekyll, un super format de site statique notamment supporter par GitHub. Donc au pire tu pourras migrer vers un éditeur Jekyll si un jour tu en as marre de Silex. Et oui, en cas de problème, créé ton instance et fais la évoluer. On est d'ailleurs preneurs de tes idées !

J'ai hâte de voir tes templates, c'est vraiment un gros coup de pouce pour nous car cela donne de la visibilité au projet tout en aidant les nouveaux. Et bien sûr, pose tes questions/idées/remarques ici et tu seras une Silexienne de premier ordre !

Bienvenue et à très bientôt :champagne:

**Comment by FannySophie** [comment]
Merci beaucoup de ta réponse rapide et très efficace ! 
J'ai rassuré mon client qui est partant pour Silex, maintenant il va falloir que je trouve des solutions pour créer cet espace membre c'est ce qui m'inquitète le plus.

**Problème PHP** 
Je ne peux donc pas intégrer du PHP à Silex car il génère uniquement des pages html est-ce bien cela? (je pensais intégrer du php dans des "html box")
Et même si j'intégrais du php et renommais mes fichiers html en .php pour les publier sur gandi, si mon client veux faire une mise à jour directe, les pages générées par silex seraient renommées en .html si j'ai bien compris? 
Dans ce cas comme tu le suggère, j'essayerai d'utiliser JS uniquement et sans php (bien que cela soit très obscur pour moi pour l'instant). Je vais me renseigner (et si je trouve la solution je pourrai donc éditer une template "dynamique" par la suite bien que ça m'ait l'air assez compliqué à intégrer dans une template).

**Erreur SFPT Gandi :** 
Toujours ce problème je peux pas me connecter à mon hébergeur gandi par sftp voici le message d'erreur : "This operation failed with the following error message:
This path does not exist (Bad Request)" 
Une idée de ce qui cloche et de ce qu'on pourrait essayer ?
![error_sfpt](https://user-images.githubusercontent.com/51905865/62126122-507f3880-b2cf-11e9-9707-2f2baea76357.png)

C'est vraiment un plaisir, Silex est un super projet et j'espère pouvoir contibuer (même un tout petit peu)  ! 
Merci beaucoup de votre accueil,
A bientôt et bonne journée, Fanny.

**Comment by JbIPS** [comment]
Pour ton problème de PHP, je ferais 2 choses différentes :
1. Un serveur PHP qui gère la communication avec la base et le mécanisme d'authentification. Ça ton client n'y touchera jamais
2. Une fonction JS dans Silex qui fait appel à ton serveur pour savoir si l'utilisateur peut aller sur la page. Regarde la fonction `fetch`, ça te donnera une idée. 

Et pour le SFTP, je vais regarder ce qui se passe dès que j'ai un peu de temps 😉

**Comment by lexoyo** [comment]
Hello

Vu que tu es chez OVH et qu'ils supportent le .htaccess, je me dis que tu pourrais utiliser ca aussi pour restreindre l'acces... Sans javascript du coup

Ce sont des fichiers php que tu poses sur ton ftp et qui définissent des utilisateurs et des pages qui sont visibles ou non. Tu peux facilement les créer à la main ou il doit exister des interfaces, [comme ce script](https://github.com/SimonSimCity/Htaccess-User-Manager) qui te permettent (ou ton client) de gérer ca de facon plus graphique, sans ftp

Questions:
1- qui crée les users ?
2- qui gère les droits sur les fichiers ? 
3- les gens peuvent se créer un compte eux meme?

**Comment by FannySophie** [comment]
Oh grand merci pour toutes ces informations, je vais essayer de me dépatouiller avec tout ça j'y comprends pas encore grand chose (en tout cas pour ce qui concerne le côté "backend").
Je suis chez Gandi (pas chez Ovh) mais peut être qu'ils supportent le htacces aussi.
Normalement il s'agit simplement d'un espace de connexion qui donne accès à des dossiers protégés (donc pas de creation de compte par les utilisateurs eux-même, on leur délivre simplement un identifiant et un mot de passe). Je vais créer les utilisateurs et gérer les droits mais je pense que le client voudra pouvoir gerer cela lui-même par la suite (le client à besoin d'autonomie : c'est un laboratoire de recherche d'université).

**Comment by lexoyo** [comment]
Alors au moins au début tu peux utiliser le ftp pour gérer les users et fichiers protégés à la main
Apres tu trouveras surement des scripts php pour le faire en mode "visuel"
Autre question: ce sont des pages ou des fichiers à télécharger qui sont protégés?

**Comment by FannySophie** [comment]
Je pense pas qu'il y ait de fichiers à télécharger mais je demande à mon client des précisions. 
Oui j'ai regardé le tuto de Gandi pour le htacces et cela me parait très bien dans le cas ou ce serait de simples pages html à accès protégé (après si le client veut un réel espace membre cela rique d'être plus compliqué...). 
Et pour que je comprenne mieux -> en réalité pour créer des sites dynamiques avec Silex (par exemple la possibilité d'un espace membre), il faudrait lui perettre de générer des pages en php ? ça a du sens ou c'est complètement faux ce que je raconte ? 
En tout cas merci beaucoup beaucoup beacoup de donner de votre temps pour répondre à mes questions c'est super sympa !

**Comment by FannySophie** [comment]
**Le topo** : htacces pourrait suffire mais je n'en suis pas sîre, 
-> il y a un ensemble de pages html et de fichiers à télécharger
-> on doit entrer un mot de passe et un identifiant pour accéder a ces pages qui contiennent du textes des images et des fichiers à télécharger (données sécurisées)
-> pas de réel espace membre (le site ne se comporte pas différement en fonction de chaque membre) mais on doit rentrer une seule fois le mot de passe pour avoir accès à l'ensemble des pages (8 pages environ) et pas retaper le mot de passe à chaque page. 
Je vais me renseigner du côté de htaccès voir si cela est possible :)

**Silex :** pour revenir à Silex proprement parlé, pensez vous développer la possibilité de créer du contenu dynamique plus facilement avec Silex ? C'est quelque chose que vous ne voulez pas spécialement faire, ou vous avez jamais eu la demande, ou vous y avez déja pensé, etc ? (voila c'est une simple question, ça serait sympa de pouvoir créer plus facilement du contenu php avec silex pour gérer des sites dynamiques (exemple : espace membre^^), bien que dans la mesure du possible je préfère faire des sites statiques !)
Bonne soirée à vous (et encore désolé de vous embêter avec toutes mes questions!)
A bientôt,
n'hésitez pas à demander, si je peux être utile c'est avec plaisir

**Comment by JbIPS** [comment]
Je vais faire court et @lexoyo pourra développer derrière mais l'ambition de Silex n'est pas de devenir le nouveau WordPress. Il faut que ça reste simple pour le créateur et rapide pour le visiteur.
Après, on adore trouver des stratagèmes pour ajouter du dynamique mais gérer par quelque chose d'autre (htaccess ou Jekyll par exemple 😉).

**Comment by lexoyo** [comment]
Tout a fait
Et avec htaccess ce que tu décris est faisable sans problème. Tu peux dire par exemple que toutes les pages dont le nom commence par "private" ou "_" sont réservées a une liste d'utilisateurs. Dans un fichier séparé tu as les noms et mdp de ces personnes

**Comment by lexoyo** [comment]
Concernant ta remarques sur le statique / dynamique
Comme dit JB on ne veut pas refaire wordpress mais on veut s'intégrer de mieux en mieux à l'écosystème du web statique. Il y a déja toutes le fonctionnalités du dynamique, je te donne des exemples:
* le projet open source staticman.net permet la création de contenu automatique, soit pour faire un systeme de commentaires (qqn commente sur une page => le formulaire poste le commentaire sur staticman => staticman crée selon tes règles une nouvelle page dans ton site => github page ou autre re-construit ton site statique), ou ca permet d'importer des éléments d'une API (par exemple j'ai fait en sorte que si on crée un meetup sur meetup.com ca ajoute un post de blog avec le meme contenu dans [le site sur lequel je bosse](http://lexoyo.me/silexlabs.org/) et qui va remplacer silexlabs.org)
* le service payant snipcart.com permet d'ajouter toutes les fonctionnalités de vente en ligne à un site statique
* le projet open source strapi.io te permet de créer un back office complexe pour administrer du contenu statique et dynamique (potentiellement le contenu peut meme etre les 2 en meme temps, par exemple si tu as une agence de voyage, tu peux créer une promo "voyage sur la lune à 400€" dont les détails sont pris à la compilation de ton site statique mais la valeur de "combien me reste il de stock" est chargée à chaque affichage pour etre du temps réel)
* stastic.net ou siteleaf.com permettent de créer des admin "à la wordpress" pour que ton client puisse editer le contenu texte seulement
* avec silex+jekyll tu peux facilement faire des blogs ou des sites multilingues

Autre exemple, [sur cette page](https://ceubri.github.io/excellence-kebab/menus.html) @ceubri a rendu tous les prix dynamiques pour que son client ne puisse changer que ca, l'interface resemble a ca (utilise silex+jekyll+stastic.net):
 
![Screenshot from 2019-07-30 18-38-56](https://user-images.githubusercontent.com/715377/62167308-4e31d400-b2f9-11e9-810b-3b03de1dc0e5.png)

Pour conclure, les sites dits statiques font tout ce que font les sites dynamiques, mais le plus de choses possibles sont faites quand le contenu change, au lieu d'être faites quand un internaute consulte une page

**Comment by FannySophie** [comment]
Merci de m'avoir aidé avec mon problème je vais opter pour la solution htaccess ducoup  ! 
Ah dis donc je ne pensais pas qu'autant de choses étaient possibles (et d'outils disponibles) ! C'est super, et j'ai regardé la vidéo à propos du site multilangue Silex avec Jekyll et Siteleaf et c'est effectivement très bien comme solution pour un client :) 
Vive Silex ! 
A très bientôt
Bonne journée :)

**Comment by FannySophie** [comment]
ps : j'ai une autre question, un peu bête peut-être mais je n'arrive pas à effacer les propriétés d'une classe.
Exemple : dans la petite icone "A" je séléctionne une classe et je mets une couleur de fond "background-color" . Mais en réalité je me suis tompée (et maintenant tout mon texte à une couleur de font alors que je n'en veux pas), comment revenir à la valeur par défaut du début, sans couleur de fond ? C'est a dire "clean" une propriété d'une classe (un peu comme si on effacait la ligne du code css).

**Comment by lexoyo** [comment]
Juste tu effaces la couleur (le texte qui commence par #)

**Comment by FannySophie** [comment]
Ah j'ai réussi ! C'est qu'on ne peut pas supprimer les numéros en entrant dans la case pour choisir la couleur, il faut le supprimer directement au nivea du menu (j'ai mis un petit moment a trouver quand même) ! :)

**Comment by FannySophie** [comment]
Enfait ça ne marche pas quand clique pour entrer la couleur qu'on efface tout et qu'on appuie sur entrée ensuite on valide. Il faut directement l'effacer dans le menu. C'est simple mais il faut le savoir^^

**Comment by FannySophie** [comment]
Je sais pas si c'est clair ce que je dis^^ Merci bien en tout cas :) Et quand vous avez des news du sftp il y a un endroit ou je peux me tenir au courant ? Ou vous m'écrirez directement ici ?
Très bonne journée à vous !

**Comment by FannySophie** [comment]
Bonjour,
et **HELP**, c'est encore moi, j'ai une erreur depuis hier très embêtante : je ne peux plus publier mon site, ni dans un dossier dropbox, ni sur github pages.

J'ai le message suivant pour **github pages :** 
"An error occured.
I did not manage to publish the website. Error while batch: Could not create a new tree UnifileError: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
Get help in Silex forums."

Et le message suivant pour **dropbox :** 
" An error occured.
I did not manage to publish the website.
Cannot GET /undefined
Get help in Silex forums."

Ci joint les **captures d'écran** :
![Capture du 2019-08-01 12-00-19](https://user-images.githubusercontent.com/51905865/62284579-27d47b80-b454-11e9-8ea0-5ca1790678ee.png)
![publishbug](https://user-images.githubusercontent.com/51905865/62284609-328f1080-b454-11e9-9919-fc8076481f63.png)

Je ne sais pas ce qu'il s'est passé tout marchait très bien avant ça et il me semble rien avoir changé... 
Bonne journée,
Fanny

**Comment by JbIPS** [comment]
Hello Fanny,
Le message d'erreur vient directement de GitHub et je t'avoue ne l'avoir jamais vu. Peut-être trop de commits d'un coup, attends un peu que ça passe.
Pour Dropbox par contre, peux-tu vérifier ton chemin de publication ? Le undefined n'est pas normal ici

**Comment by FannySophie** [comment]
Coucou,
Alors j'ai revu mon chemin cela m'a fait la même eurreur puis j'ai réessayé et cela m'affiche ceci :
![bug](https://user-images.githubusercontent.com/51905865/62297532-b73c5780-b471-11e9-8420-4e9d5aa8c914.png)

C'est vraiment bizzare je ne vois pas à quoi cela peut être lié, peut être mon site est trop lourd?

**Comment by lexoyo** [comment]
Tu peux nous partager le site stp?

**Comment by FannySophie** [comment]
Je veux bien mais je ne vois pas comment faire ?

**Comment by lexoyo** [comment]
tu as sauvé ton fichier sur github?

**Comment by FannySophie** [comment]
https://github.com/FannySophie/TEST_SITE/blob/master/editabletemplate.html

Oui je l'ai sauvegardé ici normalement :)

**Comment by FannySophie** [comment]
Plus aucune publication ne marche, j'ai réessayé de publier dans un autre répertoir github et voici : 
![mkdir](https://user-images.githubusercontent.com/51905865/62316347-8707af80-b497-11e9-86e5-69406f62092f.png)

**Comment by lexoyo** [comment]
Je regarde d'ici 1h

**Comment by lexoyo** [comment]
Mes remarques

1- tu as plein de pages et ton site est multilingue, tu pourrais gagner bcp de temps et qualité en utilisant silex+jekyll, je te propose de t'inscrire ici à la liste silex PRO http://eepurl.com/gjYnib
2- l'erreur `Cannot GET /undefined` est connue, c'est seulement la 1ere fois que tu publies apres avoir changé les parametres de publication => re-publie direct apres et choisis "Continue"
3- en faisant cette astuce du "2-" j'ai réussi a publier sur dropbox en essayant 10 fois... je pense que ton site est trop gros pour dropbox, @JbIPS des fois ca passe et des fois pas
4- toujours en faisant l'astuce du "2-" j'ai réussi à publier sur github sans probleme. l'erreur que tu as eu est temporaire, surement due au fait que ton compte est tout jeune? github pense que tu fais des trucs abusés... laisse leur 24h et on te cherche une nouvelle technique si ca passe pas

Enfin une chose qui peut t'induire en erreur : si tu fais "enregistrer sous" comme tu l'as surement fait pour enregistrer ton site sur github alors qu'il était sur dropbox, les images ne sont pas déplacées, seulement le fichier html... Tu devrais sans doute rester sur dropbox et publier sur github

**Comment by JbIPS** [comment]
Ah je sais qu'il y a une limite de taille de fichier sur Dropbox mais c'est bizarre que des fois ça passe et des fois non...

**Comment by FannySophie** [comment]
Ah tout s'éclaire merci ! Je me disais bien que mon site devait être trop lourd. 
Merci beaucoup pour cet aide précieuse ! Je réesayerai avec jekyll ducoup. Oui j'ai crée ce compte il y a peu ça doit être pour ça alors ^^Désolé/GitHub^^ . 
Un dropbox capricieux alors, y a il un moyen de faire sortir les fichiers de publication directement sur son ordinateur au lieu de passe par dropbox et le télécharger d'ailleurs ? 
Bonne journée ! :)

**Comment by JbIPS** [comment]
Tu peux prendre la version Desktop de Silex qui te permet de tout enregistrer sur ton disque dur 😉

**Comment by FannySophie** [comment]
Ah super merci bien ça va être mieux pour moi :) très 
bonne journée

**Comment by lexoyo** [comment]
Hello
Tu t'en sors?
Sinon j'ai l'intention de proposer un service de support pour les agences ou freelances qui utilisent silex. Je conduis qques interviews pour voir ce qu'en pensent ma cible, tu serais ok pour discuter 15 min en audio?

**Comment by FannySophie** [comment]
Coucou, désolé du retard j'ai énormément de travail en ce moment, finalement au vu des demandes du client qui sont venues se rajouter j'ai du opter pour une autre formule car il y avait vraiment besoin d'un site purement dynamique pour le coup ! Mais j'ai un autre client potentiel (espérons !) et le site demandé serait statique donc je choisirai Silex pour celui ci (j'essayerai aussi d'éditer une template pour mettre à dispo mais qui sera pas là avant octobre je pense) ! Oui si je peux être utile en quoi que ce soit c'est avec plaisir. Dis moi quand tu sera dispo et je te confirme :)

**Comment by lexoyo** [comment]
Hello
Calons un rdv par email si tu veux bien ?
alex à silex.me
