### ISSUE TITLE
Inserting text over an image in mobile

### ISSUE THREAD

**Issue by fxaddict** [silexlabs/Silex#955]
Hi all,
New to Silex and loving it so far. Created a page on the desktop view and was easily able to put text over a background image. I didn't like the way it rendered on the mobile view and started over.
When I try to put text over the image in mobile, it stacks the image on top of the text box. I need the text over the image and can't seem to figure out how. Would appreciate it if someone could tell me how to achieve this. Trying to build a mobile only landing page.

Thanks
Mike

**Comment by lexoyo** [comment]
Hi Mike
The easiest way is to set the image as the background image of a container and the text box inside the container
Let me know how it goes ok?

**Comment by fxaddict** [comment]
Thanks for the fast reply!

I removed all elements and set the image as background.
That worked like a champ except it made a partial duplicate of the image
below. Should I just resize it?
Thanks again for your help.

**Comment by lexoyo** [comment]
It is probably the "repeat" settings
Play with the background image settings

**Comment by fxaddict** [comment]
Will do! Thanks again!
Didn't expect such a fast response either time. WOW!

**Comment by fxaddict** [comment]
That nailed it! Thanks so much!
