### ISSUE TITLE
Error on publishing my website

### ISSUE THREAD

**Issue by fernandammoutinhobarros** [silexlabs/Silex#958]
Can someone help
![image](https://user-images.githubusercontent.com/25388113/63042587-40b44680-bec2-11e9-80bb-5060a6292a5c.png)

**Comment by lexoyo** [comment]
Hi
Could you tell me what service you use, and if you are on preprod.silex.me or editor.silex.me ?

**Comment by fernandammoutinhobarros** [comment]
Hi Alex,

I used editor, but when the error occurred I used prepod also, to see if it would solve the issue, but I got the same error.

**Comment by fernandammoutinhobarros** [comment]
![image](https://user-images.githubusercontent.com/25388113/63159440-7c125a80-c013-11e9-85a6-4e1f1e62ae8a.png)

**Comment by fernandammoutinhobarros** [comment]
![image](https://user-images.githubusercontent.com/25388113/63162463-7b30f700-c01a-11e9-8fcd-6db59cb535ed.png)

**Comment by fernandammoutinhobarros** [comment]
I solved the problem by separating the files.
Instead of having one editable file with 2 pages -english + chinese
I deleted the chinese and made 2 editable files separated, so now with only one page for each editable it publishes fine.

you can check the website here. 
www.rarchina2019.net

thanks

**Comment by lexoyo** [comment]
Hi @fernandammoutinhobarros 
Very nice website !!!
I'd love to find out what was the bug, would you share the file before you split it?

**Comment by fernandammoutinhobarros** [comment]
Of course I sent you e-mail with the files

**Comment by lexoyo** [comment]
Hi @fernandammoutinhobarros 
Sorry for the time it took me :(
As your bug seems to be the same as #960, could you please open your website with preprod.silex.me, then save it, then publish it?
