### ISSUE TITLE
Add cancel button to publish prompt

### ISSUE THREAD

**Issue by UltraNiels** [silexlabs/Silex#959]
#### Issue
In the prompt that appears when you click on *Publish* (rocket icon) is no cancel/close option, so when you accidentally click it the only thing you can do is continue or refresh the page to close the prompt. Clicking outisde of the prompt will not close it either.
#### Fix
Add a *Cancel* button to the prompt that closes the prompt.
#### Image
![aaa_censored](https://user-images.githubusercontent.com/45306483/63213644-1f946580-c10f-11e9-8136-da3bafc9b372.jpg)

**Comment by lexoyo** [comment]
Nice catch thx
I'll try to fix this soon
Or if you feel like contributing some code let me know I'll guide you to change that :+1:

**Comment by UltraNiels** [comment]
I would like it if i can add it, but i realy dont know typescript :D

**Comment by lexoyo** [comment]
Ok no prob I'll let you know about this
Thx
