### ISSUE TITLE
Dropping a background image triggers an internal server error

### ISSUE THREAD

**Issue by ygramoel** [silexlabs/Silex#961]
While looking for a website builder,  I came accross Silex;  it looks really good.
Then it tried it, and one of the first thing I tried caused an internal server error. I am doing something wrong?

I did this:
1. Go to https://editor.silex.me/
2. Select the "clean square" template
3. At the right,  open "background image" and click "select image"
4. Take a .png image (576x460 pixels, 38kB) and drop it in the browser window

I get an internal server error.  See screenshot below.
![Screenshot from 2019-09-01 17-58-18](https://user-images.githubusercontent.com/24917266/64079080-388e4080-cce3-11e9-9bf0-0529186ae251.png)

**Comment by lexoyo** [comment]
Hello

The problem is that you need to select a service first. Because this instance of Silex is provided for free by Silex Labs foundation and we don't host any file, you are the one who own your data

The fact that Silex crashes when you do that is a bug which been fixed and will be live soon

**Comment by ygramoel** [comment]
OK,  but how do I "select a service"?  There is nothing obvious about selecting a service in the menus or on the silex website; or did I miss something? Is there some documentation I should read first,  a "gettign started" maybe?

**Comment by lexoyo** [comment]
You just need to double click on ftp or Dropbox...

If you choose GitHub, you need to create a folder and a folder in that folder to put images in it
