### ISSUE TITLE
Bug: insert an image ( Preprod )

### ISSUE THREAD

**Issue by BaguetteAgile** [silexlabs/Silex#963]
@lexoyo 

Salut Alex, je suis de retour ...

Je viens de remarquer un bug dans l’éditeur de texte.
Quand je clic sur `Insert an image` la barre de navigation disparaît et rien se passe,
il me semble également que la fonction `aide` soit `?` a le même comportement.

**Sur Editor sa fonctionne.**

![Capture d’écran de 2019-09-18 08-46-32](https://user-images.githubusercontent.com/35597855/65123829-661dfe00-d9f4-11e9-934f-8507a1e47c2f.png)

**Comment by lexoyo** [comment]
Ah ok merci baguette ;)
Je regarde ça demain

**Comment by lexoyo** [comment]
Hello
Je pense avoir résolu le probleme. L'image se positionne toujours en haut du texte mais on peut la déplacer avec la souris
Tu peux tester l'edition de text en général @BaguetteAgile ? Ca serait super de faire la release bientot (mettre ce qui est sur preprod.silex.me en prod)
