### ISSUE TITLE
Rearrange the section

### ISSUE THREAD

**Issue by dmyterritory** [silexlabs/Silex#964]
Hi, I have a question.

If we create a new section, they would appear at the most bottom. How can we rearrange the newer section to be at the top or wherever my liking?

**Comment by lexoyo** [comment]
Hi
Did you find your answer?
(The keyboard arrows or the arrows of the context menu at the top)

**Comment by dmyterritory** [comment]
Yes I did. Sorry for the inconvenience. Thank you for responding.
