### ISSUE TITLE
Cant Publish To github

### ISSUE THREAD

**Issue by Starseed95** [silexlabs/Silex#968]
does anyone know what im doing wrong with publishing my site made with silex to github. After it gets done downloading files it says: "I did not manage to publish the website. Error while batch: Could not complete action mkdir: Reference already exists" what does this mean?!

**Comment by lexoyo** [comment]
aouch
several people reported problems with publicatoin these times
could you tell me the size of your html page?
or just put a link to your github please

**Comment by lexoyo** [comment]
@Starseed95 ? bump!

**Comment by lexoyo** [comment]
see the temporary workaround here 
https://github.com/silexlabs/Silex/issues/960#issuecomment-539630301
