### ISSUE TITLE
Need your help preparing the next version of Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#971]
Hi all
I will have time for Silex and will implement the following features of [the road map](https://github.com/silexlabs/Silex/milestones) in the near future. Any idea, questions or design elements are welcome at this stage ;)
cc @suddenheroes @ceubri @budislav @clemos @JbIPS @fernandammoutinhobarros @godzone @fxaddict @UltraNiels @MACscr @BaguetteAgile @Lea75 

* [thumbnails of images in the file browser](https://github.com/silexlabs/CloudExplorer2/issues/88)
* [Free photos within silex](https://github.com/silexlabs/Silex/issues/477)
* [Redesign the page list](https://github.com/silexlabs/Silex/issues/969)
* [Page properties](https://github.com/silexlabs/Silex/issues/882)
* [Overlay pages](https://github.com/silexlabs/Silex/issues/885)
* [Library](https://github.com/silexlabs/Silex/issues/940)
* [better stage UI](https://github.com/silexlabs/Silex/issues/970)

**Comment by fernandammoutinhobarros** [comment]
Hi Alex,
ok.

**Comment by BaguetteAgile** [comment]
Je regarde pour la page Overlay ;)

**Comment by lexoyo** [comment]
Hello 

Would you please check if the image banks and image thumbnails view work for you?
It's in the cloud explorer on preprod.sikex.me
Cc @BaguetteAgile @fernandammoutinhobarros  @rapenne-s 
@ceubri 

Also I am wondering what library of icons I can add too, let me know if you know of a good one

**Comment by fernandammoutinhobarros** [comment]
Whato do you mean by image banks?

**Comment by BaguetteAgile** [comment]
Bonjour à tous,

voici ce que j'ai réussi à faire dans le contexte de la page OVERLAY:

https://baguetteagile.github.io/essaiSilex/

Cependant je souhaiterai supprimer l'action du Clic avec la souris pour afficher le Popup, l'idéal serai que le Popup se charge directement, il me semble qu'il est possible de faire une "Temporisation automatique" après chargement de la page principal. 

Je vais avoir besoin de vous pour ajouter cette fonction et modifier le code.

Qu'en pensez vous ?

**Comment by BaguetteAgile** [comment]
> Hello
> 
> Would you please check if the image banks and image thumbnails view work for you?
> It's in the cloud explorer on preprod.sikex.me
> Cc @BaguetteAgile @fernandammoutinhobarros @rapenne-s
> @ceubri
> 
> Also I am wondering what library of icons I can add too, let me know if you know of a good one

Pour moi tout fonctionne super ( Chromium sous Linux) , je trouve l'idée extra d'offrir une banque d'image...

**Comment by BaguetteAgile** [comment]
> Cependant je souhaiterai supprimer l'action du Clic avec la souris pour afficher le Popup, l'idéal serai que le Popup se charge directement, il me semble qu'il est possible de faire une "Temporisation automatique" après chargement de la page principal.

Est-ce que ce code pourrai être inséré?

`<html>
  <head>

    <script language="javascript">
    
    </script>

  <body onload="popup()">

  page html courante...

  </body>
</html>`

**Comment by ceubri** [comment]
Hello,
chez moi ça fonctionne, par contre c'est bizarre que le download télécharge l'image dans un onglet (chrome / win10) : il fuadrait que cela l'ajoute à Silex ou alors supprimer ce "download".

Pour ce qui est des icones "the best ever"> https://developer.flaticon.com/landing

**Comment by lexoyo** [comment]
> What do you mean by image banks?

@fernandammoutinhobarros I mean free image stock directly inside Silex, such as unsplash.com

**Comment by lexoyo** [comment]
@ceubri flaticon c'est exactement ça sauf que c'est propriétaire et payant ... ca pourrait peut etre le faire avec leur plan gratuit mais je vais chercher une alternative

**Comment by lexoyo** [comment]
Merci pour les tests @BaguetteAgile @ceubri

> chez moi ça fonctionne, par contre c'est bizarre que le download télécharge l'image dans un onglet (chrome / win10) : il faudrait que cela l'ajoute à Silex ou alors supprimer ce "download".

En fait si tu double click ca l'ajoute mais si tu click sur download c'est pour voir l'image en grand... Innutile? Mal nommé?

De plus il y a une question sur la taille des images, là ca pose une image de taille intermédiaire sur la scene (ou en bg d'un élément ou dans un champs de texte). Peut etre qu'on devrait demander a l'utilisateur la taille désirée?

**Comment by lexoyo** [comment]
@BaguetteAgile pour ta popup tu as utilisé quoi?
Là mon idée serait de pouvoir créer des pages de type "overlay", qu'on peut maquetter comme on veut mais quand il y a un lien vers cette page ça l'ouvre par dessus la page en cours

**Comment by lexoyo** [comment]
@ceubri I changed "Download" with "Preview"

And I have released the version on preprod.silex.me to editor.silex.me
This correspond to this code: https://github.com/silexlabs/Silex/pull/984

Then I have added new features to preprod.silex.me for you to test please:
* new properties for containers and elements to crate layouts (see screenshot bellow)
* better page tool, closes #882
* data sources experimental feature, closes #924 

![screenshot_20191124_105107](https://user-images.githubusercontent.com/715377/69495680-68934d00-0ea8-11ea-825f-ae0f772a5a37.png)

**Comment by ceubri** [comment]
Great ! I don't understand how Flex flow work but seems to be good ;)

**Comment by ceubri** [comment]
> De plus il y a une question sur la taille des images, là ca pose une image de taille intermédiaire sur la scene (ou en bg d'un élément ou dans un champs de texte). Peut etre qu'on devrait demander a l'utilisateur la taille désirée?

Oui bonne idée, comme dans wordpress : 
![image](https://user-images.githubusercontent.com/7302680/69529401-85935300-0f70-11ea-918f-0e750d6a3406.png)

**Comment by BaguetteAgile** [comment]
@lexoyo 

> @BaguetteAgile pour ta popup tu as utilisé quoi?

https://html-online.com/articles/simple-popup-box/

**Comment by Lea75** [comment]
Bonjour,je suis une quiche en anglais et en programmation... alors je n'ai à peu près rien compris des échanges précédents de mails :(
mais j'adore créer des sites web et je veux bien aider à la nouvelle version de Silex (s'agit-il bien de ça ?) et que les personnes comme moi sont des cibles pour vos projets !Si c'est le cas : quel lien dois-je utiliser pour créer un site et vous faire des retours ?Si la demande n'a rien à voir avec ça, toutes mes excuses pour le dérangement !
Une bise,Léa
    Le lundi 25 novembre 2019 à 17:49:25 UTC+1, BaguetteAgile <notifications@github.com> a écrit :  
 
 
@lexoyo


@BaguetteAgile pour ta popup tu as utilisé quoi?


https://html-online.com/articles/simple-popup-box/

**Comment by lexoyo** [comment]
C'est exactement ça !!! :))
Merci pour les tests, n'hésite pas à poser des questions dans une nouvelle issue même si c'est sont des trucs que tu n'as pas compris c'est très utile de savoir que ça n'est pas évident. Et ça te permet d'apprendre, on est là pour ça

**Comment by lexoyo** [comment]
Le lien pour les tests est https://preprod.silex.me

**Comment by Lea75** [comment]
ok.
Pour poser mes questions, comme ce n'est pas clair "où est-ce que je pose une nouvelle issue"... je suis déjà un peu bloquée à ce niveau là !Ci-joint, une première feuille de questions... en pièce jointe !
Explique moi où/comment faire des issues pour chaque question si c'est mieux ? J'essaierai de le faire...Et sinon, je peux vous rejoindre à un apéro silex pour mieux témoigner de ce qui est flou pour les novices comme moi !
Merci merci !Léa

    Le mercredi 27 novembre 2019 à 23:10:11 UTC+1, Alex Hoyau <notifications@github.com> a écrit :  
 
 C'est exactement ça !!! :))
Merci pour les tests, n'hésite pas à poser des questions dans une nouvelle issue même si c'est sont des trucs que tu n'as pas compris c'est très utile de savoir que ça n'est pas évident. Et ça te permet d'apprendre, on est là pour ça

**Comment by lexoyo** [comment]
C'est ici pour créer une issue
https://github.com/silexlabs/Silex/issues

Il y a un lien dans le menu d'aide de silex si tu le perds
