### ISSUE TITLE
SFTP and FTP 

### ISSUE THREAD

**Issue by kimb1** [silexlabs/Silex#974]
Seemingly I can't get the online version (editor.silex.me or preprod.silex.me) to connect to my web server using either SFTP or FTP.     From the server log it seems to be sending a blank string - not a .

I get `This path does not exist (Bad Request)`

Then shortly after:

```
This operation failed with the following error message:  
<!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <meta charset="utf-8"> <title>Application Error</title> <style media="screen"> html,body,iframe { margin: 0; padding: 0; } html,body { height: 100%; overflow: hidden; } iframe { width: 100%; height: 100%; border: 0; } </style> </head> <body> <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe> </body> </html> 
(Service Unavailable)
```  

I can connect fine with WinSCP using either protocol, and the Silex server connects but seems to send a blank request. <details><summary>See sFTP log</summary>
```
Oct 27 11:03:51 dev2 internal-sftp[27970]: session opened for local user testsite from [54.170.243.223]
Oct 27 11:03:51 dev2 internal-sftp[27970]: received client version 3
Oct 27 11:03:51 dev2 internal-sftp[27971]: session opened for local user testsite from [54.170.243.223]
Oct 27 11:03:51 dev2 internal-sftp[27970]: stat name ""
Oct 27 11:03:51 dev2 internal-sftp[27970]: sent status No such file
Oct 27 11:03:51 dev2 internal-sftp[27971]: received client version 3
Oct 27 11:03:51 dev2 internal-sftp[27970]: session closed for local user testsite from [54.170.243.223]
Oct 27 11:03:51 dev2 internal-sftp[27971]: stat name ""
Oct 27 11:03:51 dev2 internal-sftp[27971]: sent status No such file
Oct 27 11:03:51 dev2 internal-sftp[27971]: session closed for local user testsite from [54.170.243.223]
```
</details>
I've tried running without chroots, all the local file permissions etc - but it seems there's something stuck on the server end.

Can't see any current open issues relating to it - is there anything I need to do to debug, or an easy fix?

Thanks
Kim

**Comment by JbIPS** [comment]
Thank you for the detailed report. The error must come from Unifile, a dependency of Silex that handle cloud connection.

Some FTP server have differencies that could cause such issue. What is your provider? I'll test the connection against it ad try to fix that ASAP.

Or if you're motivated, try to reproduce the case in silex/unifile unit test, that would be of great help :blush:

**Comment by kimb1** [comment]
Thanks for the reply!
It's my own box - Debian.    I can send you some credentials if you want to test, but probably best not on GitHub.

SFTP is OpenSSH_7.4p1 Debian-10+deb9u7, OpenSSL 1.0.2t  10 Sep 2019  with the internal sftp server.

FTP is vsftpd   vsftpd: version 3.0.3

I will have a look at the unifile repo shortly and see if I can find the tests.

Thanks
Kim

**Comment by JbIPS** [comment]
That should be enough to test, I agree you shouldn't send credentials here.

Could you try to run https://github.com/silexlabs/unifile/blob/master/test/unifile-ftp.js with your server?

**Comment by kimb1** [comment]
More info.   I'm afraid I've never used JavaScript  or  Node as a developer, but I've cloned the git repo and done a bit more.

Testing from a new install debian client VM, with node installed according to the instructions on nodejs.org (https://github.com/nodesource/distributions/blob/master/README.md).   and "make" from the debian packages.

using the example in 
unifile/samples/simple-api-server.js
`node simple-api-server.js`

Fetching the page on the vm  port 6805   works fine.     I edited simple-api-server.js with the hostname in place of "localhost" - no problem.   With that,  the big "log in" button brings up same as editor.silex.me   SFTP credentials same

Apparently works.   No errors on the server console.  Seems to log in ok.

Using the "list" button with a blank entry give error
```
Error: This path does not exist
    at parseError (/home/kim/unifile/lib/unifile-sftp.js:25:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 2
```

and in the form, `{code: 2}   `- which makes sense

If I enter the path "/"  (no quotes) and "list button"  - it works fine - listing the two folders in the root path when you log in - all good.  Creating folders works and I imagine uploads will too.

So I'm back to thinking that the editor is trying to list a blank string when it first logs in - which SFTP doesn't like.    That page still gives the error `**"This path does not exist (Bad Request**`

I've not quite worked out how to follow your second suggestion and run that file from test directly but it's the next thing to do.

**Comment by kimb1** [comment]
Sorry to ask a very basic question – but how – I’ve tried “node unifile-sftp.js”   - with or without editing that file to have real credentials in.
```
node unifile-sftp.js
/home/kim/unifile/test/unifile-sftp.js:27
describe('SFTPConnector', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/home/kim/unifile/test/unifile-sftp.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

I have mirrored the whole Silex project and got the editor running from that local mirror - that works fine - but still won't connect to SFTP - which is good as it's consistent, but I'm now very stuck about where to go next other than use filesystem access and build a user login system to map to appropriate paths.

**Comment by lexoyo** [comment]
Hi
Thx for those tests :)
I'm not sure what@JbIPS meant to do next
Some other things I am thinking about:
1- can you check the network of your browser and see what path cloud explorer is calling?
2- is that cloud explorer stores the current path in the local storage and when you open it (in silex or outside) it uses it to restore the path
So maybe you can try setting the path "/" using this?

**Comment by JbIPS** [comment]
Thank you @kimb1 for those tests, your guess about a blank string might be the good one, I'll check this on my local installation to reproduce (and fix) it.

About the test, you need to run the command `npm test`. This will automatically create, among other thing, a local FTP server and try to connect to it. Since it's a fresh out-of-the-box temporary server, the credentials are hard coded but you don't need to modify them.
