### ISSUE TITLE
Support of `picture` tag

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/Silex#979]
Have you ever consider to support and use the [`picture`](https://devdocs.io/html/element/picture) tag ?

To speed up further my website I'm looking to server WebP image but due to the lack of support of some browser, I'd like a fallback strategy and `picture` is perfect for it. 

Ideally, any new image could be a `picture` tag with the selected image as a `img` inside and maybe a file chooser for alternated source. Or even better: checkboxes for formats with auto encoding and addition to the source :money_mouth_face: 

Another usecase could be tinier images for mobile display (again with a "Allow compressed version on mobile" checkbox).

For now, I think I'll replace all my images with an HTML box but I'm not sure how it will be displayed.

**Comment by lexoyo** [comment]
Hi
Yes I thought about it and I would like to create the picture tag at publication, with automatic image resize+webp, as explained in #780 
This is only server side, let me know if you would like to add it yourself

**Comment by JbIPS** [comment]
Oops, I missed this issue :sweat_smile: 

I don't see a usecase were I would like to change the image other than for compression so I guess it's OK to do it on the server side. If I understand correctly, this will be completely hidden from the user?

I'll close this since it's a duplicate.
