### ISSUE TITLE
Mobile Menus Overlayed by Images

### ISSUE THREAD

**Issue by Dawnstride** [silexlabs/Silex#981]
Hi everyone. I saw that the version of Silex at editor.silex.me was updated to a new style recently. Well when it did that, it created an issue that was not present before.

I have a site I've been editing on both desktop and mobile. On the mobile, there are several navigation menus. On click, it uses this JS code to open the menu:

  document.getElementById("mySidenav").style.width = "425px";
  document.getElementById("main").style.marginLeft = "425px";
  document.getElementById("mySidenav").style.zIndex = "2147483647";

There's also CSS code for the menu. The problem is, when the menu opens, the images that are below it are always displayed on top of the menu. I've tried changing the zindex of the menus and putting it at max, I've even tried using jquery code to hide the images when the menu bar is opened, and no matter what, the images are always displayed on top of the menus.

EDIT: Forgot to mention this, but on the older version of Silex, this issue wasn't present and the menus displayed just fine. Only on the new version did this start happening.

**Comment by lexoyo** [comment]
Hello 
1- Can you provide a link to the buggy version of your website?
2- do you use the "new" hamburger menu component or is it the old one?

**Comment by lexoyo** [comment]
Forget about question 2, I will check your website and see :))

**Comment by Dawnstride** [comment]
Hi, thank you for your response! The buggy version of the site is at http://www.fosterkidnews.com/SiteN1/index.html 
Again it's only on the mobile version of the site, the desktop version is fine. Also for your 2nd question, I'll just mention that I'm not using the hamburger menu component at all. I'm just using an image that when clicked, calls a Javascript function to display the menu as well as the CSS to make it look right.

**Comment by lexoyo** [comment]
Oh ok
Can you try tout add a CSS class "fixed" in silex to the container of the menu? If it doesn't work I will investigate
There is some info about this style in the docs here (would probably need to be rewritten better) https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#silex-css-classes

**Comment by Dawnstride** [comment]
I do already have position: fixed in the CSS of each of the menus. I read on that page and noticed there's something about fixed and applying it to certain elements in silex, would this be different? If so, my elements are called sidenav1, sidenav2, sidenav3, sidenav4. What would be the code for that?

**Comment by lexoyo** [comment]
Yes it is different (please fix the docs if you can)
Silex has a mechanism to appear perfect on all screens. It scales to fit the width of the screens (desktop width is section width, mobile width is the media query width). It uses css transforms for that. Not sure if what I say is true for mobile though as the viewport can do that already... But I guess so. And position: fixed does not work inside a container which is resized with css transform, as the fixed element will be moved by the browser into a new "stacking context" (if I remember correctly)

In any case, remove all the position fixed and simply apply the "fixed" css class to the containers. Then silex "front-end.js" script will resize it and move so that it appears well

**Comment by lexoyo** [comment]
https://github.com/silexlabs/Silex/blob/develop/static/2.10/front-end.js#L118

**Comment by Dawnstride** [comment]
Okay, I did as you said and removed position: fixed and added the fixed class to the menus. It certainly made the menus in a fixed position so they stay on the screen even when you scroll, but they are still obscured by the images. This newest version is on the same link I listed above: http://www.fosterkidnews.com/SiteN1/index.html

Still being obscured by the images on mobile. :(

**Comment by lexoyo** [comment]
Oh ok
Can you move the container of the menu to the background of the section? I guess for now it is in the body of the section?

**Comment by Dawnstride** [comment]
I'm not sure how to move it to the background of the section. Currently it is in a section, and the container of the menu is in a section container. I have uploaded an image that shows the placement of it, as well as pictures of all of the code and CSS that is involved with the menu: 

https://i.imgur.com/3IH2WBh.jpg

Hope this helps to figure out what's going on. It was certainly working a few weeks ago on the 'old' silex, but when it changed to the new version, it started messing up.

**Comment by Sajidhussain10** [comment]
what happend why you guys add me here ?


---- On Sun, 17 Nov 2019 17:23:38 +0500 Alex Hoyau <notifications@github.com> wrote ----


Oh ok
 Can you try tout add a CSS class "fixed" in silex to the container of the menu? If it doesn't work I will investigate
 There is some info about this style in the docs here (would probably need to be rewritten better) https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor#silex-css-classes

**Comment by lexoyo** [comment]
I think I understand. You put the button which opens the menu in the section background but I can see in the HTML source that the HTML box containing the menu is still in the section container

This is what you have
![screenshot_20191119_112616](https://user-images.githubusercontent.com/715377/69154815-74a19800-0abf-11ea-9eff-e30dec52451a.png)

And this is what you want

![screenshot_20191119_112542](https://user-images.githubusercontent.com/715377/69154830-7a977900-0abf-11ea-8b40-0028f8e5c14a.png)

So in Silex, drag the HTML box to the section background

From this:
![screenshot_20191119_112721](https://user-images.githubusercontent.com/715377/69154899-97cc4780-0abf-11ea-90c4-edd798341b4a.png)

To this:
![screenshot_20191119_112727](https://user-images.githubusercontent.com/715377/69154904-9b5fce80-0abf-11ea-87af-d7561f112f25.png)

**Comment by lexoyo** [comment]
Bump @Dawnstride 
Does it work for you?

**Comment by lexoyo** [comment]
> what happend why you guys add me here ?

I have no idea, feel free to unfollow the issue

**Comment by Dawnstride** [comment]
Yeah, you're exactly right about what I want. I want it to look like in your second image, and that's how it looked before the new silex version. I did try the fix by moving it off, and it's the same issue. At the same time, I've also noticed a similar problem on the desktop. Like I made a navbar sticky, and despite setting the correct z-index, it still is obscured by the images. I think there's some kind of issue with the z-index working properly.

**Comment by lexoyo** [comment]
Is your site on github or Dropbox ? Can you share It with me?

**Comment by Dawnstride** [comment]
It's not on either, but I can place it on a dropbox or something so you can take a look. All you need is the .html file that I open with silex, correct?(the file that you edit before publishing) or do I need to upload the other files as well?

**Comment by lexoyo** [comment]
Yes I think it should be enough

**Comment by lexoyo** [comment]
Hi

I had a look but I don't understand where is what and it freezes my browser when I switch to mobile editor, I wonder why...

But I can see that there is a problem with silex: the selector `.section-element > .silex-element-content > :not(.prevent-auto-z-index)` is applyed to all elements. it is made to prevent elements disappear behind section containers but in your case it makes everything in the section containers at the same z-index. 

I will investigate later, but for now you can just add this css class to your HTML boxes: `prevent-auto-z-index`

**Comment by Dawnstride** [comment]
@lexoyo Thank you for your help. Rather than open a new topic, I'll ask here. 

One thing I've tried to do is add some jquery to the HTML HEAD editor on the site to apply some of these changes. It has <head> <script> then lots of jquery code, then </script> </head> at the end. This worked just fine and the jquery worked on the old editor, but now I've noticed that none of the jquery code is working. Is there a different way to apply it or something that I've done wrong?

**Comment by fadanan** [comment]
Hello, i'm facing the same problem as my drop down menu is hidden under the other elements in the below section.

> But I can see that there is a problem with silex: the selector `.section-element > .silex-element-content > :not(.prevent-auto-z-index)` is applyed to all elements. it is made to prevent elements disappear behind section containers but in your case it makes everything in the section containers at the same z-index.

where shoud i paste this code? I paste it in my CSS editor and it did not work. could you please help?

**Comment by lexoyo** [comment]
Hello
You are too?? argh! :cactus: 
Paste it in the [CSS editor](https://github.com/silexlabs/Silex/wiki/Silex-CSS-editor) (the docs are old)

**Comment by fadanan** [comment]
I already did and it did not work. Instead something weird is happening to my dropdown. The container do not have any x or y value. If I delete the container, all my element cannot be drag, only can be move by using arrows on keyboard. Should I share you the file by dropbox?

**Comment by lexoyo** [comment]
yes please share it with a.hoyau [at] im-paris.fr

**Comment by fadanan** [comment]
okay I just share you the file. Sorry for late response

**Comment by fadanan** [comment]
@lexoyo hello, do you have any updates regarding the issue? I'm sorry if you are busy.

**Comment by lexoyo** [comment]
hello @fadanan 
thx for the reminder, sorry about the delay
I will look at this now

**Comment by lexoyo** [comment]
@fadanan here is what I found in your file

1- you added a hamburger menu by editing the HTML file outside of silex right? you need to add the css class `fixed` to it: 
![screenshot_20191217_100626](https://user-images.githubusercontent.com/715377/70976608-fff45600-208a-11ea-8e96-2bb923d2b9bf.png)

2- the "sticky header" widget needs to be changed to go under the hamburger menu, so open the js editor and replace `nav.css('z-index', '101');` with `nav.css('z-index', '19');`. I will fix the widget now

**Comment by fadanan** [comment]
Thank you it works!

> The container do not have any x or y value. If I delete the container, all my element cannot be drag, only can be move by using arrows on keyboard.

I'm still having this issue. Just to let you the container do not have any x or y value because it turned into section. I don't know how. It cannot be move or change size. How can I resolve this problem?
![Capturejn](https://user-images.githubusercontent.com/58411215/71224499-c896db00-2310-11ea-824f-dc42d6302695.PNG)
![InkedCapture m_LI](https://user-images.githubusercontent.com/58411215/71224677-0d227680-2311-11ea-9330-f4cb92018ea0.jpg)

**Comment by fadanan** [comment]
nvm, I solved the issue above. Sorry for the fuss
