### ISSUE TITLE
Nice to have - Icons & Share buttons

### ISSUE THREAD

**Issue by tariqbenezza** [silexlabs/Silex#983]
Dear all,

Currently Silex proposes a bunch of share buttons :

<img width="457" alt="Screenshot 2019-11-22 at 09 16 28" src="https://user-images.githubusercontent.com/4911564/69409266-db65c200-0d08-11ea-9d76-cd8a98fe9403.png">

But we cannot have them separately. 
By example I want to add LinkedIn, Github & Twiter icons only like here : 

<img width="136" alt="Screenshot 2019-11-22 at 09 21 22" src="https://user-images.githubusercontent.com/4911564/69409593-8a0a0280-0d09-11ea-887b-66284e45c15e.png">

It could be nice to have the choice between the most famous icons/share buttons.

Thank you in advance.

**Comment by lexoyo** [comment]
Hi @tariqbenezza nice to have you back!

The share buttons component is really not easy to understand but it has a parameter to choose which icons you want. It is a text box where you can list the names of the icons, just delete the ones you don't need

Is that what you need?

**Comment by tariqbenezza** [comment]
Thank you @lexoyo ! It is very helpful !

I started to play with the options and I'll let you know.

I'll take the liberty to re-open it if it doesn't fit my needs ;)
