### ISSUE TITLE
Both latest .deb and Appimage not working on Kubuntu 19.04

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#986]
Heyo, I'm back! Also congrats on 256 open issues hehe, anyway, I installed the latest Silex desktop version on my Kubuntu 19.04 using the .deb file but the app doesn't launch. I also tried using the Appimage, here's what the console displayed:

fran@fran-HP-ENVY-17-Notebook-PC:~/Descargas$ ./silex-website-builder-2.5.43-x86_64.AppImage 
Invalid Type= "fixed" line for icon theme:  "/home/fran/.local/share/icons/McCrouz/places/symbolic/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"

(silex-website-builder:26620): Gtk-WARNING **: 15:41:19.175: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(silex-website-builder:26620): Gtk-WARNING **: 15:41:19.175: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(silex-website-builder:26620): Gtk-WARNING **: 15:41:19.175: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/tmp/.mount_silex-SBnYPn/resources/app.asar/node_modules

Silex starts with backward compat version 2,2,10 and front end version 2,10

...it's stuck there. Am I supposed to use my web browser?

**Comment by lexoyo** [comment]
hello
what version of silex desktop did you try?
2.5.43?

**Comment by FranGamer1892** [comment]
The latest on GitHub, the one where you talk about the exe stuff i think

**Comment by lexoyo** [comment]
Can you please clone this repo and run `npm run start:electron`?

Anyway you can run silex like this 

$ npm install -g silex-website-builder
$ silex

**Comment by FranGamer1892** [comment]
Wait, if i got all dependencies on a new ubuntu server, could i just do
$ npm install -g silex-website-builder
$ silex
To get Silex started? No need to git clone?

**Comment by lexoyo** [comment]
Sure. No need to git clone. No dependencies needed, just npm and node 10. You may want to set some env vars to customize silex

All this is in the docs, let me know if you don't find it

**Comment by FranGamer1892** [comment]
Alright, might try it later then. Also, you gave me two options. Is it the
same to you or is it better to use the first option to troubleshoot what's
going on with the .deb file? Thx!

**Comment by lexoyo** [comment]
I guess it's the same thanks for asking
Cc @JbIPS

**Comment by FranGamer1892** [comment]
Today I tried doing the npm thing on my ubuntu 18.04 server but no luck.
Then tried cloning the repo and doing npm install and still fails.
Basically the command which fails is npm install. I'll send the debug log
later but I remember it says it is probably not npm's fault and that some
files were missing on the repo...not sure.

I didn't download any software like python, neither updated any (maybe
accidentally using apt) since I already had Silex on that Ubuntu machine, I
just deleted the folder some days ago to update it.

**Comment by FranGamer1892** [comment]
[npm-debug.log](https://github.com/silexlabs/Silex/files/3908305/npm-debug.log)

**Comment by fcolecumberri** [comment]
same with ubuntu-mate 18.04, .appimage and .deb just prints:

```
/opt/silex-website-builder/resources/app.asar/node_modules

Silex starts with backward compat version 2,2,10 and front end version 2,10
```

but not doing anything, I am using version `2.5.43`

and with version `2.4.0` this just prints:
```
Silex starts with backward compat version [ 2, 2, 8 ] and front end version [ 2, 8 ]
/opt/silex/resources/app.asar/node_modules
```
and nothing else

but I'm not just bad news, I could make it work with the `npm install -g silex-website-builder` just as a reminder, if you install it without sudo, **you also need to add** `$HOME/.npm-global/bin` **to the path** (and open a new terminal to reload the path) **or the command will never execute and the instructions are skipping that part**.

**Comment by FranGamer1892** [comment]
Hmm I'm kinda confused. I'm right now on vacation till 2020 so I'll check
later. Btw, i have ubuntu mate 19.10 now

**Comment by fcolecumberri** [comment]
Well the thing here is that when you install stuff by `npm install -g` the programs get installed into `/home/<yourUser>/.npm-global/bin/` but bash does not know that programs are there, because of that, if you just type `silex`, bash wont find the program. You need to edit `/home/<yourUser>/.bashrc` adding `export PATH="$HOME/.npm-global/bin:$PATH"` this way each time you open a terminal, bash will know that apart of the common places where programs might be, also there might be programs in the npm directory so when you type `silex` bash will search also in that directory.

**Comment by FranGamer1892** [comment]
@fcolecumberri yeah but i cant even install it in the first place. i will try again with my Ubuntu 18.04 and then with my Ubuntu Mate 19.10

**Comment by FranGamer1892** [comment]
I've used NVM to install node 13, hope it works. Now this is what happens.

mcu2@ubuntu:~$ nodejs --version
v8.10.0
mcu2@ubuntu:~$ node --version
v13.6.0

So far so good, hope it installs correctly and as it should, even though some dependencies i have might be outdated.

**Comment by FranGamer1892** [comment]
Alright! Everything is working, the silex command responded as it would, and it is now listening to port 6805. Keeping this issue open as of now. Thanks.
