### ISSUE TITLE
Silex say: Error: Publication : an error occured: I did not manage to publish the website. (Setting for publication is ok) Using Drop Box

### ISSUE THREAD

**Issue by MarcelloCavallo** [silexlabs/Silex#987]
I can't update my site. Response is very urgent .

**Comment by lexoyo** [comment]
Hello
What is the size of your editable HTML file?

**Comment by lexoyo** [comment]
If it is relatively big (a few Mo) maybe the official instance provided by silex labs on editor.silex.me is struggling to publish. Someone should fix this bug
In the meantime you can run silex on your local computer and it would be ok if this is the problem

**Comment by lexoyo** [comment]
I recommend this method to run silex on your computer

https://github.com/silexlabs/Silex/wiki/How-to-Host-An-Instance-of-Silex#as-a-web-app-silex-web-version

**Comment by MarcelloCavallo** [comment]
The site is  14MB  (image jpg and writing content ).
The size of editable is 960x1200 (A4)
The Page of website are N° 60 
The site is  www.istitutoaden.eu (if you want to check)
Tank you for the council , I'll try.
Saluti from Roma and Happy new year

**Comment by lexoyo** [comment]
Ok let me know if it worked
Happy New year to you too!!!

**Comment by photopaperus** [comment]
Hallo, a "problem" similar.
Loading images from Dropbox, all goes ok .
Loading images from FTP, i receive this error:
"Error.  I did not manage to load the image. An error occurred while loading the image"
Obviously, the same (or similar) file and the same image (very light... in kb)
Soruy for my bad English...I'm from Italy. 
Thanks.

**Comment by lexoyo** [comment]
Hello @photopaperus 

A few questions

1- You are saying that you can add a image to your site when the image is on Dropbox but not when it is on ftp, is that correct?

2- when you save the website on the ftp, can you open it afterwards?

**Comment by photopaperus** [comment]
1. Yes
2. Yes.
