### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by anonimo82** [silexlabs/Silex#992]
Please, either make your site responsive or make an Android App from it.

Thanks, happy holidays.

**Comment by lexoyo** [comment]
What site?!

**Comment by anonimo82** [comment]
The editor

Il mar 24 dic 2019, 07:42 Alex Hoyau <notifications@github.com> ha scritto:

**Comment by lexoyo** [comment]
Thank you for the idea but nobody does design on a phone
I think touch friendly would be nice to have but it is too much work
You can use Silex to create a jekyll template and then use a headless CMS from your phone to edit the content, see stastic.net or siteleaf.com
