### ISSUE TITLE
Changer le nom des pages ou en ajouter/supprimer

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#993]
Bonjour,
comment faire pour changer le nom d'une page (ex : home > accueil) dans la nouvelle version ?
> quand je clique droit ou double clique, rien ne se passe
> quand je clique sur la petite molette (ou la poubelle) non plus
Pour ajouter ou supprimer des pages, je n'arrive pas à trouver non plus : 
> quand j'essaie de rajouter une page en cliquant sur "plus" ça fait disparaitre la page en cours...
> je n'arrive pas non plus, dans cette version sur ce modèle (photo en PJ) à supprimer une page (ex. le "book")
Merci !
Léa
![page](https://user-images.githubusercontent.com/34609544/71531923-320a8100-28f1-11ea-9e59-42eed6889f09.jpg)

**Comment by lexoyo** [comment]
Ah bon ?
Si tu cliques sur la poubelle ça ne supprime pas ?
Et le "+" n'ouvre pas le dialogue de création de pages?
Pour renommer, le bouton "roue" doit ouvrir le même dialogue que pour la création

**Comment by Lea75** [comment]
Alors, à partir d'un nouveau modèle : tout cela fonctionne.
A partir de celui que j'ai déjà retouché/modifié (en l’occurrence, juste la page "home" : rien de tout cela ne fonctionne.
Peut-être faut-il générer toutes les pages voulues avant de les modifier... car les modifications bloque après les fonctionnalités ?!

**Comment by lexoyo** [comment]
Il doit y avoir un bug dans silex
1- Tu utilises editor.silex.me?
2- tu peux partager le site qui bug? Dropbox ou github

**Comment by lexoyo** [comment]
@Lea75 bump!
