### ISSUE TITLE
Supprimer toute une section

### ISSUE THREAD

**Issue by Lea75** [silexlabs/Silex#994]
Bonjour,
est-il possible de supprimer toute une section dans une page ?
Par exemple, si je veux supprimer la section encadrée en PJ ?
Encore merci,
Léa
![section](https://user-images.githubusercontent.com/34609544/71532169-66cb0800-28f2-11ea-8ccf-62ed3959110e.jpg)

**Comment by lexoyo** [comment]
Hello
Sélectionne la section et click sur la poubelle dans le menu horizontal en haut

**Comment by Lea75** [comment]
Alors oui, ça fonctionne. Merci !!
