### ISSUE TITLE
Section in mobile view visible in all pages

### ISSUE THREAD

**Issue by fadanan** [silexlabs/Silex#995]
Hello, I need some help. I created 2 sections for mobile view only. I already hide all of them and display only on one page but the empty sections still appear in all pages in mobile view. Why is that happening? I hope anyone could help.

**Comment by lexoyo** [comment]
Hello @fadanan 
I just tested and I can see it too, this is a bug
Elements which are visible only on mobile are visible on all pages no matter the visibility settings
I will try to fix this soon, expect it to be live in about a month :-/

In the mean time here is a workaround I found:

1- select the section background (the green part in the image) 
2- make it visible only on some pages
3- add a css class `no-desktop` to it

![screenshot_20200107_095515](https://user-images.githubusercontent.com/715377/71896930-cff11d80-3133-11ea-9565-51ca001cd66e.png)

4- open the css editor
5- paste this code

```
div.no-desktop {
  display: none;
}
```

The CSS code will make the section invisible on desktop

**Comment by lexoyo** [comment]
Here is my test site: http://www.responsize.org/?url=https://lexoyo.me/silex-tests/bug-995.html#!page-page-1

**Comment by achuet** [comment]
Hi, I am also getting the same problem. In the mobile view, I created a section and make it visible only on a single page. But it is showing on all pages. Could you please tell me how to resolve this. Thank You
