### ISSUE TITLE
I need a bit of help with my website

### ISSUE THREAD

**Issue by FranGamer1892** [silexlabs/Silex#996]
Hey, so I've been remodeling my website using the "creative" template and I noticed after a couple of previews my like "zoom out" menu broke, so now my **Home** button, my **Services** button and **Cross** (or exit) button don't appear as they used to do when I started (see creative template). They are apparently always present, and zoom out with the rest of the website instead of appearing after triggering the menu button. 

Not sure why tho, never touched the code, and sincerely can't understand it either. I'm kinda new to this whole making websites thing, I'm not sure if I did something wrong or it is the template's fault. It's probably either a little bit of both, or completely my fault.

I'm posting my editable.html file if anyone wants to check or fix my issue, of course it's up to you. If anyone could help it'd be appreciated. Thanks.

Link: https://notindie.servegame.org/editable.html (download and open in Silex, don't worry about broken images and stuff)

PS: Can I use this template for any scenario? Or is there some copyright kinda restrictions?

**Comment by lexoyo** [comment]
Hello @FranGamer1892 
Sorry for the delay
I will look into this bug very soon

> PS: Can I use this template for any scenario? Or is there some copyright kinda restrictions?

Yes you can, no restrictions

**Comment by FranGamer1892** [comment]
I don't know if it's a bug or but anyway. Thanks for answering.

**Comment by lexoyo** [comment]
@FranGamer1892 I had a chance to look at this finally

There is a css rule on the body which i never saw before, did you edit the html by hand or is it a bug with Silex? On the body there is:
```css
    position: relative;
    top: 0px;
```

The workarounds are these (choose 1 of them, the first one is the cleanest)  
* edit the HTML in a text editor and remove `position: relative; top: 0px;` which is on the body tag: 
![screenshot_20200116_135133](https://user-images.githubusercontent.com/715377/72545195-6d043280-3867-11ea-8ac3-6e5b9a51ee5e.png)
* OR add this to the css editor **at the bottom**: 
```css
@media (min-width: 480px) {
  body.silex-runtime .show-when-active {
    top: unset;
  }
}
```
It will look like this:
![screenshot_20200116_135503](https://user-images.githubusercontent.com/715377/72545476-d8e69b00-3867-11ea-8c35-ac4b1e7950e9.png)

**Comment by lexoyo** [comment]
Please let me know how it goes? thx

**Comment by FranGamer1892** [comment]
Yeah, as soon as i can check it out (probably this evening) I will tell you
about it. Thanks. Oh, also, I didn't modify anything on the htmls or
anything. As i said i know little to nothing about html.

**Comment by FranGamer1892** [comment]
Lol, seriously was it that simple? I did the second one since i think it was easier and problem solved! Not sure why this happened. I NEVER touched any code! Just pasted the Google Translate string on the HTML box.

**Comment by FranGamer1892** [comment]
Thanks, by the way.

**Comment by lexoyo** [comment]
Oh ok it may be done by the Google translate widget
Then I need to fix the template before I close this issue

**Comment by lexoyo** [comment]
You're very welcome, happy to have you in this small community of makers 🎉
