### ISSUE TITLE
New version of Silex, testers wanted

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/Silex#998]
<a href="https://github.com/silexlabs/Silex/issues/998"></a>
A new version is coming with great improvements.

Please help me test it on <a href="https://preprod.silex.me">https://preprod.silex.me</a> and let me know how this goes below

<a href="https://github.com/silexlabs/Silex/pull/997#issue-363055184">Here is a list of the improvements</a>

**Comment by FranGamer1892** [comment]
Hi lexoyo, I will probably beta test it in my free time. Good luck.

**Comment by DurtyDev** [comment]
I'd be more than happy to if i could get it running on my Manjaro .

**Comment by FranGamer1892** [comment]
Doesn't the appimage work? Or is it just for Debian-based distros?

**Comment by DurtyDev** [comment]
From my reading an appimage should run on virtually any Distro. I even
tried to get the tar to spawn and had no luck. I might have missed it but I
didn't see any database files. I was going to attempt to copy the DB setup
from Blue Griffin builder to set up my own database and virtual server so
everything is confined.

**Comment by FranGamer1892** [comment]
Yeah, I thought appimages were kinda universal in the Linux environment.

**Comment by DurtyDev** [comment]
Me too. My driver has came with an app image launcher pre installed.
Something is missing in the appimage that's keeping it from launching. I
like Silex too.

**Comment by FranGamer1892** [comment]
I think I never got the appimage to work, sadly.

**Comment by BaguetteAgile** [comment]
Salut Alex, je commence mes tests,

je rencontre des problèmes pour faire fonctionner correctement le 
`LAYOUT`  a part `Absolute, Automatic` le reste des options restent vide, et quelle est la difference de ces options ( Fixe et Automatique ?? )

Il y a toujours le soucis avec les images, il est vraiment difficile de remanier leurs dimensions et leurs placement.

**Comment by lexoyo** [comment]
> je rencontre des problèmes pour faire fonctionner correctement le
LAYOUT a part Absolute, Automatic le reste des options restent vide, et quelle est la difference de ces options ( Fixe et Automatique ?? )

hmm en fait je pense faire un systeme plus simple

actuellement

* select container, set "layout > container flow" to "flex"
* select element in container, set "layout" to "automatic"

ce que je pense faire c'est juste un param:

* select container, set "layout content" to "flex"
* les éléments du container seront tous alignés selon les options de layout du container
* si on veut forcer un élément à etre en absolu dans un container "flex", je peux ajouter un param "force absolute layout"

> Il y a toujours le soucis avec les images, il est vraiment difficile de remanier leurs dimensions et leurs placement. C'est bien plus facile de gerer les images avec un Container et Background image

c'est vrai :grimacing: 
on devrait peut etre juste remplacer le "composant" image par un élément avec background image?

**Comment by AAODC** [comment]
![Capture](https://user-images.githubusercontent.com/63512172/79076416-dcb47d00-7cf1-11ea-8abf-e1e98fe16d53.JPG)

quelqu'un peut me aider s'il vous plait !

**Comment by lexoyo** [comment]
ca c'est le serveur qui est down je coirs :(
c'est revenu la non?

**Comment by AAODC** [comment]
Bonsoir Alex

c'est quand je veux ajouter une image dans le site que je reçoi le message.
et c'est quoi la solution ?
j'ai une autre question s'il vous plait : c'est quoi la différence entre
https://editor.silex.me
https://preprod.silex.me

je travail sur qu'il site entre les deux ?
Merci d'avance

Le dim. 12 avr. 2020 à 20:23, Alex Hoyau <notifications@github.com> a
écrit :

**Comment by lexoyo** [comment]
Salut @AAODC 

Désolé j'ai mis bcp de temps a répondre, j'ai fait un gros boulot de refactoring, je viens de mettre en ligne pas mal de correctifs aussi

@BaguetteAgile désolé aussi, je suis de nouveau dispo pour des questions et bug fix

**Comment by lexoyo** [comment]
I just released a new version with lots of bug fixes but a lot of refactoring too so maybe other bugs too. 

It is live, please help me test it : https://preprod.silex.me/

cc @clemos @molyrichez

**Comment by gravinyl** [comment]
Hello,
I'm using the preprod.silex.me because the editor.silex.me is not even working.
I get this "Error: I did not manage to open this file. Unexpected token w in JSON at position 5" when I try to open the page on editor.silex.me .
I'm able to open and edit in the preprod.silex.me but I'm pointing the links to their destination but then it's not actually saving these changes.
So when I reopen the file the links are not pointing to where they should.
Can you explain what could be wrong?
Thanks
Flávio

**Comment by lexoyo** [comment]
Hi @gravinyl 

Preprod is where you can test the beta version of silex, si it is bugguy right now
You cannot open her website saved with preprod.silex.me on editor.silex.me, the upgrade works but not downgrade

**Comment by lexoyo** [comment]
I will look at the links to see  if I reproduce your bug

**Comment by gravinyl** [comment]
Hello,

 

I think I did a big mess, because I saved the original project on the preprod version and now I'm not able to open it on the editor version...


 

I get the message "error: I did not manage to open this file. Unexpected token w in JSON at position 5".

 


 

I can actually open it on the preprod version but when I try to publish it I get the message "An error ocurred I did not manage to publish the website."

 

I don't know what's happening. I'm publishing it on an empty folder.

 

Could look into it? Thanks



 

 

 


Sent: Wednesday, June 24, 2020 at 2:32 PM

**Comment by lexoyo** [comment]
Hi
Yes I will look into this
Could you share your website with me pls? Are you using github or dropbox?

**Comment by gravinyl** [comment]
Hi,

 

The site is gravinyl.com, I'm using dropbox.

 
 

Sent: Saturday, July 04, 2020 at 6:21 PM

**Comment by lexoyo** [comment]
Ok then, please share it with me (a.hoyau [at] im-paris.fr)

**Comment by lexoyo** [comment]
I like the site https://gravinyl.com/ !!!
It looks great !

**Comment by lexoyo** [comment]
@gravinyl I had a look and it loads fine in https://preprod.silex.me/
Could you try again please?

**Comment by DurtyDev** [comment]
another exe too? That would be awesome. Speaking of which I figured out
another reason could cause a few of the very minor bugs. It's running out
of the appdata\temp\folder. Needs to be run from the Programs (or Programs
(x86)for 32bit.

**Comment by gravinyl** [comment]
Hello,

 

I will have a look and try again soon then.

Nice you liked the site. :)

I'll say something soon.

Thanks

 


Flávio

 

 

Sent: Tuesday, July 14, 2020 at 9:51 AM

**Comment by lexoyo** [comment]
Hello all

I have fixed so many bugs it took me 3 more months

Big thank you to the testers, especially @ceubri for his infinite patience and kindness
Also @molyrichez who helped a lot while creating professional websites

It will soon be live on https://editor.silex.me/
