### ISSUE TITLE
Try to install an instance of Silex on my own server

### ISSUE THREAD

**Issue by aermike** [silexlabs/Silex#999]
OS: CentOS8
node version: 
editor.silex.me]# node -v
v10.15.3
Error
 npm install -g silex-website-builder
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/silex -> /usr/local/lib/node_modules/silex-website-builder/dist/server/server/silex_web.js

> node-expat@2.3.18 install /usr/local/lib/node_modules/silex-website-builder/node_modules/node-expat
> node-gyp rebuild

gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.18.0-147.el8.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/silex-website-builder/node_modules/node-expat
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-30T12_08_44_812Z-debug.log

**Comment by lexoyo** [comment]
Hello
This looks like an npm and access rights issue
Please read this to fix the problem
https://frontend-development.com/how-to-fix-eacces-errors-with-npm-on-mac-os-x/

Maybe you need to chmod the folder /usr/local/lib/node_modules/

**Comment by aermike** [comment]
trying as root and have same error

**Comment by lexoyo** [comment]
I'm sorry I have no idea what causes that
It says the module `node-gyp` fails to remove a folder in `/usr/local/lib/` because of file permissions

**Comment by lexoyo** [comment]
@aermike did you find a solution?

**Comment by aermike** [comment]
somethinng adapted
Use other version of silex
custom-silex-templates or else like that
Error persist
And if use other version of silex, which use node-gyp there is no problem

**Comment by lexoyo** [comment]
> somethinng adapted
> Use other version of silex
> custom-silex-templates or else like that
> Error persist
> And if use other version of silex, which use node-gyp there is no problem

I did not understand this :-/

**Comment by aermike** [comment]
Instead use Silex I use an instance of -custom-silex
When install custom-silex, don't see any error aboute node-gyp
I try install node-gyp, and do't have errors

custom-silex]# npm install -g node-gyp
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git                                                                             hub.com/request/request/issues/3142
/usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@6.1.0
added 100 packages from 66 contributors in 4.754s

When try install silex error(error.txt)
[error.txt.txt](https://github.com/silexlabs/Silex/files/4239339/error.txt.txt)

**Comment by lexoyo** [comment]
I'm not sure to understand but I think you found a way?

**Comment by aermike** [comment]
Yes
Apparently depend by browser.
Because acces same instalation on other computer, and it works
I don't think this is an bug

**Comment by Yamakasi** [comment]
I have the exact same issue, I can install node-gyp manually but what then ? The silex install still fails on it.

**Comment by aermike** [comment]
Try install custom-silex, and it not falls
